### ISSUE TITLE
Bug: Import: Supplier Prices: Not working with supplier number

### ISSUE THREAD

**Issue by code-chicken** [Dolibarr/dolibarr#10190]
# Bug
When importing prices from suppliers, the import expects Dolibarr's internal supplier IDs instead of the supplier numbers from external source

## Environment
- **Version**: 8.0.2
- **OS**: Latest Gentoo Linux
- **Web server**: NGINX 1.14.0
- **PHP**: 7.2.10
- **Database**: MariaDB 10.1.34
- **URL(s)**: /imports/import.php?step=3&format=csv&datatoimport=produit_supplierprices

## Expected and actual behavior
- Expected: imported prices should be visible to the user
- Actual: After the import has successfully finished, the imported prices are not being shown in the user interface. In the field fk_soc in the table llx_product_fournisseur_price, there are the original values as imported from external source instead of Dolibarr's internal supplier IDs. Changing theses values manually to Dolibarr's internal supplier IDs solves this problem.

## Steps to reproduce the behavior
Import supplier prices

**Comment by torvista** [comment]
I use the Develop version and import supplier prices using the supplier name.
The value inserted into the db field is the internal Dolibarr reference, as expected.
So, it appears this problem has already been fixed at some point.

**Comment by atm-maxime** [comment]
Seems fixed in 8.0.6, I just imported a product supplier price file to update prices and the update went well, data are correctly showed. Please reopen if you're still facing the issue.

Here's the lines of my CSV I tested :

Produit ou Service* (sp.fk_product),Fournisseur* (sp.fk_soc),Réf. produit fournisseur (sp.ref_fourn),Quantité minimum* (sp.quantity),Taux TVA (sp.tva_tx),Code Taux TVA (sp.default_vat_code),Prix quantité min. HT* (sp.price),Prix unitaire HT* (sp.unitprice),Remise par défaut quantité min. (sp.remise_percent)
P001,Fournisseur 9,F48615,1,20,,50,50,10
