### ISSUE TITLE
VAT should be included for Deposits for Services.

### ISSUE THREAD

**Issue by mdeweerd** [Dolibarr/dolibarr#10408]
# Instructions
- Create a proposal with one or more services.
- Validate the proposal.
- Indicate that the proposal is accepted.
- Create a deposit invoice for the proposal (with a fixed amount).

# Bug or Feature
The deposit invoice VAT rate is set to 0 while it should be set to the VAT rate of the SERVICE if the proposal is only about services.

## Environment
- Dolibarr 8.0.4
- Debian/Wheezy/Apache/PHP5.X/Mysql or Mariadb.

## Expected and actual behavior

The deposit invoice VAT rate is set to 0 while it should be set to the VAT rate of the SERVICE if the proposal is only about services.

It may be more complex if the deposit is both for services and products.  It may be best to generate several lines for that - one with 0 VAT indicating the amount paid as a deposit for the products, and extra lines for each service VAT rate (in case there would be several services).

**Comment by eldy** [comment]
Rules depends on your activity, country, what you sell, the reason of credit note and a lot of other reason that differs in each country. 
We should introduce an option to choose which predefined product/service use when making deposit instead of a free line so we will use the vat of this service and will be able to address all cases.

**Comment by mdeweerd** [comment]
Great - I am looking forward to this feature which will avoid the common mistake to forget to add the VAT on service deposits as required by french tax rules.

**Comment by mdeweerd** [comment]
Still a valid request. Commenting to keep this open.
