### ISSUE TITLE
{line_options_xxx} not working in ODT in version 9.0.1.

### ISSUE THREAD

**Issue by bartiest** [Dolibarr/dolibarr#10521]
# Bug
In Dolibarr 8.x the use of {line_options_xxx} in ODT files for proposals, orders and shipment works fine. After upgrading to 9.0.1 none of the ODT templates work anymore.
{line_options_xxx} isn't filled out anymore

## Environment
- **Version**: 9.0.1
- **OS**: Linux
- **Web server**: Apache 2
- **PHP**: 7.3.1
- **Database**: MariaDB 10.1.37-MariaDB-cll-lve

**Comment by ksar-ksar** [comment]
Hi,

I have just created an extrafield on my proposal module, then use it on the ODT and this is working.

Could you please check your configuration and post the details ?

**Comment by ksar-ksar** [comment]
Hello,

Discussion on the forum help me to understand that what it is not working for you is product extrafield on proposal/bill etc..
https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/28899-line-options-xxx-in-odt-files-broke-since-9-x

After a review of the code there is a change between V8 and V9 : 
V8 : https://github.com/Dolibarr/dolibarr/blob/8.0/htdocs/core/class/commondocgenerator.class.php#L550
V9 : https://github.com/Dolibarr/dolibarr/blob/9.0/htdocs/core/class/commondocgenerator.class.php#L580

So the Product Extra field of a line changed from {line_xxxx} to {line_product_xxxx}

Could you try ?

**Comment by ksar-ksar** [comment]
Issue to close : Not a BUG
https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/28899-solved-line-options-xxx-in-odt-files-broke?start=15#36804
