### ISSUE TITLE
Export / import from Dolibarr

### ISSUE THREAD

**Issue by sebcapside** [Dolibarr/dolibarr#10983]
# Bug
Don't have enough datas in csv, excel file from Export, to Import.

## Environment
- **Version**: 9
- **OS**: Debian
- **Web server**: Appache
- **PHP**: 7
- **Database**: Mysql 

## Steps to reproduce the behavior
Export Datas, like Products, all items.
Import on a new Dolibarr.

# Feature Request
Have same informations from export to import them again

**Comment by swedebugia** [comment]
Hi
You can do this instead with Libreoffice Base until this is fixed. 

STEPS:
1 setup LO base for both your databases (old + new)
2 copy al the rows by going to the table e.g. llx_product_product and selecting them
3 open LO calc and paste the rows
4 edit if necessary
5 follow this video https://www.youtube.com/watch?v=D_W-FAT3XE4

Make sure to untick the first row called rowid before import (because this row is special and autoincremented).

**Comment by swedebugia** [comment]
If there is a difference in versions of the 2 dolibarr you can create a sample product in the new one to see how it should look in the table

**Comment by eldy** [comment]
Which field are you missing ?

**Comment by StephaneLesage** [comment]
This is still relevant in version 12.
