### ISSUE TITLE
Bug: variant - duplicate sales price

### ISSUE THREAD

**Issue by wdammak** [Dolibarr/dolibarr#11005]
Version: 9
When I create a new variant of a service, I have two lines in sales price that is created including a line with price ht 0?

it's normal?

**Comment by atm-maxime** [comment]
Thanks for the feedback. I just tested and I have reproduced it.
The product creation from a variant is done in 2 steps. First it creates the product, then it applies and saves the sell price. But when the product is created, Dolibarr automatically saves a price to 0. That's why there are 2 prices in the log. That's not abnormal and not blocking anything, but it could be improved.
