### ISSUE TITLE
Error while creating new Agenda type entry in Dolibarr dictionary

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#11267]
# Bug
While creating a new agenda type entry under Dolibarr Dictionary with value, **Holidays**; Dolibarr does not show the entry type list at the time creating new agenda. 

## Environment
- **Version**: [9.0.3]

**Comment by atm-maxime** [comment]
I tried just now, the dictionnary value is ok :

![image](https://user-images.githubusercontent.com/2097773/58556763-11742e80-821d-11e9-82bf-9b081faf9581.png)

And when I try to create a new event :

![image](https://user-images.githubusercontent.com/2097773/58556794-2355d180-821d-11e9-93ce-da00aa14b5f1.png)

I think because you used "Holidays" it's not shown like that. Holidays is a key for a translation. On my Dolibarr I don't see Holidays in the dropdown list but "Congés".

**Comment by alsoft10** [comment]
Yes you are correct. But in my case the second dropdown don't show the word **Holidays** in the list. So I made the value from **Holidays** to **Holiday**. By the way, how can I achieve the value **Holidays** in the second dropdown?

**Comment by atm-maxime** [comment]
You don't have the entry at all in the drop-down or do you have it translated to something else ?

**Comment by alsoft10** [comment]
![Holidays](https://user-images.githubusercontent.com/1249577/58629655-b0bb2380-82fa-11e9-8ecd-160f87ae563d.png)
![Dropdown](https://user-images.githubusercontent.com/1249577/58629664-b4e74100-82fa-11e9-961c-586db6a71d88.png)

As you can see from the above images. I have added **Holidays** but it is not appearing in new agenda create page.

**Comment by atm-maxime** [comment]
Yes it appears, but it's translated to "Leave".
