### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#11602]
# Bug
In the release version 9.0.4 the German translation is missing a lot.

Is there an easy way to get everything from transifex?
How are differences between (major) versions managed? There is no selection in transifex per version, right?

I am going to help complete the de_DE translation but for testing without the proper tools its very hard. In the WordPress environment Poedit is a dream and for me everything must live up to it.

## Environment
- **Version**: 9.0.4

**Comment by Tim-Otte** [comment]
**In german:**
Hi,

das sind zwar nicht die Übersetzungen von Transifex, aber ich habe viele Texte schon selbstständig übersetzt, da viele der vorgegebenen Übersetzungen falsch oder ungenau sind. Die angehängte Datei enthält einen SQL-Befehl, mit dem Sie diese Übersetzungen, falls Sie Zugriff auf die Datenbank haben, hinzufügen können.

Ich hoffe, ich konnte helfen...

**In english:**

Hi,

these are not the translations of Transifex, but I have already translated many texts by myself, because many of the given translations are wrong or inaccurate. The attached file contains an SQL command that you can use to add these translations if you have access to the database.

I hope I could help...

[Dolibarr Translations de_DE.zip](https://github.com/Dolibarr/dolibarr/files/3455705/Dolibarr.Translations.de_DE.zip)

**Comment by cfoellmann** [comment]
Das sind dann strings, die unter `Einstellungen` > `Übersetzungen` angelegt wurden. Richtig?

Blöd, dass ich Poedit für die transifex übersetzungen nicht so einfach nutzen kann.

**Comment by Tim-Otte** [comment]
Ja, genau. Es fehlen noch ein paar Übersetzungen, die meisten konnte ich aber damit abdecken.

**Comment by eldy** [comment]
New translations done in transifex were sync into v10. So i close the ticket.

**Comment by cfoellmann** [comment]
There are not all strings from the source in transifex!?

Translations are very important to us. My most current issue is in the `holidays` section-

In https://github.com/Dolibarr/dolibarr/blob/22b91f36935cbe835cc214dd36b69625ea17a14b/htdocs/langs/de_DE/holiday.lang I got
```
LastHolidays=%sneuste Ferienanträge
AllHolidays=Allen Ferienanträge
```
which is wrong and these strings are not in transifex.
There needs to be some kind of automatic sync both ways. Right?
