### ISSUE TITLE
Possible bug: v10.0.0 PNG logo only displayed on first PDF page

### ISSUE THREAD

**Issue by kess78** [Dolibarr/dolibarr#11651]
# Bug
Since years I use the same logo image file. It's a normal, standard PNG with a transparent background. It worked perfectly until v9.0.3. After the upgrade on v10.0.0 the PNG logo is shown only on the first page of the invoice (or proposal). Of course I use native PDF reports, so crabe or azur.
If for testing I use a JPG logo, it works on all the pages as expected. The problem seems only with PNG files (tried many).
Forum post here: https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/29339-10-0-0-logo-on-the-first-page-only

## Environment
- **Version**: v 10.0.0
- **OS**: Debian Stretch x64
- **Web server**: Apache 2.4.25
- **PHP**: 7.3.7 (and also 7.2.20)
- **Database**: MariaDB 10.1.38
- **URL(s)**: Invoice / Proposal PDF Generation

## Expected and actual behavior
Described above

## Steps to reproduce the behavior
Described above

**Comment by jtraulle** [comment]
Related to tecnickcom/tc-lib-pdf#56

**Comment by jtraulle** [comment]
Workaround is detailed here https://www.dolibarr.org/forum/527-bugs-on-a-stable-version/29339-10-0-0-logo-on-the-first-page-only#38142

----

@eldy As current version 6.2.26 of TCPDF is considered obsolete and no new release has been released since 16 Oct 2018, should me make an exception an patch `htdocs/includes/tecnickcom/tcpdf/tcpdf.php` file directly on Dolibarr repo ?

**Comment by dpriskorn** [comment]
Update to v12 and reopen if the problem persists.
