### ISSUE TITLE
Return of products when Credit Note is validated

### ISSUE THREAD

**Issue by ariffidaali** [Dolibarr/dolibarr#11665]
## Environment
- Version: [9.03]
- Operating System: [Cent OS 7]
- Web Server: [LiteSpeed]
- PHP: [7.0.32]
- Database: [MySQL 10.2]
-URL: /compta/facture/card.php

# Feature Request
[Return of products when Credit Note is validated]

## Use case
[Credit Note creation]

## Suggested implementation
[When I create a Credit Note I would like an option to return the products to the warehouse it was reduced from i.e
I created a customer order then created an invoice from that cust. order. The customer fully pays and so I enter payment for that invoice. Having fully paid for that invoice, I then create a shipment and then deliver the items to the customer. A few days later the customer returns the items and he wants his money back. So I create a credit note to reverse the invoice but the stock will not be automatically returned back to that particular warehouse. I have to manually do a stock adjustment to return the items. I want an option for the stock to be returned to the respective warehouse once the credit note is validated and only if the shipment was done.

![Screenshot_2019-08-05Stockmodulesetup](https://user-images.githubusercontent.com/53896008/62686998-86f33c80-b9ce-11e9-83a3-5549f83c1cf4.png)
The issue with the stock module setup is that you can only choose one rule for decrease or increase of stock and furthermore it is decrease/increase real stocks on validation of customer invoice/credit note and not separate one for invoice and one for credit note]

## Suggested steps
[Credit Note should have a button for returns similar to a customer order with a create shipment button. So similar functionality except this will return products to the specified warehouse. ]

**Comment by ariffidaali** [comment]
Any solution to this issue/feature request?

**Comment by atm-maxime** [comment]
Solution is to implement this option, don't be impatient with your issue in the middle of August...

That said, I don't think this should be automatic but it should be asked on credit note validation. What if the customer returns the product because it has a defect ? Do you really want it back to your stock ? And what if your credit note is just to correct an error in your invoice but you do another invoice right after with the same products ?

Have you searched in the issues if this has already been asked ? If no, good chance is that it's needed by a few for now.

**Comment by futurehousestore** [comment]
Good point @atm-maxime this kind of "transfers" shouldn't be automatic. Any of the returns shouldn't go back to the main warehouse with pristine stock because that is not the process. The return of stock should be logged but all the sellers deal with the returns in a different way. All returns need to be checked. Some of them can go to the main warehouse (customer just changed his mind) some of them need to be repaired, some of them just need a new packaging and some of them need to go to the bin. It would be nice to have this kind of implementation in Dolibarr where we can have an option to "return the products to the warehouse" and an option to choose the warehouse (from my experience most companies have at least 2 warehouses, one for pristine stock and one for faulty stock)
Just a thought... AXeL has a great module for product returns which could be implemented in the core and improved to make the smooth returns ;-)

**Comment by ariffidaali** [comment]
@atm-maxime 
So what's special in the middle of August that I shouldn't get impatient about?? It's not being impatient was just wanting to know if and when this issue can be tackled.
Yes ok your points are valid:
If defective stock is returned then there should be a way to return them them as @futurehousestore says to a warehouse for defective stock. So I propose instead of automatic return there could be a button for returns when a credit note is validated. It would be like a shipment in customer order but in reverse, this will add stock back to the system. So now the user can choose the particular warehouse where each stock goes plus also there should be a record in the stock movement for the same.

**Comment by atm-maxime** [comment]
Opening an issue and asking again about it 5 days later is what I call impatient. The Dolibarr community is mainly French and August is a month of vacation.

The option proposed already exists when your stock setup is based on invoice validation. In this case Dolibarr asks for a warehouse when validating a credit note. This option could also appear even if the stock setup is not on invoice validation.

**Comment by ariffidaali** [comment]
As I've mentioned above 

> The issue with the stock module setup is that you can only choose one rule for decrease or increase of stock and furthermore it is decrease/increase real stocks on validation of customer invoice/credit note and not separate one for invoice and one for credit note]
Currently my stock setup is: Increase real stocks on manual dispatching into warehouse, after supplier order receipt of goods. I can only choose one rule. What I'm then suggesting that for credit note a separate rule for stock: Increase real stocks on validation of credit note and multiple rule validation.

**Comment by StephaneLesage** [comment]
+1
This needs to be implemented

**Comment by WILLIBBY** [comment]
+1
This needs to be implemented
