### ISSUE TITLE
Discussion: Drop support for unsupported PHP versions

### ISSUE THREAD

**Issue by jtraulle** [Dolibarr/dolibarr#11763]
Currently, only PHP version 7.1 and above are officially supported by the PHP team (have security fixes) and PHP 7.1 will be EOL in next December (3 months).

https://www.php.net/supported-versions.php

I wonder if this will not be a good decision to stop supporting really old versions of PHP that are unmaintained (5.5 in EOL-EndOfLife since mid 2016 so more than 3 years now!) and potentially dangerous to run.

Since Dolibarr runs well on PHP 7.3, we should **at the very least** drop support for PHP 5.5 (this will allow us to migrate Travis-CI to Xenial based VMs that provide PHP versions from 5.6 and which are faster and becoming the default on Travis-CI infrastructure ; Trusty VM are kept but deprecated) but I am in favor of keeping only supported PHP version (so 7.1, 7.2 and 7.3).

It does not mean that Dolibarr will stop working on PHP < 7.1 but that it is not _officially supported_.

**Comment by eldy** [comment]
The first thing we must consider is not the roadmap of PHP but the state of PHP version of current customers.
If dolibarr works correctly on version X of php and customers are using version X, we have no reason to force the customer to upgrade their infrastucture just for the reason "PHP team does not support version X". I think forcing users to upgrade for this reason is not a good reason :
Currently keeping compatibility of Dolibarr with old version of PHP does cost us nothing. So, for the moment i see only 3 reason why we shoud increase the minimal number of a PHP version. They are:
1) We need a new feature available only in a new version of PHP (this is rarely happened). 
2) We have no choice because we depends on a major external library or tool and this library/tool does not works anymore on version X (this is the most common reason why we increase the PHP version)
3) The security. However, increasing security by upgrading PHP means : forcing a user to upgrade its PHP version, so its PHP Operating system and often all its other dependings development. This is also taking a big, very BIG risk. So the argument saying "it increase your security" also means "you take also high risk to have a situation worse after, so it is a security problem too (not same level of security)". For this reason, i prefer to have the user the choice to decide if increasing the security by upgrading its PHP with all other side effects worth the risk. If we don't support old PHP version when we can at no cost, means we dont let the choice to the user. It is, in m opinion, a bad philosophy. Users must be able to choose, not being forced. For this reason, i do not consider the point 3 as a valid reason. It is a good reason, but only the end user can really evaluates if it is better for him or not to do it. So we must, as long as we can, let the user decides and not the project. As a user of a lot of other software, I thanks all projects that let me choose, and hates projects that put the knife under my throat when they have choice. When maintaining several version costs to the project, this is something i can understand, but when it is not the case (and it is rarely the case for Dolibarr), i prefer to be free to choose myself (I will resume this like this: "Some forced and repeated upgrades that has major impacts on all your information system, done with a planning that you can't decide because it was decided by your supplier, is not always the best security choice"). It is of course just a point of view but this explain why it is more often point 1 and 2 that rules, than point 3.
To keep the choice to most users, in most cases, we take into consideration the abandon of a supported PHP version when the number of Dolibarr users with a PHP version is lower than 10%,. Rarely when this rate is higher.

**Comment by jtraulle** [comment]
Thanks for your detailed reply, I see your point :slightly_smiling_face:

**Comment by swedebugia** [comment]
Maybe we could strike a middle ground and warn customers about insecure PHP versions e.g. in the installer?
