### ISSUE TITLE
SuperAdmin can't change his permissions when "advanced permissions" are activated

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11865]
# Bug
The SuperAdmin can't change his permissions when the Option
`Security -> Miscellaneous -> Use the advanced permissions of some modules`
is activated

## Environment
- **Version**: 10.0.1
- **OS**: Windows NT DOLIBARR 10.0 build 17763 (Windows Server 2016) AMD64
- **Web server**: Apache/2.4.39 (Win64) PHP/7.2.18
- **PHP**: 7.2.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.14-MariaDB
- **URL(s)**:  `/user/perms.php?id=1`

## Actual behavior
`SuperAdmin` can't change his own permission, when option `Security -> Miscellaneous -> Use the advanced permissions of some modules` is activated

## Expected behavior
`SuperAdmin`  can always change his own permission

## Steps to reproduce the behavior
* Fresh install a Dolibarr
* (Eventually) Use MariaDB database
* Activate `Security -> Miscellaneous -> Use the advanced permissions of some modules`
* Try to change your own permissions (SuperAdmin)

## [Attached files]
![2019-09-11 13_08_15-Dolibarr – Opera](https://user-images.githubusercontent.com/17874713/64692386-46875280-d495-11e9-8118-6f28c78f08dc.png)

## Workaround
1. Create a new user 
2. Activate permission `Create/modify internal/external users and permissions` for this user
2. Login in as the new user
3. Change the permission of the `SuperAdmin`

**Comment by hregis** [comment]
@TobiasSekan 
I do not have this problem! 
did you add external modules?

**Comment by ghost** [comment]
No, no external modules, only a fresh install.

I have noticed that all user/group permissions was check for the `SuperAdmin` 
but couldn't not change my own permissions (as SuperAdmin) and i couldn't not create a usergroup.

After I have click on the first `All` (from the another account) the `SuperAdmin` have become all rights and now it is possible to change the own permission of the `SuperAdmin` and the `SuperAdmin` can create groups.

IMHO I think the problem was related in the additional permission rule `Read its own permissions`

**Comment by sam-anam1** [comment]
Right its a bug when you install a fresh v10.0.1
the issue 'cause Dolibarr doesn't modify DB Table structure for table llx_user_rights when you turned on [the advanced permissions of some modules]

 I have fixed by log into database and I can confirm that it will 100% work 
in DB  ALTER TABLE `llx_user_rights' and and put this sql

`INSERT INTO `llx_user_rights` (`rowid`, `entity`, `fk_user`, `fk_id`) VALUES (159,1,1,11),(158,1,1,12),(157,1,1,13),(156,1,1,14),(155,1,1,15),(154,1,1,16),(153,1,1,19),(152,1,1,21),(151,1,1,22),(150,1,1,24),(149,1,1,25),(135,1,1,26),(134,1,1,27),(133,1,1,28),(119,1,1,31),(118,1,1,32),(117,1,1,34),(116,1,1,38),(115,1,1,39),(114,1,1,41),(113,1,1,42),(112,1,1,44),(111,1,1,45),(110,1,1,61),(109,1,1,62),(120,1,1,64),(121,1,1,67),(132,1,1,68),(131,1,1,69),(130,1,1,70),(129,1,1,71),(128,1,1,72),(127,1,1,74),(126,1,1,75),(125,1,1,76),(124,1,1,78),(123,1,1,79),(122,1,1,81),(108,1,1,82),(213,1,1,84),(199,1,1,86),(198,1,1,87),(197,1,1,88),(196,1,1,89),(195,1,1,91),(194,1,1,92),(193,1,1,93),(192,1,1,94),(143,1,1,101),(160,1,1,102),(146,1,1,104),(145,1,1,105),(144,1,1,106),(142,1,1,109),(191,1,1,111),(190,1,1,112),(189,1,1,113),(200,1,1,114),(201,1,1,115),(212,1,1,116),(211,1,1,117),(210,1,1,121),(209,1,1,122),(208,1,1,125),(207,1,1,126),(206,1,1,141),(205,1,1,142),(204,1,1,144),(203,1,1,151),(202,1,1,152),(188,1,1,153),(187,1,1,154),(186,1,1,161),(172,1,1,162),(171,1,1,163),(170,1,1,164),(169,1,1,165),(168,1,1,167),(167,1,1,221),(166,1,1,222),(165,1,1,223),(164,1,1,229),(163,1,1,237),(162,1,1,238),(173,1,1,239),(174,1,1,241),(185,1,1,242),(184,1,1,243),(183,1,1,251),(182,1,1,252),(181,1,1,253),(180,1,1,254),(179,1,1,255),(178,1,1,256),(177,1,1,262),(176,1,1,281),(175,1,1,282),(161,1,1,283),(107,1,1,286),(53,1,1,331),(39,1,1,332),(38,1,1,333),(37,1,1,341),(36,1,1,342),(35,1,1,343),(34,1,1,344),(33,1,1,351),(32,1,1,352),(31,1,1,353),(30,1,1,354),(29,1,1,358),(40,1,1,511),(41,1,1,512),(52,1,1,514),(51,1,1,517),(50,1,1,520),(49,1,1,522),(48,1,1,524),(47,1,1,525),(46,1,1,527),(45,1,1,531),(44,1,1,532),(43,1,1,534),(42,1,1,538),(136,1,1,701),(137,1,1,702),(147,1,1,703),(28,1,1,771),(27,1,1,772),(26,1,1,773),(12,1,1,775),(11,1,1,776),(10,1,1,777),(9,1,1,778),(8,1,1,779),(7,1,1,1001),(6,1,1,1002),(5,1,1,1003),(4,1,1,1004),(3,1,1,1005),(139,1,1,1101),(141,1,1,1102),(140,1,1,1104),(138,1,1,1109),(2,1,1,1121),(13,1,1,1122),(14,1,1,1123),(25,1,1,1124),(24,1,1,1125),(23,1,1,1126),(22,1,1,1181),(21,1,1,1182),(20,1,1,1183),(19,1,1,1184),(18,1,1,1185),(17,1,1,1186),(16,1,1,1187),(15,1,1,1188),(1,1,1,1189),(106,1,1,1191),(92,1,1,1201),(91,1,1,1202),(90,1,1,1231),(89,1,1,1232),(88,1,1,1233),(87,1,1,1234),(86,1,1,1235),(85,1,1,1236),(148,1,1,1251),(84,1,1,1321),(83,1,1,1322),(82,1,1,1421),(93,1,1,2401),(94,1,1,2402),(105,1,1,2403),(104,1,1,2411),(103,1,1,2412),(102,1,1,2413),(101,1,1,2414),(100,1,1,2501),(99,1,1,2503),(98,1,1,2515),(97,1,1,20001),(96,1,1,20002),(95,1,1,20003),(81,1,1,20004),(80,1,1,20005),(79,1,1,20006),(65,1,1,20007),(64,1,1,23001),(63,1,1,23002),(62,1,1,23003),(61,1,1,23004),(60,1,1,50401),(59,1,1,50411),(58,1,1,50412),(57,1,1,50420),(56,1,1,50430),(55,1,1,50440),(66,1,1,55001),(67,1,1,55002),(78,1,1,56001),(77,1,1,56002),(76,1,1,56003),(75,1,1,56004),(74,1,1,56005),(73,1,1,59001),(72,1,1,59002),(71,1,1,59003),(70,1,1,63001),(69,1,1,63002),(68,1,1,63003),(54,1,1,63004);
UNLOCK TABLES; `

**Comment by hregis** [comment]
@TobiasSekan ok, i send a fix https://github.com/Dolibarr/dolibarr/pull/11872
