### ISSUE TITLE
[BUG] Additional PHP warning after click on validate leave request

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#11871]
Hello,

# Bug
When a user validate his own leave request, after creating a leave request and the email server is not configured, Dolibarr show two messages.

1. The normal information banner
![2019-09-12 08_33_41-Leave – Opera](https://user-images.githubusercontent.com/17874713/64760005-e9dd7380-d538-11e9-826b-fa3bae3d8de3.png)

2. An extra PHP warning
![2019-09-12 08_05_48-](https://user-images.githubusercontent.com/17874713/64760016-f06beb00-d538-11e9-8014-dee8fe6494aa.png)

## Environment
- **Version**: 10.0.1
- **OS**: Windows NT DOLIBARR 10.0 build 17763 (Windows Server 2016) AMD64
- **Web server**: Apache/2.4.39 (Win64) PHP/7.2.18
- **PHP**: 7.2.18
- **Database**: MySQL or MariaDB 5.5.5-10.3.14-MariaDB
- **URL(s)**: `dolibarr/holiday/card.php?id=28&action=sendToValidate`

## Actual behavior
A information banner and a additional PHP warning is shown.

## Expected and actual behavior
Show only a information banner.

## Steps to reproduce the behavior
1. Fresh install
2. Don't set valuers for email server
3. Create a new user
4. login as this new user
5. Create a new leave request 
6. Click on "Validate" of your leave request

**Comment by eldy** [comment]
A check on port does not work always. It depends on setup (mail agent may be a remote or local, on security option. It is bases on socket connection when using mail may be based on TCP/IP that does not use same protocol).
Adding a check here before sending an email, is like having your web browser making a ping before making a GET or POST.
Best thing is to report an error message to say mail server is not reachable (it is what we have in the yellow message).
The second annoying message is because the user has enable the xdebug module to get more information when an error occurs. So the second message on screen is the expected behaviour and not a bug.
Of course this must not be done on a production server.

So if user want debug information, there is nothing to do, if user is on a production and don't want the second more accurate message, he must disable xdebug.
