### ISSUE TITLE
Dolibarr users can't see manually created event for them by Super Admin

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#11957]
#Bug
[*When super admin of Dolibarr create an event manually for a Dolibarr user (employee) and assigned the event to them, they can't see the deatils of the event after login. When they click on the events tab they can only see the list of events assigned to them. When they try to click on the event ID to open it, there is no link anchored with event ID.
You may think it is the permission issue. But this is not the premission issue. As ........

1. Read actions (events or tasks) linked to his account permission is allowed
2. Create/modify actions (events or tasks) linked to his account is allowed

So according to the above permission they should open the event and modify them to mark the event is complete. 

Interestingly when we set the below two permission allowed then they can open and modify the event

1. Read actions (events or tasks) of others is allowed
2. Create/modify actions (events or tasks) of others

But in the above case they can also see the event assigned to other users. So there is a security and privacy issue. Please fix the problem.

*]

## Environment
- **Version**: 10.0.1

**Comment by eldy** [comment]
By definition, only a owner of an event can modify it. The assignment goal is to know who is invited or not to the event, but only the owner can edit. It is the same when creating an event in google calendar or most online calendars. Invited people car read and answer, but they are not allowed to edit.
This seems to be the expected behaviour. The label of permission
"Create/modify actions (events or tasks) linked to his account" 
should be 
"Create/modify actions (events or tasks) linked to his account as owner"

i don't think there is an option to allow someone to edit an event he is not the owner without giving permission "Create/modify actions (events or tasks) of others"

**Comment by alsoft10** [comment]
@eldy You are perfectly correct. But the problem about the event reading. So when these two options are allowed

1. Read actions (events or tasks) linked to his account permission is allowed
2. Create/modify actions (events or tasks) linked to his account is allowed

They must can see the event to click on the event ID on the event list page. But they can't without the other these two options allowed which is not correct.

    1. Read actions (events or tasks) of others is allowed
    2. Create/modify actions (events or tasks) of others

I don't allow to add these two options as I don't want to give one employee permission to see event's for other employees. Please understand the issue.
