### ISSUE TITLE
[Request] A few resource module improvements

### ISSUE THREAD

**Issue by ghost** [Dolibarr/dolibarr#12205]
# Feature Request
1. Make resource module more visible (extra menu symbol or into agenda menu)
2. Add combo-list of resources into `Create an event` form
3. A option to hide `Origin country` in `New resource` form 

## Use case
1. User don't find the resource menu points and need a easier way to find it (e.g. resource symbol)
2. User want to add a resource to a event direct in the `Create an event` form
3. A user or company don't need a `Origin country` for resources

**Comment by braito4** [comment]
About point 3. Not origin but location yes (timezone mainly)

**Comment by Jenbalco** [comment]
I very much support the addition of resources to main menu. Resources (Assets) are great part of running a business.
If I may add to this, I would suggest link assets to warehouses/office locations in order to reflect exactly where they actually are.

additionally, it would not be a bad idea to extend the barcode and categories/tags modules to the resources module as well.
