### ISSUE TITLE
Hide sensitive menu (php version, server kernel) 

### ISSUE THREAD

**Issue by tanguy-opendsi** [Dolibarr/dolibarr#12737]
# Feature Request
Hide sensitive server infos. 

## Use case
On Dolibarr there is the configuration panel, this panel allow admin user to get information about the server like : 
Php version , Server Kernel, Php values. 

## Suggested implementation
Secure access to for admin(superadmin) group not for all admins.

**Comment by eldy** [comment]
This is the expected behaviour. 
The "admin" user is in most cases the guy responsible of the application. He must know what is the php version, what is setup.
In dolibarr "admin" means the "superadmin".
If you need simple "admin", you must create a group "admin" and give all permissions to this group and set users inside this group.

**Comment by elarifr** [comment]
i think we should have a flag file to lock access to server information values (working the same manner install.lock) the session data are needed only in install / dev / repair stage not for usual admin use.
i have same need when i request a token send by mail to allow a feature, but the token is in session ( i use it in virtual time zone to update core file )
