### ISSUE TITLE
API REST v10: réponses JSON attendues dans la langue de l'utilisateur ou une langue choisie

### ISSUE THREAD

**Issue by RAYBAUDI** [Dolibarr/dolibarr#12853]
# Feature Request
Les libellées des réponses JSON de l'API devraient être dans la langue de l'utilisateur pour toutes les méthodes de l'API

## Use case
Récupération des données dans une appli tierce

## Suggested implementation
Plusieurs possibilités, avec dans l'ordre des préférences :
* inclure un paramètre "lang" dans l'URL (comme pour setup/setupRetrieveListOfCountries)
* utiliser le paramètre de langue de DoliBarr
* utiliser le paramètre de langue de l'utilisateur

## Suggested steps
Langue par défaut de Dolibarr : Français
Langue de l'utilisateur : Français

Ex avec : setup/setupRetrieveAvailability, j'obtiens : 
`{
    "rowid": "2",
    "code": "AV_1W",
    "label": "1 week"
  }`

label devrait me retourner "1 semaine" (traduction française) et non "1 week"

**Comment by eldy** [comment]
I don't think this is a good idea.
API are a features for developers. Most values returned are code. And the code for week is w, we should not return here s because s means nothing in API language.
Here, the "label" return is the value into a table, we have no reason to change it. It must appears as it is in database. It is a fallback value when a translation is not found in language file. And there is only 1 fallback value, the value in database.

**Comment by dpriskorn** [comment]
@eldy is this a won't fix? I suggest closing it then.
