### ISSUE TITLE
Easy way to customize receipts in TakePOS - Receipt Templates

### ISSUE THREAD

**Issue by javierybar** [Dolibarr/dolibarr#12989]
Currently to modify a receipt in TakePOS is not easy because We need modify the Dolibarr core, I think is very interesting to use receipt templates as 'Receipt printers' module.
A receipt templates solve other opened issues.
What do you think and what idea do you have @andreubisquerra ?

**Comment by denis-poncereau** [comment]
I also think it would be good to have more information on the receipt, some of them being obligatory I think (like the name and adress of the company or payment method).
The best would be to make it customisable with models !

**Comment by andreubisquerra** [comment]
I am working with the 'Receipt printers' (I hope will be stable in Dolibarr 12) and my idea is leave 3 printing methods for TakePOS. In my opinion some people want easy setup without customization, and other people want full customization. Please look the picture. And please I want to know your opinions.
![1](https://user-images.githubusercontent.com/28452516/73614865-66b1dc80-4603-11ea-8c1f-6217424a5279.JPG)

**Comment by javierybar** [comment]
Nice!

**Comment by denis-poncereau** [comment]
It seems good to me this way ! What's the difference between receipt printers and TakePOS connector ? Isn't TakePOS connector used for receipt printers ?
I think some basic configuration should be included for the receipt, like  :

- [x] Display company name
- [ ] Display professional id. 1
- [x] Display VAT number
- [ ] Display free text : _____________

Maybe the same for all the methods ? It would be nice to have some accountancy advice to know what are the compulsory or important things !

**Comment by soerpoers** [comment]
yeah that would be nice. I think it should be easier to modify all receipts – dolibarr-wide…

**Comment by andreubisquerra** [comment]
Solved with commit https://github.com/Dolibarr/dolibarr/pull/13156

**Comment by sarksloane** [comment]
@andreubisquerra @javierybar I have a suggestions, please if you can put and add also in the receipt the following with black circle so that we can show to the customers the tendered amount and the change of their money. It would be great also if you can also add the total number of items purchased. Thanks.
![grocery3-receipt](https://user-images.githubusercontent.com/36034786/77922014-14273080-72d3-11ea-9de3-4e81b99f7194.jpg)
![Grocery-Receipt-1](https://user-images.githubusercontent.com/36034786/77922025-15585d80-72d3-11ea-8463-5aa58da8ec0a.jpg)
![grocery2-receipt_sm](https://user-images.githubusercontent.com/36034786/77922027-15f0f400-72d3-11ea-941c-6d3066f9de7a.jpg)

**Comment by xITmasterx** [comment]
Is this feature already added into Dolibarr?

**Comment by andreubisquerra** [comment]
Solved with new Receipt Printer Module

**Comment by altairis-tof** [comment]
hello, if it is solved as @andreubisquerra wrote, may somebody close this issue ?

**Comment by goldenwt** [comment]
This is an important topic. Pls can we have opportunity to add logo to the invoice/receipt under takePOS receipt using the variable statement?

Tried setting up the receipt printer,always comes out with "cant parse the Ip Address(xxx.xxx.x.xxx)", and the printer IP address is correct as i print directly from the printer fromDolibarr.

Pls any help?
