### ISSUE TITLE
Extrafields Supplier invoice

### ISSUE THREAD

**Issue by dieperie** [Dolibarr/dolibarr#13018]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Extrafields with supplier module (invoice lines) does not work anymore. The field is existing, but not saved.

## Environment
- **Version**: 11.0
- **OS**: Debian 
- **Web server**: Apache 2.4
- **PHP**: 7.0.33-0+deb9u6
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
Field data saved, currently not saving

## Steps to reproduce the behavior
Modify invoice line and save

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by RubenRuCh** [comment]
Can you give more info about the issue? Maybe screenshots? 

The extrafield is available when you are creating a supplier invoice but the data is not being saved when you introduce it on the extrafield, OR the extrafield is not even being showed at the moment of the creation of the invoice?

**Comment by dieperie** [comment]
When creating or cloning a supplier invoice, the extrafield (det) for
the invoice lines are not created. 

For existing invoices or when I manually create manually the extrafield
record, it is displayed correctly. I can also change it and save. 

FYI, there is a problem with the creation of the records. I also noticed
the same behavior with llx_elements_elements records. When you wish to
bind purchase order to supplier invoice. 

Maybe this is a hint for you. 

Le 04/02/2020 11:33, Rüger a écrit :

> Can you give more info about the issue? Maybe screenshots? 
> 
> The extrafield is available when you are creating a supplier invoice but the data is not being saved when you introduce it on the extrafield, OR the extrafield is not even being showed at the moment of the creation of the invoice? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/Dolibarr/dolibarr/issues/13018?email_source=notifications\u0026email_token=AIGN5DX3EPUD7UH4NNKZ6T3RBFAA7A5CNFSM4KPLGWY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKXD2UY#issuecomment-581844307", "url": "https://github.com/Dolibarr/dolibarr/issues/13018?email_source=notifications\u0026email_token=AIGN5DX3EPUD7UH4NNKZ6T3RBFAA7A5CNFSM4KPLGWY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKXD2UY#issuecomment-581844307", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1]
https://github.com/Dolibarr/dolibarr/issues/13018?email_source=notifications&amp;email_token=AIGN5DX3EPUD7UH4NNKZ6T3RBFAA7A5CNFSM4KPLGWY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKXD2UY#issuecomment-581844307
[2]

**Comment by appoloniaSrc** [comment]
Dears all,

A few informations about this issue, i encoured the same pb since i upgrade to verison 11.0. 
This issue is found on SUPLLIER Invoice onlye at the moment: **/fourn/facture/card.php**, on a CUSTOMER invoice the pb pb is not existing. 

**Process to reproduce**
1. Create an extrafield on supllier invoice line
2. Create a SUPPLIER invoice 
3. Add a product and inform your extrafield, in the creation process (when you add a product) the extrafield is correctlly recorded. 
4. Edit the line of the product and try to modify the extrafiled value, when you record it, the line of extrafield value is not recorded (still previous value in fact)

I send two screenshot one it show the process to reproduce and a second one show the debug line from debug bar, we can see in the INSERT request the extrafield value is not setted correctly. 

I saw on the changes logs that extrafields code is moved to array(), may be there is any troubles due to tit. 
![Dolibarr_extrafields](https://user-images.githubusercontent.com/29565150/73928573-9b5bb780-48d3-11ea-8256-d31204bd0c49.jpg)


Note the issue is really blocking for the exploitation we cannot use SUPPLIER invoice, and extrafields are mandatory for us. 

Thanks all.

**Comment by RubenRuCh** [comment]
https://github.com/Dolibarr/dolibarr/pull/13073

Can you try if this solve your issue?
