### ISSUE TITLE
Erreur de codage des accents

### ISSUE THREAD

**Issue by mreneb** [Dolibarr/dolibarr#13027]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Erreur de codage des accents

## Environment
- **Version**: V11.0.0
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: 7.3
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actuaL
Sur les note de frais, le paramètre APPROUVÉ ou PAYÉ. ne s'affiche pas correctement sur la version pdf du document
![B1CE71C0-2008-48D4-9E22-17EC1208E196](https://user-images.githubusercontent.com/60667541/73774023-925bd080-4783-11ea-9aea-1503803d97e5.png)

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
What is your language code ?

**Comment by mreneb** [comment]
French


Cordialement

Matthieu RENE-BAZIN

Envoyé de mon Ipad

**Comment by laurpaum** [comment]
Issue can be reproduced using French translation (or I guess any language using accentuated characters).

Create a new expense report, add a line and click validate and submit. Then preview the generated PDF, it will show "Valid&amp;eacute;" instead of "Validé".

Error comes from LibStatut() function in expensereport/class/expensereport.class.php.

In v10.0.x, this function used calls to $langs->transnoentities() whereas in v11.0.x it now calls $langs->trans() which includes call to htmlentities() resulting in HTML encoded return value.

Reverting to transnoentities() seems to fix the problem.

**Comment by mreneb** [comment]
👍

Cordialement

Matthieu RENE-BAZIN

Envoyé de mon Ipad
