### ISSUE TITLE
Translation: products.lang - DE

### ISSUE THREAD

**Issue by 2dig4it** [Dolibarr/dolibarr#13088]
file: dolibarr/htdocs/langs/de_DE/products.lang

CountryOrigin=Ursprungsland (add missing r)
p=u. better p=St. (abbreviation Stück)

If unitKG=kg
than it should be
unitG= g (not Gramm)
unitM3=m^3
... actually the same for all units i.e., unitM2,.. 

My background: German native speaker

**Comment by ksar-ksar** [comment]
Hi,

You should post that here : https://www.transifex.com/dolibarr-association/dolibarr/dashboard/

**Comment by eldy** [comment]
PR on files into langs/xx_XX where xx_XX is not en_US is useless because files are erased by Transifex translation of en_US. Change on translation files must be done with PR for en_US only. For other languages (en_NZ, es_ES, ...), fix of translation must be done directly on https://www.transifex.com/dolibarr-association/dolibarr/
