### ISSUE TITLE
Margin error, when assigning two sales commercials to the same Customer

### ISSUE THREAD

**Issue by cistelsa** [Dolibarr/dolibarr#13142]
I have a third party as a GENERIC CLIENT which I always invoice through Takepos in dolibarr 11, I use it to bill any person since we do not create customer names, to this third party "GENERIC CLIENT" we assign a commercial and everything perfect, it You can see the margin filtered by the selling user. But if I assign a second selling User to this same third party "GENERIC CUSTOMER" it does not show how much each user billed in the Margin since it shows the total value for each one in a wrong way.

**Comment by eldy** [comment]
If 2 sales representative are assigned to a thirdparty, when you get margin per sale representative, the amount of invoices of this thirdparty (imagine it is 100 euros) will be included for each one.
The sale representative A has sell for 100 euro, and the sale representative B has sold for 100 euros too. Both have a 100 euros sale in their record. But this addition will return 200. It just means it has no sense to add amounts per sale representative. But each one has generated 100. This is expected result. We must just know what the number means. This is for this reason that the application say a warning on screen:

>  "The report of margin per user use the link between third parties and sale representatives to calculate the margin of each sale representative. Because some thirdparties may not have any dedicated sale representative and some third parties may be linked to several, some amounts may not be included into this report (if there is no sale representative) and some may appear on different lines (for each sale representative)."

Because result are correct, but it is not correct to think we can make a sum of each line to retrieve total invoiced.

**Comment by cistelsa** [comment]
I understand, so how do I know how much each sales representative sold, considering that the same third party is used as a customer?

**Comment by altairis-tof** [comment]
in that specific case, you should assign sales representatives on each invoice and change the margin setup, otherwise have only one sales representative by customer.
