### ISSUE TITLE
Vendor SKU - option to set as non-mandatory field

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#13282]
# Feature Request

an option (global parameter ...) to set the **field  Vendor SKU**  as not mandatory field

we have a lot of customers wich have not always or not always a unique supplier artile number

**Comment by atm-maxime** [comment]
Not sure I understand. If you add a new supplier price for a product, the supplier sku is today mandatory. But this doesn't mean you can't add another supplier price with a different sku.
I think this field is mandatory and should remain so because when you do a purchase order, the supplier needs it's sku to understand which product you want to buy...

**Comment by dolibit-ut** [comment]
The SKU is more or less used 'only' by dealing with standard articles in a consumer or industrial environment, but not for individual order-related production or in agriculture/farming.
And than this field content make often troubles.

**Comment by mstoluca** [comment]
se puede poner no obligatorio?

**Comment by dolibit-ut** [comment]
> se puede poner no obligatorio?    >  can it be set as non-mandatory?

Without changing the php code?  I don't know how.

**Comment by Waraqa** [comment]
I need this feature.
Is it possible to add an option to make it non-mandatory for those who don't use it?
