### ISSUE TITLE
Add the possibility to rent a product

### ISSUE THREAD

**Issue by maxoghana** [Dolibarr/dolibarr#13746]
# Feature Request
Currently, we can only buy and sell product and there is no possibility to rent a product.
I would like to add functionnality to rent product.

## Use case
My company rent chairs and tables. 
I would like to be able to  : 
**Product :** 
- [ ]    buy product (currently available in dolibarr)
- [ ]    manage stock of my product in a wharehouse (currently available in dolibarr)
- [ ]     tag some of my product for renting or  some for sale or both
- [ ]     add a price for renting with a variant depending on the renting duration

**stock :** 
- [ ]      check how many items I have in stock for renting/selling for a specific product at anytime.
- [ ]      be able to switch some of my items from "for renting" to "for sale". For instance, after a time, I cannot rent my item because it's too used but I can sell it.

**proposal/invoice :** 
- [ ]     fill the renting duration and renting date
- [ ]      show easly the stock available at  that time or for similar product
- [ ]     adjust the price depending on the renting duration

**Comment by altairis-tof** [comment]
Hello, there is already an external module that completes all your requirements; maybe you might be interested : https://www.altairis.fr/en/shop/dolirent-equipment-rental-management-for-dolibarr/

**Comment by maxoghana** [comment]
Thx Altatof for you reply. I saw this module but I can't afford now to buy it. 

I saw on the forum that people are also interested. Maybe if I find few other guys who are interested to develop an free module with me I may start the development.

**Comment by JTMWi** [comment]
I'd love to help with the development of such a module in any way I can; it would be awesome to add this functionality to Dolibarr's core, and I'm sure it would help a great many people. (Different warehouses is an adequate  workaround for the time being, but this doesn't help with moving products in / out of inventory, nor the addition of the appropriate lines on proposals, invoices and other documents)

**Comment by altairis-tof** [comment]
i've been developing this module for years now and i can tell you it is not as easy as you seem to think, even if it has become more simple now with the hook system (that did not exist or poorly at the time i started the dev with dolibarr 3.2). IMHO it will take lot of time before having something approaching all the job done on Dolirent.
My only advice if you really want to do it is to think a lot about the functionalities needed and the user experience before writing any line of code, especially if you want to add it to dolibarr core.
It would be a big project and you need to really have good bases if you want to achieve it.
And please be inventive and do not just copy/paste Dolirent functionalities ;-)

**Comment by JTMWi** [comment]
I certainly don't think it would be easy! 

I also don't want to steal food out of your mouth but, on the other hand, I also think that this is something quite essential for a CRM. I've been looking at different CRMs for months now and although Dolibarr is the best I've seen so far (with Apache's "ofbiz" in a close second place), rental management is something that Dolibarr, too, misses - just like every other (open source) CRM out there. (although ofbiz does seem to include this functionality by default, but I can't assess that because their demo doesn't work).

I also want to give you props for this module: I've tested your demo (thanks for the opportunity) and it seems to be designed very well in terms of both UI and code, well thought-out and robustly implemented. If it didn't cost more than my employer is willing to pay, I'd jump on it like a cowboy on a steer! Bravo to you, sir.

**Comment by sunshuvo** [comment]
> Thx Altatof for you reply. I saw this module but I can't afford now to buy it.
> 
> I saw on the forum that people are also interested. Maybe if I find few other guys who are interested to develop an free module with me I may start the development.

Hi Maxoghana, 
Good to hear you are interested to create new module which is usefull to other as well as it is also usefull to me. Let me know if you need me, will help you whatever I can..
Thank you

**Comment by maxoghana** [comment]
Hi,

The request is still relevant and not yet covered by latest stable version

**Comment by LaplancheMaxime** [comment]
Hi,
Is this feature taken into account for the next versions?

**Comment by mschamp** [comment]
Hi,
I would also really like to have this functionality.
If it would be helpfull, I will help to develop this feature.
I understand it will be a lot of work and not an easy task, but I think many companies will like the feature.

**Comment by altairis-tof** [comment]
There is a solution already existing with Dolirent.
Please contact at altairis.fr or visit our website for more informations.

**Comment by mschamp** [comment]
> There is a solution already existing with Dolirent. Please contact at altairis.fr or visit our website for more informations.

I saw that, but I think it should be a module that is available within the default installation of Dolibarr.

**Comment by altairis-tof** [comment]
Why ?

**Comment by mschamp** [comment]
> Why ?


-  It would lower the entry threshold/ enable the use of dolibarr in companies that rent products (or have a combination of selling/rental).
- The module would be available in multiple languages (also helping the adoptation)
- Why only offering selling/ordering in the core modules and not rental?

- Adding it to the core modules of dolibarr would also motivate other companies to improve the implementation and update the functionality based on their wiches/experience/use cases.

**Comment by altairis-tof** [comment]
Hello, the aim of free opensource dolibarr erp is to give a core solution that can be extended by external modules for specific needs.
Our Dolirent solution is developped and improved since 2012 with customer financements and is now sold as a package of module or a hosted solution for 100€ per month.
It includes lot of functionalities like long term mode or one shot rents, lot /serie compatibility, possibility to have orders with rental lines and sale lines, and so on... 
Part of the work is a return module to manage equipment rental return and we have just improved it to manage sales return with credit note generation. 
We are currently starting a crowdfunding to integrate this return module into the core.
For the whole rental solution, the work to integrate 10 years of development in the core would certainly cost too many to do such a crowdfunding, and too much time to modify the core. 
Furthermore, and to be clear, we have a business model around this cheap solution (100€/month for such a solution is almost nothing comparing to the advantages for the companies) and that low cost is used to finance evolutions and following of new dolibarr releases (every 6 month !).
Big improvements and new functionalities are still financed by companies that need them.
I am sorry we do not work for free, but my butcher and my baker always want me to pay their work too.
And also all altairis employees want money at the end of the month ;-)
Best regards
Christophe

**Comment by mschamp** [comment]
I completly understand that you and your colleagues don't work for free (neither do I). And I understand the idea of the module and that it is quite complete and offers a lot of functionality.
Although from my opinion it would be very interesting to have a (basic) rental functionality in the free version.

It can also be a benefit for you: maybe now companies that rent products will not consider Dolibarr because of the lack of the rental functionality. If a basic functionality would be available they can try/consider it. Once they see the benefits of Dolibarr they maybe want a more extended rental function and order your package.

€100/month is not much, but to much for the case i'm considering: It is a small company that mainly sells products, but has 2,3, max 4 rented products per month.

**Comment by git-putz** [comment]
Maybe update the verbiage to "rental or lease"
Have an asset management module to track serialized equipment/assets that are company owned.  
Then have some way to create a rental or lease for a third party for a specific period of time where the asset(s) can be assigned to the rental/lease.
Also would be a plus if the rental/lease could be incorporated into an invoicing.  For example the ability to create a sales quote that includes the lease at specific term and cost.  If its approved then prompt to assign the asset to the lease and have it created under the third party that is leasing the equipment.

**Comment by altairis-tof** [comment]
Hello, we organize an online presentation in french of the DoliRent solution on March 30 ! https://www.altairis.fr/webinaire-dolirent-cloud-2/

**Comment by maxoghana** [comment]
Still révélant. Please keep it open. Maybe one day. De could get this new feature

**Comment by altairis-tof** [comment]
https://www.dolistore.com/en/modules/2037-Dolirent---Rental-Management---14-0-x---18-0-x.html

**Comment by mschamp** [comment]
> Still révélant. Please keep it open. Maybe one day. De could get this new feature

Completly agree that (at least a basic version of) rental management would be a good feature for the default version of Dolibarr

**Comment by lmag** [comment]
I suggest you discuss the subject of rental on the forum. The essential elements have been integrated into the core of Dolibarr
https://www.dolibarr.fr/forum/t/gestion-de-location-de-materiel-avec-dolibarr/31501

**Comment by Doliflex-net** [comment]
hello guys,

there is a working external module for this rental issue, that adds additional column for rental duration, and updates calculations formula as per below > Total HT = unit price * Qty * duration

check this blog in french for additional informations

https://doliflex.net/module-location-dolibarr-doliflex/

**Comment by Nexyll** [comment]
I think this issue deserves to be reopened and discussed again.

First, I'd like to acknowledge the excellent work done by existing external modules such as DoliRent and others. They provide advanced rental management features that many companies need, and they clearly demonstrate that the use case is real.

However, I don't think the existence of commercial modules should automatically exclude a basic rental capability from the core.

Dolibarr already includes the foundations for sales, purchases, stock, warehouses, serial numbers, proposals, orders and invoices because these are considered common business processes. Renting products is just as common in many industries (construction equipment, events, furniture, audiovisual, medical equipment, tools, etc.).

The objective would not be to replace existing commercial solutions, but to provide a minimal, generic implementation that could include for example:
- marking a product as rentable
- defining a rental period on commercial documents
- checking product availability over a given period
- generating the corresponding invoice

More advanced features (returns workflow, damage management, maintenance, long-term rental, pricing rules, planning, deposits, etc.) could remain in external modules.

In fact, having a basic implementation in the core could even benefit external module developers by lowering the adoption barrier for rental businesses and providing a common API and data model on top of which advanced modules could build.

Given the number of users who have expressed interest over the years, I believe this feature request is still relevant and would deserve to be reopened as a long-term core enhancement, even if the implementation is incremental over several releases.
