### ISSUE TITLE
Replenishment integration with manufacturing orders

### ISSUE THREAD

**Issue by ToniTen** [Dolibarr/dolibarr#13756]
# Feature Request
Currently, Replenishment only shows products that are classified as purchased, even if you don't have a current vendor for the product. With the addition of manufacturing orders, there is another way to meet desired stock requirements, so products with a BoM should appear under replenishment even if they aren't purchased, and you should be able to create manufacturing orders from replenishment

**Comment by atm-maxime** [comment]
I reopen this feature request that seems relevant to me.
Currently, replenishment is designed to create supplier orders. It works well and also take into account the products needed in MO because virtual stock calculation checks MO.
I think we shouldn't mix the current replenishment function, but create another one very similar for products having a BOM and generate MO instead of supplier orders.

**Comment by elsp1991** [comment]
Hello @atm-maxime,

I totally agree that this is a valid feature. But I was thinking is still nicer to have all your missing stock in one page. I think is totally possible to mix them since each product has this special property "type of product" that can be "raw material" or "manufactured product" using this parameter we can propose the either the existing implementation that is for products that you can buy so "raw material" and for "manufactured products" instead of a list of suppliers we can have a list of BOMs that produce this product.  We have to decide what happens in the case that the "type of product" is not set and in the case that BOM and supplier exist for one product.

If you have a branch that you work already on that I would be happy to contribute.

**Comment by ToniTen** [comment]
@elsp1991 I agree that having both PO creation and MO creation in a single screen is the best option (and that's why my original proposal wanted to enhance replenishment so everything was done through a single replenishment process)

I feel that differentiating with the current "type of product" in the product card is not a good idea. In my case, it would not be useful, and the reason for this is that for quite a few products, they nare "manufactured products" and we normally assemble them, but if we end up missing some of the parts, we have the option of buying them fully assembled from the supplier (which was rare, but it much more common given the current pandemic).

**Comment by atm-maxime** [comment]
For me having this in the same screen / same function is not a good idea. The user who deals with suppliers and send the orders is not the same as the one dealing with MOs and production planning. And the process is not the same after generating x draft supplier orders and w draft mos. And the best argument is that the raw material needs is based on MOs, so MOs must be created first to have the correct stock replenishment values... That's why I would keep it separated.
