### ISSUE TITLE
Alarm stock and preference stock set to NULL in db

### ISSUE THREAD

**Issue by jongerli** [Dolibarr/dolibarr#13805]
# Bug
[*Short description*]

## Environment
- **Version**: 11.0.02 11.0.3
- **OS**: Server 2012
- **Web server**: IIS
- **PHP**: 7.2
- **Database**: MySQL

## Expected and actual behavior
Fields are not included while filled in .. eg new product entered. Alarm stock and preference stock entered at 0 and then in the stock tab, nothing is entered. At least not the "0" value. In the database there is a NULL value.

## Steps to reproduce the behavior
When creating a new product, the explicit filled in values for Alarm stock and Preference stock are 0 but this value is not saved in the database.

**Comment by Langlais115** [comment]
I reproduce only the _alarm stock_ issue under version 12.0.0-alpha
# **Environment**
-  **Version:** 12.0.0-alpha
-  **OS:** Linux (Ubuntu 18.04.1)
-  **Web server:** Apache2 (version: 2.4.29)
-  **PHP:** 7.4
-  **Database:** MySQL 5.7.30-0ubuntu0.18.04.1

# **Result from the test**
### Test 1 : 
Product creation with _Stock limit for alert_ "0" and _Desired Stock_ "0"

Result in DB:
Stock limit for alert = NUL
Desired stock = 0

### Test 2 : 
Product creation with _Stock limit for alert_ "2" and _Desired Stock_ "1"

Result in DB:
Stock limit for alert = 2
Desired stock = 1

### Test 3 : 
Following the test 1 I check what value was in the field _Stock limit for alert_ in the product "settings>stock" tab
This fealty didn't display anything
So I edit the _Stock limit for alert_ in the product "settings>stock" tab and put "0"

Result in DB:
Stock limit for alert = 0

So the issue is at the product creation level for the setting _Stock limit for alert_.
In version 12.0.0-alpha the issue about _Desired stock_ mention by OP seems to be resolved (at least under my environment)
