### ISSUE TITLE
ODT option for automatic Vat Type Selection

### ISSUE THREAD

**Issue by hussain-attari** [Dolibarr/dolibarr#13838]
HI,

**The Issue:** 

While preparing the invoice under the Indian GST Tax system we bill the item for inter state sale at 18% [IGST] and if the same item is sold to a customer located inside the same state it is billed under  9% / 9% [CGST / SGST]

ODT Tags for each have been provided

IGST: {line_vatrate}

CGST / SGST: {line_localtax1_rate} and {line_localtax2_rate}

We currently have to manually change the tax rate as required. This can be done for 1 or 2 items however, if the number of items is more then its cumbersome. Also, if an item is not updated then the tax amount is not reflected in the invoice as a result incorrect tax amount is displayed.

**Our Feature Request**

A way to read the complimentary attribute and insert the relevant vatrate or local_tax_rate using the IF ELSE statement in ODT.

We have created a 'Complimentary Attribute' as a 'radio button' in the Invoice module. To identify whether the invoice is being made under IGST or SGST / CGST

**Alternate and a Better Method for Resolving the Issue**

While making the Third Party we enter the 'Prof Id 1 (GSTIN)' of the Party and each third party we enter the address and the State/Province of the third party.

If an ODT tag is generated for identifying the state shortcode* then we can automate the selection of the tax rate to be applied using the IF ELSE statement.

Also, please provide a way to show the same under the _Tax Type [IGST or CGST/SGST]_ and _Total Tax Amount_ in the row located below.

State Short code Example: if state is Andhra Pradesh then the short code is AP [This feature already exists.]

I have attached my ODT templates for better understanding. Currently using separate templates for IGST and CGST_SGST

**CGST_SGST**
![CGST_SGST](https://user-images.githubusercontent.com/47553388/81257732-a4cefa00-9051-11ea-9daa-b6c91dcd2b8e.jpg)

**IGST**
![IGST](https://user-images.githubusercontent.com/47553388/81257767-bd3f1480-9051-11ea-87ad-5873cd5532dc.jpg)

**Comment by hussain-attari** [comment]
Any update on this?

**Comment by mxmp210** [comment]
I've managed to implement GST with 3x Taxes rules in which IGST is local_tax & CGST / SGST is tax1 and tax2 respectively.
It calculates these things perfectly except when it comes to fixing Tax rate in Purchase Order.

Sales order module is already supporting feature of defining default tax rate and sales rates as per Customer, this same logic can be applied to Purchase order and it will allow setting tax rates / classes & prices according to set rules, you simply apply IGST on other state customer / supplier by these rules and SGST / CGST on third parties residing in same state. makes this process much easier.

the only problem is, PO module doesn't support default tax & also there's bug in 12.0.1 which shows tax1 & tax2 as 0/999.999/999.999% instead of 0/9/9 for 9% Tax Split when changing tax from local_tax to tax1+tax2 combination.

If anyone can help giving insights, it would be great!
Keep in mind that Sales Module is working as intended while Purchases don't have functionality & may be using old code creating this bug. I'll be looking into it but any help is appreciated to fix it.
