### ISSUE TITLE
deprecated curly braces array access

### ISSUE THREAD

**Issue by fx2300** [Dolibarr/dolibarr#13929]
Hi 
In php 7.4 curly braces array access is deprecated.
For example in core/antispamimage.php line 45 (v. 11.0.4)
$string .= $letters{mt_rand(0, $number - 1)};
should be:
$string .= $letters[mt_rand(0, $number - 1)];

**Comment by Langlais115** [comment]
Ref: [https://www.php.net/manual/en/migration74.deprecated.php](https://www.php.net/manual/en/migration74.deprecated.php)

**Comment by Langlais115** [comment]
I'll create a pull request for files owned by dolibarr project, but I notice that some third party library are using curly braces as well.
What should we do with them? do we fix third party files that are into dolibarr or do we try to update them with newer version? (We should keep in mind the risque that it might brake things) 
I search for **`\$[a-z0-9_]+\{`**

- htdocs/includes/phpoffice/phpexcel/Classes/PHPExcel  (100+ usages found) => Deprecated since 2017
- htdocs/includes/phpoffice/PhpSpreadsheet/Reader  (6 usages found)
- htdocs/includes/restler/framework/Luracast/Restler  (2 usages found)
- htdocs/includes/tcpdi  (9 usages found)
- htdocs/includes/tecnickcom/tcpdf/include/barcodes  (4 usages found)

Another thing. Should we replace this as well:
Ex:
$obj->{$fieldlist[$field]}
by this
$obj->[$fieldlist[$field]]

In this case search for this **`\$[a-zA-Z_\-\>0-9]+\{`**
If it is the case, I found around 700 matches.

**Comment by Langlais115** [comment]
After a closer look, only **phpexcel** third party have some curly braces to be replace.
As phpexcel is deprecated no more official update will be release so I guess that we can do the modification in dolibar repo.
Should I do the modification or should we way to migrate to PhpSpreadsheet?

**Comment by eldy** [comment]
It is better to keep unchanged an external library.
Currently PhpSpreadsheet is available in core but it is used only for export module and not for import.
Updating the import.php page to use PhpSpreadsheet instead of phpexcel will allow to remove completely phpexcel. I did it for export.php but i had no time to do it for import.
Help is welcome...

**Comment by Langlais115** [comment]
We can close this issue I guess, as it's a duplicate from the issue #8172
