### ISSUE TITLE
Expense reports stats on statistics dashboard of home page wrong

### ISSUE THREAD

**Issue by suged** [Dolibarr/dolibarr#13932]
11.0.3
The number of expense reports displayed on statistics dashboard of homepage does not take into account the user connected
(Always displays total number)

**Comment by suged** [comment]
pour corriger, on peut modifier la requête dans load_state_board() de expensereport.class.php
```
global $conf,$user;

$this->nb = array();

$sql = "SELECT count(ex.rowid) as nb";
$sql .= " FROM ".MAIN_DB_PREFIX."expensereport as ex";
$sql .= " WHERE ex.fk_statut > 0";
if (!$user->admin) $sql .= " AND ex.fk_user_author = ".$user->id;
$sql .= " AND ex.entity IN (".getEntity('expensereport').")";
```

**Comment by atm-maxime** [comment]
Hi ! Thanks for contributing.
I think this is expected behavior. All statistics on the home page are global. Having them filtered by the user connected is a feature request. And it needs some discussion before coding to agree on what it should do.
For example, a manager would want to see all expense report from its subordinates, the accounting team for all employees, ... I don't think this is the "admin" property we should use. And beware, on expense report, the fk_user_author is not necessarily the user concerned by it. Use fk_user instead.
And after, we have to think about other modules. Should the user see only its projects ? Its proposals ? ...

**Comment by suged** [comment]
The other modules display only what the user is entitled to see in this stats board (for projects, invoices, ...). The only discrepancy I noticed is on expense reports. So I think it should be the same logic... don't you see the same?
(total number is displayed in the "meteo" dashboard on the top)
And I think in the database table you don't have fk_user on expense report, if you want to keep it simple you have to choose between _author, _modif, _valid, _validator, _approve, _refuse, _cancel

**Comment by atm-maxime** [comment]
My mistake on the fk_user_author column, you're right, that's the good column.
Yes users see only data they are entitled to see. But not necessarily data they are the author of. For projects, if they don't have the permission to see all, they see projects they're associated to or public projects. For invoices, orders, proposals, ../, they can see all, or only the ones related to thirdparties they are salesrep of (if they can't see all thirdparties).
Finally, I find that you're right for expense report. If they don't have the permission "Read expense reports of everybody", they should only see theirs and their subordinates ones. I just made a PR for this : #13944

**Comment by suged** [comment]
thanks !
