### ISSUE TITLE
Bug: Invoices Le total des lignes ne peut pas être négatif pour un taux de TVA donné.

### ISSUE THREAD

**Issue by fpav** [Dolibarr/dolibarr#13942]
![2020-05-21_19-05-48](https://user-images.githubusercontent.com/58973675/82585327-1d779f80-9b96-11ea-88db-fe99320179c8.jpeg)
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 11.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.18
- **Database**: MySQL or MariaDB 5.7.26-log
- **URL(s)**: /compta/facture/card.php?facid=51&action=valid&page_y=290

## Expected and actual behavior
Impossible to apply specific discount on an invoice for a specific customer.

## Steps to reproduce the behavior
Create a new standard invoice
When prompted, create before validating it a new discount as client and apply any amount
Validate creation of the invoice
apply discount for such customer
Add any product to meet positive amount of the total invoice
try to validate and you'll get the error message
## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by eldy** [comment]
This is the expected behaviour: The sum for all lines with a VAT 0% is currently negative.
If you want to grant a discount on an invoice with a VAT of 20%, your disount line must also have a VAT of 20%.

**Comment by fpav** [comment]
Ok, so in that case how do you deal with suppliers like sumup which are paying you on your account with the amount of your sale minus the commission which is witout tax. I give you the instance :

My payment received corresponds to 24,56 € which will be written in the bank account but VAT shall be calculated on 25 € because the bank commission is without tax, so to meet the bank monthly recipe I should have only one entry not 2. That's why I considered that this way could work by introduction of :

0,44 € Commission for bank (without tax)
25 € payment with 20 % tax

Invoice payment : 24,56 € corresponds to what is written in the bank recipe.

**Comment by BebZ** [comment]
it depends if your customer pays the Sumup 0.44€ or if your company pays it

If your company pays it, in my opinion you should register 
a sales invoice for the products you sold for 24.56€ tax included with VAT 20%
and a supplier invoice for the "sumup"  0.44€ without VAT

the same line of bank account is used to conciliate ?

if your customer pays the sumup you should display a positive amount not a negative one

**Comment by fpav** [comment]
it depends if your customer pays the Sumup 0.44€ or if your company pays it

My company pays it.

If your company pays it, in my opinion you should register
a sales invoice for the products you sold for 24.56€ tax included with VAT 20%
and a supplier invoice for the "sumup" 0.44€ without VAT

the same line of bank account is used to conciliate ?

Yes and if I do so then I have 2 lines in my bank account. Moreover, if I do an invoice with 24,56 € with 20 % VAT, then my VAT to pay is 4,912 € but it is wrong because my sale is in fact 25 € so VAT should be 5 € so if I do what you mention, then my VAT is false.

if your customer pays the sumup you should display a positive amount not a negative one

**Comment by eldy** [comment]
So if the charges of Sumup are payed by yourself:

Sumup charges you. As any company that take you money for a service, they must provide you an invoice that you must register as a vendor invoice. Sumup may simplify the process of taking you money by taking their commission directly into each customer payment instead of at end of month so on your bank account you have a different amount that your customer has paid. But legally, this difference must not be removed from your customer invoice. 

You must not make a confusion between the amount that is visible on your bank account and the amount visible on your customer invoice. If your company pays the Sumup charges, sumup information must NOT be visible into your customer invoice, above all, the VAT of 0% between you and Sumup must never appears ! 
If your customer pays 25 euros with tax and you are elligible to a 20% vat, then, you must make you invoice with 25 euros and then part without tax must be 25 euros - 20% (what charge sumup and what is the vat between sumup must and you must have no effect on your customer invoice). So, yes the part of the VAT will be a little bit higher. This is the principle of the VAT. If you try to have only 20% of 24.56 euros of VAT when your customer pay 25 euros, I recommend to prepare yourself to big problems with your governement when you will get a control.

This means your sumup account record will not match your invoice record. But at the end of month, you should have an invoice from Sumup with amount of all charges and sum of all of this amount including taxes (in your cas taxes seems to be applied only to customer) must be equals. Sumup is not a bank, so reconciliation will not match on each line but only at end of month when you will enter a vendor invoice to take into account all the charges sumup has charged for you during the month. If you try to match your customer invoice with the amount on sumup, you just make things that are not legal according to accounting rules. At end of month it will be equals when including the Sumup invoice (you can also make a sumup invoice for each sell you do, but it is not a common way of working because payment system do often only one invoice report for charges per month).

**Comment by fpav** [comment]
I see, so , il will leave two entries in the bank account and cope with it. Thanks anyway for your feedback.

One thing would be if possible then to prevent anybody to do so in the discount possibility?

Regards,

**Comment by dpriskorn** [comment]
> I see, so , il will leave two entries in the bank account and cope with it. Thanks anyway for your feedback.
> 
> One thing would be if possible then to prevent anybody to do so in the discount possibility?

Is this a feature request?

**Comment by Boubou-it** [comment]
pour ceux qui ont le même problème que moi (Amazon me fait les versement et me facture mais en fonction du pays le taux de TVA des frais Amazon ne correspond pas au taux de TVA des produits vendus.
![Image](https://github.com/user-attachments/assets/a590260c-06aa-4063-ba70-6dc424074042)

Accueil -> configuration -> divers 
-> Nom : ALLOW_NEGATIVE_TVA_LINES
-> Valeur : true

-> ajouter

![Image](https://github.com/user-attachments/assets/62b08733-fdec-42fc-bfa3-ef01a44a469f)

Et voila problème résolut
![Image](https://github.com/user-attachments/assets/ffe4b578-8b52-4b63-9ca9-1f25a13cac21)

Une belle facture !!!

![Image](https://github.com/user-attachments/assets/ccec0e0b-3330-43bd-bbf0-e786d28626a3)
