### ISSUE TITLE
Accurate time tracking for projects

### ISSUE THREAD

**Issue by paddatrapper** [Dolibarr/dolibarr#14144]
# Feature Request
Please allow project task time tracking to be done by clicking a button at the start of work and a button at the end. Provided the web page stays open for the duration of work, this time can be used to populate the time spent form to submit into a task

## Use case
We use the time tracking feature to Track employee time for salary payments. It would be useful for them to be able to start tracking time when they begin a task and stop tracking when they finish instead of having to do that manually and entering the manual calculation into the time spent

**Comment by dpriskorn** [comment]
There are lots of tools to do this outside of Dolibarr. 
Emacs org mode can do this. 
TimeTracker on fdroid can do this.

**Comment by paddatrapper** [comment]
There are other apps that can do it, however this requires staff to have both and double enter all data around timings - track in their app of choice and then enter into Dolibarr. Having the feature directly in Dolibarr, extending the existing time-tracking makes this much easier

**Comment by dpriskorn** [comment]
Ok I understand that. 
Using the browser to collect this is not ideal because of accidental data loss because of session timeouts, user navigating away, etc.
I could add this functionality to my Dolibarr Python API and write a simple GUI-frontend in tkinter. That would make it easier to collect the data and the user does not have to keep the browser open because the program simply sends the timedata directly to the server via the REST API. Does that sound interesting to you?
The GUI would have these parts: 1) choosing a project in a dropdown list, 2) recording buttons, 3) save to dolibarr button. 4) error pop-up. 5) enter the api key and server url popup.

**Comment by paddatrapper** [comment]
That sounds very interesting. Do you have a link to your Python API? I am much more comfortable with Python than PHP, so could certainly help with it

**Comment by dpriskorn** [comment]
Hi paddatrapper. You are welcome to contact me on egils@riseup.net for more information.
