### ISSUE TITLE
BUG: ajax_object_onoff not functionnal v12

### ISSUE THREAD

**Issue by ptibogxiv** [Dolibarr/dolibarr#14201]
switch (activated with hidden option MAIN_DIRECT_STATUS_UPDATE, not functionnal with thirdparty and product.

Display, click but no changes in database and when refreshing always on (or off)

![image](https://user-images.githubusercontent.com/3135833/86914228-3aedd200-c120-11ea-957b-3b7649a83cef.png)

edit: this bug affects all switch buttons everywhere

**Comment by dpriskorn** [comment]
Sorry, I don't understand this report at all. Could you copy the bug report template and fill it in? Otherwise we might as well close this IMO.

**Comment by ptibogxiv** [comment]
this secret function is no more functionnal (when clicking no action is done in database)

**Comment by ptibogxiv** [comment]
@eldy PRIORITY BUG! this bug affects all switch buttons with ajax everywhere on dolibarr (product sale/buy and admin settings) (no action saved)

**Comment by dpriskorn** [comment]
Please add the information asked for. I don't understand the problem at all. What does the option you mention do?

**Comment by fappels** [comment]
I confirm also this bug, but find this a bad hidden option and always advice my customers not to use because no update triggers are executed using this option.

**Comment by dvdwalker** [comment]
I was looking into this since I have the same problem. The issue seams to be that starting in version 12 the "[element]_UPDATE" trigger is called in file core/ajax/objectonoff.php but some properties that are required on $object are not set. Those are (at least for product that is what I use):

- $object->id
- $object->table_element
- $object->fields[$field]

The error occurs on the setValueFrom function in core/class/commonobject.class.php file

A quick fix that worked for me was to change objectonoff.php as shown below (added lines 83-85).

![on off fix](https://user-images.githubusercontent.com/9135955/109007471-e84f2f00-768a-11eb-9f50-fa68179c7153.png)

I'm not creating a PR since I'm sure my solution is not the most elegant but I'll keep working on this to provide a clean fix

Hope it helps
