### ISSUE TITLE
Bug: annoying POST question from browsers when navigating back to list.php

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#14454]
# Bug
I think its a bug to use POST for simple search parameters in list.php. It results in the browser (Pale Moon, GNU Icecat) asking me in a popup every time if I want to resend the request with the search params.
In Chrome its even worse because it results in a ERR_CACHE_MISS and the user gets a verbose admonishment to resend the request by manually finding and pressing the refresh-button.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.8
- **Database**: PostgreSQL 12.3
- **URL(s)**: /product/list.php

## Expected and actual behavior
no question from the browser because everything is GET-based and the URL is enough

## Steps to reproduce the behavior
navigate to list.php
search for something
navigate to a product from the result
press back

**Comment by spsolauv** [comment]
I agree with @dpriskorn 

This problem is still there on last stable version. It's a widespread problem in Dolibarr that is not only encountered in search forms and which could be fixed by using proper HTTP method (GET or POST depending context) and applying post/get/redirect pattern (see https://en.wikipedia.org/wiki/Post/Redirect/Get). But before to be a technical issue, it is mainly a UX problem for final users, who are using Dolibarr and who are annoyed by their browser asking to redo the action they just did, even for a simple search.

Indeed, there are many POST requests which are directly returning HTML content to the browser without doing a 30x redirection to another response page in GET method.

Maybe it is just a consistency problem, since there are pages which are already managing this properly, like product creation, which makes a redirection (to the product url in GET) after having created the product.

### Current search list behavior in Dolibarr

- user makes a search in product list (submit form using POST)
- Dolibarr receives the request and search in Database
- Then Dolibarr returns directly HTML content to display created product
- So request response received by the browser is a POST response
- If user needs to display previous page, the browser will ask to resend POST request because it will ensure that the user wants to make the POST request again

#### => using pattern POST / Redirect / GET, it should be :

- user makes a search in product list (submit form using POST)
- Dolibarr receives the request and searches in Database
- Then Dolibarr should send back a redirect header
- Browser receives the POST request containing only the http redirect header
- Browser will ask for the new location using GET method
- Dolibarr returns the HTML content to display the list of products
- If user needs to display previous page, it will simply go back to previous GET page (browser doesn't need to ask for user confirmation)

### Current product update behavior in Dolibarr

Currently : 

- user modifies an existing product (submit form using POST)
- Dolibarr receives the request and modifies database (product is updated)
- Then Dolibarr returns directly HTML content to display updated product
- So request response received by the browser is a POST response
- If user needs to display previous page, the browser will ask to resend POST request because it will ensure that the user wants to make the POST request again

#### =>using pattern POST / Redirect / GET, it should be :

- user creates an existing product (submit form using POST)
- Dolibarr receives the request and modifies database (product is updated)
- Then Dolibarr should send back a redirect header
- Browser receives the POST request containing only the http redirect header
- Browser will ask for the new location using GET method
- Dolibarr returns the HTML content to display the updated product
- If user needs to display previous page, it will simply go back to previous GET page (browser doesn't need to ask for user confirmation)

### Conclusion

GET method should be used when user is asking for a page content (display single product, display thirdparty list search results...)

POST method should be used for actions having an impact (as modifying data stored in database or submitting a form contact...)

And for POST requests, good practice would be to use post / redirect / get pattern.

As a solution for search lists, I thought to a Javascript code which would intercept form submit (in POST) and then sends request in GET), but it would only fix it on search list pages. A more global and proper fix should be better, but would certainly touch large parts of PHP code.
