### ISSUE TITLE
Upgrade DoliWamp 11 -> 12  is not possible

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#14640]
Hello,

ist it right, that an Upgrade from WoliWamp 11 to DoliWamp 12 ist not possible,
because of switching the database engine?

**Comment by eldy** [comment]
Yes, and no : It is not possible to benefit of the "automatic" upgrade by just double clicking on the .exe of v12 when coming from v11 or lower to move to v12.
But it is still possible to upgrade from v11 (or lower) to v12 by making a backup and a restore. But this need technical knowledge.
The README of v12 says:

WARNING FOR DOLIWAMP USERS ONLY:

Only people that installed Dolibarr using the all-in-one auto-installer for Windows called "DoliWAMP" are concerned by the following warnings:
 
* DoliWAMP auto-installer for Windows is no more available on 32 bits systems. Use standard package if you need to use such architecture.
* It is not possible to migrate from an installation done with the old DoliWAMP auto-installer for Windows by using this new one. You must make a backup of your database, make a fresh installation using the new installer and reload your backup. Don't forget that DoliWAMP is a good solution to make a quick test of Dolibarr on your local computer but is not recommended as a production solution on a local desktop since a local desktop computer has often no backup and security policy, or not as good as on a server (when there is one). DoliWAMP remains a solution for fast test or demo purposes. Prefer using standard packages, deployed on a server, for production.

**Comment by dolibit-ut** [comment]
Okay. Thank you for the information.
