### ISSUE TITLE
MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND not work

### ISSUE THREAD

**Issue by dadyhood** [Dolibarr/dolibarr#14705]
Hi, 

It's look like MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND don't work on version 10.0.1.

I still try but the calculation of VAT still going by line.

Anyone know why ?

**Comment by ksar-ksar** [comment]
Hi,

This variable doesn't have any link with VAT calulation.
It is related to TTC : Change way of rounding total TTC lines, rounding first of after.

**Comment by dadyhood** [comment]
Hi,

Thank you, so can we calculate the VAT on the HT to get TTC and not line by line ?

**Comment by eldy** [comment]
Try to upgrade to v12. If you still have trouble with MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND, please add a screenshot of your order, proposal or invoice to show us detail of line you got.

Note: since now several years, there is no more software that use this old method to calculate vat detail (hits method was used before computer was introduced to make accountancy).

**Comment by dadyhood** [comment]
" Dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l’option $dolibarr_main_prod sur ‹ 1 › pour supprimer quelques notifications):
Date: 20210107182405
Dolibarr: 11.0.5
Niveau de fonctionnalités: 0
PHP: 5.5.12
Server: Apache/2.4.9 (Win32) PHP/5.5.12
OS: Windows NT LAPTOP-5A456MB2 6.2 build 9200 (Windows 8 Home Premium Edition) i586
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

Url sollicitée: /dolibarr/comm/propal/card.php?id=41
Referer: http://localhost/dolibarr/comm/propal/card.php?id=41
Gestionnaire de menu: eldy_menu.php

Modules/Applications: user, expensereport, propal, accounting, agenda, cron, ecm, facture, ficheinter, fournisseur, holiday, resource, salaries, societe, service, tax, loan, banque, margin, product, prelevement, stock, projet, fckeditor, import, export
Message: A rounding difference was detected into TOTAL but is too high to be corrected. Some data in your line may be corrupted. Try to edit each line manually."

**Comment by dadyhood** [comment]
Anyone can help ?

**Comment by dadyhood** [comment]
No one know about this ?

**Comment by Timoune974** [comment]
if it can help you dadyhood 
tested with succeed in Dolibarr 12.02
Put the parameter MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND ==> 1 
In 'limit and precision" section change the 
Maximum number of decimal places for unit prices ==> 2 
Maximum number of decimal places for the amounts displayed on the screen ==> 2 
and for me during my unit tests it's working :)

**Comment by DomiMacMan** [comment]
For years, we've been experiencing this persistent issue, which I regularly revisit for research across different Dolibarr versions: V10, V13, V17, and now during testing on V20. The same problem persists. (I've never encountered this type of negative VAT issue in other management software like Sage, EBP, or Météor).

Here's a link to a Dolibarr forum thread where I've landed again and taken the time to illustrate the problem with screenshots and recalculations, hoping that a solution might exist that I simply haven't found or understood yet:

https://www.dolibarr.fr/forum/t/calcul-de-la-tva-faux/19995/4?u=domimacman

And below is a screenshot demonstrating that this problem is not recent."

https://lists.gnu.org/archive/html/dolibarr-dev/2011-01/msg00032.html
<img width="871" alt="Image" src="https://github.com/user-attachments/assets/f59dc7f7-d1d1-459f-b3f4-afb30dabb32e" />

**Comment by Thiago-Morais** [comment]
This issue still happens

Why was the `Issue Stale (automatic label)` removed, but the issue was not reopened?

**Comment by hregis** [comment]
@Thiago-Morais can you reload and send screenshots with your problems ?
five years with no fix it's not possible !!!
