### ISSUE TITLE
Bug: No send email from member form.

### ISSUE THREAD

**Issue by FeliceCor** [Dolibarr/dolibarr#14715]
# Bug
Hello, I report an error that prevents me from sending an email from the member form.

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.3.22
- **Database**: MySQL or MariaDB 5.5.5-10.3.24-MariaDB
- **URL(s)**: /htdocs/adherents/card.php?id=1&action=presend&mode=init

## Expected and actual behavior
When I select the member's tab from the member form and try to send an email or an email template when clicking on submit it goes to an error page, as indicated in the attached video.
Greetings

## Steps to reproduce the behavior
[video_dolibarr-1.mkv.zip](https://github.com/Dolibarr/dolibarr/files/5212722/video_dolibarr-1.mkv.zip)

**Comment by ksar-ksar** [comment]
Hi,

You have a 403 error : This is most probably linked to your hosting, need to see the rights on the folder/files and if there is any .htacess fils that could do some filtering.
If you don't find anything ask your hosting provider.

**Comment by FeliceCor** [comment]
Hi,
I saw the files with FTP and the permissions in the folders are at 755 and the files with 644, this should be regular.
The fact is that sending emails works well with third parties and from this error with the members tab.
In the haderent folder there is no htaccess file.

**Comment by ksar-ksar** [comment]
Hi,

Could you post the access.log and error.log of your hosting ?

**Comment by FeliceCor** [comment]
Hi,
attached as you requested
[gestione.evergete.it.zip](https://github.com/Dolibarr/dolibarr/files/5225295/gestione.evergete.it.zip)

**Comment by ksar-ksar** [comment]
Hi,

If you have a look on your log, you should be able to find the reason of all that : 
`[Mon Jun 08 21:44:14.759633 2020] [:error] [pid 18400:tid 140160493020928] [client 62.11.xxx.xxx:54698] [client 62.11.xxx.xxx] ModSecurity:  [file "/etc/httpd/conf/modsecurity.d/rules/tortix/modsec/12_asl_adv_xss_rules.conf"] [line "37"] [id "341256"] [rev "18"] [msg "Atomicorp.com WAF Rules: Possible Cross Site Scripting attack (detectXSS)"] [data "4951,ARGS:message"] [severity "CRITICAL"] Access denied with code 403 (phase 2). detected XSS using libinjection. [hostname "gestione.xxxxx.it"] [uri "/htdocs/adherents/card.php"] [unique_id "Xt6VDs0He@iltsji7-VnvgAAACc"], referer: https://gestione.xxxxxx.it/htdocs/adherents/card.php?id=1&action=presend&mode=init`

You have problems with the rules of the ModSecurity 

This is related to your hosting, not due to Dolibarr
