### ISSUE TITLE
Recruitment module - non english code

### ISSUE THREAD

**Issue by cfoellmann** [Dolibarr/dolibarr#14753]
recruitment is still in the early stages but there are again file names with french terminology.
what is `candidature`? it that the person applying that is called `candidate`?

**Comment by ksar-ksar** [comment]
Hi,

Sorry but this is an english word : https://www.collinsdictionary.com/dictionary/english/candidature

**Comment by cfoellmann** [comment]
But that does not make sense here.
on the pages "called" `candidature` you track your candidates.

**Comment by eldy** [comment]
With the object candidature, we track candidature, not candidate (it is nearly the same but candidature is a "candidate request for 1 given job position", if 1 candidate apply for 2 job positions, we will create 2 record).
But term "candidacy" may be a better translation ?

**Comment by cfoellmann** [comment]
I am not a professional translator but have done a lot of translations.
For me `candidates` are people looking to get voted or accepted into a political or honorary position.

For a job the people are `applicants` and their request to get the job is an `application`

**Comment by atm-maxime** [comment]
I agree that a better translation would be application (candidacy) and applicant (candidate)

**Comment by atm-florianm** [comment]
I completely agree with @cfoellman regarding the terminology, but since this issue seems to be about file names and/or variable names (not `.lang` files), it might be too late to change them (some external modules may already be relying on the misleading names, and fixing them might break compatibilty).

[edit]
Sorry, I didn't get that this was about the new v13.0 feature… I'll have a look then; please forget my previous comment.

**Comment by cfoellmann** [comment]
I think that this an alpha feature so it should be good to change this before going a step further.
as much as i like the speed new features are coming, older features as mostly not really usable because of some crucial part missing.

There should be a big break with new features for v14 and only make this an improvement release. Adding needed features to existing parts and polishing up the code.

**Comment by atm-florianm** [comment]
> I think that this an alpha feature so it should be good to change this before going a step further.

Yes, I realized that a minute ago. It should be possible to fix this terminology issue, except for strings that get inserted into the database (such as `recruitmentcandidature`). Actually, even for those, a migration script could be provided so that users who already use the feature can update their data.

**Comment by atm-florianm** [comment]
I’m having second thoughts about this mass renaming… it turns out to be harder than I figured.

**Comment by cfoellmann** [comment]
That is what I thought but should be done,
Moving from the French expressions to ENG is hard too. But it makes the project more open to international audiences

**Comment by cfoellmann** [comment]
maybe adding new features should be a PR as long as it is not "complete" that way multiple devs can have a look and give input in naming and translations
