### ISSUE TITLE
Indexe unique sur llx_societe_remise

### ISSUE THREAD

**Issue by torbenpyndiah** [Dolibarr/dolibarr#14788]
# Bug
J'ai remarqué que si on clique rapidement deux fois sur le bouton ajouter une remise relative, deux fois la même entrée est crée.
Il faudrait ajouter un indexe unique sur fk_soc je pense dans la table llx_societe_remise.

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
Cliquer deux fois sur le bouton ajouter dans tiers/clients/remise relative

**Comment by eldy** [comment]
Are you speaking about the relative (%) or fixed discount (amount). Adding an index on fixed discount is not a good solution, because we may want to have several discount, with same amount.
A new feature is coming (for security purpose) to forbidden to submit twice the same form. i suggest to wait this feature that will also solve this ticket.

**Comment by torbenpyndiah** [comment]
Hi, are both stored in the same table?
I am talking about the relative discount.
Ok, nice to know about the feature. Thank you!

**Comment by eldy** [comment]
For the "relative discount", you can have only 1 value for a given thirdparty.
