### ISSUE TITLE
Print product list lost filters

### ISSUE THREAD

**Issue by dbeniamine** [Dolibarr/dolibarr#14958]
## Description

On the product list, clicking the print button resets the filters, If you set the filters after going in print view, you are back to the normal list view.

## environment

+ Dolibarr : dolideb 12.0.3
+ Debian 10
+ Apache 2.4 : Server version: Apache/2.4.38 (Debian)
+ Mariadb 10.3 : mariadb  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
+ Php 7.3 fpm :  7.3.19-1~deb10u1

**Comment by atm-jpb** [comment]
try to reproduce your bug here 
![01-pr](https://user-images.githubusercontent.com/68547382/103754034-19589f00-500c-11eb-9ca6-fa59b81dcc38.png)
the filters remains after cliked print button.
![02-pr](https://user-images.githubusercontent.com/68547382/103754088-2e353280-500c-11eb-825b-ebc9312df6b4.png)

i suggest to update your dolibarr version from 12.0.3 to 12.0.4.

**Comment by dbeniamine** [comment]
I upgraded to 12.0.4 last monday, the problem persists ...

After a deeper inspection it seems to concern only the tag/category filter
