### ISSUE TITLE
Filter by default for lists

### ISSUE THREAD

**Issue by Mx74** [Dolibarr/dolibarr#15043]
# Feature Request
Being able to chose what is the default filter when displaying lists

## Use case
User of Dolibarr for more than 14 years now, we have a pretty long list of products. 
With the time, some products kept the same name, but different version have been added, like:
2008: Item 
2010: Item V2
2012: Item V3 ....

Of course older products have been deactivated both for sell and buy.
But when looking for "Item" in the product list, the complete listing Item, Item V1, ... ,Item Vn appears, and now the list of inactive product is longer than the list of active products. 
It easily sorted out by selecting in the filter bar Active product for sale and buy, but this is an extra unnecessary manipulation. 

So, being able to say "display only active product by default" would be a plus. 

Same would apply for any list, like customers list,

**Comment by atm-maxime** [comment]
In latest versions, there's a dedicated setup area for default values on forms, default filters and sort on lists, ... Check in home / setup.

**Comment by aspangaro** [comment]
And if you want, you can complete default values on list (button for filters, sort) with the module quicklist available on dolistore :

https://www.dolistore.com/fr/modules/863-QuickList.html?search_query=quicklist&results=1

**Comment by Mx74** [comment]
Thanks for the hint regarding the dedicated setup. 
But some example would be useful, as it's not self explanatory, and the wiki page is poorly documented. 
https://wiki.dolibarr.org/index.php/Setup_Default_values/filters/sorting

**Comment by UlusoftConsultancy** [comment]
I recently added a default search filter for actions. I will explain how this works.

For example: I wanted to set the default search filter for agenda events users (agenda_filter.png) to be empty so I can see all the events when I navigate to the agenda interface. For this, you have to note the URL for this specific page (agenda_url.png). In this case it was under comm/action/index.php . Then you have to open the element inspection window of chrome and select the selectbox you want the filter to apply on. You will see an id when you are searching the element inside the inspection page (agenda_element_inspect.png). You can see that the select box I was hovering on had the id of : search_filtert. Then you simply fill in this information inside the Setup>Default Values>Filters like in the image (default_filter_settings.png). I gave the default value of -1 because the first option inside the selectbox has a value of -1

![default_filter_settings](https://user-images.githubusercontent.com/93868548/153454064-4cc47757-4082-4d5c-b1c9-9c0c98d1267d.png)
![agenda_element_inspect](https://user-images.githubusercontent.com/93868548/153454068-f497c57c-50f0-4dbd-b8db-8c92e8a1aded.png)
![agenda_filter](https://user-images.githubusercontent.com/93868548/153454070-9210ca42-b213-4118-bbf3-0c9e4825d735.png)
![agenda_url](https://user-images.githubusercontent.com/93868548/153454072-5c9eacb0-c517-4235-9623-b77d483f56f2.png)
.
