### ISSUE TITLE
Virtual product, batch, and stock

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#15129]
Hi everyone;

I have a doubt and I would like to understand why this action isn't possible.

I try to set the stock of a product composed of 1 other virtual product. Those products use the batch number.

When I try to set the stock of the parent product I receive this error message (sorry it's in french) ...
![image](https://user-images.githubusercontent.com/3658458/97055326-e2372d80-1586-11eb-84e4-b328e87a73ec.png)

Can someone explain to me why this action isn't possible? Is it a bug?

I found in the code where to set the dates and the batch number but if it's not present I guess there is a reason ...

Cheers
L.

**Comment by atm-maxime** [comment]
My guess is that virtual product and module batch are not compatible with each other. Virtual product is used to have automatic stock movement, but movement can't be automated if you have to set a batch on it...

**Comment by laudeco** [comment]
Why not by example if you have compress that are available in pack of 20 and also by unit 

When you buy 20 units actually your stock of  unit is increased by 20.

So actually there is no difference between the batch of the pack and the unit 

Isn't it ?

Cheers

**Comment by atm-maxime** [comment]
So in your case you use the virtual product to deal with packaging right ? I don't think it has been designed for that.
And what if your virtual product is composed with 2 sub products ? They surely won't have the same batch as the parent...

**Comment by laudeco** [comment]
> So in your case you use the virtual product to deal with packaging right ?
Indeed, do you have another solution to increase the stock by the number of products in the package?

> And what if your virtual product is composed with 2 sub products ?
That's the only problem that I see. We may limit the usage of the batch on the virtual product only if there is one sub product.

What's your input @eldy @aspangaro ?

Cheers
L.

**Comment by eldy** [comment]
The virtual product is a feature to manage "Kit".
For example "Promotional kit of christmas" than contains 1 product A (chocolates) and 1 product B (oranges).
When you sell your kit for quantity 1, you must change stock for product A and product B. Lot/serial number for product A differs for product B, so automatic stock change is for the moment not possible. We must be able to manage the input of each lot/serial of each sub-product to be able to record a stock movement of a kit that contains sub-product that need lot/serial.

**Comment by laudeco** [comment]
Ok
What about the problem of a pack?

Eg:
I sell one chocolate or a pack of 10 chocolate

In the first point I have to decrease my stock by one and in the other I have to decrease my stock by 10 but it's the same stock of the same product "chocolate"

How do you achieve that?

Cheers
L.

**Comment by prietojc** [comment]
The matter that @laudeco comments affects several pending issues (#5342, #5824, #7210, #11653, #11636).
The source of the problem is that products typically come in multi-unit packages. You could think of doing three things:
- A kit (virtual product)
- A variant (sizes and colors)
- A manufacture (BOM)

but it doesn't really fit either case. There is only one product packed in different size boxes.
The solution is to manage the **packaging** in some way and to be able to indicate:
- Types of packaging
- Units per package
- Reference
- Size, volume, weight.

As a minimum, you would have to add a field in the product file that indicates the number of units per package (I have an extrafield), but I think the best in the long term would be to move and group everything in a new characteristics tab along with:

- Nature of the product
- Weight
- Length x Length x Height
- Surface
- Volume
- **Packaging** (with the possibility of several definitions)
