### ISSUE TITLE
New widget : Encours dépassé

### ISSUE THREAD

**Issue by emsproto** [Dolibarr/dolibarr#15307]
# Feature Request

Avoir un widget sur la page d'accueil qui gère les dépassements d'encours de tous les tiers et qui liste les tiers dont l'encours est dépassé
## Use case
Contrôler a l'arrivée d'une nouvelle commande si le tiers a dépassé l'encours afin de lui dire de régulariser son encours afin de valider la nouvelle commande

## Suggested steps
Des emails paramétrables pourraient être envoyé au moment d'un dépassement d'encours
premier mail : gentil
deuxième : moins gentil
troisième mail: mail de dernière relance un peu sec

**Comment by dolibit-ut** [comment]
translation to english:

### Feature Request

Have a widget on the home page that manages the outstandings of all third parties and lists the third parties whose outstandings are exceeded.

### Use case

To control has the arrival of a new order if the third party has exceeded the outstanding amount in order to tell him to regularize his outstanding amount in order to validate the new order.

### Suggested implementation

### Suggested steps

Customizable emails could be sent when an overrun occurs.
first mail : nice
second: less nice
third mail: the last mail of the last reminder is a bit dry.
