### ISSUE TITLE
Bank entries : add user link on salary payments in the thirdparty column

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#15323]
# Feature Request
We would like to add a link to a user card in the bank entries, in the thridparty column, for salary payment lines. Currently the thirdparty column shows the thirdparty link when we are on a customer or supplier payment.

@eldy @aspangaro is it ok to use the same column for this thirdparty notion ?

**Comment by atm-thibaultf** [comment]
Also, we would like to do the same with social/fiscal tax entries and not only for salary payment (to have the user on the thirdparty column for social/fiscal tax payment when a user is associated to the tax).

**Comment by aspangaro** [comment]
In reality, this feature was never implemented because of a security issue. 

Indeed, people who have access to the bank module and the salary module can see the details of the net salaries paid but if they don't have access to the salary module, we can't see which employee it concerns even though we do have access to the bank. Thus, we hide the employee's information without emptying the list of bank entries...

**Comment by atm-thibaultf** [comment]
Ok, I understand, maybe we could do it linked to the permission to access to the salary module. The bank entries is shown for user who has access to the bank module but the name of the user linked to the salary is shown in the third party column only for user who has access to the salary module. I don't know if it's possible but should it be ok like that ?

@ludovicandrieux Just so you know this task is visible by the Dolibarr community.

**Comment by ludovicandrieux** [comment]
I like your idea @atm-thibaultf 
This permission (VIEW tax or VIEW salary) already exists.
With a standard message in bank, there is no disclosure of information.
What do you think @aspangaro ?
