### ISSUE TITLE
Modify length of societe.url

### ISSUE THREAD

**Issue by matDOTviguier** [Dolibarr/dolibarr#15562]
# Feature Request
Modify lenght or type in DB of societe.url
## Use case
Google maps link
## Suggested implementation
VARCHAR 255 seem to short for some url (ie Google maps)

## Suggested steps
MariaDB supports 65535 VARCHAR.

**Comment by daraelmin** [comment]
Hi, 

I'm not sure what you would like, but your request seems to require new functionality.

Instead of modifying the "societe.url" attribute which should store the third party's website, it seems you need a localization module (why only for third-party? It could be interesting for member and contact). There's already something of this kind in the statistics of provenance of the adherent module, perhaps this is a track that has been studied.

If not, possibly you could create an extra company field with the name "location" to store the Google Map urls.

Cheers

**Comment by matDOTviguier** [comment]
It's while trying to add a long url to the "societe.url" that I knocked on the varchar 255 limit.
A localization module is another thing IMO.
