### ISSUE TITLE
Passwords can be stored in clear in database

### ISSUE THREAD

**Issue by papoteur-mga** [Dolibarr/dolibarr#15596]
# Security
Passwords are stored in clear in database

## Environment
- **Version**: 11.0

## Expected and actual behavior
The database has in table `llx_user` the column `pass` which contents password in clear. It has also `pass_crypted` which is fine
Passwords shouldn't be stored in clear, but only in encrypted form.
I have then enabled "Chiffrer les mots de passe stockés dans la base de données (PAS en texte brut).". Then passwords in column `pass` has been deleted.
I think that this has not to be an option and should be the default behaviour.

**Comment by eldy** [comment]
The column pass is no more used.
Password are now stored encrypted into column pass_crypted. 
If you have clear password, it's probably because you disabled the default behaviour "store encrypted password" from your setup (available for backard compatibility with very old systems). Just restore the defaut setup.

**Comment by papoteur-mga** [comment]
My installation is not so old, perhaps five years.
And why not migrate to the new behaviour the old ones?

**Comment by matDOTviguier** [comment]
**I** need a clearpassword for another use, I made it possible by an extra field.
