### ISSUE TITLE
Bug: "order method" is a required field in make order

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#15657]
# Bug
this is a bug IMO. I don't care how the order was made, I would rather save 2 clicks than have to type this in. Additionally it defaults to none. It should have a reasonable default instead that saves clicks. Maybe a user preset default in the settings? 

## Environment
- **Version**: 12.0.2
- **OS**: Linux
- **Web server**: nginx/1.18.0
- **PHP**: fpm-fcgi 7.4.13
- **Database**: PostgreSQL 12.5
- **URL(s)**: /fourn/commande/card.php?id=250&action=commande

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by dolibit-ut** [comment]
Hey, i don't see this field at Version 12.0.3.
Can you send a screenshot.

**Comment by dpriskorn** [comment]
Its a form that appears when you press "make order"

**Comment by dpriskorn** [comment]
Still present in v13

**Comment by priojk** [comment]
I think it would be helpful, if it was possible to set a default value for the order method (field: methodecommande) via 
start->settings->default values/filters/sorting. Currently, this seems not to be the case.

Alternatively, the default first empty entry could be omitted, so that the first entry of the defined list will be automatically preselected, saving the mandatory clicks to select something. This requires just one parameter to be set from 1 to 0 but removes some kind of protection for cases, where the correct selection is important and should be enforced.

This is the relevant line in fourn/commande/card.php, the addempty parameter just needs to eb set to 0 and the default can be determined bu the order of the dictionary entries used in this selection.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/10772984/207831550-aa1942b7-c994-4982-a9c3-823d41e0e797.png">


@dpriskorn the issue may be re-opened from my point of view

**Comment by FlorentPoinsaut** [comment]
@priojk I wrote a patch to add the ability to set a default value: https://github.com/Dolibarr/dolibarr/pull/24676
What do you think about it?

**Comment by priojk** [comment]
Thanks for taking the initiative. I already sent an answer to your PR. It seems as if we tackled the issue almost at the same time, but I forgot to mention it in this issue, because I was addressing the underlying problem while solving a different bug where it was also not possible to set a default value.
