### ISSUE TITLE
Extrafields  interventions dont be on PDF

### ISSUE THREAD

**Issue by webmasterproxy-media** [Dolibarr/dolibarr#15803]
extrafields dont be printed on pdf

v12 /wamp

https://www.dolibarr.fr/forum/t/extrafield-pdf-sur-les-interventions/33432

**Comment by john-botella** [comment]
Hi

Displaying Extrafields on PDF depending of PDF model compatibility.
This feature was include in V12 of Dolibarr see https://github.com/Dolibarr/dolibarr/pull/13185 and https://github.com/Dolibarr/dolibarr/pull/13179
Actually compatible models include in Dolibarr are : 

- espadon (V12) for shipping
- eratosthene (V12) for order
- sponge (V12) for invoice
- cyan (V12) for quotation
- cornas (V12) for supplier order

- Storm  (V13) for delivery

For me it's not a bug but a feature request because there is actually no interventions PDF model using the new PDF generation columns  system.
But modules can add new models based on on new PDF model system. 

So, for me the good title for your issue is : 
Need new PDF model compatible with new col system and extrafields display feature on  PDF
