### ISSUE TITLE
Bug: Unable to edit the pricing in Sales Order

### ISSUE THREAD

**Issue by asolslk** [Dolibarr/dolibarr#15820]
# Instructions
Unable to update the pricing of the product in the Sales order as it throws error and unable to save, error trigger on the tax field tva_tx=0_0

# Bug
[*Short description*]

## Environment
- **Version**: 12.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.3.23
- **Database**: MySQL or MariaDB 5.6.40-84.0-log
- **URL(s)**: /commande/card.php?id=51

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Capture](https://user-images.githubusercontent.com/52134143/103203332-9fe7ef00-492f-11eb-9604-00935a5db954.JPG)

![2](https://user-images.githubusercontent.com/52134143/103204752-ff93c980-4932-11eb-94dc-e42b9df9b114.JPG)

**Comment by zuiko** [comment]
I agree,
it's more generally impossible to modify a line of a customer order, even for the quantity.
The only workaround is delete the line and re-create it. Not cool...

**Comment by dpriskorn** [comment]
Regression bug? I cannot reproduce on 12.0.2

**Comment by asolslk** [comment]
> Regression bug? I cannot reproduce on 12.0.2

This happened in multicurrency enabled SO which the VAT is 0.

![1](https://user-images.githubusercontent.com/52134143/104093597-6cf61180-52c6-11eb-87ab-4d3fa42d91b8.PNG)
![2](https://user-images.githubusercontent.com/52134143/104093601-71222f00-52c6-11eb-8f8a-10f32b8f50ad.PNG)
![3](https://user-images.githubusercontent.com/52134143/104093608-78493d00-52c6-11eb-9516-a5381841a395.PNG)

**Comment by zuiko** [comment]
@asolslk 
On my installation (V12.0.4), the multicurrency module is disabled...

**Comment by dpriskorn** [comment]
I have it enabled

**Comment by asolslk** [comment]
Its seem the issue was triggered by the tva_tx which receiving the value of 0_0 that is not identify by the script. The tva_tx in the database of the table either is 0 or 7 (set to 7% tax), but when trying to edit in the SO and save, the value given as in the debug msg showing the text is 0_0

**Comment by asolslk** [comment]
i have try to update the quote, and seem like the only different is the apostrophe, should be '0_0' instead of 0_0.

![a](https://user-images.githubusercontent.com/52134143/104144406-0e33b380-53fe-11eb-9b2d-e18e9d93ed28.PNG)

**Comment by yorkhood** [comment]
Not only SO, but invoice module as well. 

     sql=UPDATE llx_facturedet SET description='', label=null, subprice=6.65301, remise_percent=0, fk_remise_except=null, vat_src_code = '', tva_tx=7-, localtax1_tx=0, localtax2_tx=0, localtax1_type='0', localtax2_type='0', qty=1, date_start=null, date_end=null, product_type=1, info_bits='0', special_code='0', total_ht=6.65, total_tva=0.47, total_ttc=7.12, total_localtax1=0, total_localtax2=0, fk_product_fournisseur_price=null, buy_price_ht='0', fk_parent_line=null, rang=12, situation_percent=100, fk_unit=NULL, fk_user_modif =3, multicurrency_subprice=5, multicurrency_total_ht=5, multicurrency_total_tva=0.35, multicurrency_total_ttc=5.35 WHERE rowid = 1357
   DoliDBMysqli::query SQL Error message: DB_ERROR_SYNTAX You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', localtax1_tx=0, localtax2_tx=0, localtax1_type='0', localtax2_type='0', qty=1,' at line 1

It shows tva_tx=7- (my VAT is 7%), I'm using 12.0.4 stable version with multi-currency enabled

**Comment by zuiko** [comment]
The abnormal case seems to receive 0_0 as tva-tx which is alphanumerical and reveals a not set VAT.
So the issue seems to be more in the function price2num($this->tva_tx) which has to give a numerical 0 when the VAT is not set and not 0_0...
When the VAT has been set for all products, it seems that the issue disappears.

**Comment by zuiko** [comment]
fix proposed in function price2num in htdocs/core/lib/functions.lib.php

add underscore and - in the pattern in instruction 
`$amount = preg_replace('/[a-zA-Z\/\\\*\(\)\<\>]/', '', $amount);`
as this:
`$amount = preg_replace('/[a-zA-Z\/\\\*\(\)\<\>\_\-]/', '', $amount);`
in order to cover some constantes cases as 20% (TX_NORMAL) or 10% (TX_REDUIT) where underscore is used.
it seems that some constantes use also "-" so I added it also in the pattern.
I don't know if more characters have to be added to this pattern.

**Comment by zuiko** [comment]
Hi,
It could be possible that this problem was bigger than I thought:
On the english forum [somebody has problems with cyrillic characters...](https://www.dolibarr.org/forum/t/issue-with-vat-in-vendor-invoice/20093/4)
So I fear that the principle of the original coding (and my fix) is not sufficient to cover all cases.
