### ISSUE TITLE
ORDERS: delivery date should be a datetime

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#15898]
https://github.com/Dolibarr/dolibarr/blob/007ae5978835b657c8c3e4ef921ed223869c9d71/htdocs/commande/class/commande.class.php#L189

at least the database field should be a datetime instead of date.
We are loosing an information provided by our partners.

**Comment by dpriskorn** [comment]
Suggest won't fix. @homer8173  you can add a custom field to orders if you need more precision. I added loads of fields to my installation because I want internal notes, reports, planned delivery date, etc. directly on the order. If you are loosing information you need to model the data in Dolibarr better before synchronizing from the source. I sell Dolibarr services you are welcome to contact me if you need help.

**Comment by homer8173** [comment]
Thanks for answer, but I'm not agree. Extrafield are for custom usage and this is a general need.
Thanks for offering your services, please send us some of your references & prices at support @ oscss-shop.fr
