### ISSUE TITLE
Import external calendar (Google calendar) and twice schedule

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#16157]
# Instructions
When import google calendar (ical) , you will see two times event .
 And one event will delay one day .

# Bug
Could import ical but get two times event in different day .

## Environment
Version: [Version 13]
OS: [Windows 7 and MX linux 19.3]
Web server: [Apache 2.4.41]
PHP: [7.4.1]
Database: [MariaDB 5.5.5-10.4.11]

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/78349579/106759447-bd665200-666d-11eb-9e29-7924fdc09595.png)

**Comment by eldy** [comment]
Can't reproduce with future 13.0.1 so i suggest to wait this version to test again.

**Comment by JESSTOFUNK** [comment]
This is happening since Version 8, I have not figured out if this is a mismatch in the importing for external calendar, even time offset on the configuration does not correct this. 

My server time is GMT-3
My local appliance is fixed to GMT-6 with  MAIN_SERVER_TZ Americas/Mexico_City
Original ICal server is GMT-8

Maybe all this server time mismatch causes this behavior.
![Captura](https://user-images.githubusercontent.com/61986181/106967551-fbff1980-670c-11eb-988d-8048f3c0373a.PNG)

 We will try with V13.0.1

**Comment by ksar-ksar** [comment]
Hi,

Have you tried with V13.0.1 ?

**Comment by trekmorris** [comment]
Hi 

I have tried v 13.0.1 , and  it is good in windows server and linux server .

**Comment by JESSTOFUNK** [comment]
Hello @trekmorris do you mean windows and linux locally?

When it is in a local environment works good, but when you try with your browser running in a different TZ than your server this happens.

I have still not try with V13.0.1. Let me try.

**Comment by trekmorris** [comment]
Hi @JESSTOFUNK 

Yes , i  try this in same time zone local server . 
If your issue happen in different TZ , then i think we need to wait your testing .
