### ISSUE TITLE
Warehouse liste with filter on ref value

### ISSUE THREAD

**Issue by BLC59** [Dolibarr/dolibarr#16308]
Hey

there is a bug when filtering warehouses by ref 
please follow this post : 
[https://www.dolibarr.fr/forum/t/entrepot-tri-par-ref/35708/3](url)

**Comment by ksar-ksar** [comment]
On Dolibarr V 11.0.5

When doing a search by warehouse reference : 

`SELECT t.rowid, t.ref, t.entity, t.description, t.lieu, t.fk_parent, t.address, t.zip, t.town, t.fk_departement, t.fk_pays, t.statut, t.datec, t.tms, SUM(p.pmp * ps.reel) as estimatedvalue, SUM(p.price * ps.reel) as sellvalue, SUM(ps.reel) as stockqty FROM llx_entrepot as t LEFT JOIN llx_product_stock as ps ON t.rowid = ps.fk_entrepot LEFT JOIN llx_product as p ON ps.fk_product = p.rowid LEFT JOIN llx_c_departements as c_dep ON c_dep.rowid = t.fk_departement LEFT JOIN llx_c_country as ccount ON ccount.rowid = t.fk_pays WHERE t.entity IN (1) AND (ref LIKE ‹ %09% ›) GROUP BY t.rowid, t.ref, t.entity, t.description, t.lieu, t.fk_parent, t.address, t.zip, t.town, t.fk_departement, t.fk_pays, t.statut, t.datec, t.tms ORDER BY t.ref ASC LIMIT 51
Error :  DB_ERROR_1052`

Seems to be because on file product/stock/list.php, need to add prefix : 
![image](https://user-images.githubusercontent.com/35605507/108047102-b7954700-7045-11eb-96ea-71aed7e2992e.png)
