### ISSUE TITLE
migration issues

### ISSUE THREAD

**Issue by tiaris** [Dolibarr/dolibarr#16315]
# Instructions
installing upgrade to 13.0.1

# Bug

Erreur  DB_ERROR_1071: ALTER TABLE llx_recruitment_recruitmentcandidature ADD  UNIQUE INDEX uk_recruitmentcandidature_email_msgid(email_msgid);Specified key was too long; max key length is 767 bytes
--
Erreur  DB_ERROR_1071: ALTER TABLE llx_recruitment_recruitmentcandidature ADD  UNIQUE INDEX uk_recruitmentcandidature_email_msgid(email_msgid);Specified key was too long; max key length is 767 bytes

## Environment
- **Version**: 13.0.1
- **OS**: Debian
- **Web server**: Apache
- **PHP**: 7
- **Database**: 5.5.5-10.1.48-MariaDB-0+deb9u1
- **URL(s)**: install/upgrade.php?versionfrom=12.0.0&versionto=13.0.0

**Comment by ksar-ksar** [comment]
Hi,

What is the Engine and Collation of the table llx_recruitment_recruitmentcandidature ?

**Comment by tiaris** [comment]
Hi 
Collations are utf8mb4_general_ci in DB but in conf/conf.php I have utf8_general_ci
Engine is Mariadb on Debian as indicated

**Comment by ksar-ksar** [comment]
Exactly the problem is mb4.

utf8mb4 requires more storage space than utf8 

You need to modify your table to utf8_general_ci

**Comment by tiaris** [comment]
We should taje the collation indicated in conf.php file not -taken when migrating and creating/updating database to avoid a system/server specific setting

**Comment by ksar-ksar** [comment]
Hello,

I don't agree, all the dolibarr table should be utf8_general_ci
The others collation are supported.

You have a script to force collation : /install/repair.php?force_utf8_on_tables=confirmed

**Comment by tiaris** [comment]
Yes all the table should be utf8-general-collation, but when I run the dolibarr migration/install script some table were created in utf8mb4_general_ci even if the dolibarr conf file has the right collation It seemed not be used by install scripts.

Thank you for the link

**Comment by eldy** [comment]
Into conf file, the collation should be utf8_general_ci and it is used when a database is created to set the default collation of database. So when you create new table, utf8_unicode_ci is used.
If you have a different collation for the database, you shout modify it for next table creation.
For tables already created, you can fix their collation by calling /install/repair.php?force_utf8_on_tables=confirmed

Another solution you can try. Launch
SET GLOBAL innodb_default_row_format='dynamic';
Before running the migration script (you must convert the format if table has already been created).
So the default format for table will be dynamic instead of compact (dynamic is the default on recent version only). With dynamic format, the limit of length of index should not be a problem. In future this will solve such trouble for everybody, however a lot of old database are still set to 'compact' by default instead of 'dynamic'.

For 13.0.1, we will try to reduce size of field so utf8mb4_general_ci will not generate troubles event when row format is not dynamic by default and if utf8_unicode_ci is not page code by default.
