### ISSUE TITLE
{company_name} in ODT not filled

### ISSUE THREAD

**Issue by danielprowald** [Dolibarr/dolibarr#16323]
# Bug
In the proposal ODT gneration the fild {company_name} will be empty

## Environment
- **Version**: [*Affected Dolibarr version(s)*] 13.0.0
- **OS**: [*Server OS type and version*] Ubuntu 20
- **Web server**: [*Webserver type and version*] apache

**Comment by trekmorris** [comment]
Hi 

This same as issue #16128 .

**Comment by atm-maxime** [comment]
Use # + issue number to add a link between issues.
#16128

**Comment by danielprowald** [comment]
I found the "Problem".
The Customer Date was changed after the creation of the proposal.

**Comment by trekmorris** [comment]
Hi 

How do you fix it ?

**Comment by eldy** [comment]
Take a look at the warning on this page https://wiki.dolibarr.org/index.php?title=Create_an_ODT_document_template
Surely the trouble.

**Comment by trekmorris** [comment]
Hi @eldy 

I have take a look that wiki page again , but i still have no idea with this issue .
My odt file works on v12.0.4 , so it won't have  invisible information in that odt file .

**Comment by soaplander** [comment]
Hi @eldy , I'm having the same issue. 

I realized the {company_name} will appear properly when I do not select a company contact, however when I do, neither the {company_name} or any of the contact info like {contact_fullname} will be reflected in the generated document.

**Comment by glu000** [comment]
This is a new bug in V13 in php-scripts htdocs/core/modules/<module>/doc/doc_generic_<modul>_odt.modules.php

The following line makes no sense, because !isset OR !empty is always true:

if ($usecontact && ($object->contact->fk_soc != $object->thirdparty->id && (!isset($conf->global->MAIN_USE_COMPANY_NAME_OF_CONTACT) || !empty($conf->global->MAIN_USE_COMPANY_NAME_OF_CONTACT))))

Also the following line makes no sense

$socobject = $object->contact;

because $socobject should be a Societe object and not contact

I'll provide a fix

**Comment by ksar-ksar** [comment]
Hello,

One workaround proposed by Libremaster is to put MAIN_USE_COMPANY_NAME_OF_CONTACT to 0 in Setup->Other

**Comment by Ced-C** [comment]
Hi 
I have the same issue, in v13 & v14, has the fixed been included in some release ? 
if not, I will try the workarround
