### ISSUE TITLE
Adding a product or service by pressing ENTER does not add to an order or an invoice after the first item

### ISSUE THREAD

**Issue by akhalz** [Dolibarr/dolibarr#16398]
# Bug
During order or Invoice creation, if you are adding a product item (either a free product or predefined product), by pressing the Enter key, the item is not added to the order or invoice. This only happens after the first item

## Environment
- **Version**: [13.0.1]
- **OS**: [Linux]
- **Web server**: [Apache/2.4.46 (CentOS)]
- **PHP**: [7.3.26]
- **Database**: [MySQL or MariaDB 5.5.5-10.2.36-MariaDB]
- **URL(s)**: [commande/card.php?id=18679#addline]

After selecting the product from the predefined list, I am able to "Tab" to the price which automatically is populated. I then edit the quantity of that item, and press the Enter key to add the product line to the order or invoice. This works fine for the first item but not the second and successive items after that. If I use the mouse to click the add button the line is successfully added.

**Comment by akhalz** [comment]
Just wanted to confirm that this also occurs when editing a line that has already been added.
For example in an draft order page, I edit a product item and change the quantity or the price, I then hit enter instead of clicking on save then the changes that were made during the edit will not be made and it will revert to the original information

**Comment by dvdwalker** [comment]
Apparently the issue was introduced with the addition of the "Update VAT for all lines" feature. Since the input field "submitforalllines" is listed first on the form that is the action sent by default when submiting the form by pressing the Enter key to submit any line change.

A possible solution would be to change the "submitforalllines" input tag for a button tag and adding the corresponding style.

**Comment by akhalz** [comment]
Thanks, awesome work on the quick bug fix
