### ISSUE TITLE
Bug: Can't set the date in batches

### ISSUE THREAD

**Issue by leninrivas** [Dolibarr/dolibarr#16529]
# Bug
Can't set the date in batches, in expedition error: ErrorBadValueForParameterEatBy

## Environment
- **Version**: 13.0.1
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 5.6.40
- **Database**: MySQL or MariaDB 5.5.5-10.3.23-MariaDB
- **URL(s)**: /product/stock/productlot_card.php

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
![Set date](https://user-images.githubusercontent.com/53640168/109821704-425c7100-7c04-11eb-8c67-5e2a332b328c.jpg)

**Comment by eldy** [comment]
When do you get the error ErrorBadValueForParameterEatBy ? Can you provide screenshot of page that show the error message ?
The shipment recording will never ask the date of DLC or DLUO because it uses a batch number. And DLC and/or DLUO are set when the batch number has been recorded into database (so during stock entry). However, shipment may check that you use a valid batch number with valid date. Here it seems your date is not valid (i don't know reason why). Can you try edit it from the page of lot to set it to empty.

**Comment by leninrivas** [comment]
When leaving it empty, both fields, one of them is automatically leveled with that data from 1969
![Arror ](https://user-images.githubusercontent.com/53640168/109982889-540b4a80-7cd0-11eb-9f7a-23bf201bd560.jpg)

**Comment by leninrivas** [comment]
Solved version 14.
