### ISSUE TITLE
May I change the name of de dolibarr and directory?

### ISSUE THREAD

**Issue by alimentarius** [Dolibarr/dolibarr#16540]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Feature Request
[*Short description*]

## Use case
[*Verbose description*]

## Suggested implementation
[*Verbose description*]

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by ksar-ksar** [comment]
Hello,

What is your question ?

**Comment by atm-maxime** [comment]
Countless people don't understand the issue template and let the basic text... How could we change that ?

**Comment by matDOTviguier** [comment]
@atm-maxime The problem could be the English language. You can put a link to a video showing a user writting a correct bug report ? Even in French, we have countless people don't write a correct ticket while asking for name and phone numer and a short description of the problem. You can also add a button "Do Not Work". :)

**Comment by Arre8** [comment]
Hi,
may be some people find the git without knowing forum in their language exist ?
adding lines in front of the template could redirect them :
"![image](https://user-images.githubusercontent.com/13518576/110085784-d0b22d80-7d91-11eb-97d9-a3990fbe5a46.png) Before posting here while completing this form, see [the forum](https://www.dolibarr.fr/forum) to make sure your problem is a real bug and/or a feature that doesn't already exist."
"![image](https://user-images.githubusercontent.com/13518576/110085720-ba0bd680-7d91-11eb-87a4-4ac21b9a6b32.png) Avant de poster ici en complétant le formulaire ci dessous, voir [le forum](https://www.dolibarr.org/forum) pour vous assurez que votre problème est bien un bug et/ou une fonctionnalité qui n'existe pas déjà."

in bold..
in red color..
flashing..
and appears while rotating 
during 5 minutes :)

**Comment by dolibit-ut** [comment]
and maybe a 4th  'New issue'  template for a general questions / notice 
- without to many details / requests
- but with a simple instruction template in it

**Comment by ksar-ksar** [comment]
> 
> 
> and maybe a 4th 'New issue' template for a general questions / notice
> 
>     * without to many details / requests
> 
>     * but with a simple instruction template in it

Better to send them to forum for this.
