### ISSUE TITLE
Excel import/export files present a jump of columns up to column 'Z'

### ISSUE THREAD

**Issue by syrinx75** [Dolibarr/dolibarr#16567]
# Bug
The example Excel files proposed to import data into Dolibarr have several empty columns before the 'Z' column.

This jump of columns is also visible in the export files. In the v10.x, this issue was already present. But it was possible to use as export option 'Excel 2007 (old)'. Since the v13.0, there is only 1 version of Excel export which has always this bug if there are less than 25 columns used in the import and export Excel files.

## Environment
- **Version**: 13.0.0
- **OS**: Linux dolionline 5.4.98-1-pve #1 SMP PVE 5.4.98-1 (Mon, 15 Feb 2021 16:33:27 +0100) x86_64
- **Web server**: Apache
- **PHP**: 7.0.33-0+deb9u10
- **Database**: MySQL or MariaDB 5.5.5-10.1.48-MariaDB-0+deb9u1
- **URL(s)**: /imports/import.php?step=2&datatoimport=stock_1&excludefirstline=1&separator=%2C&enclosure=%22

## Expected and actual behaviour
Each columns of Excel files should be filled when after one without anu empty columns between them.

## Steps to reproduce the behaviour
Go to Tools, New imports, then Stocks-Warehouse, download the "template file with field content information (* are mandatory fields)". Open it in Excel 2019. See the empty columns up to 'Z' columns.

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screen casts, dolibarr.log, debugging informations…)
![Excel Capture](https://user-images.githubusercontent.com/3815422/110199630-f27ae580-7e61-11eb-9390-c883bb27bbf5.PNG)

**Comment by eldy** [comment]
Can you try with version 13.0.1 ?

**Comment by Hystepik** [comment]
Works for me in 13.0.1

**Comment by RubenRuCh** [comment]
I have detected that in the previous Excel 2007 (old) library the first column started at 0. However, with the new option (the only one available from Dolibarr 13) the first column starts at 1. Thus, when passing it the 0 to the new library, it causes the first column to appear in the last (Z) with several blank columns between column Z and what should be the last column.

The solution is to indicate that the first column is number 1 instead of 0. I comment on this for those developments that make use of Dolibarr Excel library to generate XLS files.

**Comment by syrinx75** [comment]
Tested in 13.0.3, importation of Excel works as it should now. Thank you.

**Comment by syrinx75** [comment]
> Can you try with version 13.0.1 ?

Tested in 13.0.3, importation of Excel works as it should now. Thank you.
