### ISSUE TITLE
Add total including options in PDF documents for commercial proposal

### ISSUE THREAD

**Issue by atm-thibaultf** [Dolibarr/dolibarr#17150]
# Feature Request
It would be really usefull to show a total (including tax or not) including the lines added in option on PDF documents for commercial proposal.

## Use case
When we add a product / service in option on commercial proposal, it's not really clear for the customer who receive the proposal. It would be really usefull to show the difference between the total with or without options at the bottom of the commercial proposal (where total appears).

**Comment by gmilad** [comment]
(French below)
Hello,

Can you describe how to reproduce the functionality of the options because I can't do it again on the 13.0.2 version or the development version so far ?

A screenshot maybe ?

Sincerely,
Gaëtan.

(Français en dessous)
Bonjour,

Pouvez décrire comment reproduire la fonctionnalité des options car je n'arrives pas à le refaire sur la version 13.0.2 ou la version de développement à ce jour ?

Une capture d'écran peut-être ?

Cordialement,
Gaëtan.

**Comment by atm-thibaultf** [comment]
Hi Gaëtan,

If you add a product / service in a commercial proposal with 0 in the field "quantity", this product appears with the label "Options" in the PDF and the amount of this line is not considered in the total of the commercial proposal. You can find below a screenshot on the develop branch but it's similar on previous version as well. 

I'm talking about adding some information for the total with options at the end of the document, as mentioned in red on the screenshot.

![option](https://user-images.githubusercontent.com/57494317/116001227-b52a0d00-a5f3-11eb-8a2a-436bd1f07e04.jpeg)

I hope it will help !
Best regards,
Thibault
