### ISSUE TITLE
Bug: Api server 404 on all routes / composer install

### ISSUE THREAD

**Issue by adiatis** [Dolibarr/dolibarr#17362]
# Instructions
- Install Dolibarr via composer
- Activate all necessary modules and api rest module

# Bug
api explorer:  404 on all routes
After debugging the Api version map is still empty after following command:
$api->r->addAPIClass('Luracast\\Restler\\Explorer');
Maybe the restler class is not loaded in composer install?
No issue with manual install via zip.

## Environment
- **Version**: 13.0.2
- **OS**: Linux (Centos)
- **Web server**: Nginx
- **PHP**: 7.3.27
- **Database**: 10.3.28-MariaDB
- **URL(s)**: /api/index.php/explorer

Installation is on Nginx server. Lost 5 days on trying the nginx settings because in the installation instructions there is focus on extra config. But there is no extra config needed anymore. Works on Apache and Nginx without extra config.

Solution:
Install with zip or copy zip over composer installation and rest api server works.

**Comment by eldy** [comment]
Due to a lot of trouble with composer, Dolibarr must NEVER be installed with composer. Installing using composer is not supported (composer install bugged libraries that are fixed into embedded version of Dolibarr).
There is no need to use composer. A simple get clone will get all required files (even from non php libraries)
