### ISSUE TITLE
BUG : Not possible to activate ant mask for Payments

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#17363]
# Bug
Not possible to activate ANT mask for Payments.
When you click on the enable switch, the page reload but cicada is still selected.

No error messages displayed or in the log.

## Environment
- **Version**: 13.0.2
- **PHP**: 7.2
- **URL(s)**: admin/payment.php

![image](https://user-images.githubusercontent.com/35605507/115557852-6823ff00-a2b2-11eb-8822-3a3ae9c4401f.png)

> 2021-04-21 14:57:36 INFO --- Access to GET /doli/13/htdocs/admin/payment.php - action=setmo, massaction= NOTOKENRENEWAL=
> 2021-04-21 14:57:36 DEBUG sql=SELECT transkey, transvalue FROM llx_overwrite_trans where lang='en_US' OR lang IS NULL AND entity IN (0, 1) ORDER BY lang DESC
> 2021-04-21 14:57:36 DEBUG sql=SELECT m.rowid, m.type, m.module, m.fk_menu, m.fk_mainmenu, m.fk_leftmenu, m.url, m.titre, m.langs, m.perms, m.enabled, m.target, m.mainmenu, m.leftmenu, m.position FROM llx_menu as m WHERE m.entity IN (0,1) AND m.menu_handler IN ('eldy','all') AND m.usertype IN (0,2) ORDER BY m.position, m.rowid
> 2021-04-21 14:57:36 DEBUG sql=SELECT rowid, title, url, target FROM llx_bookmark WHERE (fk_user = 12 OR fk_user is NULL OR fk_user = 0) AND entity IN (1) ORDER BY position
> 2021-04-21 14:57:36 DEBUG functions2::get_next_value mode=next
> 2021-04-21 14:57:36 DEBUG sql=SELECT MAX(SUBSTRING(ref, 4, 4)) as val FROM llx_paiement WHERE ref LIKE 'PAY____' AND ref NOT LIKE '(PROV%)' AND entity IN (1)
> 2021-04-21 14:57:36 DEBUG functions2::get_next_value return PAY0001
> 2021-04-21 14:57:36 DEBUG functions2::get_next_value mode=next
> 2021-04-21 14:57:36 DEBUG sql=SELECT MAX(SUBSTRING(ref, 4, 4)) as val FROM llx_paiement WHERE ref LI...
> 2021-04-21 14:57:36 DEBUG functions2::get_next_value return PAY0001
> 2021-04-21 14:57:36 DEBUG sql=SELECT MAX(CAST(SUBSTRING(ref FROM 9) AS SIGNED)) as max FROM llx_paie...
> 2021-04-21 14:57:36 INFO mod_payment_cicada::getNextValue return PAY2104-0011

**Comment by DGNCH** [comment]
Dear everyone,

I confirm that the Ant mask cannot be selected for Payments on the following Dolibarr install:
Dolibarr version: 13.0.2
PHP version: 7.3
Language: French
Module: Invoices and Credits (FR: Factures et avoirs)
Tab: Payments (FR: Règlements)
Section: Payments numbering model (FR: Modèle de numérotation des factures et avoirs)
Ant Mask: PAY-DI01CHXX{yyyy}{mm}-{000000@1}

I have two questions (if it is OK to ask them here):
- Will there be issues (technical, accounting, etc) if I start using Cicada now and then switch to Ant (after the bug is solved) ?
- When I switch to Ant (after the bug is solved), can the Cicada payments be renamed automatically and without counter issues ?

Thank you very much for all the programming work.

Best regards

DGNCH
