### ISSUE TITLE
Bad link to Wiki Help 

### ISSUE THREAD

**Issue by philazerty** [Dolibarr/dolibarr#17608]
Correction line 190 of admin/translation.php : 
`$wikihelp = 'EN:Setup_Translation|FR:Paramétrage_Traduction|ES:Configuración_Traducción';`

**Comment by Hystepik** [comment]
Hello, could you tell in what version you found this bad link please

**Comment by ksar-ksar** [comment]
The bug is on all versions : 
V11 : https://github.com/Dolibarr/dolibarr/blob/11.0/htdocs/admin/translation.php#L200
V12 : https://github.com/Dolibarr/dolibarr/blob/12.0/htdocs/admin/translation.php#L200
V13 : https://github.com/Dolibarr/dolibarr/blob/13.0/htdocs/admin/translation.php#L190
V14 : https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/admin/translation.php#L191

**Comment by Hystepik** [comment]
It seems to be fixed so I close the issue.
Feel free to reopen if not.
