### ISSUE TITLE
Wrong path of attached files Lot/batch number

### ISSUE THREAD

**Issue by nuagetec** [Dolibarr/dolibarr#17675]
# Bug
Wrong path of attached files in module Lot/batch number

## Environment
- **Version**: 14.0.0-alpha
- **URL(s)**: /product/stock/productlot_document.php

## Expected and actual behavior
The download link for attached files is not working.

## Steps to reproduce the behavior
Create a receipt of products with a lot number.
Add a new file / document to this batch number.
See ErrorFileDoesNotExists when clicking on the document link.

**Comment by toni-mx** [comment]
Same happens within the Shipment module when using Public Key of file. (this comes at least from 7.x version)
Maybe similar patches may work?

Thankyou

**Comment by nuagetec** [comment]
Maybe, but if I remove the lot number of file name link like this :

/document.php?modulepart=product_batch&entity=1&file=2112002/Note.txt
to
/document.php?modulepart=product_batch&entity=1&file=Note.txt

Where the "2112002" is lot number, the file is reached well...

Thanks

**Comment by gmilad** [comment]
(English below) 
Bonsoir,
oui je reproduis le problème sur la version de développement avec la base de démo, lors l'import des pièces jointes la création du sous-dossier du lot ne se créé pas alors que le lien lui rajoute le sous-dossier, je viens de comparer avec la version 13.0.2 : 

`dolitest@ssh01:~/d13/dolibarr$ find -name *Malo*`
`./documents/productlot/Lot-20210520-2152/Lot-20210520-2152-IMG_2935_StMalo.jpg`
`./documents/productlot/Lot-20210520-2152/thumbs/Lot-20210520-2152-IMG_2935_StMalo_mini.jpg`
`./documents/productlot/Lot-20210520-2152/thumbs/Lot-20210520-2152-IMG_2935_StMalo_small.jpg`
`dolitest@ssh01:~/dev/dolibarr$ find -name *Malo* `
`./documents/productlot/Lot-2021-05-20-2145-IMG_2935_StMalo.jpg`
`./documents/productlot/thumbs/Lot-2021-05-20-2145-IMG_2935_StMalo_small.jpg`
`./documents/productlot/thumbs/Lot-2021-05-20-2145-IMG_2935_StMalo_mini.jpg`

Cordialement,
Gaëtan.

Good evening,
yes I reproduce the problem on the development version with the demo base, when importing attachments the creation of the subfolder of the batch is not created while the link adds the subfolder, I just compared with version 13.0.2:


`dolitest@ssh01:~/d13/dolibarr$ find -name *Malo*`
`./documents/productlot/Lot-20210520-2152/Lot-20210520-2152-IMG_2935_StMalo.jpg`
`./documents/productlot/Lot-20210520-2152/thumbs/Lot-20210520-2152-IMG_2935_StMalo_mini.jpg`
`./documents/productlot/Lot-20210520-2152/thumbs/Lot-20210520-2152-IMG_2935_StMalo_small.jpg`
`dolitest@ssh01:~/dev/dolibarr$ find -name *Malo* `
`./documents/productlot/Lot-2021-05-20-2145-IMG_2935_StMalo.jpg`
`./documents/productlot/thumbs/Lot-2021-05-20-2145-IMG_2935_StMalo_small.jpg`
`./documents/productlot/thumbs/Lot-2021-05-20-2145-IMG_2935_StMalo_mini.jpg`

Regards,
Gaëtan.

**Comment by FHenry** [comment]
Can't reproduce on 13.0 branch or develop branch.

**Comment by gmilad** [comment]
(English below)
Bonsoir @FHenry,

Désolé mais je viens de refaire vers 21h25 (Heure Française) une installation de la version de développement (pour la version 13 ça fonctionne) et j'arrive à reproduire le problème avec la base de démo voici de mémoire mon cheminement :

- Installation de la version de développement et de la base de démo
- Création d'une commande fournisseur pour le produit APPLEPIE chez Indian SAS,
- Validation de la commande,
- Création de la réception de la commande
- Rajout du numéros de lots dans la réception de la commande (Lot-20210525-2125)
- Validation de la réception de la commande,
- Dans l'onglet Fichiers joints du lot rajout d'une pièce jointe,
- L'import du fichier joint est OK, par contre le lien n'est pas bon :

http://dev.exemple/document.php?modulepart=product_batch&entity=1&file=Lot-20210525-2125%2FLot-20210525-2125-Annecy-lac1.jpg

Alors que sur le serveur :

```
dolitest@ssh01:~/dev.exemple$ find -name *lac1* 
./dolibarr/documents/productlot/Lot-20210525-2125-Annecy-lac1.jpg
./dolibarr/documents/productlot/thumbs/Lot-20210525-2125-Annecy-lac1_small.jpg
./dolibarr/documents/productlot/thumbs/Lot-20210525-2125-Annecy-lac1_mini.jpg
```

PS : Désolé ma langue maternelle est le Français c'est pour ça que ma réponse est d’abord en Français.

Amicalement,
Gaëtan.

(English below)
Good evening @FHenry,

Sorry but I have just redone the installation of the development version (for version 13 it works) around 21:25 (French time) and I manage to reproduce the problem with the demo base. Here is my path from memory:

- Installation of the development version and the demo base
- Creation of a supplier order for the APPLEPIE product at Indian SAS,
- Validation of the order,
- Creation of the receipt of the order
- Addition of the batch numbers in the order receipt (Lot-20210525-2125)
- Validation of the order receipt,
- In the attached files tab of the batch add an attachment,
- The import of the attached file is OK, but the link is not good:

http://dev.exemple/document.php?modulepart=product_batch&entity=1&file=Lot-20210525-2125%2FLot-20210525-2125-Annecy-lac1.jpg

While on the server :

```
dolitest@ssh01:~/dev.exemple$ find -name *lac1* 
./dolibarr/documents/productlot/Lot-20210525-2125-Annecy-lac1.jpg
./dolibarr/documents/productlot/thumbs/Lot-20210525-2125-Annecy-lac1_small.jpg
./dolibarr/documents/productlot/thumbs/Lot-20210525-2125-Annecy-lac1_mini.jpg
```

PS : Sorry my mother language is French that's why my answer is in French.

Kind regards,
Gaëtan.

**Comment by FHenry** [comment]
@gmilad Yes I can reproduce on develop branch

**Comment by gmilad** [comment]
Good evening,

Thanks @FHenry  it works for me with your fix.

Kind regards,
Gaëtan.
