### ISSUE TITLE
Ticket page display "header message" from Paypal Module

### ISSUE THREAD

**Issue by Likeandfeel** [Dolibarr/dolibarr#17830]
HI Team

I found this morning this issue :

# Bug
On ticket public page when you want open a new ticket, footer display message box from Paypal module insert on the Paypal module box > Message sur l'écran de paiement en ligne

## Environment
- **Version**: 13.0.2
- **OS**: Linux
- **Web server**: Apache 
- **PHP**: PHP 7.3.27
- **Database**: 10.3.27-MariaDB

## Expected and actual behavior
Paiement not suposed to be display on ticket page > Open New issue

## Steps to reproduce the behavior
Configure Paypal module paiement
Go to public ticket page and open new one
go on the footer.

**Comment by gmilad** [comment]
(English below)
Bonjour,
Je n'arrives pas à reproduire le problème, pouvez-vous tester rajouter des captures d'écrans afin que l'on soit bien sur d'être au même endroit ?

Cordialement,
Gaëtan.

(English)
Hello,
I can't reproduce the problem, can you test and add screenshots so that we can be sure to be in the same place?

With kind regards,
Gaëtan.

**Comment by atm-maxime** [comment]
Same as #11470 ?

**Comment by gmilad** [comment]
Hello, @atm-maxime 

> Same as #11470 ?

Yes, and i can reproduce the problem on Dolibarr 10, 11, 12, 13 and develop

Kind regards,
Gaëtan.

**Comment by Likeandfeel** [comment]
Hi @gmilad 

Yes same, but its supposed to be the header ^^
Just try al work also with the footer

Issue confirmed and not solved since version 10 ?
Thanks for you time
Best regards

Fr :

Hello
En fait quand tu vas dans la configuration du module, c'est lorsque le texte est entré au niveau du message de bienvenue (première box).

Un grand merci
