### ISSUE TITLE
customer order error to invoice

### ISSUE THREAD

**Issue by ariaconseil** [Dolibarr/dolibarr#17866]
Hello,

I am using Dolibarr 13.0.2, the button "invoice orders" is present but I have this new menu :

https://www.dolibarr.fr/forum/uploads/default/original/2X/1/146ac75c42256e50a54248c747c594ef2d58628d.png

So I click on CONFIRM at the top right (new menu before I didn't have it) and I get this :

https://www.dolibarr.fr/forum/uploads/default/original/2X/d/d563af8521ccf7de0e6c2ad2f38327e2f99e4d17.png

I toggle the choices on YES for the third party invoice and the invoice validation then I click on Invoice Orders and it returns directly to the third party orders page, the invoice has been created.

So forcing you to go to the invoices and add the payment method while before going through the classic part we chose the options from the start.

In addition, I use the WEE / DEEE module ( https://www.dolistore.com/fr/modules/343-Eco-Tax-DEEE.html?search_query=deee&results=1 ) and when creating the invoice, it is automatically added when there is already a WEEE / DEEE line in the order, an additional WEEE / DEEE line which contains the order number. And nothing if not in the original order.

There's no problem with Dolibarr 12.0.5.

**Comment by eldy** [comment]
What do you mean with "So forcing you to go to the invoices and add the payment method while before going through the classic part we chose the options from the start."
The goal of the bulk action feature "Bill order" is to generate the invoice for orders, not to pay it. So it seems to be the expected behavior.

For pb of ecotax, i tried a fix for v14.
