### ISSUE TITLE
product and product_lot db fields stock update

### ISSUE THREAD

**Issue by lmag** [Dolibarr/dolibarr#17980]
# Bug
batch creation instead of moving the stock

## Environment
- **Version**: [*14.0.0-beta*]

## Expected and actual behavior
Error message: "You cannot authorize the 4 products of lot 2 since there is no stock on lot 2

## Steps to reproduce the behavior
On /product/stock/product.php from product/stock/list.php?leftmenu=
Product A with activated batch management
Put in stock on depot 1 of 10 product lot 1
Transfer of stock to depot 2 of 4 product from lot 2 (which does not exist) >> It works.
I have now
6 products lot 1 on depot 1
4 lot 2 products on depot 2
The products on batch changes!

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging 
![image](https://user-images.githubusercontent.com/3288514/122605425-b7e73280-d077-11eb-87e0-1776978c02a7.png)

**Comment by lmag** [comment]
@altairis-noe I did my best 🥇

**Comment by atm-maxime** [comment]
@lmag the way of not having this for now is to change the stock module configuration to unauthorize negative stock. Because when I try your action, the result is not 6 product of lot 1 in depot 1 and 4 product of lot 2 in depot 2, but I have :
10 products A of lot 1 in depot 1
-4 products A of lot 2 in depot 1
4 products A of lot 2 in depot 1
