### ISSUE TITLE
Incorrect display of telephone number depending on county

### ISSUE THREAD

**Issue by gstax** [Dolibarr/dolibarr#18003]
# Bug
Incorrect display of telephone number depending on county

## Environment
- **Version**: [13.0.3]
- **OS**: [Linux]
- **Web server**: [Apache 2.4.46]
- **PHP**: [7.4]
- **Database**: [MySQL 5.6]
- **URL(s)**: [societe/list.php?leftmenu=thirdparties]

## Expected and actual behavior
Display should not depend on country and country code should be separated from phone number, e.g +33 6 23 44 56 78 or +41 22 345 67 89

 ![dolibarr_13 0 3](https://user-images.githubusercontent.com/3268679/122898082-e51f3380-d34a-11eb-8d5c-8adefce83cfd.png)

**Comment by daraelmin** [comment]
I think that the display MUST depend on country. 

For example, the common display un France is different un Switzerland.

In Switzerland the common display of a phone number are +41 XX 123 45 67 or 0XX 123 45 67. Where XX is the code of the departement (canton).

In France the common display is +33 X 12 34 56 78 or X12 34 56 78. But I dont know why.

However the display for France seems wrong hère.

**Comment by gstax** [comment]
I don't 100% agree. Country code (+41 or +33) should always be separated from the rest, regardless the country registred for the customer, that is, it should not matter if customer live in CH or FR, the phone number should be

+41 XX 123 45 67
+33 X 12 34 56 78

So even if customer lives in the USA, it's still a swiss or french phone number.

Is it more clear stated like this ?

Thanks

**Comment by wisbit** [comment]
Hi there I have the same issue on version 14.0.5.

The phone numbers are systematically badly written.
The number should be (belgium) 
+xx xxx xx xx xx for mobile phones
+xx x xxx xx xx for landlines in certain regions
+xx xx xx xx xx for landlines in other regions.

since it might be difficult to figure that one out, why not simply let the numbers be displayed the way the user input them
if I write +32 2 589 63 62, just leave it like that, how about that ?
