### ISSUE TITLE
Attachment(s) in emailcollector 

### ISSUE THREAD

**Issue by pcbleu** [Dolibarr/dolibarr#18049]
# Feature Request
Attachment(s) in emailcollector 

## Use case
When recording an event into Dolibarr, it would be very useful to record attchments automatically
For example when collecting email for job candidatures, **it would be great to know which documents are attached**

## Suggested implementation
attachments should be stored in a new directory

Thanks for reading this request and Good continuation

**Comment by EmergyCH** [comment]
Same suggestion for me. Thanks in advance

**Comment by atm-maxime** [comment]
A good start here #19153
Thanks @moreauftheobald

**Comment by moreauftheobald** [comment]
all standard Dolibarr object whitch have a ref Number and joined piece management activeted are managed by my PR.

it can be hooked in order to add external Mods.

you just have to execute  'addmoduletoeamailcollectorjoinpiece' hook and add to  'arrayobject' parameters an array with:

 ex : 'fournisseur/commande' => array('table' => 'commande_fournisseur',
									'fields' => array('ref', 'ref_supplier'),
									'class' => 'fourn/class/fournisseur.commande.class.php',
									'object' => 'SupplierProposal'),

'folder path in documents folder' => array('table'=>'table name without prefix',
                                                                     'fields' => array (fields to search in),
                                                                     'class' => 'path to find the class of the object'
                                                                      'object' => 'object to create(need a standard fetch method'),

then push the whole array in hook resarray

**Comment by freechelmi** [comment]
Duplicate of #19569 , please close
