### ISSUE TITLE
Bug in export "Customer invoices and invoice details"

### ISSUE THREAD

**Issue by rycks** [Dolibarr/dolibarr#18141]
# Bug
export invoices with "Customer invoices and invoice details" option get total amount different from export same invoices with "Customer invoices and payments" option !

This is due to the "DISTINCT" in SQL request if there is two identical products into the invoice !

## Steps to reproduce the behavior

For example, invoice:

- product 1, quantity 1, amount 5
- product 2, quantity 1, amount 2
- product 1, quantity 1, amount 5

"Customer invoices and invoice details" export will get only two lines:

- product 1, quantity 1, amount 5
- product 2, quantity 1, amount 2

## Solution

The solution is to remove DISTINCT in sql request for that sort of export ...

**Comment by rycks** [comment]
here is a solution (can't attach patch files ??? wtf)

```
diff --git a/htdocs/exports/class/export.class.php b/htdocs/exports/class/export.class.php
index 5450613bb2..b896057225 100644
--- a/htdocs/exports/class/export.class.php
+++ b/htdocs/exports/class/export.class.php
@@ -196,8 +196,8 @@ class Export
 									// Array of help tooltips
 									$this->array_export_help[$i] = (!empty($module->export_help_array[$r]) ? $module->export_help_array[$r] : '');
 
-									// Requete sql du dataset - #https://github.com/Dolibarr/dolibarr/issues/18141
-									$this->array_export_sql_start[$i]=preg_replace("/DISTINCT/","",$module->export_sql_start[$r]);
+									// Requete sql du dataset
+									$this->array_export_sql_start[$i] = $module->export_sql_start[$r];
 									$this->array_export_sql_end[$i] = $module->export_sql_end[$r];
 									$this->array_export_sql_order[$i] = (!empty($module->export_sql_order[$r]) ? $module->export_sql_order[$r] : null);
 									//$this->array_export_sql[$i]=$module->export_sql[$r];

```

**Comment by eldy** [comment]
Note: "Customer invoices and invoice details" and  "Customer invoices and payments" are 2 different things.  You may but in most case, you wont get the same value.
1 invoice of 100 euros can have 2 line of details (20 and 80) and be paid partially in 3 times (10, 30 and 50 and 20 not yet paid), so line will be output twice in first output (one for the 20, one for the 80) and 3 lines in second output (one for the 10, one for the 30 and one for the 50, that last list of payment of 20 has not been done yet so won't be output).

If you have the same product in 2 lines, this should not be a problem, because the field with the invoice line id is automatically added into the exported field when you add a product field so the line differs when doing "Customer invoices and invoice details" so the distinct has no effect (we must keep it for other purposes). In your example, you should get 3 lines:
lineid1, product 1, quantity 1, amount 5
lineid2, product 2, quantity 1, amount 2
lineid3, product 1, quantity 1, amount 5
You should get this message when you add the first field that is a line field:
![image](https://user-images.githubusercontent.com/883887/125650150-0129454c-b9b1-4fa9-9220-178cdce71220.png)

**Comment by rycks** [comment]
Hello eldy,
ok please forget the part compair with "Customer invoices and payments" and try to export "Customer invoices and invoice details", here is what i have:

Screenshot of invoice  :

![image](https://user-images.githubusercontent.com/1468823/125651540-b8a26913-32a9-477a-b868-15c1cfcf2713.png)

Then export:

![image](https://user-images.githubusercontent.com/1468823/125651896-0d767884-17cf-4c84-8456-9e01c2597a38.png)

one line is missing due to DISTINCT on SQL request ... but maybe i made something wrong in export setup ?

**Comment by rycks** [comment]
Ok, here is what could be a "bug" : "Identifiant de ligne" is not required, then that is the reason why i have the "DISTINC" problem, i'm sure if i add that "Identifiant de ligne" in the export the problem will gone away ...

![image](https://user-images.githubusercontent.com/1468823/125652256-70f05775-4c7f-4051-9292-f31f93a86b1f.png)

hum ... so ... do we have to make a mandatory export of "Identifiant de ligne" in some case ?
