### ISSUE TITLE
Bug sur Dolibarr 14.0.0

### ISSUE THREAD

**Issue by MarieP0567** [Dolibarr/dolibarr#18345]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: [*Affected Dolibarr version(s) 14.0.0*]
- **OS**: [*Server OS type and version Windows*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
[*Verbose description*]
Bonjour,

Je ne sais pas où saisir ça donc j’essaie là. Quelques bugs trouvés sur la v14…

- J’ai saisi 2 cotisations pour une adhérente par erreur, et je ne peux pas en supprimer une car pb de droits d’accès me dit-on, alors que je suis admin et j’ai tous les droits.
- Session de formation, si on veut chercher dans la liste en tapant un nom dans les champs de recherche, rien n’est trouvé quelque soit la recherche
- Sur une facture client, une description de services contient une apostrophe et elle sort en code HTML à l’affichage du PDF de la facture
- Dans Banque, en saisie ou consultation de règlement, l’onglet « suivi » affiche un message « Accès refusé »
- Enfin, je voulais modifier un convention de formation avec DocEdit, et en fait je peux la modifier mais elle ne s’affiche pas dans le module formation. Ce qui s’ouvre dans le module formation, quand on choisit « convention », est en fait un contrat de formation. Contrat introuvable dans Doc Edit pour le modifier…
- Enfin une question, comment puis-je récupérer le champ « nombre de places disponibles » d’une fiche formation pour le mettre dans la convention de formation ? J’ai trouvé un modèle de document avec plein de noms de champs, (modèle pour le module formation, super !) mais pas celui-ci…

Merci beaucoup et belle journée,
Marie
## Steps to reproduce the behavior
[*Verbose description*]

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by daraelmin** [comment]
Hello @MarieP0567,

Chaque bug doit être séparé individuellement dans un ticket et peut ainsi faire l'objet d'une discussion technique. Une liste à la Prévert telle que fournie dans ce ticket ne permet pas au développeurs de travailler dessus.

De plus, il faut un titre qui identifie clairement chaque problème car les développeur ont leur domaine d'expertise propre.

Enfin, il est d'usage décrire en anglais.

Cordialement.

Hi @MarieP0567 ,

Each bug must be separated individually in a ticket and can thus be the subject of a discussion technique. A Prévert-style list as provided in this ticket does not allow developers to work on it.

In addition, you need a title that clearly identifies each issue because developers have their own area of expertise.

Finally, the repports should be in English.

Cheers.

**Comment by matDOTviguier** [comment]
_Le problème de l'apostrophe me semble confirmé._
The apostrophe problem is reproductible.

#18568

**Comment by matDOTviguier** [comment]
_14.0.2 est ok._
14.0.2 is ok.

**Comment by freechelmi** [comment]
Hi @MarieP0567  could you edit the title so we can sort issues easier ?
