### ISSUE TITLE
Add sub total and title

### ISSUE THREAD

**Issue by BB2A-Anthony** [Dolibarr/dolibarr#18380]
# Feature Request
[EN]
I would like to add in the corp the possibility of adding titles and subtotals in the documents. Do you think the best option is to add free line types or buttons at the bottom?

[FR]
J'aimerais ajouter dans le corp la possibilité d'ajouter des titres et sous-total dans les documents. Penssez vous que la meilleur option est de rejouter des types de ligne libre ou des bouttons dans le bas?

[PR Draft] #18369 

![128700072-9c276e98-453d-4936-9a17-5f3d5a9ca6ab](https://user-images.githubusercontent.com/34568357/128713343-a95bebf3-2b1d-4fe0-aba1-2031c59be888.png)

**Comment by eldy** [comment]
The product type = 9 is already used by external module to set a line that is not a product or service. We can keep this.
And the parent_line is used to make a difference to know if it is a title or subtitle. We can also keep this.
However, having this in combo list of "free line" is not the good place (free line may have been disabled and is dedicated to add a line with a price, qty, etc...).
I think best way seem to integrate into core a feature the same way it is implemented by subtotal module (at least the main feature to add a title or subtitle).
PS: Note also that in develop, the line
if (is_object($hookmanager) && (($line->product_type == 9 && !empty($line->special_code)) || !empty($line->fk_parent_line))) {
has been replaced in develop with 
if (is_object($hookmanager) && (test on result of hook)) {
car interact on on lines, not only the line with product type = 9
Because this feature is a transversal feature, having it as a module (like it is for external modules that do the job) looks good to me.

**Comment by cfoellmann** [comment]
@eldy you suggest leaving this to the 3rd party module and only potentially extend the core with hooks to better accommodate that module, right?
If so I am totally with you.
I am in the process of testing and debugging the subtotal module so we can release it to our production environment.

**Comment by eldy** [comment]
No i do not suggest to keep this feature as an external module. it is an interesting feature that is requested by enough users to be into the core. I suggest to have the feature implemented with a "module" (i mean core module) and to use the same specification than the one already used by external modules (because the specification is currently good and it will allow compatibility).
May be merging a subtotal module (with only light features) as core module is a better idea than developing another one.

**Comment by bb2a** [comment]
> No i do not suggest to keep this feature as an external module. it is an interesting feature that is requested by enough users to be into the core. I suggest to have the feature implemented with a "module" (i mean core module) and to use the same specification than the one already used by external modules (because the specification is currently good and it will allow compatibility).
> May be merging a subtotal module (with only light features) as core module is a better idea than developing another one.

@eldy what mod are you referring to?  and how soon do you think it will be available?  I want to participate!

**Comment by BB2A-Anthony** [comment]
@eldy what name for module?

**Comment by cfoellmann** [comment]
Is this compatible with the atm subtotal module data?

**Comment by BB2A-Anthony** [comment]
> Is this compatible with the atm subtotal module data?

yes as said by @eldy the goal is to make them compatible

**Comment by eldy** [comment]
The name "Subtotal and titles" or "Advanced lines In doc" seems a good name for such a module.
Why not just asking ATM if we can include this light version of the module https://www.dolistore.com/de/moduleplugins/976-Subtotal-LITE.html into the core ?  It is already stable and it will avoid to re-stabilize another module like the one suggested into [PR Draft] https://github.com/Dolibarr/dolibarr/pull/18369 or #21675?

**Comment by BB2A-Anthony** [comment]
> The name "Subtotal and titles" or "Advanced lines In doc" seems a good name for such a module.
> Why not just asking ATM if we can include this light version of the module https://www.dolistore.com/de/moduleplugins/976-Subtotal-LITE.html into the core ?  It is already stable and it will avoid to re-stabilize another module like the one suggested into [PR Draft] https://github.com/Dolibarr/dolibarr/pull/18369 or #21675?

@eldy it's a good idea to integrate the ATM module but what do you think @atm-maxime ?
