### ISSUE TITLE
REST: Add API for receiving supplier orders

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#18411]

**Comment by atm-maxime** [comment]
Just for my knowledge, what is the use case of "receiving supplier order" ?

**Comment by BebZ** [comment]
Maybe : 
 it is when a supplier sends a shipping note / but goods does not enter stock (drop shipped) but you have to record a stock movement to be able to invoice your customer and make a normal traceability ?

because dpriskorn had a question on how to populate datas in commande fournisseur distach tables :)

Question about logic for receiving orders #14335

**Comment by smil2k** [comment]
Implementing this seems to be fairly straight forward for me:

A new path should be registered in api_supplier_orders.class.php, eg. "/receive"

Which calls this:
        /**
         *      Set a delivery in database for this supplier order
         *
         *      @param  User    $user           User that input data
         *      @param  integer $date           Date of reception
         *      @param  string  $type           Type of receipt ('tot' = total/done, 'par' = partial, 'nev' = never, 'can' = cancel)
         *      @param  string  $comment        Comment
         *      @return int                                     <0 if KO, >0 if OK
         */
        public function Livraison($user, $date, $type, $comment)

Like /validate.

Or I miss something?
