### ISSUE TITLE
Rename llx_commande TABLE by llx_commande_client

### ISSUE THREAD

**Issue by PyroShape** [Dolibarr/dolibarr#18415]
In order to by clear as the TABLE llx_commande_fournisseur

**Comment by atm-maxime** [comment]
Renaming is often a long job because we have to check everywhere the old name is used. But uniforming and keep data and code clear is a good goal. And the renaming should be in English so customer_order and supplier_order. And customer_proposal, supplier_proposal customer_invoice, supplier_invoice...

**Comment by PyroShape** [comment]
If I do this with a find/replace on all the files (except for the old migrations files that need to stay as they are today), am I missing something ?

Regarding language : with french it's easier to find the good TABLE because it's start with the purpose (example : commande). English format will invert all... (example : customer_order)
Does it make sens to rename like this : order_supplier, order_customer,... ?

**Comment by atm-maxime** [comment]
I think we must do better than a simple find / replace. The table name of an object is defined in the class ($table_name) so it should not be hard coded anywhere else (except SQL files). We should use $object->table_name (or better ObjectClass::table_name @eldy ?) everywhere.
As for the name, easier is a point of view. Some would argue that renaming as I suggested will regroup "customer_" tables and "supplier_" tables...
