### ISSUE TITLE
Get next auto generated customer code using Thirdparty API

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#18715]
# Feature Request
*A lot of operations are already available inside Dolibarr Third-party API. But one important operation is not available. Which is getting next auto generated customer and vendor code through the API, if Monkey  is enabled at the backend. This is very important features. Because when we are going to create any third party, Dolibarr creates the third party without Customer Code.*

## Use case
This way getting the Customer Code is perfect. As you know customer code is option in Dolibar system. So if any company wants to use from their API, then they will just call for next available Customer Code. Once they get the code, they will create the customer using that customer code.

![Customer code](https://user-images.githubusercontent.com/1249577/133256798-c6a0fead-8c3d-4749-a374-678f8a729d1f.png)

**Comment by priojk** [comment]
Just to better understand your request:

It currently is already possible to create a new customer via the REST interface, and this customer gets auto-assigned a regular customer code (the next one according to the selected schema). For this to happen, it is important to set the value "-1" for the field "code_client"  before sending the data via REST to Dolibarr. Then the code gets auto-assigned. You can read back the third party data and have the assigned client code.

This said: Are you asking for a mechanism to just get the value of the next customer code without creating the customer in Dolibarr? How would you "reserve" this value? There may be multiple requests going on in parallel - before you finished the creation of "your" customer, someone else may already have requested and gotten the same value, or there will be gaps in the numbering scheme, because requested values get reserved but never used.

**Comment by alsoft10** [comment]
Hello @priojk ,

Thank you very much for your valuable information. Your solution is perfectly works for us. Then there is no need for new feature that I have asked. I appreciate your help.

Thanking you,
H. Sattar
