### ISSUE TITLE
Message not send when SMTP server allow only one sender email

### ISSUE THREAD

**Issue by c-orazio** [Dolibarr/dolibarr#18755]
# Bug
After having set properly the SMTP server, it allows only one email address to be used as sender, but dolibar in many modules try to define a different from email address that is rejected by the SMTP server. 

## Environment
- **Version**: 11
- **OS**: ubuntu 20
- **Web server**: apache2
- **PHP**: 7.4
- **Database**:mariaDB
- **URL(s)**: send

## Expected and actual behavior
wee expect email to be sent, we have an error message

## Steps to reproduce the behavior
workaround found so far : force sender  see https://www.dolibarr.fr/forum/t/probleme-de-configuration-de-lemetteur-de-mails/35424/7
 core/class/CMAilFile.class.php ligne 149 set $from

	// Add autocopy to (Note: Adding bcc for specific modules are also done from pages)
		if (!empty($conf->global->MAIN_MAIL_AUTOCOPY_TO)) $addr_bcc .= ($addr_bcc ? ', ' : '').$conf->global->MAIN_MAIL_AUTOCOPY_TO;

        $from="contact@com.com";
        $this->subject = $subject

**Comment by priojk** [comment]
To me this seems more like a problem/limitation of the SMTP server you are using, rather than a bug of Dolibarr. There are of course mail providers who do not allow sending via SMTP with other addresses than one defined sender address, but this is by no means the general behaviour of SMTP. I can confirm, that with my installation, I can use different sender addresses (all from my company domain) without any problems.

I would recommend to check with your mail provider, if this limitation can be lifted or to change to a different provider, if possible. With regard to Dolibarr, I could imagine an additional feature, which checks sending from several different addresses during the installation process to issue a warning right during setup, if the configured SMTP provider has this limitation.

**Comment by erikvanberkum** [comment]
Agree with the above message we use aws ses for many years and works flawless. 

https://aws.amazon.com/ses/

**Comment by c-orazio** [comment]
I already explored option with my provider; I do not want to use any GAFAM knowing the american policy on personal data : nothing on any american server!!!

**Comment by c-orazio** [comment]
github : https://iplookup.flagfox.net/?ip=140.82.121.3&host=github.com

**Comment by warnerbryce** [comment]
For this use of case, i use a module called MULTISMTP. 
You can then setup SMTP parameters for every users in your Dolibarr. 
You can also get a copy in an IMAP Folder if you want to keep track of the mails you're sending from Dolibarr.
It was sell before in the DoliStore, but not anymore, you can contact Open-DSI for getting this module if you are interested

This module was close to get into a Core Module but the original dev says no at the last minute... quite sad.

**Comment by eldy** [comment]
Dolibarr allows any value into the from because the standard in SMTP.
One SMTP account does not means you have only 1 email address. You may have several one. And your SMTP server should accept this (as long as they are in the same domain).
If your SMTP limits to only one email, this is a limitation of your SMTP server meaning that your SMTP server is dedicated ot one and only 1 email account with 1 and only 1 email alias (However, I don't know any smtp provider setup like this).

**Comment by c-orazio** [comment]
The point is that I provide an user name and an user password, configuring SMTP in dolibarr, so it is logical that it accept only to send on behalf of this user...

**Comment by warnerbryce** [comment]
> Dolibarr allows any value into the from because the standard in SMTP. One SMTP account does not means you have only 1 email address. You may have several one. And your SMTP server should accept this (as long as they are in the same domain). If your SMTP limits to only one email, this is a limitation of your SMTP server meaning that your SMTP server is dedicated ot one and only 1 email account with 1 and only 1 email alias (However, I don't know any smtp provider setup like this).


It's not totally true. 
Example : 
I have a domain on OVH.com ->  ilovedoli.fr
My MX/STMP server is mail.ilovedoli.fr that is a CNAME for ssl0.ovh.net 
I have bought 5 Emails on this domain 
a@ilovedoli.fr / b@ilovedoli.fr / c@ilovedoli.fr etc...
Every address have it's own password and isn't the same from one to another

I go into my Dolibarr for configuring the Email section : 
Host : mail.ilovedoli.fr or ssl0.ovh.net 
Port : 465
SSL : Yes
Username : a@ilovedoli.fr
Password : PasswordforA

Then i create my Dolibarr users and gave them b , c , d , e addresses
When user B is logged he can send emails but it's a little dirty. 
The email is send like this : 
From : b@ilovedoli.fr
To : user@gmail.com
Sender : a@ilovedoli.fr

But when you have a case where you have two different domains from different mail server in the same Dolibarr entity, it won't work...

Having something like multismtp (module) merged into core or rewritten will be great because : 
Every user can have it's own mail server and credential 
The mail is really sent using the SMTP credentials of the user
You can write a copy of the email into your IMAP Folder (Sent folder for exemple or Sent from Dolibarr)

**Comment by c-orazio** [comment]
Thanks
This is exactly my case, I am using OVH also, but in some cases it works as you say, but in many case, for example validating vacancies, it tries to send out with b@ilovedoli.fr as sender... and we are warn that b user is not allowed to send emails.. 
with doli 11.0.4

**Comment by c-orazio** [comment]
> For this use of case, i use a module called MULTISMTP. You can then setup SMTP parameters for every users in your Dolibarr. You can also get a copy in an IMAP Folder if you want to keep track of the mails you're sending from Dolibarr. It was sell before in the DoliStore, but not anymore, you can contact Open-DSI for getting this module if you are interested
> 
> This module was close to get into a Core Module but the original dev says no at the last minute... quite sad.

I did not find how to implement multiSMTP...

**Comment by oraki23** [comment]
Hi, I've also had a similar issue when trying to send with SendGrid.

Context: I have a sendgrid server with my domain.com authenticated, so therefore I should be able to send all my email from any adress of this server.

When I send a test mail, if I send it from the automated email address:
test@mydomain.com <test@mydomain.com>
It refuses to send.

However, if I set a name for my address, it works:
TEST PERSON <test@mydomain.com>

There seems to be some problem with the way that it's handled, and apparently SendGrid does not like it when the name is equal to the email. But I haven't been able to see the exact content of the $from variables that is passed in the CMailFileClass line 157.
