### ISSUE TITLE
The Bank swift code should be optional

### ISSUE THREAD

**Issue by javieralapps4up** [Dolibarr/dolibarr#18847]
# Feature Request
The Bank swift code should be optional, I think

The swift code should be optional. And its subsequent check in public function verif () (Account class)

**Comment by esaumell** [comment]
+1

I don't know the regulation in other European countries, but as far as I know, in Spain it's not mandatory to use BIC codes for SEPA payments. I checked that with my bank. Furthermore, people are not used to know what BIC number is and asking for it is a bummer.

I'm using Dolibarr 13.0.4, and I fill the BIC/SWIFT field with 'XXXXXXXXXXX' in order to be able to save the IBAN in the third-party payment information tab. **Be careful that some banks charge you if you send a wrong BIC number**, even being not mandatory.

**Comment by josett225** [comment]
Hi There,

I jumping on this feature request to add also swift transfer payment (as today we can only do SEPA credit transfer wire) could be great improvement for companies with international importation/exportation activities.
