### ISSUE TITLE
Waste products Management

### ISSUE THREAD

**Issue by WKSOF** [Dolibarr/dolibarr#19354]
How can we manage the waste products (spoiled products)? Do we have to develop a specific feature or is it just a parameterization to do?

**Comment by milenmk** [comment]
There is no native option. I have made a custom module for one of my clients.

**The easiest way, without a module, is to create a warehouse for waste products and move them manually.**

The module I've made was because the client wanted to generate PDF that should be presented to the warehouse manager in order to replace the product i.e. keep paper track.

**Comment by WKSOF** [comment]
Thank you for your reply. Is specific development expensive (especially in terms of time)? because my client wants to view the status of his stock and the waste products in the same screen.

**Comment by milenmk** [comment]
> Thank you for your reply. Is specific development expensive (especially in terms of time)? because my client wants to view the status of his stock and the waste products in the same screen.

Depends on what they want exactly. I've used a different warehouse, and the module workflow is similar to creating an order - create draft, add products, validate, generate pdf etc. You can send me an email if interested (see it on my profile)
