### ISSUE TITLE
Stock at a warehouse

### ISSUE THREAD

**Issue by ecroow** [Dolibarr/dolibarr#19434]
When I'd like to see how much stock I have in general from one category of products, it's okay.

But when I try to see the stock at a particular warehouse from a particular category of products, I can't see how many I have.

**Comment by atm-maxime** [comment]
So your suggestion is ... ?

**Comment by ecroow** [comment]
> 

To be able to see how many products from a particular category I have in a particular warehouse .

**Comment by atm-maxime** [comment]
Yes I got that. Where ? On which page ? A new screen ? The stock list filterable by warehouse? Adding tag filters on the warehouse card ? Can you add a screenshot to have an example ? Usually, when someone posts a feature request, he gives details about how he imagines the feature.

**Comment by lhxc4247** [comment]
I'd say, add a drop-down-select filter as in the image below.

![stocks_filter_warehose](https://user-images.githubusercontent.com/1887870/151119940-23300847-e0dc-46c8-90a6-3da528ce0082.png)

Since in stock module we have this option:
"Manage also value for minimum and desired stock per pairing (product-warehouse) in addition to the value for minimum and desired stock per product"

As its current state, to see those info, we have to select an individual product to view, then click stock tab of that particular product.


I understand that we can view stock at a particular warehouse by looking into a warehouse, as in the 2nd image below.

![stocks_at_a_warehouse](https://user-images.githubusercontent.com/1887870/151121439-215a9d15-269b-4db2-8f09-2bfa54bc974c.png)
But in this page there's no minimum or desired stock info, and there is no option to filter products by tag/category
