### ISSUE TITLE
Email Template __SHIPPINGTRACKNUM__  and __SHIPPINGTRACKNUMURL__ are the same 

### ISSUE THREAD

**Issue by ultrasites** [Dolibarr/dolibarr#19445]
# Bug
The template variables __SHIPPINGTRACKNUM__  and __SHIPPINGTRACKNUMURL__  are the same values in email templates. __SHIPPINGTRACKNUMURL__ has only the TrackingId and not the full tracking url. 

Example:
__SHIPPINGTRACKNUM__  -> 12345
__SHIPPINGTRACKNUMURL__ -> 12345 

## Environment
Dolibarr Version 14.0.3

## Expected and actual behavior
__SHIPPINGTRACKNUMURL__  should be the tracking url

## Steps to reproduce the behavior
Paste the two variables in the email template

**Comment by daraelmin** [comment]
Hi @ultrasites,

I'm not sure, but it could be that the problem is with the link  and number tracking registration rather than the email creation process.

Indeed I checked the substitution function and it seems correct to me. On the other hand, in the process of editing an expedition (expedition / card.php), there are some strange things. in fact, when displaying the label of the tracking number, it is the url that is displayed and editable, while the tracking number is not displayed or editable.

Anyway, I have a suggested patch that appears in the thread, could you test that and tell me what you see?

cheers

**Comment by ultrasites** [comment]
I tested it. I it was my mistake. I have double wrapped the variable __SHIPPINGTRACKNUMURL__ with `<a href... `. I will close this issue. Thank you!

**Comment by ultrasites** [comment]
@daraelmin  But one thought about that. SHIPPINGTRACHNUMURL returns the full html link construction, e.g `<a href="....">`. It should only returns the full url. The html link should be created by a user in the UI or? - regarding different design guides how the a-tag should work. 

Here is the response from the REST-API:

`"tracking_url": "<a target=\"_blank\" href=\"https://nolp.dhl.de/nextt-online-public/set_identcodes.do?lang=de&idc=11111\">11111</a>",`

**Comment by ultrasites** [comment]
@daraelmin any ideas?

**Comment by daraelmin** [comment]
Hi @eldy, 

Is this a feature or bug ?

In many pages tracking_number is used for storing/showing the tracking_url so I'm not sure.

Cheers

**Comment by ultrasites** [comment]
Bug is still present

**Comment by ultrasites** [comment]
still present, any news?
