### ISSUE TITLE
Wrong Label String

### ISSUE THREAD

**Issue by VaderD** [Dolibarr/dolibarr#19490]
# Bug
It shows "NumberOfTicketsByMonth" instead of Monthly statistics

## Environment
- **Version**: [*14.0.4*]
- **OS**: [*CentOS 7*]
- **Web server**: [*Apache 2.4.6*]
- **PHP**: [*7.4.26*]
- **Database**: [*MySQL 5.5.68*]
- 
![1](https://user-images.githubusercontent.com/34111030/143543381-6fa10eff-8437-41e5-a9bf-9d1c56d8b692.png)

**Comment by ksar-ksar** [comment]
Hello,

What is your language?

**Comment by VaderD** [comment]
Hello 

My language is Greek ... After i added the Greek Translation it is fixed ...but still is a issue ..It is missing the English translation ..

**Comment by atm-maxime** [comment]
Translation are dealt with on transifex.

**Comment by VaderD** [comment]
> Translation are dealt with on transifex.

Hello,

OK !

**Comment by VaderD** [comment]
Any news regarding this issue ..?

**Comment by priojk** [comment]
Dear VaderD,

please let me offer some advice, which is intended in a friendly way. It is not helpful to comment all your issues in GitHub with a question  asking for news on the issue. This is not how the development of open source software works, since noone is obliged to work on this. Rest assured that if someone has a solution for your issue, they will publish it in this place without the need to ask for an update.

In the meantime, there are various options:
- if you are into programming, you can provide a patch, which can then be reviewed and integrated
- if you are not into programming, you can fund a programmer to create a patch
- or you can wait, if someone picks the issue up - again, noone is obliged to do this

And in this particular case regarding a translation issue, it's just about creating an account on Transifex (it's absolutly hassle-free and also possible for non-programmers) and just correct, whatever the issues with translations are.
