### ISSUE TITLE
Add configurations to activate comment on tasks and projects

### ISSUE THREAD

**Issue by aschio** [Dolibarr/dolibarr#19710]
Comments on projects and tasks are available only with PROJECT_ALLOW_COMMENT_ON_TASK and PROJECT_ALLOW_COMMENT_ON_PROJECT constant inserted manually. 

Why there isn't configuration in Project module admin page?

**Comment by atm-maxime** [comment]
Hi @aschio !
This is a hidden feature for now because there has been not so much feedbacks about it, and it is very similar to events so maybe it should be replaced by events with a specific display/type

**Comment by aschio** [comment]
Thanks @atm-maxime for clarification. 
In my opinion, comments features are very useful and they can help and improve communication between users that work on same task/projects

**Comment by IgorA100** [comment]
It's not a good idea to use events for commenting, because events are displayed in the calendar, which clutters it up.
There are two options:
1. Pass the event module so that it can be used as comments, but IMHO this is not the best idea.
2. Refine the comments module (sending notifications by mail, the ability to attach files). I think this will be the best solution.
