### ISSUE TITLE
14.0.4 - Bug on Deposit Invoice Supplier For Final Supplier Invoice

### ISSUE THREAD

**Issue by Sylvain089** [Dolibarr/dolibarr#19724]
# Bug
When generating a Deposit Supplier Invoice (After paid this invoice), and applying this "deposit" invoice on a Final Invoice Supplier, the amount of this invoice is not applied to "remain to pay" of the Final supplier invoice.

## Environment
- **Version**: 14.0.4
- **OS**: Linux (NAS Synology), although irrelevant
- **Web server**: Apache, although irrelevant
- **PHP**: 7.4.18, although irrelevant
- **Database**: MariaDB 10, although irrelevant
- **URL(s)**: htdocs/fourn/facture/card.php?facid=23&save_lastsearch_values=1

## Expected and actual behavior
The remain to pay is not affected when applying a Deposit Supplier Invoice to a Final supplier invoice. 

## Steps to reproduce the behavior
- Create a Deposit Supplier Invoice with the TTC amount : 300 €
- Paid this Deposit Supplier Invoice
- Create a Final Supplier Invoice with the TTC amount : 900 €
- Validate the final supplier invoice
- Apply the Deposit Supplier Invoice (The invoice number and the total amount appear, on the right position)
- The Deposit amount is not apply on the remain to pay, the amount keeps : 900 €

You can fix this issue by : 
This error is due to a bug in the file : htdocs/core/class/commoninvoice.class.php : 
To fix this issue : The lines 162 to 164 must be commented to avoid return "0.0" for the function "public function getSumDepositsUsed($multicurrency = 0)"

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
Subject in English Forum : 
https://www.dolibarr.org/forum/t/report-bug-supplier-deposit-invoice/21015/2

**Comment by josett225** [comment]
Hi there,

This issue is still  in Dolibarr v14.0.5.
Also strangely, we cannot do it anymore in V15 and V16 as the Deposit can be used only as a discount line added to the supplier invoice. Anyway to fix the issue as explain above and if possible understand the changes done in V15 and V16 
See screenshots for v14 and v16 and V14 with the fix above.
Many thanks

V14 with no fix
<img width="626" alt="Screenshot at May 20 19-55-53 Deposit issue" src="https://user-images.githubusercontent.com/57623859/169586899-a5bc0bba-0390-483d-8434-e1ffcd6253e8.png">
V16
<img width="611" alt="Screenshot at May 20 19-55-53 Deposit issue V16" src="https://user-images.githubusercontent.com/57623859/169587355-ef3694a0-2d63-412b-923d-36c4a8d75b8b.png">
V14 with fix
<img width="623" alt="Screenshot at May 20 20-13-27 Deposit V14 after fix" src="https://user-images.githubusercontent.com/57623859/169588618-3fa43ab1-c4fb-4b54-b4bc-a93a828b67f3.png">

**Comment by josett225** [comment]
Dear @aspangaro and @eldy 

Not sure if I have to open a new issue here but this bug in v14 and the new behavior in v15 and above is impacting us.
I have been trying to find information on both forums and in the changelog without success. 
We would like to keep same behavior as in v14 as this is bringing margin issues in Customer Invoices. see Screenshot. In this example, the margin has to be 50% and not 31,03%. The issue is coming from the Deposit is considered as a product...
Could you please have a look on these 2 issues/bugs are stopping us in using v14 in the supplier side and also migrating to new versions v15 and above?
Many thanks
Jose
<img width="620" alt="Screenshot at May 21 19-34-50 Margin issue" src="https://user-images.githubusercontent.com/57623859/169662994-50deddaa-e45a-4da3-a0a3-a13d4313edcc.png">

**Comment by josett225** [comment]
Of course this is for both Supplier and Customer Deposit behavior.

**Comment by josett225** [comment]
Hi there,

Surprisingly, to make it work in v15 as in v14, I used the following const FACTURE_DEPOSITS_ARE_JUST_PAYMENTS and now I get this screenshot where everything is OK :

<img width="638" alt="Screenshot at May 22 09-31-31 DEPOSIT AND MARGIN OK" src="https://user-images.githubusercontent.com/57623859/169684025-e7a7d58d-ded8-4caf-b022-87b093a814a7.png">

**Comment by eldy** [comment]
Using a deposit as a payment, instead of as an invoice used to reduce the amount of final invoice, is not recommended. It brings a lot of trouble. But you can get this feature working by setting the hidden option FACTURE_DEPOSITS_ARE_JUST_PAYMENTS to 1. However, this is supported for down payment (deposit) for sale invoice only.
Having this feature working for purchase invoice need to introduce similar code like FACTURE_SUPPLIER_DEPOSITS_ARE_JUST_PAYMENTS     (not yet implemented)
