### ISSUE TITLE
XDebug does not work docker build environment

### ISSUE THREAD

**Issue by smil2k** [Dolibarr/dolibarr#19896]
# Bug

XDebug in the docker build is upgraded to 3 meanwhile, settings stayed 2.

**Comment by IC-Florian** [comment]
The last version of xdebug released last thursday is not compatible with php 7.3 because of a security flaw it is more than supported by php 8.
It is fixed in the PR #23274  With the use of docker in PHP7 I forced the XDebug version 3.1.6
![image](https://user-images.githubusercontent.com/71641704/208677635-c6543c51-45fb-42de-8da3-58642338e535.png)

**Comment by ksar-ksar** [comment]
Hello,

Is it still the case on V18 ?
