### ISSUE TITLE
Cannot create new installation: duplicated table llx_onlinesignature

### ISSUE THREAD

**Issue by cbrunet** [Dolibarr/dolibarr#19974]
### Bug

Cannot create database from scratch.

In htdocs/install/mysql/tables, there are two files with the same table definition: llx_onlinesignature.sql and llx_online_signatures.sql. It causes the install process to fail at step2.php.

After that, there is a duplicated index uk_code_region:
llx_c_departements.key.sql:ALTER TABLE llx_c_regions ADD UNIQUE INDEX uk_code_region (code_region);
llx_c_regions.key.sql:ALTER TABLE llx_c_regions ADD UNIQUE INDEX uk_code_region (code_region);

When loading data,
there is a conflict on key uk_c_tva_id on table llx_c_tva
on the same table, there are two rowid 1471 (in Mali) and tow rowid 107 (in Tunesia) 2051 and 2052 are there two times (south africa)

After all those changes, I was finally able to install Dolibarr...

### Environment Version

14.0.5

### Environment OS

arch linux

### Environment Database

mariadb

**Comment by eldy** [comment]
The lines
llx_c_departements.key.sql:ALTER TABLE llx_c_regions ADD UNIQUE INDEX uk_code_region (code_region);
llx_c_regions.key.sql:ALTER TABLE llx_c_regions ADD UNIQUE INDEX uk_code_region (code_region);
Is not a duplicated index code. The sql is exactly the same, so it is just a try to create the same index, so same name on same table. This should not be a problem for the installer that ignore such cases.
The goal of having this request duplicated into llx_c_departements.key.sql is because when we create the keys for table llx_c_departments, we can not add a foreign key if there is no index on parent table, so we create it just before creating the 
ALTER TABLE llx_c_departements ADD CONSTRAINT fk_departements_fk_region	FOREIGN KEY (fk_region) REFERENCES llx_c_regions (code_region);

Then we recreate it when creating the indexes of llx_c_regions because it should be its real place to be create. If  it already exists, the installer should ignore this.
Do you mean you have an error during wizard install process ? Can you provide a screenshot that show the error with error code ?

**Comment by cbrunet** [comment]
![image](https://user-images.githubusercontent.com/25658/152611686-0f4d26ef-a70d-4034-b624-5f0d8708958f.png)

**Comment by cbrunet** [comment]
![image](https://user-images.githubusercontent.com/25658/152611796-f5dd7efc-66af-4bfe-8fc8-812898489a5f.png)

**Comment by cbrunet** [comment]
This installation is directly from the 14.0 branch.

**Comment by caos30** [comment]
I suppose that this has not been solved yet. I've passed 2 days trying to install unsuccessfully Dolibarr14 and Dolibarr13, taking the last versions on Github / Dolibarr / Releases (in fact i tried with all the versions of 14.X) and i never accomplished the install process... 

Just all begin with the error explained in the first comment of this Github thread. And altgough i've been doing a hard and slow work of debugging, fixing those errors (duplicated insertions in database) then arise more and more duplications in an unfinished chain of fix and new error, fix and new error.

Certainly, i have no idea how does it's possible, because i had installed those versions in my previous "desktop server" (ubuntu+mysql). Maybe the difference is that now i'm using PHP 8.1 instead of PHP 7.2 ? Or maybe that i'm using last versions of mariadb and probably before i was using mysql for database instead of.

I don't know. But this is quite annoying. As module developer i like to test all my modules and its changes (new features) to be compatible in all the "old" versions (Dolibarr 14 is only 1.5 years away !). For this reason i had installed in my development desktop ubuntu all the Dolibarr versions from 5.x to 16.x but now i don't know how i will do this debugging 😞

So, Eldy, it would be very useful for all of us to have warranty that these versions are "usable" (at least installable!!!) in PHP/mariadb versions of 3-5 years ago... You know (i hope) that there are people that sadly doesn't update their servers or OS ... 

Maybe there is an easier way to run these "old" versions in an more easy way that let us to try our modules... please tell me! Maybe a docker containing certain linux versions, and mysql/php/dolibarr versions ?
