### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jongerli** [Dolibarr/dolibarr#20005]
# Feature request
When extra fields are created in modules, they are displayed on the various UI screens. And right now it is only possible to render these fields one line at a time.
Perhaps it is a possible to place moere then one field per line? I.e. 2 or three to keep the amount of extra lines limited?
This would make the use of extra fields even better. 

## Expected and actual behavior
- Every extra field is placed on a new line.
- Several extra fields can be placed on the same line on the UI.

**Comment by ksar-ksar** [comment]
Hello,

It is possible with External modules like https://www.dolistore.com/en/modules/1199-Dolitools.html

**Comment by jongerli** [comment]
Hello Ksar, Many thanks for your reply. We will contact the developer (altairis.fr). The video's were not conclusive so we have to investigate a little more.

**Comment by ksar-ksar** [comment]
@altairis-tof ?

**Comment by altairis-tof** [comment]
hello @ksar-ksar i was indeed in contact with @jongerli ; thanks

**Comment by jongerli** [comment]
We bought the Dolitools module in the Dolistore but the requested functionality is unfortunately not covered by this module.  Christophe has confirmed that this is the case:-(

So this feature request is still alive.

**Comment by altairis-tof** [comment]
for more information, dolitools allows to display document lines extrafields in the line instead of on one line per extrafield like on the screeshot below : 
![image](https://user-images.githubusercontent.com/396322/153244357-48f98095-2d2d-431c-8099-ea2148e16342.png)

but the requested feature concern display of extrafields on card like this : 
![image](https://user-images.githubusercontent.com/396322/153244442-1d238a56-9951-46b3-b012-60a65d7d21b6.png)

**Comment by dpriskorn** [comment]
I have 15 extrafields on my product module and mostly populate them via my Dolibarr Python API. I sometimes want to edit a card and the I have to scroll a lot. 
Maybe a switch to a searchable interface could help? 
So you have a search bar after clicking edit that helps filtering the list of fields?
