### ISSUE TITLE
v15 can't classify "billed" in order after upgrade from 14.0.3

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#20191]
### Bug

Can't classify the order status to " billed " .

### Environment Version

v15.0.0

### Environment OS

windows 7

### Environment Web server

 Apache/2.4.38 Apache/2.4.41 

### Environment PHP

7.4.1

### Environment Database

MariaDB 5.5.5-10.4.1

### Environment URL(s)

commande/card.php?id=144&save_lastsearch_values=1

### Expected and actual behavior

Should can classify the order to " billed " , if the user hasve the permission .

### Steps to reproduce the behavior

In windows system and upgrade to v 15 then try to classify the order to billed status .

**Comment by eldy** [comment]
What do you mean with "can't". Do you have an error message ? Which one ? When ? What is the current behaviour ?

**Comment by trekmorris** [comment]
Hi 

That is mean that you can see  the button " CLASSIFY BILLED " button .
But when you try to click it , nothing happen . And no error message show out .
The situation  is like my the other issue #20131 , noting happen after click the button .
So i have restored dolibarr back to 14.0.3 .
If you need more information , i could try to upgrade and try again .

**Comment by ojt1998** [comment]
I had this error and it seemed to relate to the new signatures function. I commented out the signature code and that then allowed me  to classify as billed.

**Comment by ojt1998** [comment]
Commenting out the getOnlineSignatureUrl() function allows an order to be classed as billed.

PHP Fatal error:  Uncaught Error: Call to undefined function getOnlineSignatureUrl() in /var/www/dolibarr/htdocs/core/lib/functions.lib.php:7273\nStack trace:\n#0 /var/www/dolibarr/htdocs/core/modules/propale/doc/doc_generic_proposal_odt.modules.php(407): getCommonSubstitutionArray()\n#1 /var/www/dolibarr/htdocs/core/class/commonobject.class.php(5297): doc_generic_proposal_odt->write_file()\n#2 /var/www/dolibarr/htdocs/comm/propal/class/propal.class.php(3738): CommonObject->commonGenerateDocument()\n#3 /var/www/dolibarr/htdocs/comm/propal/class/propal.class.php(2679): Propal->generateDocument()\n#4 /var/www/dolibarr/htdocs/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php(126): Propal->classifyBilled()\n#5 /var/www/dolibarr/htdocs/core/class/interfaces.class.php(183): InterfaceWorkflowManager->runTrigger()\n#6 /var/www/dolibarr/htdocs/core/class/commonobject.class.php(5559): Interfaces->run_triggers()\n#7 /var/www/dolibarr/htdocs/commande/class/commande.class.php(2954): CommonObject->call_trigger()\n#8 /var/www/dolibarr/htdocs/commande/card.php(506): Commande->classifyBilled()\n#9 {main}\n  thrown in /var/www/dolibarr/htdocs/core/lib/functions.lib.php on line 7273

**Comment by ksar-ksar** [comment]
Hello,

Seems linked to the workflow module.
Another user got the problem here : https://www.dolibarr.org/forum/t/uncaught-error-when-creating-an-invoice-from-sales-order/22165

Fatal error : Uncaught Error: Call to undefined function getOnlineSignatureUrl() in /home/berlintr/public_html/dolibarr/core/lib/functions.lib.php:7273 Stack trace: 
#0 /home/berlintr/public_html/dolibarr/core/modules/propale/doc/doc_generic_proposal_odt.modules.php(407): getCommonSubstitutionArray(Object(Translate), 0, NULL, Object(Propal)) 
#1 /home/berlintr/public_html/dolibarr/core/class/commonobject.class.php(5297): doc_generic_proposal_odt->write_file(Object(Propal), Object(Translate), ‘/home/berlintr/…’, 0, 0, 0, NULL) 
#2 /home/berlintr/public_html/dolibarr/comm/propal/class/propal.class.php(3738): CommonObject->commonGenerateDocument(‘core/modules/pr…’, ‘generic_proposa…’, Object(Translate), 0, 0, 0, NULL) 
#3 /home/berlintr/public_html/dolibarr/comm/propal/class/propal.class.php(2679): Propal->generateDocument(‘generic_proposa…’, Object(Translate), 0, 0, 0) 
#4 /home/berlintr/public_html/dolibarr/core/triggers/interface_20_modWorkflow_WorkflowManager.class.php(126): Propal->classifyBilled(Object(User)) 
#5 /hom in /home/berlintr/public_html/dolibarr/core/lib/functions.lib.php on line 7273

**Comment by hregis** [comment]
@ksar-ksar @eldy @ojt1998 @trekmorris 

it's fixed here : https://github.com/Dolibarr/dolibarr/pull/20610
