### ISSUE TITLE
Invalid date when creating invoice

### ISSUE THREAD

**Issue by daftac** [Dolibarr/dolibarr#20361]
### Bug

My timezone is -10 (Pacific/Tahiti). The php.ini and OTHER SETUP "MAIN_SERVER_TZ" is set for this timezone.
I created a new invoice and put the date of today. I got this error : "Erreur, la date ne peut pas être dans le futur."

Tested with two different webserver and PHP and DB version.
Noted the error message is only the morning from Tahiti.
Noted that's still working with proposals.
Version 14.0.5 didn't work too.

But with the SETUP "INVOICE_MAX_FUTURE_DELAY" to 86400, it can accept the date of today.

### Environment Version

15.0

### Environment OS

Linux OVH or others

### Environment Web server

Apache

### Environment PHP

7.4

### Environment Database

MariaDB 5.6.50

### Expected and actual behavior

No error message

### Steps to reproduce the behavior

I created a new invoice and put the date of today.

### Attached files

![image](https://user-images.githubusercontent.com/2188830/158370929-d51dde1a-88a0-4272-83f2-dcb0210e29c9.png)

**Comment by Enjoy987** [comment]
Hello, I from Tahiti too and I have the same problem
I search for the variable "INVOICE_MAX_FUTURE_DELAY" but I think that it is not the good solution
From what I understood this variable allows when it is modified to make invoices in the future

And you ? You have find a solution ?
I'm really interested because it bothers me a lot

**Comment by daftac** [comment]
For sure it's not the good solution to use the variable "INVOICE_MAX_FUTURE_DELAY" but it's the only solution at the moment.
