### ISSUE TITLE
Third party merging : need to merge llx_bookkeeping 

### ISSUE THREAD

**Issue by AurelienBISOTTI** [Dolibarr/dolibarr#20454]
### Feature Request

When merging 2 third parties, modifications occurs in the llx_facture table, which is fine.

The missing part is for llx_bookkeping : the "thirdparty_code" and label are still those of the third party that was deleted.

This is going to cause a mess in accounting of users, and cause headache to a lot of accountants.

Before merging : 

![7](https://user-images.githubusercontent.com/12530585/159892073-239fba81-4f92-43d4-beaa-07567606af1a.PNG)
![8](https://user-images.githubusercontent.com/12530585/159892096-4bf8a5eb-4815-4cb2-9d8e-202b5fcda256.PNG)

Merging :

![9](https://user-images.githubusercontent.com/12530585/159892114-dd2ccb71-b392-42aa-bdef-4f004eca9e81.PNG)

After merging : llx_facture is OK but llx_bookkeeping is NOK

![11](https://user-images.githubusercontent.com/12530585/159892140-5e8bd3ae-fe52-4599-aeac-55cc0db6eda7.PNG)
![10](https://user-images.githubusercontent.com/12530585/159892128-687d18c3-3f84-42b0-afde-e1aabb46eb54.PNG)

### Use case

Use the Dolibarr core function "merge" from third party.

### Suggested implementation

Also merge thirdparty_code and subledgder_laber

**Comment by aspangaro** [comment]
Hello,

In fact, you are right, the merger of third parties does not affect the accounting.

Nevertheless, it is desired because there is a principle in accounting that consists in keeping the information historical. Imagine the case where you merge a third party that you have been using for several fiscal years, you will come back to modify accounting entries that are several years old? This is not allowed.

Moreover, in Dolibarr, only the accounting module has the right to modify information, not the other modules. This is normal given what I explain above. If you want the information to be up to date, you have to delete the operation from the accounting (Sales + Payment) and re-enter the operations. It's annoying but you respect the accounting generation procedure this way.

Have a nice day
