### ISSUE TITLE
Authorship recognition at ticket API messaging

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#20582]
### Feature Request

Currently in Dolibarr 15.0.1, Dolibarr provides very simple ticket messaging via it's API. Generally API client is connected using an API key. The SuperAdmin key is generally used for API communication. Now here is the lack of features in the ticket API communication.

1. If a website user, third party or customer creates a ticket using API, Dolibarr can't recognize them. It simply logged SuperAdmin as the ticket author. But the author should be the user or customer.
2. If a website user, third party or customer  reply to a ticket with the message, again SuperAdmin is taken as the author of the message. While the message author would be the website user, customer or third party.

The above said features is not available in the DOLIBARR Ticket API. I think it's a very basic required features for a ticket based messaging system.

**Comment by alsoft10** [comment]
@eldy I am actively waiting for feedback in this matter.

**Comment by priojk** [comment]
What kind of feedback do you need? Whether it's ok to submit a pull request? Since it's quite straight forward, I would say, just go ahead.

However, since @pratushraj already created something and mentioned your issue - does this suit your needs? Could be a helpful input. Note: the pull request is based on 15.0, but since it's a new feature and not a bug, I guess it will rather go into the develop branch.

**Comment by alsoft10** [comment]
@priojk you are correct. @pratushraj's issue will be fit for the purpose. Pratushraj already created the pull request for this feature request. You can check that at #20598.
