### ISSUE TITLE
Take POS Terminal Stuck

### ISSUE THREAD

**Issue by Mohamedali1880** [Dolibarr/dolibarr#21048]
### Bug

Normally when we make the payment of any takepos invoice its transferred from  Provision to validated invoice and take invoice number instate of (PROV-POS1-0) in provision status 
but some time this error happing 
Invoice paid and Stuck in terminal in takepos and still have invoice number (PROV-POS1-0) so terminal will not work and the only solution to make it work again to delete this invoice with its payment 

### Environment Version

15.0.1

### Environment OS

Linux

### Environment Web server

Apache

### Environment PHP

7.4.29

### Environment Database

MySQL or MariaDB 5.5.5-10.6.7-MariaDB

### Environment URL(s)

takepos/index.php

### Attached files

![aaa99](https://user-images.githubusercontent.com/101186512/170850408-5f407d45-f434-43cf-8761-77a60ff0b935.JPG)

**Comment by pajariko** [comment]
This bug is still present in Dolibarr v23.0.
Environment:

Dolibarr: v23.0
PHP: 8.x
Database: MariaDB
OS: Linux

Description:
We are experiencing the same issue. Occasionally, after completing a payment in TakePOS, the invoice remains stuck as PROV-POS1-x instead of being validated with a definitive invoice number. When this happens, the terminal becomes unusable and the only workaround is to manually delete the stuck invoice and its associated payment from the database.
This is a critical issue for daily operations as it blocks the POS terminal and requires technical intervention that regular staff cannot perform.
It would be very helpful if TakePOS included a built-in mechanism to recover from this situation without needing direct database access.
