### ISSUE TITLE
REST API documents upload not working with multicompany

### ISSUE THREAD

**Issue by Inkapa** [Dolibarr/dolibarr#21062]
### Bug

I've been trying to upload a file through the `/documents/upload/` route of the REST API, to no avail.

When sending an object formatted like so:
```json
{
   "filename":"jwas.png",
   "modulepart":"product",
   "subdir":"REF12345",
   "filecontent":"some base 64 image string",
   "fileencoding":"base64"
}
```

I am met with a 401 and the error: `Unauthorized: Error returned by dol_check_secure_access_document: Value entity must be provided`.

The error seems to come from this function: https://doxygen.dolibarr.org/15.0/de/d28/files_8lib_8php.html#a7c5616c107346560a8a21b85cc12a291

What I've tried:
- Sending the same object through a local dolibarr instance's api without the multicompany plugin (it works)
- Making sure I have the `DOLAPIENTITY` header (I get a different 401 "Unauthorized" message when I don't)
- Making sure I have the correct perms to upload documents
- Trying to upload the same document through the product page route rather than the api (it works)
- Adding an `entity` property to my object (it obviously does nothing, but at least I tried)

### Environment Version

15.0.1

### Environment OS

Ubuntu (I'll need to ask my boss)

### Environment Web server

Apache

### Environment Database

MySQLi

### Environment URL(s)

/api/index.php/documents/upload

**Comment by evilham** [comment]
@Inkapa hey, thanks for confirming I wasn't losing my mind there.

Once that was settled, I figured that it's a permissions issue:

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/api/class/api_documents.class.php#L579

`ecm` does not exist AFAIK, and it ought to be `->fournisseur->`  something, since the corresponding permission does not exist (by checking in the database directly), I decided to patch the file and using `fournisseur->supplier_invoice_advance->validate` as a proxy for "can upload since it can validate".

Hope this helps someone with a deeper understanding of Dolibarr to fix the issue.
