### ISSUE TITLE
After restore database , the public notes of proposal and order willl show error message

### ISSUE THREAD

**Issue by trekmorris** [Dolibarr/dolibarr#21072]
### Bug

After restore database to the other new server , if you try to edit public notes of old proposal and old order willl show error message as below .
If you create new proposal or new order then edit public notes , it will not show any error .

![image](https://user-images.githubusercontent.com/78349579/171199615-efc31692-8c35-4d34-87fb-ed05f11acbc1.png)

### Environment Version

v 14.0.3 and v15.0.2

### Environment OS

Deian 11 windows 7

### Environment Web server

Apache/2.4.38 Apache/2.4.41

### Environment PHP

7.4.28

### Environment Database

5.5.5-10.5.15-MariaDB-0+deb11u1

### Environment URL(s)

comm/propal/note.php

### Expected and actual behavior

Should not show any error .

### Steps to reproduce the behavior

Create a new proposal , then backup database .
Import that datebase to the other new server .
Try to edit public notes of that proposal .

**Comment by rycks** [comment]
hello, could you please send us a database backup ? i'm sorry but i can't reproduce the bug...

**Comment by trekmorris** [comment]
Hi 

Sorry for late reply .
Please test the database . You could login with username ' test ' and password ' test ' .

**Comment by rycks** [comment]
Hello,
thanks for your database, please remove it if you can because there is some informations about your staff.

Here is what i have on a dolibarr 14.0.5:

![image](https://user-images.githubusercontent.com/1468823/216776314-23fc190f-e015-49f4-aa65-1afb30ab6f1e.png)

then i clic on the icon to update public note :

![image](https://user-images.githubusercontent.com/1468823/216776343-18d0fa35-2d8f-4ef0-9682-4e6ba714e982.png)

and no problem ... sorry

**Comment by rycks** [comment]
hmmmmmmm ok the problem is after, when you clic on save ! i've got it !!!

![image](https://user-images.githubusercontent.com/1468823/216776560-dcd20f17-a505-43c4-9cb8-120e2535b676.png)


sorry, not so easy for me with a non latin language like your :)

**Comment by rycks** [comment]
Ok,
the solution / the reason is ... your propal was linked to a special document type /var/lib/dolibarr/documents/doctemplates/proposals/01_quot_print_locale.odt

and that file does not exist on my dolibarr and the same problem on your "new" dolibarr ... so just switch to "azur" for example, clic on save button, then after that you could add public notes on your propal without any errors :)

![image](https://user-images.githubusercontent.com/1468823/216777347-4d11fa59-8de0-4472-ba05-1765f68d3165.png)

**Comment by rycks** [comment]
but you found real a bug, let me do the job to correct that ! thanks

**Comment by rycks** [comment]
and here is the "good" solution i think, i will send that patch as a PR to dolibarr core

![image](https://user-images.githubusercontent.com/1468823/216777684-50963664-35fc-45f7-bb13-7f5c841275c0.png)

**Comment by rycks** [comment]
i've switched from error message to warning because of that is not a real error
