### ISSUE TITLE
dolibarr_15.0.2-4_all.deb is corrupted

### ISSUE THREAD

**Issue by ksar-ksar** [Dolibarr/dolibarr#21109]
### Bug

root@dolibarr:~# dpkg -i dolibarr_15.0.2-4_all.deb
dpkg-deb: error: archive ‘dolibarr_15.0.2-4_all.deb’ uses unknown compression for member ‘control.tar.zst’, giving up
dpkg: error processing archive dolibarr_15.0.2-4_all.deb (–install):
dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
dolibarr_15.0.2-4_all.deb

Workaround :
#!/bin/sh
ar x dolibarr_15.0.2-4_all.deb
unzstd control.tar.zst
unzstd data.tar.zst
xz control.tar
xz data.tar
rm dolibarr_15.0.2-4_all.deb
ar cr dolibarr_15.0.2-4_all.deb debian-binary control.tar.xz data.tar.xz

### Environment Version

15.0.2

### Environment OS

Debian

**Comment by qaOYR** [comment]
@ksar-ksar 

Hi,

I can confirm the above error happens in Debian 11.3, but the same binary file (15.0.2-4_all.deb) installs correctly in Ubuntu Server 20.04.

It appears that dpkg has not implemented the zst compression library for package archives in debian.

Previous Dolibarr releases did not have this issue as the same deb package was installable in both Debian 11 and Ubuntu Server 20.

Please let me know if additional info is needed in order to solve this packaging issue.

**Comment by qaOYR** [comment]
@ksar-ksar 

I hope the wonderful folks at Dolibarr will fix the issue, but in the meantime you can workaround as follows:

Install ar in Debian which is part of the binutils package.  Install the zstd compressor as well:

apt install binutils zstd

Create and run the following script in the directory where you have the deb package. The result will be a deb package that is packaged in the xz compression algorithm and one that you can install on Debian without issues.

    #!/bin/sh
    # Convert deb package from zst compression to xy compression
    ar x dolibarr_15.0.2-4_all.deb
    unzstd control.tar.zst
    unzstd data.tar.zst
    xz control.tar
    xz data.tar
    rm dolibarr_15.0.2-4_all.deb
    ar cr dolibarr_15.0.2-4_all.deb debian-binary control.tar.xz data.tar.xz

**Comment by stephanehofman** [comment]
Duplicate with https://github.com/Dolibarr/dolibarr/issues/20894
