### ISSUE TITLE
Lien de paiement de facture Stripe KO

### ISSUE THREAD

**Issue by Drosdov56** [Dolibarr/dolibarr#21122]
### Bug

Le lien de paiement Stripe dans factures qui fonctionnait jusqu’alors m’envoie depuis la dernière mise à jour (v15) sur une page 404

### Environment Version

15.0.2

### Environment OS

Debian 10

### Environment Web server

nginx/1.20.2

### Environment PHP

php 7.4.29

### Environment Database

MariaDB 10.3.34 // libmysql - mysqlnd 7.4.28

### Environment URL(s)

 https://crm.serpette.fr/crm/htdocs/public/onlinesign/newonlinesign.php?source=proposal&ref=DEV-22191&securekey=%242y%2410%24f/2QutPXzYcgyQI5ZvxyPeksSOgSTjQXnr.XiutVZuSQoWf7Oi6tG

### Expected and actual behavior

Renvoyer l'url de paiement stripe vers le paiement en ligne

**Comment by daraelmin** [comment]
Hello,

There seems to be a problem in the beginning of the link. Indeed, the correct URL should be:
https://crm.serpette.fr/htdocs/public/onlinesign/newonlinesign.php?....
and no
https://crm.serpette.fr/crm/htdocs/public/onlinesign/newonlinesign.php?...
(Without the "crm/" between ".fr/" and "htdocs/")
Something like that :
https://crm.serpette.fr/htdocs/public/onlinesign/newonlinesign.php?source=proposal&ref=DEV-22191&securekey=%242y%2410%24f/2QutPXzYcgyQI5ZvxyPeksSOgSTjQXnr.XiutVZuSQoWf7Oi6tG
I just can't reproduce the error. It may be because all my instances are configured so that the root of the site is the htdocs and not its parent.

sorry

*********** French version ***********

Hello,

Il semblerait qu'il y ait un problème dans le début du lien. En effet, l'URL correcte devrait être :
https://crm.serpette.fr/htdocs/public/onlinesign/newonlinesign.php?....
et non
https://crm.serpette.fr/crm/htdocs/public/onlinesign/newonlinesign.php?...
(Sans le "crm/" entre ".fr/" et "htdocs/")
Quelques choses comme ça :
https://crm.serpette.fr/htdocs/public/onlinesign/newonlinesign.php?source=proposal&ref=DEV-22191&securekey=%242y%2410%24f/2QutPXzYcgyQI5ZvxyPeksSOgSTjQXnr.XiutVZuSQoWf7Oi6tG

Je n'arrive pas à reproduire l'erreur simplement. C'est peut être parce qur toutes mes instances sont configurée pour que la racine du site soit le htdocs et non son parent.

Désolé

**Comment by emheyarssi** [comment]
Please write in english. Thanx

**Comment by hregis** [comment]
@Drosdov56 @daraelmin

And what is the URL in conf.php?

**Comment by Drosdov56** [comment]
Bonjour,
Merci pour la réponse.
en fait le "quelque chose comme ça" fonctionne :)

[Quelques choses comme ça : [https://crm.serpette.fr/htdocs/public/onlinesign /newonlinesign.php?source=proposal&ref=DEV-22191&securekey=%242y%2410%24f/2QutPXzYcgyQI5ZvxyPeksSOgSTjQXnr.XiutVZuSQoWf7Oi6tG](https://crm.serpette.fr/htdocs/public/onlinesign/newonlinesign.php?source=proposal&ref=DEV-22191&securekey=%242y%2410%24f/2QutPXzYcgyQI5ZvxyPeksSOgSTjQXnr.XiutVZuSQoWf7Oi6tG)]

Il y a donc bien /crm en trop dans la chaine ... 
Est-ce que c'est un souci de paramétrage initial ou bien le module qui configure mal le lien ?

**Comment by Drosdov56** [comment]
> @Drosdov56 @daraelmin
> 
> Et quelle est l'URL dans conf.php ?

de quelle url parlez vous dans le fichier conf ?

**Comment by hregis** [comment]
@Drosdov56 the value of "$dolibarr_main_url_root"

**Comment by Drosdov56** [comment]
> @Drosdov56la valeur de "$dolibarr_main_url_root"

https://crm.serpette.fr/crm/htdocs

**Comment by emheyarssi** [comment]
Sorry but this conversation has nothing to do here. Please go to the Dolibarr forum for such of details. Thanx

**Comment by ksar-ksar** [comment]
> > @Drosdov56la valeur de "$dolibarr_main_url_root"
> 
> https://crm.serpette.fr/crm/htdocs

C'est de là que vient le problème, ça devrait être https://crm.serpette.fr/htdocs (sans crm)

**Comment by hregis** [comment]
Tu peux même définir ton dolibarr dans htdocs! Un truc de dingue !..  Avant de poser un "bug" est-ce que vous pouvez apprendre à faire un serveur Web ! Souvent le bug c'est soit même ! 😉

**Comment by Drosdov56** [comment]
> Tu peux même définir ton dolibarr dans htdocs ! Un truc de dingue !.. Avant de poser un "bug" est-ce que vous pouvez apprendre à faire un serveur Web ! Souvent le bug c'est soit même !😉

Dis donc Régis un peu plus d'amabilité et moins d'ironie ça ne nuit à personne (au fait je suis un des tes très anciens clients c'est un truc de dingue ça aussi nan ;) !!
J'ai posté un message sur le forum on m'a envoyé ici ... perso je m'en serais bien passé.

Entre toi et emheyarssi (qui demande en français de parler en anglais haha ... please excuse my poor English ^^) vous devez bien vous entendre merci pour l'accueil ça fait plaisir :)

Bref belle soirée à vous et pas d'inquiétude je ne reviendrai pas ...
Love 

ps : juste pour parler un peu technique, le module fonctionnait bien jusqu'à maintenant et la page de paiement se chargeait bien ... Je n'ai fait aucune manip dans mon ftp et mes variables et ça a merdé ...

**Comment by Drosdov56** [comment]
> > > @Drosdov56la valeur de "$dolibarr_main_url_root"
> > 
> > 
> > https://crm.serpette.fr/crm/htdocs
> 
> C'est de là que vient le problème, ça devrait être https://crm.serpette.fr/htdocs (sans crm)

Merci beaucoup pour le retour  ... ça fonctionne sans /crm je n'avais pas analysé le lien ... cependant je n'ai touché à rien et ça marchait avant ...
Belle soirée <3

**Comment by hregis** [comment]
@Drosdov56 
je suis le plus aimable du monde ! c'est juste que... à force... et bien... je... enfin... comment dire... ;-)

**Comment by hregis** [comment]
C'est la faute à Macron !
