### ISSUE TITLE
[BUG] Public notes are lost when donation status is changed from valid to draft

### ISSUE THREAD

**Issue by iouston** [Dolibarr/dolibarr#21507]
### Bug

When a donnation is validated. You can add a public note.
If you rechange the donnation's status to draft, notes are lost

### Environment Version

15.0.2

**Comment by emheyarssi** [comment]
Related with #21199?

**Comment by atm-jpb** [comment]
we have this on update action 
 $object->note_private = (string) GETPOST("note_private", 'restricthtml'); 
 $object->note_public = (string) GETPOST("note_public", 'restricthtml');
i think the bug came from this two lines.
there is no sense to update public and private note at this point. the tab note do the job very well
a quik fix is to comment this two lines
