### ISSUE TITLE
Add Slack-like chat/discussion module

### ISSUE THREAD

**Issue by Adventurousdonut** [Dolibarr/dolibarr#21760]
### Feature Request

Add a chat/discussion module that looks similar to slack, where employees can chat with each other and send each other files, etc.

### Use case

Employees can send each other texts and files.

**Comment by ksar-ksar** [comment]
Hello,

This is typically something that could be developed as external module (an there is already some : https://www.dolistore.com/en/search?controller=search&orderby=position&orderway=desc&tag=&search_query=chat)
I don't think it is necessary to have it on the core, because it is not a common need.
