### ISSUE TITLE
Add a summary line to replenish.php

### ISSUE THREAD

**Issue by AndreasSt-2022** [Dolibarr/dolibarr#22337]
### Feature Request

Please add a summary line to the replenish page, especially when a single supplier is selected. This summary line should show the total amount of a possible new order that is necessary to reach the desired stock levels for all products of this supplier. Of course this is possible only after all supplier prices have been entered.

### Use case

Some suppliers have a minimum order amount, some have a limit for free shipping. It would be helpful to see if the total order amount of a possible new order would be above this limit, or not. This would help to decide to create the new order now or later.

**Comment by ibuiv** [comment]
Hi @AndreasSt-2022 
I think your idea is great. 
It would be a lot of changes in the native code to do that. So I developed a module and put it in the Dolistore : 
[My module](https://www.dolistore.com/fr/modules/1858-Franco-Et-Minimum-de-commande.html)

The amount of your replenish order refresh without load the page again.
Warning : does not manage orders on several pages

Info : I choose to sell it 12 € (10 € excl. Taxes) because I spent 4h to design it. It's just to justify my time for my partners ;)
