### ISSUE TITLE
Extrafields not fetch correctly in Porpousals.

### ISSUE THREAD

**Issue by nach41710** [Dolibarr/dolibarr#22364]
### Bug

Extrafield no working properly or not fetching in propousals.
I am using **volume** module from @ksar-ksar , where I calculate the units base on 2 extrafields
                if (isset($object->array_options['options_qty']) && isset($object->array_options['options_nbarras']) && isset($object->array_options['options_longitud']))
		{
			$new_qty = $object->array_options['options_qty'] * $object->array_options['options_longitud'] * $object->array_options['options_nbarras'];
			$object->qty = price2num($new_qty,'MU');
		}

nbarras and qty.
It is working for invoices but not for propousals.

I also create a odt where the extrafield appears in the invoices but not in the propousals.

Al this was working on version 15.

### Environment Version

16.0

**Comment by ksar-ksar** [comment]
Hi,

Most probably, linked to #22312

**Comment by nach41710** [comment]
@ksar-ksar 
Any idea when this will be fixed?
I tried the solution on  #22312 without success, it does not take the extrafield for the odt.
Neither fix the calculation of the quantity base on the extrafields, thanks for your help.
Thanks a lot.

**Comment by nach41710** [comment]
I tested again and solution on 22312 fix the issue with the odts and the extrafield, but it does not fix the issue with using the extra fields in the volume module. Any idea, thanks?

**Comment by opcoach** [comment]
Hi, 
I have the same problem with some extra fields in a new proposal odt document... 
This is very weird because I have two similar date extra fields (datedebut and datedefin) used in my odt document like this : 

**Dates** : du  {object_options_datedebut} au  {object_options_datedefin}

but it generates : 

**Dates** : du  12/05/2023 au  {object_options_datedefin} 

So the two fields are very similar but one is generated and the other not !  

I have also the same problem for other extra fields (the list is below)....   {object_options_stagiaires} is correctly replaced while {object_options_conditionsdefacturation} is not replaced... 

What could be the reason ? Having extra fields is a MUST have feature, but all of them should be replaced easily and directly...  

Here is my extra fields list definition for proposal (French custom...) : 

![image](https://github.com/Dolibarr/dolibarr/assets/1716878/57cfd1bd-e9ca-4809-adae-b88f6bd2e37a)

**Comment by ksar-ksar** [comment]
Hello
> **Dates** : du {object_options_datedebut} au {object_options_datedefin}
> 
> but it generates :
> 
> **Dates** : du 12/05/2023 au {object_options_datedefin}

Most probably you have hidden characters on `{object_options_datedefin}`

**Comment by opcoach** [comment]
Hi ksar-ksar ! 

I have already seen that with the '{' character that seems to be very sensible... 

I use to copy paste the name of my field from the web configuration page. Indeed when I write manually the end date field works now !!

That would be nice to have a warning message to explain this bug ! :). Because the field is well written (like the other one...)... and no extra character is visible in my odt template ... 

Thank you for your quick answer !

**Comment by ksar-ksar** [comment]
Hello,

Good if it was helping.

Warning is written there : https://wiki.dolibarr.org/index.php?title=Create_an_ODT_document_template
`
Warning, tags must be rounded with {} or [] for arrays (see later) and must be typed with no stop using Office suite (with no backspace and no copy-paste). If not doing that, Office suite adds some invisible information makes detection/replacement impossible. With LibreOffice you can also use the Ctrl+M to remove direct formatting from Tags `
But may be not visible enough

**Comment by opcoach** [comment]
I have read this document more than once, and I didn't see this warning.  

I styled the warning **in bold and red color** on the page...
