### ISSUE TITLE
admin.lang is a 'monster' - lets divided into more handy manageable files

### ISSUE THREAD

**Issue by dolibit-ut** [Dolibarr/dolibarr#22417]
### Feature Request

admin.lang  has become so extensive and in many cases you load so much terms with, that you don't need at all and sometimes this leads to conflicts because the terms are used in a different way. 

I think more domain-specific and handy files are better, e.g. 
- backups/database-handling, widgets, email   ...

**Comment by eldy** [comment]
Loading lang file time increase with the number of files. 
Having a very large admin.lang files should not be a trouble. If a key is used for 2 different meaning, splitting the file in 2 will not change anything. If we need 2 different meanings, it means we need 2 different keys for translation, not 2 different files. Where the keys are stored is not important.  I don't think having admin1 and admin2 file will enhance something: We will have to load the 2 files instead of 1 in admin setup page and it will not make things easier for a dev to search a key into a file.

**Comment by milenmk** [comment]
Maybe editing the file itself and splitting it into sections (with appropriate comments) can be of some help.
