### ISSUE TITLE
French string in english source code string to be translated 

### ISSUE THREAD

**Issue by dpriskorn** [Dolibarr/dolibarr#22432]
### Bug
See Transifex and search for the string below
![image](https://user-images.githubusercontent.com/68460690/192496094-f30d5a6e-3cbc-4b4a-b88e-5e621a32ab0a.png)

**Comment by ksar-ksar** [comment]
Hello,

Can you explain ?
I do not understand what you are saying

**Comment by dpriskorn** [comment]
I tried clarifying. The problem is that somewhere in the repo there is this french original string where it should be in English

**Comment by ksar-ksar** [comment]
Hello,

I have search for that string on V16 : 
```
langs/lo_LA/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/ms_MY/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/ta_IN/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/tg_TJ/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/uz_UZ/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/cy_GB/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/ur_PK/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/uk_UA/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
langs/kk_KZ/members.lang:209:AmountIsLowerToMinimumNotice=sur un dû total de %s
```

Doesn't exist for French or English or on the core PHP.
It has been deleted, except for the languages without update.

Still don't understand your issue.

**Comment by dpriskorn** [comment]
Oh, good. So why is it present still in transifex?

**Comment by ksar-ksar** [comment]
No Idea, but that's not a "bug".

**Comment by sonikf** [comment]
Hi @ksar-ksar 
What @dpriskorn means is that the English en_US source contains French strings instead of English and someone should translate them.
I've already fixed the easy ones, but the following need a native speaker perhaps...I've also tried with machine translation but it usually sucks!

langs/en_US/members.lang
AmountIsLowerToMinimumNotice=sur un dû total de %s


langs/en_US/intracommreport.lang


INTRACOMMREPORT_NUM_AGREMENT=Numéro d'agrément (délivré par le CISD de rattachement)
INTRACOMMREPORT_TYPE_ACTEUR=Type d'acteur
INTRACOMMREPORT_ROLE_ACTEUR=Rôle joué par l'acteur
INTRACOMMREPORT_NIV_OBLIGATION_INTRODUCTION=Niveau d'obligation sur les introductions
INTRACOMMREPORT_NIV_OBLIGATION_EXPEDITION=Niveau d'obligation sur les expéditions
INTRACOMMREPORT_CATEG_FRAISDEPORT=Catégorie de services de type "Frais de port"

INTRACOMMREPORT_NUM_DECLARATION=Numéro de déclarant
