### ISSUE TITLE
Error in the totals when duplicating the order or when creating an invoice from the order

### ISSUE THREAD

**Issue by cluza** [Dolibarr/dolibarr#22872]
### Bug

Error in the totals amount when duplicating the order or when creating an invoice from the order

### Environment Version

15.0.3

### Environment OS

Linux

### Environment Web server

nginx/1.20.1

### Environment PHP

7.3.31

### Environment Database

MySQL or MariaDB 5.5.5-10.3.31-MariaDB

### Environment URL(s)

https://domain/htdocs/compta/facture/card.php

### Expected and actual behavior

The total amount should be equal in the orden and facture

### Steps to reproduce the behavior

1. Create a product with price 0.695 inc taxes
![image](https://user-images.githubusercontent.com/60309439/202210043-30b6a1fe-11ae-40c9-bf19-ebc32fc8a81a.png)

2. Create a order and choose product and enter the quantity 45197

**The total amount is 31411,92**

![image](https://user-images.githubusercontent.com/60309439/202210859-c7356352-f511-41d4-89e4-c2e613636fd3.png)

3. Create a facture from the order. ehe tax base and total amounts are different
   **The total amount is 31411,75**

![image](https://user-images.githubusercontent.com/60309439/202211521-418ceb8a-db63-4b46-b850-35993f616ac8.png)

The same issue ocurrs to duplicate the order

### Attached files

![1_product_price](https://user-images.githubusercontent.com/60309439/202213824-c81afe1c-ba0b-4a1a-817a-418110d80005.png)
![facture](https://user-images.githubusercontent.com/60309439/202213838-dc694257-182b-4b37-b511-8d724e8990df.png)
![Order](https://user-images.githubusercontent.com/60309439/202213839-58531a10-582a-44c9-90c0-0c71b3d89abb.png)

**Comment by Delthair** [comment]
Hello, 

It seems to me that this is not a bug but it is due to at least 2 different factors : 

1. By using the tax included price base for your product your force Dolibarr to recalculate each time you insert a line the price from tax included to net of tax
2. Your level of precision in the Dolibarr's limit and precisions setting seems to be  5, 2, 8 

These 2 factors together makes it impossible to calcula
te the net price from the tax included price and then back without any problems. Moreover if you have changed your setting of precision in between calculation it will change the way Dolibarr calculates.

Please see the attached file to see the same line and the result with different settings of precision and the different results:

![Capture d’écran 2022-11-26 à 00 13 30](https://user-images.githubusercontent.com/41671350/204062775-01d35249-0ff3-467e-8e3e-812b98cc03be.png)
