### ISSUE TITLE
Extrafields on Expense Report detail lines

### ISSUE THREAD

**Issue by avolani** [Dolibarr/dolibarr#23641]
### Feature Request

I all,

the expense report module does not manage the extrafields on details lines.

I was able to use them with common object function by creating the table on db and add the missing 'table_element' on the class.

By the way actually I had to change the core card.php for show them (I found no way to replace list with hooks or tabs).

Will be good have this as part of standard core.

Thank you

### Suggested implementation

- Add missing table
- Add missing element name on object class `public $table_element = 'expensereport_det';`
- Add configuration page
- Manage fields on Expense report card.php (or have a way to replace the list with external hooks)

_No response_

**Comment by avolani** [comment]
I created a pull request for add element table name, this allow the use of extrafield logic without touch the dolibarr core.
I also managed to replace the card page with mine using a hook (tanks to the help on forum)

**Comment by ClementPourchayre** [comment]
Hello, I am currently on an internship in a company that uses Dolibarr. In order to make life easier for the administrative sector, I would like to add fields in the expense report after P.U TTC | Qty | Amount including VAT. I would therefore like to add (Mission City and Client). I have already found the table and added the fields but it is in the code in php or I do not know how to add its two fields. I managed to add the titles but it is at the level of the addition of the text zone that I block.
Can you help me ?
