### ISSUE TITLE
Release 16.0.4

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#23869]
### Bug

Hi @eldy 

For a plugin, I use the GitHub API to check new release. Will you create a new release for 16.0.4 or not ? Thanks.

**Comment by Daviid-P** [comment]
Weird question.

I assume v16.0.4 will be created if necessary, what's your problem to mark this as BUG?

**Comment by tuxgasy** [comment]
The label BUG is added automatically when I opened the issue and I can't remove it.

**Comment by Daviid-P** [comment]
> The label BUG is added automatically when I opened the issue and I can't remove it.

Well I don't know WHY you need v16.0.4 but you can probably close this and reopen as a feature request.

Although I still see it as pointless, when the devs thinks 16.0.4 is needed/ready they'll release it.

**Comment by Daviid-P** [comment]
If you're looking to get these fixes https://github.com/Dolibarr/dolibarr/issues/23569 with 16.0.4 I believe the code on the `develop` branch will only go to v17.0

**Comment by Daviid-P** [comment]
Sorry, I just noticed that v16.0.4 actually exists, it's just not on the "Releases" page.

@tuxgasy You might want to check if the Github API in your plugin can be changed to check https://github.com/Dolibarr/dolibarr/tags instead of https://github.com/Dolibarr/dolibarr/releases

I'm not sure what the difference is between a tag and a release but it might be enough for you to check tags instead of releases.

**Comment by tuxgasy** [comment]
Ok. I will try to check with tags. Thanks.
