### ISSUE TITLE
Not able to delete invoice

### ISSUE THREAD

**Issue by r9guy** [Dolibarr/dolibarr#23979]
### Bug

receiving the folowing errorthen deleting invoice.
`Cannot delete or update a parent row: a foreign key constraint fails (`replic14_erp`.`llx_paiement_facture`, CONSTRAINT `fk_paiement_facture_fk_facture` FOREIGN KEY (`fk_facture`) REFERENCES `llx_facture` (`rowid`)) sql=DELETE FROM llx_facture WHERE rowid = 16`

### Environment Version

16-17

### Environment OS

Linux

### Environment Web server

nix

### Environment PHP

8.0

### Environment Database

MySql

**Comment by atm-maxime** [comment]
The message indicates that the invoice deletion is not possible because a payment is attached to it. Can you confirm ?
Usually the delete button is not available when a payment is present on an invoice. If you have the delete button available, maybe you are using a hidden option named INVOICE_CAN_ALWAYS_BE_REMOVED. IMHO this is not a good practice.
