### ISSUE TITLE
Product List not appear in v17.0.1

### ISSUE THREAD

**Issue by jsairdrop** [Dolibarr/dolibarr#24442]
### Bug

After upgrading from version 16.0.4 to version 17.0.1 the product list in localhost no longer appears. Tested on Brave Browsers Version 1.49.132 Chromium: 111.0.5563.147 (Official Version) 64-bit, Microsoft Edge
Version 111.0.1661.62 (Official Build) (64-bit) and Firefox 111.0.1 (64-bit).
![bug product list1](https://user-images.githubusercontent.com/86256621/230100843-fb24165c-e974-4c6b-8fcb-7b34b6166f37.jpg)

### Environment Version

v 17.0.1

### Environment OS

Windows NT 10.0 build 22621 (Windows 11) AMD64

### Environment Web server

Laragon 6.0.0 LOCALHOST - Apache/2.4.54 (Win64) OpenSSL/1.1.1q 

### Environment PHP

PHP/8.1.10

### Environment Database

MySQL or MariaDB 8.0.30

### Environment URL(s)

/product/list.php?leftmenu=product&type=0

**Comment by ksar-ksar** [comment]
Hello,

Can't repoduce : 
![image](https://user-images.githubusercontent.com/35605507/230303134-53c75109-55c2-4fc4-b5d3-d5a07665542f.png)

White page = PHP error => Have a look on Apache log

**Comment by dagonix** [comment]
Hello,
Like Jsairdrop, We have the same issue here. Upgraded from 16.0.3 to 17.0.1 and have no more list of services.

`[Thu Apr 06 09:19:34.400365 2023] [php:error] [pid 44265] [client xx.xx.xx.xx49961] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'xxxxxx.llx_workstation_workstation' doesn't exist in /var/www/html/dolibarr/htdocs/core/db/mysqli.class.php:366\nStack trace:\n#0 /var/www/html/dolibarr/htdocs/core/db/mysqli.class.php(366): mysqli_result->fetch_object()\n#1 /var/www/html/dolibarr/htdocs/product/list.php(1361): DoliDBMysqli->fetch_object()\n#2 {main}\n  thrown in /var/www/html/dolibarr/htdocs/core/db/mysqli.class.php on line 366, referer: https://xxx.xxx.xxx/product/index.php?mainmenu=products&leftmenu=`


Obfuscated private data with xxx.

Seems a table is missing when upgrading from 16.0.3 to 17.0.1 of Dolibarr.

MariaDB :
Server version: 10.6.12-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04

PHP:
PHP 8.1.17 (cli) (built: Mar 16 2023 14:38:37) (NTS)

Thank you for your help.

**Comment by ksar-ksar** [comment]
Hello,

Workstation table is missing, workstation is an experimental module, try to deactivate it.

**Comment by dagonix** [comment]
Sorry but I cannot find the Workstation Module. Can you help me deactivate it ?

![image](https://user-images.githubusercontent.com/25879473/230418938-29392c62-2015-4751-993f-ab9b9a4037fc.png)

**Comment by frederic34** [comment]
try this : set MAIN_FEATURES_LEVEL => 2 to display module, activate module to create table

it's because https://github.com/Dolibarr/dolibarr/commit/20ddd04d14074b0847e2b0df84fc2c1d53a64b8b

**Comment by dagonix** [comment]
Thank you Frédéric, now I see it :

![image](https://user-images.githubusercontent.com/25879473/230613395-84866d44-a78b-439b-83bb-d2d2658a6a39.png)

Ufortunately, it is already deactivated so the original problem still remains : we cannot see the services list and the apache log still show the same error too : 

`[Fri Apr 07 15:05:36.567018 2023] [php:error] [pid 50105] [client xx.xx.xx.xx:51627] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'xxx..llx_workstation_workstation' doesn't exist in /var/www/html/dolibarr/htdocs/core/db/mysqli.class.php:366\nStack trace:\n#0 /var/www/html/dolibarr/htdocs/core/db/mysqli.class.php(366): mysqli_result->fetch_object()\n#1 /var/www/html/dolibarr/htdocs/product/list.php(1361): DoliDBMysqli->fetch_object()\n#2 {main}\n  thrown in /var/www/html/dolibarr/htdocs/core/db/mysqli.class.php on line 366, referer: https://xxx.xxx.xxx/product/index.php?mainmenu=products&leftmenu=`

When I do "show tables;" in my MariaDB server, the table xxx..llx_workstation_workstation really does not exist.

[EDIT]
I activated the Workstation module and the services list now shows the services.
I deactivated then the Workstation module and the services list still appears.

→ I consider that the problem is now solved

[END EDIT]

Thanks for your help.

**Comment by Sutefan974** [comment]
> try this : set MAIN_FEATURES_LEVEL => 2 to display module, activate module to create table
> 
> it's because [20ddd04](https://github.com/Dolibarr/dolibarr/commit/20ddd04d14074b0847e2b0df84fc2c1d53a64b8b)

Thanks :) Merci Frédéric çà a fonctionné pour moi !

**Comment by jsairdrop** [comment]
Thanks for all.
The solution for me it's same I activated the Workstation module and the services list now shows the services.
I activated then the Workstation module and the services list still appears.
→ I consider that the problem is now solved

**Comment by ksar-ksar** [comment]
Thanks for your update, but I think this is a bug that need to be corrected.
