### ISSUE TITLE
Tax handling inconsistent 

### ISSUE THREAD

**Issue by Basti-Fantasti** [Dolibarr/dolibarr#24554]
### Bug

I have set default prices for products.
The default prices are set with a default German tax of 19%

When adding these products to a quotation to a foreign customer who has no tax added in the settings, the tax rate from the default price is used instead of the customers tax preset.

So instead of 0% the 19% are set.

On the other hand when a default price is set without tax (0%) this value is always added instead of the customers preset of 19% when it's a customer with applied tax.

This issue only came up in Version 17.0 (maybe also 16.x)

### Environment Version

17.0.x

### Environment OS

ubuntu

### Environment Web server

Apache2

### Environment PHP

7.4

### Environment Database

mysql

### Expected and actual behavior

Customers presets regarding taxes settings should be applied.

### Steps to reproduce the behavior

see bug description above

**Comment by AurelienBISOTTI** [comment]
Same in v18


edit : the "no tax" field means "this company does not add tax to its own customers"
So I am not sure this should mean "do not apply tax when selling to this customer"

Maybe this should be discussed on the forum because it might not be a bug

![Capture d’écran du 2023-06-10 11-10-24](https://github.com/Dolibarr/dolibarr/assets/12530585/877dc9e2-cd4a-4a10-9b4a-29193d9a5fc1)
![Capture d’écran du 2023-06-10 11-12-22](https://github.com/Dolibarr/dolibarr/assets/12530585/2fc402fe-9b7d-4aa7-95ae-c0f116d9522f)
![Capture d’écran du 2023-06-10 11-14-25](https://github.com/Dolibarr/dolibarr/assets/12530585/bc8c0b2c-5a2d-4625-9cda-1dd418300eac)
