### ISSUE TITLE
(BLOCKER) Dolibarr breaks after upgrading from PHP 8.0.x to 8.0.29

### ISSUE THREAD

**Issue by bos4711** [Dolibarr/dolibarr#25117]
### Bug

See [this Dolibarr forum post](https://www.dolibarr.org/forum/t/upgrade-from-v16-to-v17-broke-things/23874) for the details.

In short: what breaks in PHP 8.0.29 is the transitions from Sales Orders / Proposals to Shipment / Invoice; basically all the info and lines in the Order/Proposal is wiped out and everything has to be reentered. With PHP error messages set to One, we found that we get some useful debug info when creating a shipment and that Expedition::loadExpeditions() is nonexistant. The code itself is not the problem I think because it worked fine prior 8.0.29, but something in this version make all interim variables lose their values.

### Environment Version

Any, tested and confirmed with 16.0.3 and 17.0.2

### Environment OS

Linux build-systems-focal 5.4.0-149-generic #166-Ubuntu SMP Tue Apr 18 16:51:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux 

### Environment Web server

Apache

### Environment PHP

8.0.29

### Environment Database

mySql / MariaDB 10.3

### Attached files

![Untitled](https://github.com/Dolibarr/dolibarr/assets/11036018/6541f194-2dfc-4c4c-8e69-8d20cd2d5665)

**Comment by bos4711** [comment]
Two weeks later and Dolibarr is still completely unusable due to this bug.

**Comment by eldy** [comment]
loadExpeditions method does not exists on Expedition object because such method is (should) never called by standard code of Dolibarr.
Did you enabled an external module ?
You may get more information by installing the php addon php-xdebug.
On my side, I can't reproduce even when using same version of Dolibarr and PHP.

**Comment by bos4711** [comment]
Only native Dolibarr-modules are used, so no error there.

Another user reported (in the mentioned thread) that when they switched hosting provider it works fine in 8.0.29, so obviously our provider (One.com) added some setting when they upgraded to 8.0.29 that made the code break completely. Unfortunately they did not tell us what, and as users we are not allowed to install php addons ourselves. This means we will have a very hard time tracking down this bug, and whatever is causing it. The thing is that Dolibarr works completely fine, _until_ you need to go from Proposal/Order to Invoice/Shipping. That's the only case where it breaks down completely.

@eldy If you'd like, drop me a PM and I can give you access to the site where the error occurs and you can try yourself. It is plain 17.0.2-code from Sourceforde and no 3rd party modules at all. It *should* work, but does not.

**Comment by eldy** [comment]
Don't think github can be used for private message. At least i don't know how.
Nevermind, you can send me credential to my public email eldy@destailleur.fr

**Comment by eldy** [comment]
I have a clue after test on your environment:

Go on this page
`.../admin/system/phpinfo.php?mainmenu=home&leftmenu=admintools&origin=aaa&abc=def&originid=123`

You will see when reading the entry
$_SERVER['QUERY_STRING']
that parameters string is
`mainmenu=home&leftmenu=admintools&abc=def`
when it should be
`mainmenu=home&leftmenu=admintools&origin=aaa&abc=def&originid=123`

Inside the entry $_SERVER['HTTP_X_ORIGINAL_URL'] we have the correct full parameter string:
`mainmenu=home&leftmenu=admintools&origin=aaa&abc=def&originid=123`

It seems there is a layer before the web server that filter and remove some parameters like "origin" and "originid". May be other parameters are removed too with no reason (May be a bad setup of Varnish).
You must ask you web hosting provider why they remove some parameters provided as GET parameters.
This is the root cause of your trouble.

**Comment by bos4711** [comment]
Web hoster has now resolved the issue: they did indeed have some sort of filter that stripped all query variables containing anything with "origin", so everything is now working again. Neither PHP or Dolibarr was the culprit.

Thank you @eldy for taking the time and digging into this issue and finding the root cause.
