### ISSUE TITLE
Premission to publish "Dolibarr" app in Umbrel App store

### ISSUE THREAD

**Issue by IMPranshu** [Dolibarr/dolibarr#25251]
### Feature Request

Hi team,

I need your team's permission to try and host this app on the Umbrel App Store. I have given appropriate credits and mentions to your team as you are the sole Developer of the App I am just publishing it to the Umbrel App Store for free as I have done with a lot of other OSS applications.

It would be great to have a go-ahead from your team as I have already created a PR https://github.com/getumbrel/umbrel-apps/pull/286 for this but it has been closed as I was not the developer of this application

Thanks,
Pranshu

**Comment by priojk** [comment]
Hi @IMPranshu, 

first of all thanks for your efforts to spread the word about Dolibarr.

Dolibarr is licensed under the GPL v3, as shown on the project page. As long as you follow the requirements from this license, it should be no problem to publish Dolibarr in an App Store. However, as I am just a community member like so many others here, I am not in a position to provide you with an "official" answer. I am also not sure, if anyone can provide you with more info than referencing the applicable license.

But let me make one addition: Since Dolibarr is really easy to install and the process is well documented in Dolibarr's Wiki, I am not sure if providing an additional app package is doing more good than harm. There are many examples, where pre-packaged versions of Dolibarr create trouble in the future, when users need to upgrade them to a later version. A clean upgrade path is required for the serious use of any ERP system and one of the strengths of Dolibarr. So please consider how upgrades shall be performed, if you create an installation package. Also consider, if you want to take care of the maintenance, i.e. to publish it not just once but to keep it current with the latest releases.
