### ISSUE TITLE
Import material line

### ISSUE THREAD

**Issue by BanMePlox** [Dolibarr/dolibarr#25353]
### Bug

When you are importing BOM lines, it works wonders. But, when you're creating the MO, it doesn't detect correctly some of the IDs. I've found that most of the times the error is where the reference is number-based, if it has some text, it works fine.
![image](https://github.com/Dolibarr/dolibarr/assets/15201580/742ef6ac-75ef-4ecb-b2dc-b166cdb66825)
****
![image](https://github.com/Dolibarr/dolibarr/assets/15201580/21647df2-8e4e-4515-8772-30fe00c96084)

### Environment Version

17.0.2

### Environment OS

Linux

### Environment Web server

Linux

### Environment PHP

7.4.33

### Environment Database

MySQLI

### Expected and actual behavior

It should be able to create the MO, but it is not.

**Comment by eldy** [comment]
It seems you have imported lines in BOM that are linked to products that does not exists.
So lines in the screenshot are empty
And creation of MO fails due to a constraint that need an existing product.
When you import lines of product, if product ref is a string, dolibarr knows it is not the id so search the id to use it in import. If it is a numeric, it think it is an id, and use value as it as id but it is not an id. To fix this, in your import file, in the column "Product ref",instead of having value 12345, use the value "ref:12345". So dolibarr will know it is a ref even if it is a numeric. Import of BOM lines for such case was done wrongly.

**Comment by BanMePlox** [comment]
Oooooooooh, that makes sense. Thanks!
