### ISSUE TITLE
improvement of public/eventorganization/

### ISSUE THREAD

**Issue by c-orazio** [Dolibarr/dolibarr#25493]
### Feature Request

This module is working very well and allow online payment for event but the public online for should be improve :
1/ we should be able to set the devise when multidevise module is set ($, £, €, ...) 
2/ the registration form should ask for first name and last name as these  field exist in dolibarr
3/ we should have a tickbox to be compliant with RGPD
4/ we  should ne able to add optional services  tiking a box : +30€ to attend to the dinner, +50€ to attend to the filed trip, ...
Thanking you for good job achieve so far.

**Comment by JonBendtsen** [comment]
Hey. I think I do something similar, since I use Dolibarr for dance class and workshop registrations.

I simply made my own python flask app that presents a form and then I use the API to feed registrations into Dolibarr.

Inside Dolibarr I have Sales Orders, which admin and teachers will Validate the sales order for those registrants they deem have the skill set to do the level they register for.

It was my plan that as soon as I validated the Sales Order the registrant would get an email about paying and such, and then once paying I would send an invoice.

HOWEVER. Even though I have the notification module installed, turned on, configured and have created an email template, my registrants are NOT getting any automatic emails unless I do 2 things:

1. Add a contact to every thirdparty, even though the thirdparty has an email defined (this I automated using the API)
2. I manually go into the Notifications tab of each and every thirdparty, for each kind of notification trigger I want I have to select the above Contact and the specific trigger. Not ideal, but this so far works for me because our old registration system was horrible. And also, many many of my Thirdparties are recurring students, so once I have setup the Notification for a thirdparty, then it should work in the future.


I actually think that you want to separate the form system and then backend inside Dolibarr, such that I would encourage you to code your own form system out side Dolibarr. Even if you do it in PHP, do it outside Dolibarr. Why? Because of Security and Flexibility.

Security:
1. you can actually run it in a separate container, even on a separate host.
2. you can even go further and create an air gap between your form and Dolibarr, such that your form system stores all registrations in a local database, a local file, or perhaps even a local git repo. Then you have "Dolibarr" regularly pull those data in behind a firewall.
3. Complication with 2. is that what when you need paying? That's going to be slightly complicated because if you send a dolibarr link to paying on dolibarr, this should still of course work.

Flexibility:
1. You can have exactly the setup and form system you like.
2. You can improve your form completely independent of Dolibarr.
3. You can have different kind of form systems depending on what kind of event you have.
4. You can have multiple form systems and do A/B testing to see which one works better.
5. If you have a high peak volume registration, your Dolibarr installation can still work while your form system is getting hammered.
6. Your Dolibarr system could still work even if some hacker is penetrating and compromising your form system
7. Your dolibarr system could survive a DDoS on your form system.


So while I would love for Dolibarr to get better event organisation, I would wish that Dolibarr developers focus on the backend side of event organisation.


ps: once I have tested my own form system I'll probably open source it because Dolibarr is also open source, but given that I literally just opened the public registration about 24 hours ago, then I want to get some real life experience before doing so.

**Comment by JonBendtsen** [comment]
I've continued to work on my form system, currently mostly making it more resilient based on using it to register for an event.

I also ordered a bar code scanner and want to make some easy system such that the checkin process works just my scanning a QR or bar code. Such a system could also be coupled with a label printer that would create their proof of entry, and based on their order this could include various kinds of tickets for different services, parties, VIP, ...
