### ISSUE TITLE
Bug: not possible to export CSV or XLS on v18.0.0

### ISSUE THREAD

**Issue by leguennecj** [Dolibarr/dolibarr#25654]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
On step 5 for export no button or choice for export data (no CSV no XLS)

## Environment
- **Version**: 18.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: litespeed 7.4.33
- **Database**: MySQL or MariaDB 5.5.5-10.6.15-MariaDB
- **URL(s)**: /modulebuilder/index.php?mainmenu=home&leftmenu=admintools

## Expected and actual behavior
[*Verbose description*]

## Steps to reproduce the behavior
Try export

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by dolibit-ut** [comment]
Yes - i have checked this and can confirm it.

At the last step (5) the button to execute is missing.

**Comment by leguennecj** [comment]
Do you know if an update will quickly fix the problem?

**Comment by dolibit-ut** [comment]
No i dont know - but i hope.

@eldy can you please check this

**Comment by CKSpringbok** [comment]
I also have the same problem since updating to v 18.0.0. It seems there's a problem declaring the ExportCsv class during exports. A quick solution might be to rename that class in the export-module (with sed) and retry, but I haven't tried that so far. 

AH01071: Got error 'PHP message: PHP Fatal error:  Cannot declare class ExportCsv, because the name is already in use in /var/../htdocs/core/modules/export/exportcsv.modules.php on line 32', referer: https://example.com/exports/export.php?step=4&action=submitFormField&datatoexport=facture_1

**Comment by ksar-ksar** [comment]
Hello,

It's working for me.

In V18, the file htdocs/core/modules/export/exports_csv.modules.php has been renamed to htdocs/core/modules/export/exportscsv.modules.php

Do you have both files or only one?

**Comment by CKSpringbok** [comment]
Yes, I had both and thanks for the answer.

After moving htdocs/core/modules/export/exports_csv.modules.php from the directory to tmp the problem doesn't exist anymore. It was caused by upgrading by copying the new files over the old ones (and folders). 

Many thanks.

**Comment by ksar-ksar** [comment]
Thanks for the notification !

It's @frederic34 that point out this change

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/25741
