### ISSUE TITLE
Can't decrypt encrypted data if instance_unique_id is not defined

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#25860]
### Bug

[dolEncrypt](https://github.com/Dolibarr/dolibarr/blob/9c903ecf56d3650bcacce4b47eb0e4e26f8f3a1b/htdocs/core/lib/security.lib.php#L122C10-L122C20) function allows to encrypt data even if instance_unique_id is not defined.

But [dolDecrypt](https://github.com/Dolibarr/dolibarr/blob/9c903ecf56d3650bcacce4b47eb0e4e26f8f3a1b/htdocs/core/lib/security.lib.php#L177) function fails if it is empty.

https://github.com/Dolibarr/dolibarr/blob/9c903ecf56d3650bcacce4b47eb0e4e26f8f3a1b/htdocs/core/lib/security.lib.php#L193C4-L195

I'm not sure what is the best solution: allow to decrypt data even or not allow to encrypt data if instance_unique_id is empty.

### Environment Version

18

**Comment by Daviid-P** [comment]
I would say "not allow to encrypt data if instance_unique_id is empty"
If there's not instance_unique_id (used as key) then:
- The key is empty which means encryption is "useless" <strike>(if it even works with empty string as key)</strike>
- The key is generated on the spot and presumably saved somewhere, at this point, why not just generate a instance_unique_id 

Edit:
dolEncrypt has no check after assigning instance_unique_id to `$key` and the [docs for openssl_encrypt](https://www.php.net/manual/en/function.openssl-encrypt.php#:~:text=The%20passphrase.%20If%20the%20passphrase%20is%20shorter%20than%20expected%2C%20it%20is%20silently%20padded%20with%20NUL%20characters%3B%20if%20the%20passphrase%20is%20longer%20than%20expected%2C%20it%20is%20silently%20truncated.) say that the key will get automatically padded with NULL characters. I'd say it's still better to not allow this, since dolDecrypt has a check aganst this, then dolEncrypt should too.

**Comment by tuxgasy** [comment]
I agree to not allow to encrypt data if unique_id is empty. But we have to show an alert to the admin user if it's empty.
@eldy What do you think ?

I started using Dolibarr since version 3.6. So in my config file, I don't have this parameter.

**Comment by hregis** [comment]
@tuxgasy Why don't you have a unique_id in conf.php? This shouldn't happen since it is created during installation!

**Comment by tuxgasy** [comment]
It is created for a new installation since Dolibarr 10 but not for old installation.

I checked the changelog, this config was [introduced since the version 10](https://github.com/Dolibarr/dolibarr/blob/da699ce3cda437c949c69807403118fa922b08f3/ChangeLog#L4123) but [sensitive parameters are automatically encrypted since 18](https://github.com/Dolibarr/dolibarr/blob/da699ce3cda437c949c69807403118fa922b08f3/ChangeLog#L267-L271).

**Comment by hregis** [comment]
@tuxgasy before you had to see a $dolibarr_main_cookie_cryptkey key, you can rename the variable to $dolibarr_main_instance_unique_id or add a variable $dolibarr_main_instance_unique_id with a random value of your choice!
