### ISSUE TITLE
Membership form should have language options

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr#25925]
### Feature Request

Currently the public membership form is in the same language as Dolibarr, and it would be nice if one could change the language to something else in the setup of the membership module - or even better that the public user could self select which language they want to see the membership form in.

### Use case

Those administrating dolibarr are probably locals, but members might not all be locals, so language can be different.

### Suggested implementation

That visitors to the membership form can self select the language, secondary that the configuration of the membership module can select a different language than the one which dolibarr uses.

**Comment by Pete-iMergencies** [comment]
Thats True what JonBendtsen wrote:
That visitors to the membership form can self select the language, secondary that the configuration of the membership module can select a different language than the one which dolibarr uses.

We just activated the selfsubscription form , because we got members from 94 differnet Nations and its really a pitty, that this feature is not available.
We would like to go away from paper-work with members.
