### ISSUE TITLE
Bug: "Create Invoice" available when Invoices module is not enabled

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2599]
Version: 3.7 at 1272b03e5e090afe54c7f45ea521d4f66e1771fe

Page: /fourn/commande/card.php

![captura de pantalla 2015-04-12 a las 22 51 56](https://cloud.githubusercontent.com/assets/168744/7107463/8a07096e-e166-11e4-87fc-801cd523bd58.png)

**Comment by eldy** [comment]
The name of invoice module is not correct. It should be "Customer invoice".
The button is for "Supplier invoice". And supplier invoice module is managed by module "Supplier". So behavior is correct for me. Here the problem is that the module Supplier is not split into 2 modules (supplier orders and supplier invoices).

**Comment by marcosgdf** [comment]
If Invoices module is not enabled, there is no way on earth I can access Supplier Invoices. So I guess the expected behavior is for the button to not be enabled.

**Comment by atm-maxime** [comment]
This is a menu issue. If only the supplier module is activated, the commercial and financial top menus should appear. It's not the case for the financial menu.

**Comment by rdoursenaud** [comment]
Not a bug.
The button creates a supplier invoice.
Supplier invoices are part of the same supplier module as supplier orders so they are available at the same time.

I don't have any menu issue either on a fresh 3.7 install: commercial and financial are both shown correctly.

Can we close the issue @marcosgdf?

**Comment by marcosgdf** [comment]
It seems to have been silently fixed.
