### ISSUE TITLE
Closed job positions still available for a new application

### ISSUE THREAD

**Issue by leonbrehme** [Dolibarr/dolibarr#26009]
### Bug

When you create a new job application, closed (canceld & recruited) job positions are still available to select.

### Environment Version

18.0.1

### Expected and actual behavior

Expected: show only the opened job positions

### Attached files

![Screenshot 2023-09-23 13 26 34](https://github.com/Dolibarr/dolibarr/assets/115941074/75e679b0-4896-47d5-9c90-d5e98e95a147)

![Screenshot 2023-09-23 13 26 49](https://github.com/Dolibarr/dolibarr/assets/115941074/2abfa10c-c03f-49c1-8611-23c20f2eb697)

**Comment by atm-thibaultf** [comment]
This modification should have been introduced only for creation of new application or with a configuration because with the fix https://github.com/Dolibarr/dolibarr/commit/64f54a4e5ae6a664535d59f7c198097af1ce8004 when you edit an application with a disabled job position, the field for the job is empty because not shown anymore in the select field. If you save, the old desactivated job is not saved.

To reproduce :
- Create a new application and add a job to it
- Desactivated the job
- Edit the application, the field of job associated is empty
- Save the application, you lost the desactivated job

@Hystepik could you fix this in v19 or v20 ?

**Comment by atm-thibaultf** [comment]
This modification should have been introduced only for creation of new application or with a configuration because with the fix https://github.com/Dolibarr/dolibarr/commit/64f54a4e5ae6a664535d59f7c198097af1ce8004 when you edit an application with a disabled job position, the field for the job is empty because not shown anymore in the select field. If you save, the old desactivated job is not saved.

To reproduce :
- Create a new application and add a job to it
- Desactivated the job
- Edit the application, the field of job associated is empty
- Save the application, the desactivated job is not saved

@Hystepik could you fix this in v19 or v20 ?
