### ISSUE TITLE
Email-Collector depends on an activated Recruitment module

### ISSUE THREAD

**Issue by thomasmeigen** [Dolibarr/dolibarr#26015]
### Bug

When testing the Email-Collector to fetch ticket related emails, we faced a problem:

Behavior: When the Recruitment module was **deactivated**

- Clicking the "Test collect" or "Collect now" buttons in one of our collectors led to a blank screen.
- The dolibarr.log showed an error message indicating that no table "llx_recruitment_recruitmentcandidature" could be found in the database
- When the  Recruitment module was **activated**, the "Test collect" and "Collect now" procedures worked fine and processed the incoming emails as expected

### Environment Version

17.0

### Environment OS

Ubuntu

**Comment by YesPoX** [comment]
Looks like this issue is still happening in 22.0.1
I am not a developer, so my analysis is only done by using AI. 


### Issue 1: Module/Table Existence (What we just discussed)

- Problem__: `recordjoinpiece` tries to query tables for disabled modules
- Symptoms__: SQL errors like "table doesn't exist" for recruitment, bom, mrp, etc.
- Solution__: Add `isModEnabled()` checks before querying each module's tables

### Issue 2: User Permission Check (Your current error)

- __Problem__: The restrictive user validation in `recordjoinpiece`
- __Code__:

```php
$sql = "SELECT rowid as id FROM ".MAIN_DB_PREFIX."user WHERE email LIKE '%".$this->db->escape($from)."%'";
$resql = $this->db->query($sql);
if ($this->db->num_rows($resql) == 0) {
    $this->errors[] = "User Not allowed to add documents ({$from})";
}
```

- __Symptoms__: "User Not allowed to add documents (h.user@ecompany.fi)"

## Why It Uses the Sender's Email:

The `recordjoinpiece` function uses `$from` (the sender's email) because that's how the email parsing works:

1. __Email is received__ from `h.user@ecompany.fi` to `m.user@pcompany.fi`
2. __Email collector processes__ the email and extracts `$from = 'h.user@ecompany.fi'`
3. __recordjoinpiece operation__ tries to validate if the sender is allowed to save documents
4. __Permission check fails__ because `h.user@ecompany.fi` is not a Dolibarr user

## The Logic Problem:

The current logic assumes that only __internal Dolibarr users__ should be able to save attachments via email, but this doesn't make sense for:

- __Customer emails__ with attachments
- __Supplier emails__ with documents
- __External partner communications__

If this is feature, not a problem, then it should be stated more clearly, like save "Save only dolibarr users attachements" 



## My Planned Changes:

### 1. Remove User Permission Check:

```php
// REMOVE these lines entirely:
// $sql = "SELECT rowid as id FROM ".MAIN_DB_PREFIX."user WHERE email LIKE '%".$this->db->escape($from)."%'";
// $resql = $this->db->query($sql);
// if ($this->db->num_rows($resql) == 0) {
//     $this->errors[] = "User Not allowed to add documents ({$from})";
// }
```
There is still security in Object Matching Logic, but that logic is not quite robust. Atleast for me headers and messages are messed. I use gmail.
// Option 1: File type whitelist
$allowedExtensions = array('pdf', 'doc', 'docx', 'txt', 'jpg', 'png', 'zip');
$fileExtension = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
if (!in_array($fileExtension, $allowedExtensions)) {
    $this->errors[] = "File type not allowed: " . $fileExtension;
    continue;
}

// Option 2: File size limit
if (strlen($content) > getDolGlobalInt('EMAILCOLLECTOR_MAX_FILE_SIZE', 10485760)) { // 10MB default
    $this->errors[] = "File too large: " . $filename;
    continue;
}

// Option 3: Known sender validation (less restrictive)




### 2. Replace Static Array with Module-Conditional Logic:

```php
$arrayobject = array();

// Only add objects if their modules are enabled
if (isModEnabled('propal')) {
    $arrayobject['propale'] = array('table' => 'propal', 'fields' => array('ref'), 'class' => 'comm/propal/class/propal.class.php', 'object' => 'Propal');
}
if (isModEnabled('holiday')) {
    $arrayobject['holiday'] = array('table' => 'holiday', 'fields' => array('ref'), 'class' => 'holiday/class/holiday.class.php', 'object' => 'Holiday');
}
if (isModEnabled('expensereport')) {
    $arrayobject['expensereport'] = array('table' => 'expensereport', 'fields' => array('ref'), 'class' => 'expensereport/class/expensereport.class.php', 'object' => 'ExpenseReport');
}
if (isModEnabled('recruitment')) {
    $arrayobject['recruitment/recruitmentjobposition'] = array('table' => 'recruitment_recruitmentjobposition', 'fields' => array('ref'), 'class' => 'recruitment/class/recruitmentjobposition.class.php', 'object' => 'RecruitmentJobPosition');
    $arrayobject['recruitment/recruitmentcandidature'] = array('table' => 'recruitment_recruitmentcandidature', 'fields' => array('ref'), 'class' => 'recruitment/class/recruitmentcandidature.class.php', 'object' => 'RecruitmentCandidature');
}
// ... continue for all modules with proper checks
if (isModEnabled('knowledgemanagement')) {
    $arrayobject['knowledgemanagement'] = array('table' => 'knowledgemanagement_knowledgerecord', 'fields' => array('ref'), 'class' => 'knowledgemanagement/class/knowledgemanagement.class.php', 'object' => 'KnowledgeRecord');
}
if (isModEnabled('bom')) {
    $arrayobject['bom'] = array('table' => 'bom_bom', 'fields' => array('ref'), 'class' => 'bom/class/bom.class.php', 'object' => 'BOM');
}
if (isModEnabled('mrp')) {
    $arrayobject['mrp'] = array('table' => 'mrp_mo', 'fields' => array('ref'), 'class' => 'mrp/class/mo.class.php', 'object' => 'Mo');
}
```
