### ISSUE TITLE
Feature request - Convert only paid amount into available credit on deposit invoice

### ISSUE THREAD

**Issue by AshleyButcher** [Dolibarr/dolibarr#26027]
### Feature Request

When working with a vendor deposit invoice (i.e. a proforma from a supplier to prepay), it should be possible to convert only the amount actually paid into available credit rather than the full amount of the deposit invoice.

### Use case

A common scenario is where prepayment is required of a minimum amount when ordering JIT manufactured items. For example, a proforma is issued by the supplier for the full amount of an order with 50-50 payment terms, and the supplier asks for at least 50% to be paid up front as a deposit (prepayment) ahead of manufacturing.

The supplier may grant a discount is more is prepaid, i.e. receive a discount if you pay 75% instead of 50%.

It is desirable to book the entire proforma ("deposit invoice") for tracabality, so it can be shown accurately what was on the proforma invoice and what was paid. In this scenario, less than 100% will be paid, however when converting the deposit invoice into credit available Dolibarr will take the total amount of the deposit invoice and not consider the paid amount.

### Suggested implementation

When a user clicks the button to convert a deposit invoice to available credit, the user should be prompted if they want the paid total amount or the invoice total amount to be converted to available credit for the vendor.

**Comment by atm-maxime** [comment]
The issue is that for many companies the deposit invoice contains vat and is accounted in the turnover. If you convert only the amount paid, then on the final invoice the amount remaining to pay will be too high.
I.e. :
Order of 1000
Deposit of 500 paid 400
Final invoice of 600 (1000 - 400)

So in this example, I have done 1100 of invoicing for an order of 1000.

So we should do a credit note to lower the deposit invoice amount, in this example of 100 to have the correct deposit regarding the payment. Then with the credit note applied to the deposit, we should be able to convert only the real paid amount.

**Comment by AshleyButcher** [comment]
@atm-maxime We have this scenario too, but we also have the scenario described in the feature request. The problem with the credit note solution is that I am told it will not pass audit as no evidence is available for this document. It would be no problem if the feature was disabled by default and possible to be made available through configuration.
