### ISSUE TITLE
Production Module Calculation Issue: Programming Error or Misunderstanding?

### ISSUE THREAD

**Issue by sara30789** [Dolibarr/dolibarr#26343]
Hello All

I'd like to discuss an issue I can't seem to understand in the manufacturing module.

Is this a programming error or a misunderstanding on my part?

After creating the bill of materials, I create a new manufacturing order, assuming I want to produce 1000 units of the product.

According to the bill of materials, the system calculates the production requirements for these 1000 units.

Then, we get to the production stage.

At this point, the system offers me two options:

CONSUME AND PRODUCE ALL: When I choose this option, the consumption process for the 1000 units is completed, consumptions are calculated, and stock movements are adjusted accurately.

CONSUME OR PRODUCE: To my understanding, this is partial production (meaning I don't produce the 1000 units completely, but I can choose to produce, for example, 500 units).

Here, I have to manually enter consumption quantities. Why doesn't the system automatically calculate consumption when I input the quantity I want to produce based on the associated bill of materials?

Furthermore, in this option, if I have more material in stock than what is actually required for production, the system accepts the higher quantity and deducts it. Where is the logic in this?

If I only need 1000 units and, for instance, I have 2000 of a certain material in stock, the system should reject this, but it doesn't.

Similarly, if I require 1000 units only and I enter 2000 in the CONSUME OR PRODUCE field, the system still accepts this quantity, even though the manufacturing order is for 1000 units only.

Is this a system bug or a misunderstanding on my part of the production process?

**Comment by sara30789** [comment]
@eldy

**Comment by eldy** [comment]
This is not a bug.
It is often not possible to decide the qty to consume when you produce.
For example to build 1000 P you need 25 A and 1 B, what do you consume for 500 ?
Also in some cases, a partial production does not mean we consule all. Some users also orefer to consule all at the end, when producing the last qty.
Only user can know. For this reason on manual partial production, user must enter manually values to consume.

A feature may je added "autofill consumption in prorata of production", but such a button does not exists yet.

**Comment by AshleyButcher** [comment]
@sara30789 This is definitely normal! @eldy already gives a good scenario where counting your consumed quantities only occurs at the end of production rather than per unit produced. It's certainly true that in some production you have a directly 1:1 on your BOM and the output, such as a scenario where you have a gift box with three items in it, and it's always those three items and an outer box which makes up the item. This seems to be what you are thinking of.

However some items are produced using variable quantities. Dolibarr doesn't use stock quantity units (yet) so you can't have stock listed in metres, litres, or kilos, so you may not have thought of this. Imagine a production of drinks, where you mix five liquids. What happens if you spill some? What happens if you use a little more of one liquid than usual? In food science especially, you often have to vary the quantities depending on the quality or potency of the ingredients at the time, which can vary from yield to yield, season to season. It's complex.

Now I doubt many people are using Dolibarr at this level, but take a simpler example: You make dolls out of fabric, cotton string and stuffing. You know you usually need a certain amount of fabric off a roll, but as you cut your shapes out of the fabric you may need more or less depending on how well you can fit the shapes from the fabric. It's an uncertainty that needs to be accounted for.

I've worked on a number of very large ERP systems for multinationals for decades and Dolibarr's implementation of production is very simplistic in comparison, but that's a okay. Dolibarr doesn't account for other types of consumption such as waste, yield, quality, and other parameters (yet), which really only interest larger companies who are analysing their production metrics heavily, but the use cases for the production module are quite broad and varied.

Maybe this is a topic better suited as an improvement for Dolibarr documentation.
