### ISSUE TITLE
Income/Expenses report doesn't take into account Miscellaneous Payments

### ISSUE THREAD

**Issue by xabitrigo** [Dolibarr/dolibarr#26367]
### Bug

When our company gets a subsidy or has to pay some non-common tax we use "Miscellaneous payments" to save it in Dolibarr.

If we go to see the Income/Expenses report or we go to the "Balance of income and expenses, By predefined groups" for a year or a month, those payments are not taken into account.

I'm not sure if this is a bug, but it's definetely unexpected behaviour

### Environment Version

18.0.2

### Environment OS

CloudLinux 7.x Linux hl109.*****.org 3.10.0-962.3.2.lve1.5.77.el7.x86_64 #1 SMP Mon Dec 12 07:06:14 EST 2022 x86_64

### Environment Web server

LiteSpeed

### Environment PHP

8.1.13

### Environment Database

MySQL or MariaDB 10.6.11-MariaDB-cll-lve

### Environment URL(s)

/compta/resultat/index.php, /compta/resultat/clientfourn.php?year=2023&month=10&modecompta=CREANCES-DETTES

### Expected and actual behavior

- /compta/resultat/index.php 
    Should add the miscellaneous payments in the month they are assigned
- /compta/resultat/clientfourn.php?year=2023&month=10&modecompta=CREANCES-DETTES
    Should show a section with the miscellaneous payments
    
At least in the "Analysis of known recorded payments" calculation mode, probably better in both calculation modes.

Currently I only see those payments in the Bank account

### Steps to reproduce the behavior

Add a miscellaneous payment and check the Income/Expenses report

**Comment by burksbuilds** [comment]
Are you using double accounting module? This comment assumes you are.

What accounting account is your 'miscellaneous payment' associated with? Every miscellaneous payment (/compta/bank/various_payment/card.php) has an associated 'accounting account' field that can be manually set. That accounting account is associated with a "group of account" (EXPENSE, INCOME, LIABILITIES, etc) which determines how it is treated in other views.

My understanding is that the income/expense report is supposed to represent an "operating income vs. operating expense" comparison (operating expense is COGS + expense). There is a separate group of accounting accounts for "other_revenue" and "other_expenses" which is probably what your miscellaneous payment is being associated with (if it is even being associated with an account at all!). I believe that these categories represent non-core business activities like making a profit selling off old equipment so that might be the right place to account for a one-off unexpected tax or subsidy. 

If your subsidies and taxes are expected and are a core part of your business than you should be able to make a new accounting account in your chart of accounts to represent the transactions within the 'EXPENSE' or 'INCOME' groups of account (or use an appropriate existing accounting account). I suspect this would cause the miscellaneous payments to show up in the Income/Expense report as you desire.

**Comment by xabitrigo** [comment]
We don't have the double accounting module enabled, as we don't have the knowledge to do the accounting ourselves. I simply wanted to use the income vs expenses report to inform the associates of our current cash status and flow. We are a small business and sometimes subsidies make a big impact.

You are probably right and I will test this behaviour in a temporal dolibarr deployment when I have the time and come here to update the issue.

Thanks a lot!

**Comment by agitnaeta** [comment]
Go to accounting module setup, 
then activate it .
in my system url is 
admin/compta.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php%3Fsearch_keyword%3DAccount

**Comment by xabitrigo** [comment]
This seems to be correct, thanks @agitnaeta!
