### ISSUE TITLE
Swagger API docs should specify that GET to invoices has a requirement to thirdparty_ids field in order to display

### ISSUE THREAD

**Issue by komali2** [Dolibarr/dolibarr#26866]
### Bug

When viewing the `api/index.php/explorer/#/invoices` page of the API docs, there are parameters listed. The parameter for `thirdparty_ids` says for description, "Thirdparty ids to filter orders of (example '1' or '1,2,3')." It fails to indicate that if *no* thirdparty_id is provided, then no invoices will return, with "no invoices found" error. It took me a while to figure out this was the issue - I assumed that if no filter value is provided, then, for example, invoices for any thirdparty would be returned. The documents should be updated to clarify this, or, the filter should be modified to function so as to return all invoices for all thirdparties if this filter is not provided. 

### Environment Version

18.0.2

### Environment OS

Linux 6dea47b70f3f 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64

### Environment Web server

Apache/2.4.57 (Unix)

### Environment PHP

8.2.10

### Environment Database

MySQL or MariaDB 11.2.2-MariaDB-1:11.2.2+maria~ubu2204

### Environment URL(s)

api/index.php/explorer/#/invoices

**Comment by hansemschnokeloch** [comment]
Hi,
that is not the case, thirdparty_ids is not requiried in order to get the invoice list. I'm not able to reproduce your issue.

$thirdparty_ids is first affected to $socids if the api user is not an external user
https://github.com/Dolibarr/dolibarr/blob/54ab138aa319193575972d5a7781c05f1eb50976/htdocs/compta/facture/class/api_invoices.class.php#L190-L191

and the sql query part with $socids is ignored if $socids (and therefore $thirdparty_ids) is empty
https://github.com/Dolibarr/dolibarr/blob/54ab138aa319193575972d5a7781c05f1eb50976/htdocs/compta/facture/class/api_invoices.class.php#L213-L215

**Comment by JonBendtsen** [comment]
I did not verify, but I think that proposals, orders and invoices + perhaps shipments and interventions should all work in the same way.

**Comment by komali2** [comment]
Weird, true, the issue just... went away today?
