### ISSUE TITLE
Opensurvey with login 

### ISSUE THREAD

**Issue by Sebastian1984** [Dolibarr/dolibarr#2721]
Hi,
I found some tools like this http://sharepointrelated.com/2013/01/25/get-all-subsites-of-a-subsite/ that collects all subsites of a website. So this would collect also our surveys of opensurvey.(I guess / Great I guessed wrong, thanks rdoursenaud) ---- no security issue, I guessed wrong---
I checked if Dolibarr kills the expired survey links. 3.7. obviously doesn't, so this tool is not safe for doing internal decision making.
Like internal votings, personal requests. this is a big security issue and would make this tool a leak when used for supporting internal decision making or personal votings. 
I called a hosting provider who told that they would be unable to defend it against such an attack, because they can't consider it as one. Looks like normal traffic.
I think this a high security issue that should be addressed. 
Please correct me, if this is not working as an entrance point on companies using dolibarr without deep knowledge of IT.
Greetings,
Sebastian

So it would be still nice to ID the person who is voting by login.

**Comment by rdoursenaud** [comment]
You're guessing wrong. The URL generated by OpenSurvey is a hash that will not be inferred by any tool unless they bruteforce it or have a direct link to follow.

It's available without authentication because the use case you expose was not taken into account during development.

I believe that what you want is to be able to create surveys that require authentication. Am I right?
Please update the issue title to a feature request if you agree.
