### ISSUE TITLE
Database fields encryption

### ISSUE THREAD

**Issue by jfefe** [Dolibarr/dolibarr#2728]
After an installation and when activating $dolibarr_main_db_encryption $dolibarr_main_db_cryptkey into conf.php all modules are disabled. 
How does the encryption works? encrypt() method which convert a string into sql formatted string https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/db/mysql.class.php#L478

**Comment by rdoursenaud** [comment]
You're supposed to enable them with the GUI at //admin/security.php
This ensures that the field are encrypted before activation.

**Comment by rdoursenaud** [comment]
Also the function you refer to seems to use deprecated and potentially insecure algorithms. See: https://security.stackexchange.com/questions/45838/is-why-should-you-avoid-aes-in-mysql-true

We should better use an application server (read PHP) implementation rather than relying on the database management system's function.
Another reason for this is the multiple database backend support. Not all database management systems provide encryption mechanisms.
