### ISSUE TITLE
Global discount management

### ISSUE THREAD

**Issue by atm-maxime** [Dolibarr/dolibarr#2762]
Many people ask about a way to add a global discount to a document.
And there's a specific management to do with "escompte" that should appear after the including tax total.

**Comment by eldy** [comment]
"escompte" seems already supported with dolibarr. When all payment are done, close invoice as "paid partially", then select for reason the choice "Remaining unpaid (5 Euros) is a discount granted because payment was made before term. I recover the VAT on this discount without a credit not" (escompte in french).
