### ISSUE TITLE
Remove message "not found user" in login page when coming from an old session

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2802]
Version: 3.5.6.

When you are a logged user and you change database in the config, Dolibarr redirects you to the login page (as it should) but it gives a message that the user wasn't found. It is better to just "finish" the session and ask the user to log in again.

![captura de pantalla 2015-05-09 a las 12 29 45](https://cloud.githubusercontent.com/assets/168744/7549814/bb022cce-f647-11e4-9452-04c60c38753f.png)

**Comment by rdoursenaud** [comment]
I agree that revealing privileged information (user exists or not) is bad.
I'd raise this as a security issue if anyone can reproduce with a forged cookie (I presume that's where the session information is stored) without previous authentication.

**Comment by eldy** [comment]
This probably means you change the database name "on the fly", but does not clean opened sessions.
Because session name depends on database name, you should also delete the php session files if doing this.
This does not happened with a forged cookie. This happen only if user was on an opened session and administrator has changed the dolibarr database without droping users sessions.

**Comment by rdoursenaud** [comment]
@eldy thanks for the clarification. I didn't think of the session. Silly me…
So, all in all, that message is justified but should go into the logs rather than the UI, right?

**Comment by eldy** [comment]
Yes, it could be in log, and i think it is even more detailed in log.
This situation is enough uncommon so we can close this PR
