### ISSUE TITLE
BUG: REST API "/mos/{id}/produceandconsume" not working and have a confuse behavior

### ISSUE THREAD

**Issue by Humml87** [Dolibarr/dolibarr#28481]
### Bug

Hi,.
either I don't understand the API function or it doesn't work.
I tried now a few hours...

id: 21
request_data:
`{
"inventorylabel": "Produce and consume using API",
"inventorycode": "PRODUCEAPI-YY-MM-DD",
"autoclose": 1,
"arraytoconsume": [{
"objectid": "203",
"fk_warehouse": "677",
"qty": "1"
}],
"arraytoproduce": []
}`

The data origin:
![image](https://github.com/Dolibarr/dolibarr/assets/78662388/ead6cc0c-b020-4eec-b2bb-cfe66d7ae7d5)

**I hope anyone can help me, its very import for my project.**
Thank you together!

Best regards 
Christian

### Environment Version

17...19...

### Environment OS

Ubuntu

### Environment PHP

8.2

### Environment Database

mariaDB

### Environment URL(s)

http://localhost/dolibarr/htdocs/api/index.php/mos/{ID}/produceandconsume

**Comment by JonBendtsen** [comment]
What happens when you send the json to the API, and which of the sub parts of the API are you using? Would you mind posting a picture?

**Comment by Humml87** [comment]
Hallo JonBendtsen,

the result is:
`{
  "error": {
    "code": 500,
    "message": "Internal Server Error"
  },
  "debug": {
    "source": "api_mos.class.php:544 at call stage",
    "stages": {
      "success": [
        "get",
        "route",
        "negotiate",
        "authenticate",
        "validate"
      ],
      "failure": [
        "call",
        "message"
      ]
    }
  }
}`

![image](https://github.com/Dolibarr/dolibarr/assets/78662388/bce9f869-50c3-45b2-a8fd-0d273840de57)

I found some logical errors:
![image](https://github.com/Dolibarr/dolibarr/assets/78662388/ed80cc9d-c2e3-46d3-89fc-ada422f71070)
... if a MoLine with already consumed Products are deleted, sometimes the consumed Products don't delete from the DB.

I think its necessary to refactor the ConsumAndProduce:
- mo_production.php => Move the actions for ConsumAndProduce to a new function in "MoLine" Class.
- api_mos.class.php => then refactor...

@mdeweerd Hi, you make a PR #26805 at 23.11.2023. You know how the API-function work?
@eldy what you think about this function und structure? I think currently we have no way to call a common valid function from the mo_production.php und the api_mos.class.php

Best Regards
Christian

**Comment by Humml87** [comment]
> ... which of the sub parts of the API are you using? ...

Sorry, what you are meaning?
In generally i use the moste API-Methodes from the MRP-Module.
Best regards Christian

**Comment by mdeweerd** [comment]
@Humml87 I made a PR because there was an obvious error.

Unit tests seem to be missing for this and I think that is a good way to have a common understanding/demonstration of issues.

I refactored the test case code for APIs a bit so that it can be shared and started a TestAPIMosTest.php #28484 .

Feel free to propose updates - maybe this code could be integrated in the develop branch as a non integrated test (i.e., not adding the test to AllTests.php) - I do not have the intention to work on the API.

**Comment by Humml87** [comment]
**Some API functions for MRP are necessary** 
_api_mos.class.php:_
- [x] POST => /mos/{id}/lines
- [x] DELETE => /mos/{id}/lines/{id}
- [x] GET => /mos/{id}/lines
- [x] POST => /mos/{id}/lines/{id}/consumeorproduce

**Following change is required**
_mo.class.php (Mo-Class):_
- [x] Add function "hasAllConsumedAndProduced" (<- this is for "autoclose")
- [x] Add function "setStatusAsProduced" (<- close Mo)

_mo.class.php (MoLine-Class):_
- [x] Add function "consumeOrProduce"


**Refactor**
_mo_production.php:_
Lines from 237 to 447
... in_array($action, array('confirm_consumeorproduce', 'confirm_consumeandproduceall') ...
to use the class functions from Mo and MoLine classes.

**Comment by Humml87** [comment]
@mdeweerd its not a new Feature, so i think its right to make a PR for branch 19.0?

**Comment by mdeweerd** [comment]
@Humml87 If you are talking about the test case, it has been accepted on the develop branch.  I think you can backport it to 19.0 but you'll have to get the CommonClassTest.php, the AbstractRestAPITest.php and RestAPIMosTest.php .

I would do a (cd test/phpunit ; git checkout develop THREE-CLASS-FILES) and commit.
I think all 3 of them are new in 19.0 so that should be fine IMHO.

**Comment by JonBendtsen** [comment]
> Sorry, what you are meaning?
> In generally i use the moste API-Methodes from the MRP-Module.
> Best regards Christian

What I meant was that in the API's I use I can use GET, POST, PUT, DELETE, and for some I can do it for all entries of some sort or for a single numbered or single referenced entry.

For orders which I use it can be all orders (with a given project id). Or for Thirdparties where I look it up using the email address. But I can also get orders by order ID which I use when they pay.

So that is what I meant with sub parts.
* GET, POST, PUT, DELETE
* ALL
* by id
* by reference
