### ISSUE TITLE
MAIN_USE_JQUERY_MULTISELECT constant breaks normal functioning

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#2860]
Version: 3.7.0

Problems:
1. WYSIWYG module does not work
2. Unable to edit buying price of a line
3. Editing user rights have no effect.

Steps to reproduce:
1. Enable MAIN_USE_JQUERY_MULTISELECT constant

Reported by a dolibarr.es forum user at http://www.dolibarr.es/foro/viewtopic.php?f=18&t=2259&p=7980

![captura de pantalla 2015-05-20 a las 13 08 40](https://cloud.githubusercontent.com/assets/168744/7724375/5c140374-fef1-11e4-83b1-bce09e4b0143.png)

**Comment by rdoursenaud** [comment]
MAIN_USE_JQUERY_MULTISELECT is **not** a boolean.
It is designed to take 'select2', 'mutiselect', 'multiple-select' or the name of the multi-select jquery plugin to use.
Hidden features are also not supported BTW.

**Comment by marcosgdf** [comment]
So... hidden constants are in the code but are not meant to be working?

**Comment by rdoursenaud** [comment]
Don't get me wrong, they should of course have useful features and be as stable as possible but there's a reason they are hidden!
Some of them may have unpredictable behavior, others don't fit in the "spirit" of Dolibarr most are technical tools meant for people that know what they're doing.
In this very case, it's obvious that the user don't know what he's doing since it took me less than a minute to figure it out.
I updated the wiki documentation to better explain this setting: http://wiki.dolibarr.org/index.php/Setup_Other

**Comment by hregis** [comment]
is used by various externals modules

**Comment by marcosgdf** [comment]
Hi @rdoursenaud I've tested with 'select2' and I still get errors:

![captura de pantalla 2015-05-25 a las 15 20 01](https://cloud.githubusercontent.com/assets/168744/7797801/88b4b0be-02f1-11e5-9268-a65d4afc5c8d.png)

**Comment by rdoursenaud** [comment]
@marcosgdf This ckeditor error seems unrelated to me.

**Comment by marcosgdf** [comment]
@rdoursenaud Well the issue was that when the constant was enabled, WYSIWYG editor didn't work among other things...

But if constants are not meant to be working then I think I can close the issue ¿?

**Comment by rdoursenaud** [comment]
@marcosgdf I'd close the bug if the bad behavior was triggered by the user, but it seems that module developers may set it. I think we don't expect Dolibarr to break in this situation, don't you?

@hregis Could you enlighten us a bit? What is it used for and what's the expected behavior, if any?
Any examples of modules requiring it?

**Comment by hregis** [comment]
@rdoursenaud @marcosgdf 
multicompany and concatpdf ( @eldy ) use the multiselect (optional).
multicompany integrates the plugin itself and does not use this constant.
if it is a problem, we should do the same in concatpdf?

**Comment by eldy** [comment]
I don't experience any problem.
Setting the constant MAIN_USE_JQUERY_MULTISELECT to 'select2' in 3.7 lod the js library select 2. It is not officially supported into 3.7 because some works still must be done, but it is available by default with 3.8.
Event if not supported, i don't experience any problem with 3.7 with this option on.

Does ckeditor is the version embedded with dolibarr ? Did you clear you browser cache ?
