### ISSUE TITLE
Add keyboard shortcuts (aka accesskeys) to the main features

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#2965]
Access keys are a great way to provide direct keyboard access to features.
When used correctly, they can significantly improve both productivity and accessibility.
Using a standard such as SAK2014
### Required

I identified the following places:
- [ ] Top menus
- [ ] Left menus (maybe not every single one…)
- [ ] Left search boxes
### Nice to have

Global shortcuts declaration and (per user?) customization GUI.
### References

_Related to #2566._
[Wikipedia article about access keys](https://en.wikipedia.org/wiki/Access_key)
http://www.standardaccesskeys.com/

**Comment by rdoursenaud** [comment]
I'll not begin working on it right now. I just set this up as a reminder.

Feel free to comment in the meantime ;)

**Comment by eldy** [comment]
This may be a enhancement into menu editor. When menu manager is auguria (so a full database description menu), we may add a new field into menu edition to setup shortcut.

**Comment by rdoursenaud** [comment]
@eldy I'm not familiar with auguria menu manager and I was under the impression that it wasn't actively maintained.
Should I focus on it rather than on the current standard eldy one?

**Comment by eldy** [comment]
Difficult to say.
auguria is a full database menu. I prefer it for future, however there is still some things that this menu is not able to do.
eldy can do everything but is "hardcoded".

So i keep both currently because i don't want to loose work done on auguria if in a future we suceed in moving all eldy features into auguria.

**Comment by atm-florianm** [comment]
I am reopening the issue because this is something I have been missing for a while.

I know some accesskeys are already implemented (such as "n" and "p" for next / previous elements).

I would vote in favor of using [SAK2014](https://www.standardaccesskeys.com/SAK2014)'s keys when they exist, but for more specific aspects not covered by SAK2014 (which is clearly better suited to websites than web apps), I would follow MediaWiki's lead (MediaWiki mainains a [list of its access keys](https://www.mediawiki.org/wiki/Manual:Access_keys#MediaWiki_core): some such as "_save_" and "_edit_" are not covered by SAK2014; some differ such as "f" for "find" (SAK2014 recommends "4")).

Actually, "save" and "edit" are the ones I really miss, having used Wikipedia a lot in the past.

Worth noting that MDN [discourages](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey) the use of access keys for general-purpose websites / apps (because they have many accessibility issues) but Dolibarr is not general-purpose. I'd argue that we can still benefit from implementing some (but maybe we should offer a way for users to disable them completely to avoid any accessibility problems).
