### ISSUE TITLE
Category module menu entries in Thirdparty are overlapped in Amarok theme

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3066]
VersIon: 3.7.1

![captura de pantalla 2015-06-18 a las 13 31 21](https://cloud.githubusercontent.com/assets/168744/8230236/b17ba0fe-15be-11e5-9ec7-496dd557cba4.png)

**Comment by atm-maxime** [comment]
This is due to the amarok theme which does not support submenu titles on several lines.
In the french translations, we only put the "Tag" instead of "Tag/Category". Shouldn't you do the same in the spanish translations ? I think we must try to keep all submenu on one line. I agree this is not the best solution because we have a risk that in some languages the bug will reproduce...

**Comment by marcosgdf** [comment]
In the English translation, it is called "Tags/Categories". So... shouldn't the English translation change so that the rest of the languages have a shorter name as well?

**Comment by eldy** [comment]
Theme has been deprecated.
Also css has been reviewed to be truncated in last version so i close ticket.
