### ISSUE TITLE
oauth2 token management: no token stored in database since v20

### ISSUE THREAD

**Issue by kubajznik** [Dolibarr/dolibarr#30690]
### Bug

After update from v19 to v20 the tokens are not stored in the database any more. The retrieval of token seems to work fine (green box), but then there is no token stored (see screenshot).
I use this to send email via the SMTPS library. When sending an email now, I get the error, that there is no token stored, but the email gets send anyway.

### Dolibarr Version

20.0

### Environment PHP

8.2.22

### Environment Database

MySQL/MariaDB

### Steps to reproduce the behavior and expected behavior

1. Open token manager on /admin/oauthlogintokens.php
2. Retrieve new token

### Attached files

![image](https://github.com/user-attachments/assets/76919f88-39bd-4412-a922-6665a63af4d2)

**Comment by JRFPlows** [comment]
Same Situation, i am still on PHP 7.4.33, went back to 19.0.3.

**Comment by eldy** [comment]
A fix has been pushed in v20 branch. Will be available with v20.0.1.
Can someone test with version after commit 52616db1b7cf70ac41e57c21e128806348933ab4 and say if its ok now and if sending email using the SMTP with Oauth2 Microsoft works correctly ?

**Comment by kubajznik** [comment]
It works, thanks @eldy !

**Comment by eldy** [comment]
> It works, thanks @eldy !

Did you just test saving thebtoken or did you try and succeed also to send an email with smtp ?

**Comment by JRFPlows** [comment]
Hi,
both is working now for me on 20.0.1, th e token is being generated and saved automatically with my e-mail-collector and sending mail is working also.

PS
e-mail-collector is not attaching attachments, from the e-mail-collector (tickets), since previous versions I believe v19


greetings

Jason.

***@***.***

Auerswald Advanced
PARTNER 2016 / 2017

[Fb-PCialist]

PCialist GbR
Jason Plows & Müslüm Kirpac

Ettinger Str. 19
85057 Ingolstadt

Fon: 0841 483 431
Fax: 0841 483 432
***@***.******@***.***>
www.pcialist.de<http://www.pcialist.de/>
https://www.facebook.com/PCialist/

Öffnungszeiten:
Montag – Freitag:
10:00 – 13:00 und 14:00 – 18:00
Samstag:
10:00 – 13:00

Außerhalb nach Terminvereinbarung

Umsatzsteuernummer: DE279309424  -  Steuernummer: 124 / 172 / 553 01

Hinweis zum Datenschutz: Der Inhalt dieser e-Mail ist vertraulich und ausschließlich für den bezeichneten Adressaten bestimmt. Jede Form der
unautorisierten Nutzung, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser e-Mail nicht gestattet ist. Diese Nachricht ist
ausschließlich für den bezeichneten Adressaten oder dessen Vertreter bestimmt. Sollten Sie nicht der vorgesehene Adressat dieser e-Mail oder
dessen Vertreter sein, so bitten wir Sie, sich mit dem Absender der e-Mail in Verbindung zu setzen sowie die e-Mail und etwaige Kopien zu löschen.


Von: Laurent Destailleur ***@***.***>
Gesendet: Mittwoch, 9. Oktober 2024 23:58
An: Dolibarr/dolibarr ***@***.***>
Cc: Jason Plows ***@***.***>; Manual ***@***.***>
Betreff: Re: [Dolibarr/dolibarr] oauth2 token management: no token stored in database since v20 (Issue #30690)


It works, thanks @eldy<https://github.com/eldy> !

Did you just test saving thebtoken or did you try and succeed also to send an email with smtp ?

**Comment by kubajznik** [comment]
For me storing token and sending email - even with attachment - works! We use smtp via Microsoft 365.

**Comment by JRFPlows** [comment]
Hi,
sending is no problem, but my e-mail-collecor is not attaching files or documents while the php-imap library is active, when i deactivate back to native php-imap, the collector is collecting e-mails inklusive attachments.
I tested two systems from 19.0 till 20.0.1 with php 7.4.33 till 8.2.16.
