### ISSUE TITLE
BUG Propal sign

### ISSUE THREAD

**Issue by zahwyrix** [Dolibarr/dolibarr#30864]
### Bug

When you sign a quote via the link, it's taken into account and you get the signature on the pdf. But there's no confirmation message, and you even get the impression that it didn't work, as the page remains indefinitely on the signature with the “wait” cursor.

### Dolibarr Version

19.0.2

### Environment PHP

7.4

**Comment by ksar-ksar** [comment]
Hello,

For me it's more a feature request than a Bug

**Comment by zephyriony** [comment]
I don't agree, if you're stuck on a page without any element showing that it's been validated and with the cursor wait which implies that you have to wait forever, it's a bug. The first time I saw this, not understanding, I signed the quote three times.
You have to put yourself in the customers' shoes, they won't understand either.
It's a bug because it seems absolutely illogical to me that this should be the expected behavior, no sensible developer could have stopped there like that. If you can, try it out, you'll see what it feels like. It feels like it's loading and waiting forever.
It's strange to consider a confirmation message as a feature request, I'm a bit puzzled.
I don't care what label you give it, bug or feature request, the main thing is that it's dealt with quickly for users and above all that it doesn't just happen in the next major release.

**Comment by ems-co** [comment]
I'm not sure but i have tried it and its working fine for me after signature and clicking accept proposal and there is a confirmation message! 19.0.2 

<img width="1462" alt="Screenshot 2024-09-06 at 12 49 26 PM" src="https://github.com/user-attachments/assets/4dd5ef2b-de58-4be0-b331-abeca8dd5924">

**Comment by zahwyrix** [comment]
I can see the message in the code, but when I validate I get the “wait” cursor at infinity.

**Comment by zahwyrix** [comment]
#30878
