### ISSUE TITLE
State dropdown is not working on User card

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#31198]
### Bug

While we are going to Edit or Add an user in Dolibarr and after selecting the desired country, the state drop-down is not popped up correctly. Please the attached screenshot below.
![state-dropdown-error](https://github.com/user-attachments/assets/203a7874-e907-46a6-8deb-009ddc873b19)

### Dolibarr Version

20.0

### Environment PHP

8.1.25

### Environment Database

MySQL

**Comment by hregis** [comment]
@alsoft10 i don't have this error, can you see your browser console if you see an error ?

**Comment by alsoft10** [comment]
@hregis There is nothing in the browser console.

**Comment by hregis** [comment]
@alsoft10 maybe a conflict with an external module?

**Comment by alsoft10** [comment]
@hregis not at all. I just installed fresh copy of Dolibarr 20.0 and the problem persist. If you want I can show you remotely.

**Comment by ksar-ksar** [comment]
Same for me : 
![image](https://github.com/user-attachments/assets/afac921b-42e5-4d75-aefd-ca5915e2c379)

I have only an event on the consol, but i'm not sure it's related to the issue : 
Cancel check_events() with dolnotif_nb_test_for_page=4. Check is useless because javascript Notification.permission is default (blocked manually or web site is not https or browser is in Private mode). [lib_notification.js.php:139:11](https://doli/20/core/js/lib_notification.js.php?layout=classic&version=20.0.0)

**Comment by hregis** [comment]
@alsoft10 sorry, I didn't understand that it was on a user sheet, I was testing on a third-party sheet

**Comment by alsoft10** [comment]
@hregis you are welcome!
