### ISSUE TITLE
Ticket markAsRead function does not update the status to STATUS_READ

### ISSUE THREAD

**Issue by cbeasley-sbb** [Dolibarr/dolibarr#31206]
### Bug

Clicking the "Read" status button does not update the object's fk_statut attribute resulting in the object's status remaining the same as before the action.

The ticket.class.php 'markAsRead' function executes a database update for the field.  However, it does not set '$this->fk_statut' to Ticket::STATUS_READ.  As a result, if there are triggers that update the object the status is reverted back to the original status.

If the following is added somewhere before or after the database update the problem is resolved.

`$this->fk_status = Ticket::STATUS_READ;`

### Dolibarr Version

18.0

### Environment PHP

PHP 7.x

### Environment Database

10.11.3-MariaDB-1 - Debian 12

### Steps to reproduce the behavior and expected behavior

1. Open a ticket card.
2. Click the 'Read' status button.
3. Observe the status did not change.

**Comment by rycks** [comment]
hello @cbeasley-sbb i can't reproduce that bug, here is the result when i click on "read" (sorry for the screenshot in french) on dolibarr 18

![image](https://github.com/user-attachments/assets/38fdc330-9f62-4278-92f3-0e3adb0a5834)

**Comment by rycks** [comment]
That bug seems to be present only if there is a trigger is that true ?

What could we do to reproduce the bug ? what trigger is called from what module ?

Maybe you could put dolibarr as debug mode, collect the log, clean private part and publish it here to help us ?

Thanks

**Comment by rycks** [comment]
i think with dolibarr debug we could read something like that:

(dolibarr core) update database with status read (but do not update object attribute status)
(trigger) update database with all current object attributes -> then sql will make update with "old status" (so not read in that case)


i search into other part of dolibarr and for example there is a solution like your for setDraft on invoices (facture.class.php) but it seems to be different in commande.class.php where attribute status is set at the end of function after trigger ...

so @eldy i think we need your expertise for that sort of things because there is different solutions on different objects, then it could be better to make a choice and publish a note with "good solution is ..." and apply it in all dolibarr objects

**Comment by eldy** [comment]
The good solution is the one suggested by cases of modulebuiler: When we update a status or a property, we first use the this->oldcopy = dol_clone($object, 2) to make a copy.
Then we set status and properties and persist them in database.
if error, we revert properties in memoery by using the value into the backup.

In v18, the dol_clone is not using the parameter 2, this means we are not sure that the properties saved into oldcopy is not modified when we modify the $object. So the copy is not reliable so having a variable like $oldStatus is the good way.
So i validated the PR, i merge it into v20 and develop and i modified develop to remove the old status and use instead the ->oldcopy object (because this object is reliable and not modified) in v20+
