### ISSUE TITLE
Add Dolibarr ticket title into the notification email subject

### ISSUE THREAD

**Issue by alsoft10** [Dolibarr/dolibarr#31250]
### Feature Request

We should have an Other Setup configuration to add **Ticket Title** directly into the **Subject of the notification email**. 

### Use case

This will make the Dolibarr email support more easy and real time.  Customer can easily identify the desired notification email out of lots of notification email by the title. Customer can their email inbox using the title of the ticket and they can easily go through the conversation step by step.

**Comment by zahwyrix** [comment]
You can use an email model with this variables : 
__TICKET_TRACKID__
__TICKET_SUBJECT__
__TICKET_TYPE__
__TICKET_SEVERITY__
__TICKET_CATEGORY__
__TICKET_ANALYTIC_CODE__
__TICKET_MESSAGE__
__TICKET_PROGRESSION__
__TICKET_USER_ASSIGN__

The reference used to be in the subject line, but I remember I removed it because it was being imposed on people who didn't want it. Just make an e-mail model if you want it.

**Comment by alsoft10** [comment]
This feature is already implemented.
