### ISSUE TITLE
build_class_from_table.php is broken with aa9f0965c0d8b9cf8814faf095dd4c50c97ec480

### ISSUE THREAD

**Issue by FHenry** [Dolibarr/dolibarr#3192]

**Comment by FHenry** [comment]
aa9f0965c0d8b9cf8814faf095dd4c50c97ec480

**Comment by rdoursenaud** [comment]
Can you explain a bit better what I broke so I can avoid doing this again next time?

**Comment by rdoursenaud** [comment]
Oh, never mind, I get it.
The template is OK.
What's broken is the ugly script that's using regexes to try and generate something from it.
What can I say. Bad practices are bad!

**Comment by tiaris** [comment]
I agree  If you work on the build_class_from_table script :
- why does the script remove all _ ? A table llx_my_table will generate a mytable.class.php and a class Mytable instead of my_table.class.php and Class My_table  
  see code
  $tablenoprefix=preg_replace('/'.preg_quote(MAIN_DB_PREFIX).'/i','',$table);
  $classname=preg_replace('/_/','',ucfirst($tablenoprefix));
  $classmin=preg_replace('/_/','',strtolower($classname));
- if a column has a default Value, generated script does not get the default value 
  (example : fk_soc INTEGER(11)  NOT NULL DEFAULT 0, generates $sql.= " ".(! isset($this->fk_soc)?'NULL':"'".$this->fk_soc."'").",";
