### ISSUE TITLE
File proxy should send headers when file changed

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#3307]
When switching Dolibarr versions, CSS, images, JS… may have changed.
But since these are proxified, headers are not modified so the browser uses it's cached version instead of the fresh one.

More research should be done on the subject but I'm pretty sure ETag headers made from file hashes should fix the problem.

**Comment by eldy** [comment]
Currently, for images, a header is set to ask browser to not load them at each time (we use cache at browser side).
If we want them to be refreshed automatically without clearing browser cache after version upgrade, it means we must send into header information that say "ask at each call if file has changed" (we use the cache on server side, no more on browser side). Using server cache instead of browser cache solve this little problem but i think it does not worth the increase of url call.

For css generated by php, js, a param version is set on url to have the refresh done even after an upgrade for both dynmaic and static files.

**Comment by simnandez** [comment]
I close this issue, as it will not be implemented
