### ISSUE TITLE
3.7 does not fill edit image alt attribute

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3322]
Title tag is filled instead.

Both attributes are similar, but the "alt" attribute is shown when the image cannot be loaded, while the title attribute is shown to the user as a complementary text to the image.

Example (from https://www.w3.org/wiki/HTML/Elements/img):

```
<img src="sales.gif"
     title="Sales graph"
     alt="From 1998 to 2005, sales increased by the following percentages
     with each year: 624%, 75%, 138%, 40%, 35%, 9%, 21%">
```

As you can see in that example, the `alt` attribute describes the image while the `title` attribute does not.

![captura de pantalla 2015-07-27 a las 13 20 42](https://cloud.githubusercontent.com/assets/168744/8904751/4fc3dd3c-3462-11e5-8670-d44591184409.png)

**Comment by rdoursenaud** [comment]
@eldy reverted my fix, so I reopen the issue.
Also, could you please explain why it's been reverted?

**Comment by eldy** [comment]
The alt is used when image is not shown like for bind people. If image does not provide any interesting information and was only here for cosmectic need (the most common case), then for terminal used by bind people, the alt must be "", so screen is not overloaded with things they don't need to see.
However, the title is used for easy to do tooltip.
That's why we must :
Set title to the value of tooltip and the alt to "" (if this is an cosmetic image) or to "a string to describe graph" if image contains non cosmetic value (very rare case).

**Comment by marcosgdf** [comment]
Can you please read again the bug report? I was describing an actual **common** bad usage of the title and alt tag, and that was what I am reporting.

I do think in Dolibarr the usage of non-cosmetic images is actually very common and cosmetic images rare.
