### ISSUE TITLE
VAT and Localtax of business object lines should not be rounded

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3347]
When charging for a product that has 3 decimals in its unit price, Dolibarr rounds VAT and other taxes to 2 decimals and stores that value in total_vat.

When calculating the total VAT of the object, it sums all total_vat fields, resulting in an error of ~0.02 cents that should be charged to the client.

If instead of rounding business object lines and just rounding the total calculated amount (llx_facture instead of llx_facturedet) we can avoid this problem.

This is an example and there is no way of fixing it without changing MAIN_ROUNDING_TOT to 3 instead of 2:
- UP: 0.195, QTY: 1198
- UP: 0.195, QTY: 766
- UP: 0.195, QTY: 107
- UP: 0.195, QTY: 1163
- UP: -0.095, QTY: 2428

I know that setting up the MAIN_ROUNDOFTOTAL_NOT_TOTALOFROUND constant this problem can be fixed, but I think that this mode should be by default.

**Comment by rdoursenaud** [comment]
Agreed. Rounding is tricky to do just right, be we should try ;)

**Comment by eldy** [comment]
Mode rounding of total was default a long time ago (when a lot of invoicing were done manually).
With the increase of computer, the mode "rounding on each lines" tend to be more frequent than "rounding the total". Above all since a lot of countries in europe as asked to make vat calculation or turnover per VAT rate (and having different VAT rate on the same invoice make rounding of total no more compatible with such requirement).
