### ISSUE TITLE
Company name is overlapped with company direction in supplier invoices PDF model

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#3383]
Version: 3.7.1

![captura de pantalla 2015-08-13 a las 18 20 13](https://cloud.githubusercontent.com/assets/168744/9255181/ff686d42-41e7-11e5-8aa4-535a53d5baca.png)

**Comment by rdoursenaud** [comment]
Our PDF generators are riddled with this kind of bugs. They need a complete rewrite IMHO. Been thinking about it for a while but I'm too lazy to undertake that huge work.

**Comment by marcosgdf** [comment]
I remember taking a look a it in the DevCamp and I kinda freaked out...

**Comment by rdoursenaud** [comment]
Yes it's just a mess with absolute hard-coded dimensions and coordinates all over the place. And let's not talk about code duplication and divergence…
This prevents us from really supporting paper sizes different from A4 (letter kinda works because its dimensions are close to A4).
I made a full "relative" and "auto-adaptative" PDF generator for a custom Agefodd template that worked a treat but I haven't taken the time to extract the relevant parts yet.
Maybe I should open a "rewrite" issue?

**Comment by marcosgdf** [comment]
That would be nice. I pushed a fix though while we don't rewrite it
