### ISSUE TITLE
Do not delete lot/serial record when qty is 0

### ISSUE THREAD

**Issue by fappels** [Dolibarr/dolibarr#3438]
Now lot/serial records are deleted when stock movement results in qty 0. 
If we use the lot/serial for serial numbers, one should not be able to make the same serial again for a new product item after delivery.
In the code there is commented 'table llx_product_batch (will be rename into llx_product_stock_batch inantoher version)', I think we keep better product_batch, because product_batch not only contains stock qty but also lot/serial info.

**Comment by eldy** [comment]
llx_product_batch is used to say what is stock content.
If a qty is 0, we have no reason to keep the line, even for serial/number.
For tracking, we use the table of movements.

So i dont( understand request. Can you provide more explanation.

**Comment by fappels** [comment]
llx_product_batch is not only stock content but also contains expiry dates, I know the dates are also stored in table of movements, but I think it's more clean to keep the data in the product_batch table.
Now there is a check on lot - sell/eatby "ThisSerialAlreadyExistWithDifferentDate", this check should also work on qty 0 lot/serials.
The product_stock table also keeps the 0 qty records, but they are filtered in the stock views.
I also have a feature request to add extrafields to lot/serial, if we remove the record we also will lose extrafield data.

**Comment by BebZ** [comment]
I agree that product batch table should keep 0 qty for history reasons (movements would maybe not enough when there is a search to make with mysql... isn'it ?), 
Moreover... contain more infos with extrafields or something else (like "row", "shelf", "short DLC/DLUO"). I don't think speed performances could be affected...

The NEW check on lot - sell/eatby "ThisSerialAlreadyExistWithDifferentDate", this check should also work on qty 0 lot/serials.
is it only a warning ? or it can block the dispatch to stocks ? because one supplier may send same serial with same date twice if he wants... hope this not blocks but only asks for agreement.

**Comment by fappels** [comment]
Supplier can send same lot with same date, but not same lot with different date. So if you want to block receiving duplicate serial numbers you can add for example the receiving date when dispatching. (a 'now' button could be useful). Can also be useful to first sell oldest serial number, if your supplier also registers serial numbers to track warranty period.

**Comment by BebZ** [comment]
Yes, implement FIFO would be a good idea when we select batch./dluo in the shipments page...
dluo or dlc is mandatory i guess (one of the two, maybe) ?
I just had the issue right now : i was disaptching and entering twice the same batch, with 30/05/2020 and 31/05/2020... shi**\* happens ahaha

**Comment by fappels** [comment]
@eldy Noticed that shipped lot/serials are still available in llx_expeditiondet_batch, so we can add this table to the check if lot dates matches, but with a different warning message. If we go for the lot extrafields we can add a batch_origin_id field to the llx_expeditiondet_batch table.

**Comment by defrance** [comment]
some more discutions about it
the first of all is to considere what the need of batch product?

for me they corresponding of a list of product with common specification (number, dlc/dluo) and a storage (fk_entrepot)
One of the most bad thing actually is what append if we receive many time a same batch species(number, dlc/dluo) for tracking it

SO what my analysis about ?
if batch/lot don't exist create it like actuality
if batch/lot is emptyed (qty=0) we keep the line (new pr proposed about )
if a new batch/lot come again, just update the quantity (new pr proposed)

it's not a good sql pactice to keep data on llx_expeditiondet_batch, they duplicate it, we must just keep the fk_product_batch key

**Comment by BebZ** [comment]
> if batch/lot don't exist create it like actuality<
> OK
> 
> if batch/lot is emptyed (qty=0) we keep the line (new pr proposed about )<
> OK, but is it a good practice to keep the fk_product_batch in memory ?
> It will not affect shipments ? it will not propose sending a "0" quantity ?
> if a new batch/lot come again, just update the quantity (new pr proposed)<
> Aggreed and  maybe more simple to update qty from fk_product_batch than from multiple fields like batch field + eatby+sellby
> 
> it's not a good sql pactice to keep data on llx_expeditiondet_batch, they duplicate it, we must just keep the fk_product_batch key<
> Then we must change the SQL queries on shipments 
> update our shipment tables with an SQL query which will replace all batch+eatby+sellby 
> with only fk_product_batch ?

BTW : you still want to change eat and sellby by date_consumption and date_sell ?

**Comment by defrance** [comment]
if we wand to made of product_batch a little tracability tools we MUST KEEP the integrity of fk_product_batch
in productbatch.class.php function findAll we have yet the filter if qty<>0
we have made some test seems good, advice welcome

I agree to use 'classic naming' of dolibarr fields (like "label" or "ref" instead "batch")

**Comment by BebZ** [comment]
@fappels 
what do you think of KEEP the integrity of fk_product_batch by not removing 0 stock from llx_product_batch and use fk_product_batch in other tables like shipment tables to track product's batches ?

as you said to Eldy it was in this sense, no ? 
 If we go for the lot extrafields we can add a batch_origin_id field to the llx_expeditiondet_batch table.

Maybe we need to know if @eldy agrees on this behaviour, because he said : 
llx_product_batch is used to say what is stock content.
If a qty is 0, we have no reason to keep the line, even for serial/number.
For tracking, we use the table of movements.

So i dont( understand request. Can you provide more explanation.

**Comment by defrance** [comment]
my goal is to use lot number in my module Equipement, i include the fk_product_batch key on my table for tracing the lot who come the product. without keeping the product_batch line i loose the integrity

so I have two choices:
- OR we keep lots with a quantity to zero and I can interface modules batch / lot with the equipement modules 
- Or you do not keep items and will explain to Equipement users why it should not use the batch/lot module to the tracability

**Comment by fappels** [comment]
@BebZ the new 4.0 table llx_product_lot from @eldy will solve a lot of lot (:wink:) issues. The batch field will now be the key field, makes a fk_product_batch obsolete and can be used in other modules like equipment from @defrance. Batch extrafields have now low priority with the note fields and link possibility to other modules. Unique key uk_product_lot(fk_product, batch) will solve the unique serial number issue.
So I can close this request, because llx_product_batch will be a stock only table.

**Comment by edupulpillo** [comment]
A lot/batch number do not have the same meaning that a serial number.

1) You can receive/send pieces belonging to the same batch, since it means same batch of manufacturing. Then the batch value in the shipment/reception can be repeated several times for the same product in several shipments/receptions.
2) Batch numbers values can be repeated in different products.
3) Serial numbers are unique for each product id, but can be repeated if are present in different product ids.

Now the fetching of a shipment fails and have bugs, since do not manage well the batch numbers if several lines of same product+bacthnumber exist in the purchase order.  

In a customer purchase order, sometimes the operator likes to use the same productid+batch number several times in the same PO document, following a purchase order clasified in "chapters" that have several times repeated the same productid+batch number. If this occurs, when a shipment is generated, the fetching when the shipment is tried to be validated, is displayed an error message warning that the batch number is repeated in several lines of the shipment. Everything normal at this point.

Then if the user fix it, editing the lines of the shipment, reducing the qty of a productid+batchnumber line to 0, and increasing the qty of it in the another line that was repeated, the validation of the shipment is accepted, but we get a mess in the quantities per batch number in the stock and the shipment wty per each batch number. Also  the "ordered qty" of the lines with shipment qty=0 remains in the shioment document.

The fetching algorithm should be smart enough to group the quantities of different lines with same productid+batchnumber in the shipment, grouping in only one line in the shipment the total qty for that  productid+batchnumber.

The current limitation to update the qty ordered per product id per line, should be allowed, always checking that do not exceed the original qty of the whole order for a product.

Also should be allowed to delete the productid lines in the shipment that are repeated, but with qty=0. Then will be possible to fix manually a shipment document that originally had repeated the same productid+batch number. 

The best should be that the shipment fetching process identify the repeated productid+batchnumber lines, and group it in only one line, warning the user about it, and asking for the confirmation of the validation of the shipment.
