### ISSUE TITLE
Documents folder on setup

### ISSUE THREAD

**Issue by atm-aurelien** [Dolibarr/dolibarr#3446]
Hello,

Should it be a good idea to include **/documents** folder or directly create it with r/w permissions on Dolibarr install?

Regards,

**Comment by tomours** [comment]
Hi,
In order to create this folder, php should have r/w permission on the parent folder, where you want to create /documents, which will probably most often not happen.

**Comment by atm-aurelien** [comment]
So, first possibility: why not to include this folder (and its subfolders) on install? And apply rights on them (chmod)?

**Comment by tomours** [comment]
Because, first, nobody will place this folder at the same place.
If I take my own exemple to illustrate : my web server is on a "small" SSD drive, and my documents are on bigger SATA disks : they're not a sub-folder of Dolibarr program.
Plus, even if we wanted to place this folder at a determined place under dolibarr folder, I don't understand how you would like to apply rights on this folder, if you don't have rights on dolibarr.

**Comment by rdoursenaud** [comment]
What's the problem with the current implementation ?

**Comment by eldy** [comment]
Current implementation create dir if server has permission for. If not, a message ask to create it or change permission manually, so nothing is wrong for me.
