### ISSUE TITLE
"CATEGORY_UNLINK" trigger is not called

### ISSUE THREAD

**Issue by all3kcis** [Dolibarr/dolibarr#3607]
If the product is update in product/card.php the "CATEGORY_UNLINK" trigger is not called because the category are directly deleted (line 385).

I propose to make the change to solve this problem.
Solution I would like to develop:
During the product upgrade from the array of categories for this product
recovery of 2 arrays, one for add categories the other to delete category (product).
Then I would use the add_type and del_type functions of the Category class.

You confirm these changes?

**Comment by rdoursenaud** [comment]
Good catch!
I think I'm the one who designed this ugly workaround in a rush.
I'm ashamed now…

We have the same issue for all categories:
- [x] products
- [x] members
- [x] contacts
- [x] customers
- [x] suppliers

Because of the way the new categories selector works, we get a list of the categories we need to set (or keep) but we don't get a list of the categories removed.

We need to come up with a better solution that would call "CATEGORY_UNLINK" only on the removed categories, not all. I believe the right place for this code would be a setCategories() method on each affected objects that figures out the diff and calls the proper Categorie::del_type() and Categorie::add_type() methods.

I'll give it a try.
