### ISSUE TITLE
Do not show user and group permissions

### ISSUE THREAD

**Issue by wankwaiwing** [Dolibarr/dolibarr#3794]
Bug found at line #279 under the file of "/user/group/perms.php", and the right statement should be 

``` php
print '<tr '.$bc[$var].'>';
```

The version is 3.8.1

**Comment by eldy** [comment]
I checked into source code and that's what we get. I mean i can't see any diff with suggested code. Can you point me the diff ?

**Comment by rdoursenaud** [comment]
@wankwaiwing Your comment was unreadable because the markup was upsetting GitHub's parser.
I updaded it so it's at least readable. The correct way is to enclose your code snippets in three backticks. Please see https://help.github.com/articles/github-flavored-markdown/ for more informations.

Now even with that sorted out, I stand with @eldy, I don't understand the problem as it's the exact current stable code!
