### ISSUE TITLE
Can't test if a field object_total_vat_locale_x.x is defined before use in odt templates

### ISSUE THREAD

**Issue by jpfox** [Dolibarr/dolibarr#3819]
I need to have a table with different VAT amounts for each rate so I use {object_total_vat_locale_x.x} field. But, if there is no line for a particular vat rat, the filed is not set and so tag {object_total_vat_locale_x.x} is display as is.

If test [!-- IF {object_total_vat_locale_20} --] could work and return false if {object_total_vat_locale_20} is not defined, it could be a solution.

How can I conditionally use these kind of field ?

**Comment by jpfox** [comment]
Many thanks, will it be pushed into 3.8 branch ?

**Comment by jpfox** [comment]
Sorry @eldy but I apply patch from https://github.com/Dolibarr/dolibarr/commit/d0d4c5e7f8a625badb0157badef4c9ae8dbe81dc and it does not work :-( 
If var is not defined whole [!-- IF ....] { } [!-- ENDIF...] is still generated as is, not replaced by the "else" value.

**Comment by eldy** [comment]
This is probably because the condition
[!-- IF ....]
was not entered in one pass into libreoffice but may have been entered by
cut and paste and using the back key of keyboard.
Sometimes also libreoffice replace the -- with -

Open the .odt file with unzip then open the file content.xml and check
inside that you can see the condition with exact syntax.

2015-11-10 11:29 GMT+01:00 Jean-Pierre Morfin notifications@github.com:

> Sorry @eldy https://github.com/eldy but I apply patch from d0d4c5e
> https://github.com/Dolibarr/dolibarr/commit/d0d4c5e7f8a625badb0157badef4c9ae8dbe81dc
> and it does not work :-(
> If var is not defined whole [!-- IF ....] { } [!-- ENDIF...] is still
> generated as is, not replaced by the "else" value.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/issues/3819#issuecomment-155381550.

## 

EMail: eldy@destailleur.fr

## Web: http://www.destailleur.fr

Google+: https://plus.google.com/+LaurentDestailleur/
Facebook: https://www.facebook.com/Destailleur.Laurent

## Twitter: http://www.twitter.com/eldy10
- Dolibarr (Project leader): http://www.dolibarr.org (make a donation for
  Dolibarr project via Paypal: contact@destailleur.fr)
- AWStats (Author) : http://awstats.sourceforge.net (make a donation for
  AWStats project via Paypal: contact@destailleur.fr)
- AWBot (Author) : http://awbot.sourceforge.net
- CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by jpfox** [comment]
I found the problem. Your last correction is not compatible with {object_total_vat_locale_x.x} tags which contain digits, dot or coma.

Here a pull request to correct it : 
https://github.com/Dolibarr/dolibarr/pull/3965
