### ISSUE TITLE
Bad upload of accountancy.lang on Transifex

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4196]
The accountancy.lang upload seem to have failed and picked up an HTML file from GitHub.
The current content makes no sense.
Please remove and reupload.

https://www.transifex.com/dolibarr-association/dolibarr/accountancy/

@eldy @novalore

**Comment by rdoursenaud** [comment]
Fixed \o/

Thanks to anyone!

**Comment by rdoursenaud** [comment]
@simnandez  fixed it yesterday. But problem reappeared. Looks like some automatic feature misbehaving since it's the only file affected.

**Comment by rdoursenaud** [comment]
@simnandez refixed it and it came back again today.
There is something strange going on.
The bad upload is always around 10 AM CET (I receive an email notification from Transifex).

**Comment by simnandez** [comment]
@eldy refixed it today.... before close this issue, we wait a few days... because we are not sure that happens...

**Comment by eldy** [comment]
It seems a batch ran with transifex account of novalore is erasing each day content of this file with rubbish data.
@novalore can you have a look at your batch ?

**Comment by novalore** [comment]
I had a look at my systems and couldn't find any batch running or cronned anywhere.
I changed the password of my transifex account (it has to be stored in .transifexrc to use the client without interaction); we'll see what happens today at 10 AM.

**Comment by ndrosis** [comment]
Today at 10 AM CET

![index](https://cloud.githubusercontent.com/assets/4933899/11917318/13bd7016-a70b-11e5-8729-d6f63a18246d.png)

**Comment by rdoursenaud** [comment]
I think an admin should check the "Auto update resources" setting on this page: https://www.transifex.com/dolibarr-association/dolibarr/content
That's the only native feature I can think of that could misbehave like this.
@eldy @novalore ?

**Comment by novalore** [comment]
I think you are right @rdoursenaud , accountancy.lang was the only file connected to an update url (the url of the file in the github repo).

That was the most probable cause of the glitch. I think it was logged as me because my user is the founder of the project on transifex. I honestly don't know how the problem could occur, but it has to be related to the fact that accountancy.lang was added later than the other language files which existed before the beginning of the translation project on transifex and were all imported at once.

**Comment by rdoursenaud** [comment]
Thanks @novalore
No spurious updates since 4 days.
Now if @eldy or @simnandez could upload the correct file ;)

**Comment by eldy** [comment]
Should be ok now.
