### ISSUE TITLE
FPDI needs upgrade to be compatible with PHP 7

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4207]
PHP 7 is now stable and is a huge improvement.
Dolibarr compatibility would be very nice.
But the version of FPDI we currently ship does not work with PHP 7 and issues the following message:

```
Declaration of FPDF_TPL::SetFont($family, $style = '', $size = 0) should be compatible with TCPDF::SetFont($family, $style = '', $size = NULL, $fontfile = '', $subset = 'default', $out = true)
```

The current stable version of FPDI (1.6.1) has a declaration that is compatible with the shipped TCPDF and should work with PHP 7 (to be confirmed).

Somewhat related to #3351.

**Comment by eldy** [comment]
With 3.8, it seems embedded FPDF_TPL has already a method setFont with the expected signature.

public function SetFont($family, $style = '', $size = null, $fontfile = '', $subset = 'default', $out = true)

**Comment by eldy** [comment]
We are now using tcpdi to build pdf (that use tcpdf).
And tcpdi current version has this note:

"Note that only the standalone version of fpdf_tpl is supported (v1.2.3); the version bundled with FPDI 1.5 is not currently compatible."
FPDI is no more used.
That's why tcpdf_tpl (the standalone version) was added manually into directory tcpdi.

May be we should make a try to use this other repo of "https://github.com/kulbakin/tcpdi".
It seems to maintain the couple tcpdi + fpdf_tpl working for it.

A PR to update composer with it for 4.0 is welcome.

**Comment by rdoursenaud** [comment]
@eldy Thanks for the clarification.
Looks like the bug indeed is in TCPDI and I got confused.
The message stated in the OP is issued because of `htdocs/includes/tcpdi/tcpdi.php`.

Also, does that mean that we can completely get rid of FPDI for 4.0?
