### ISSUE TITLE
Posible Command Injection in Backup Section

### ISSUE THREAD

**Issue by naxonez** [Dolibarr/dolibarr#4309]
Hi,

Testing the backup page I see that if you put a command like this in "Full path to mysqldump command" you can execute commands like ls and the result appear in the .err file generated:

![dolibarr](https://cloud.githubusercontent.com/assets/7959568/12011931/a88eed7c-ace3-11e5-80dd-bdd27f45a812.png)

The payload used is /bin/ls; but an attacker can use other commands to create a shell o execute arbitrary code.

Regards

**Comment by marcosgdf** [comment]
Version?

**Comment by naxonez** [comment]
3.8.2

**Comment by marcosgdf** [comment]
The attacker will need administrator privileges to do so. 

I am not sure if it can be avoided… Will a check for "mysqldump" binary in the given path be enough to avoid that?

**Comment by naxonez** [comment]
I think that de best practice is autodetect mysqldump in the system or disable this option and only permit "Mysql Dump (php)" option. Another workarround is escape the character ';' without this character i can't inject arbitrary commands. Maybe scape other characters like '&' can avoid the combination of multiple Os commands.

On the other hand the user needs admin as you say but using this command injection an admin user can compromise the entire server.

**Comment by rdoursenaud** [comment]
Yes, I agree, this is a serious issue that can allow privilege escalation from a Dolibarr admin to the server.

**Comment by rdoursenaud** [comment]
The same is true for the antivirus commands at `htdocs/admin/security_file.php` (sic).
I successfully uploaded and executed a script.
It's still executed with the PHP server privileges which should limit damages but is still enough to access and modify privileged data available to the server process.

**Comment by rdoursenaud** [comment]
Oh and of course the cron job module `htdocs/cron/list.php` allows similar behavior.

**Comment by eldy** [comment]
@rdoursenaud If you can upload a script, why no uploading directly a php page to execute code of your choice. You don't need to use the reported "hole".

The dolibarr "admin" user is the user that is granted permission to admin dolibarr, so to decide which unix command to use to make dump, or antiviruscan. So yes, this user is able to decide to run a linux command that is not a dump or antivirus.
If we want to change this and decide that admin can choose the antivir command or the dump command among only 2 programs and not a third one, this can be protected only at the OS level.

Another solution is to introduce an option into config file conf.php, for example called
"dolibarr_admin_cant_admin_cli_command=1"
to say the "admin" has no permission for setup this related to filesystem commands, but currently being able is the expected behaviour.

**Comment by marcosgdf** [comment]
But if the cron module allows similar behaviour I don't really think this is avoidable… Even if we don't allow the final user to modify it, an attacker could enable a 3rd party module and do the same thing…

**Comment by rdoursenaud** [comment]
@eldy The problem is not that we allow administrator to run commands. The problem is that we allow him to run **arbitrary** commands. And this always is a security vulnerability.
I believe the mysqldump and clamscan commands should be checked and validated before being accepted.
Cron are a different matter, because it's their whole purpose and they need (some) server privileges anyway.

**Comment by eldy** [comment]
What is difference between command and arbitrary command ?
By definition the admin user in dolibarr is the user that is allowed to make maintenance on dolibarr, so able to do everything on it. 
Checking mysqldump command is useless. If you allow a user to 1) run an external unix command + 2) you allow user to add command on unix side, it means you allow it to run any command. The only solution to block the 1) is to provide an admin profil not allowed todecide which admin tool he want to use at all (we don t want this, this is no more an admin user, or it is just a second level admin so a standard user) or to restrict point 2), to define which unix command the user can run. But point 2) become no more a problem into dolibarr but a default into your os setup. Selinux for example solve this lack of linux os.

So if a user can login as admin, yes he can decide which command to run (with restriction on os permission), this is done on purpose. We want admin user to choose its admin command to run. So not a hole, just an authotization provided on purpose.

**Comment by hregis** [comment]
this is the "server administrators" to ensure that the www-data or other user is restricted to certain commands. This requires configure "sudo" correctly. I do not see the point of adding a right and more particularly to an administrator!

http://www.linuxpedia.fr/doku.php/commande/su_sudo

**Comment by eldy** [comment]
A parameter $dolibarr_main_restrict_os_commands were introduced into previous version to limit command user can run to do a backup. This allow a sysadmin to manage apparmor or other security systems on a more restricted list of commands.

**Comment by priyankn** [comment]
This fix can be bypassed and it doesn't concern the configuration of available commands.

I have a PoC, let me know how/where I can share this confidentially?

**Comment by eldy** [comment]
You can send your POC to security@dolibarr.org

**Comment by priyankn** [comment]
I have sent the details over, please check.

Also the following CVE IDs was assigned to this Issue: **CVE-2019-11200**
