### ISSUE TITLE
[WIP] Support printing extrafields on documents

### ISSUE THREAD

**Issue by rdoursenaud** [Dolibarr/dolibarr#4410]
Some extrafields may be needed on documents (PDF, OTD…) but others only for internal data.

Tentative implementation:
- [x] Add a boolean "Printable" property to extrafields
- [x] Modify interfaces to allow setting this
- [ ] Modify PDF documents to display these extrafields if the property is set
  - [ ] Customer proposals
    - [ ] azur
  - [ ] Customer orders
    - [ ] einstein
    - [ ] proforma
  - [ ] Supplier proposals
    - [ ] aurore
  - [ ] Supplier orders
    - [ ] muscadet
  - [ ] Supplier invoices
    - [ ] canelle
  - [ ] Customer invoices
    - [x] crabe
    - [ ] crevette?
  - [ ] Expeditions
    - [ ] merou
    - [ ] rouget
  - [ ] Interventions
    - [ ] soleil
  - [ ] Contracts
    - [ ] strato
  - [ ] Projects
    - [ ] baleine
    - [ ] beluga
  - [ ] Member
    - [ ] standard
  - [ ] More?
- [ ] Modify ODT document generator?

This is a work in progress.
Please test and comment!
Source code is available at https://github.com/GPCsolutions/dolibarr/tree/dolibarr-pdf-extrafields

If you want to contribute, you are very welcome!
Just pick a task in the list and comment below to let us know.

**Comment by BebZ** [comment]
Extrafields and custom fields are different, why not merging custom fields module inside dolibarr as it has a lot of documentation and powerful functions built-in  (constrained fields, etc...) ?
Just a general comment as always... but implementing the print of extrafields is already a so big answer to so many problems always reported on forums.. 
Thanks, Santa Raphaël !

**Comment by rdoursenaud** [comment]
Thanks @BebZ. I'm not familiar with the custom fields module at all. What does it provide that extrafields does not?

**Comment by BebZ** [comment]
Implementing of fields is already very detailed : 
https://wiki.dolibarr.org/index.php/Module_CustomFields_FR

and dev doc is awesomely detailled too : 
https://wiki.dolibarr.org/index.php/Module_CustomFields_Dev

the repo of lrq3000 (stephen larroque)
https://github.com/lrq3000/dolibarr_customfields

with detailled readme

**Comment by defrance** [comment]
ODT are already capable to display extrafields on document (fill_substitutionarray_with_extrafields in commundocgenerator class)
in pdf the main problem is to define where display the fields (top, bottom, ...), think it's définitly a specific development or we need to develop a complete customising pdf builder feature...

**Comment by eldy** [comment]
@rdoursenaud Why introducing a property "printable" ?
Any fiedls (extrafields like other) are already available into pdf and odt templates. It is goal of template to decide which data is output.
A future version will introduce a PDF generator that accepts tags like ODT do. And extrafields are already available for substition into core code for PDF like it is for ODT..

**Comment by BebZ** [comment]
I think he wants to make it accessible to most of us, not only the developpers...
because there are many questions about how to print an extrafield, or any other field on a pdf, the answer is given on the wiki I guess, but not many understands how...
So I think it is a "democratization" process of printing fields...

**Comment by defrance** [comment]
I think is not the good way to say if the field is printtable in pdf or not (in odt is allway printable)
But display extrafields in pdf is a good enhancing feature

we need to remember a little the architecture of a pdf
we have many parts
- right header
- bottom header
- information bottom page
- totalisation bottom page
  ...

For me, the "killer" feature is to add a dropdown list in extrafields to select where we want to display the extrafields in the pdf parts

my 2 cents

**Comment by rdoursenaud** [comment]
Thanks everyone for the feedback.

@eldy The idea is to natively provide users a simple way to "display" their extrafields to predefined positions in documents.
Most of the users (well, err, clients…) I met have two kind of extrafields:
- internal data records for their eyes only
- public properties they want displayed on their documents

The "printable" property tries to reflect that.
AFAIK there is no facility to easily print extrafields data in Dolibarr generated PDFs at the moment.
Of course the data is available to my smart fellow developers but integrators and users alike need something a little more "usable" ;)

As for the future PDF generator, I didn't knew that. Is this something public?  Did I miss the roadmap? Is there a spec?

@defrance The idea is to provide a generic feature to avoid custom developments as much as possible.
The current implementation displays "global" extrafields just where the public note would be or below it if it's set and "line" extrafields just below the description.
The code is here for you to see:
https://github.com/GPCsolutions/dolibarr/commit/a2536742c8afcd1c2f6965b9d4267295a3175c4a

I have no interrest in providing a PDF template editor/generator but if someone wants to tackle that, go ahead!

**Comment by defrance** [comment]
Custom development is what makes live ... and allows us to create an itegrator community who's promote dolibarr better than we ...
ODT and PDF native are two easy solutions but I think they are a 3rd track, That's why I will present 'myPrint' at next devcamp.

**Comment by lrq3000** [comment]
This post is a bit long, so please bear with me, I think the information here are pertinent to the discussion.

I am the developer of CustomFields. Initially, the module was created when ExtraFields didn't really exist (it was partially supported for only one or two modules, Dolibarr v3.1 IIRC). ExtraFields has evolved a long way already and proposes features that CustomFields do not (but the opposite is also true).

The main problem in merging the two modules is that they have completely different philosophies: ExtraFields was made as a prototype class that you could attach to any module that wants to support extra fields. This means that each module needs to implement this class, and somewhat manage the extra fields (at least the bits that aren't managed by ExtraFields).

CustomFields was first designed somewhat like that, but after the Dolibarr developers advice to take advantage of the new hooks system to extract it from the core modules, I decided to totally revamp the module to make it almost completely independent from Dolibarr, and turn the implementation of extra fields upside down: you just need to define what modules you want to support in CustomFields configuration, and the modules get supported. The modules do not have to make any change, except support  the hook system (ie, place somewhere a placeholder for additional contents provided by 3rd-party modules). Even 3rd-party modules can add the support of CustomFields this way, without needing to learn anything about how CustomFields will then manage their custom fields (the learning curve is non-existent, whereas to integrate ExtraFields you need to learn how the class works and how to manage extra fields).

In the end, we have two technically different modules: ExtraFields is tightly coupled with Dolibarr, while CustomFields is quite remote. Both have advantages and cons: ExtraFields benefits from more freedom in the display and the manipulation it can make on the Dolibarr display, and also has access to more parameters ; whereas CustomFields is very constrained and cannot freely modify Dolibarr's display but it's quite easy to maintain because adding a new module is just a few additional lines in a configuration file (hence why I could maintain it over all these years and still support most if not all core Dolibarr modules, all by myself).

However, I think that it's possible to attain a middle ground: having a semi-constrained system implementing the best of both modules. This way, it would benefit from a real integration with Dolibarr just like ExtraFields but not so tightly coupled as it is now, making maintenance way more easy similarly to CustomFields. But this would involve not just a merge of both modules, but a major effort to rewrite a new library based on the lessons learnt from both experiences...

**Comment by lrq3000** [comment]
About the integration in PDF, I think that the idea of constraining the display of extra fields to specific areas is horrible. Lazy or neophyte integrators already use the ODT templating with the amazing tag system, and this allows free placement of the tags anywhere they want.

From my experience, people use the PDF templating for more advanced customization. Constraining them to a few specific spots will certainly not fit this kind of needs. That's why I preferred in CustomFields to just provide easy methods to fetch the custom fields content and then they can print it anywhere they want, as long as they know a bit of programming and the TCPDF doc.

**Comment by eldy** [comment]
Support of extrafields should be available in v12.
New property "Display on PDF" has been introduced into extrafields
