### ISSUE TITLE
DIscussion : How do you manage levels of packagings ?

### ISSUE THREAD

**Issue by BebZ** [Dolibarr/dolibarr#4493]
Hello Community ;)
How do you manage levels of pacaging on your products ? 

For example you can buy per carton to your supplier (easy for him, good price for you) 
but you sell the boxes to your customers...
but you can also sell the unit that is in the box... 
or buy a pallet to your supplier and sell the units to customers...

Sometimes it is really messy and tricky to know what price to put in the product's supplier price
and the product's customer price... (because if it's wrong your virtual margin is wrong : the buy price of a unit is the one of a carton/pallet)

There is no way to handle that more clearly ? And also if it is clearer, it will be more comfortable to remember the numbers of units in a box, and the number of boxes in cartons, and the .... blablabla...

**Comment by casati-dolibarr** [comment]
"Stock" the total number of smallest unit of the received delivery?

Then create "products for sale" in number of units?

**Comment by rdoursenaud** [comment]
I'd classify that as a feature request.

Dolibarr doesn't currently provide a streamlined workflow for that use case.
This is a management problem that is not easy to solve because there are various ways to do this.

I think the first step is to define the "storage unit".
Ie. for that product, what's the unit I stock and sell. Is it a single item, is it a box…
I'd use the smallest subdivision I actually handle. Be it by buying, managing it in stock or selling it.
Ie. single items.

From there, I'd use "virtual" products to create the greater containers.
Ie. Box is 10 single items, shipment box is 10 boxes and pallet is 10 shipment boxes.

Then I'd use these to place my orders.

I believe some code needs to be written to help with receiving the orders and breaking the virtual products into the "storage unit".

Needs more thought…

**Comment by BebZ** [comment]
I thought also of virtual products, but when I sell a Box of 10 it doesnt count as 10 units of a single item... everywhere in Dolibarr...
Packaged virtual products should have some automatic behaviour of converting greater units in smallest unit saleable, or something like that.
Or maybe it should only be a stock related info...

**Comment by accett** [comment]
Can the module Composite product solve this?

2016-01-25 16:08 GMT-06:00 BebZ notifications@github.com:

> I thought also of virtual products, but when I sell a Box of 10 it doesnt
> count as 10 units of a single item... everywhere in Dolibarr...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/issues/4493#issuecomment-174689713.

## 

Gracias por no enviar cadenas.
Ing. Víctor Ortiz Pérez
AcceTT - Soluciones Computacionales
Mártires 28 de Agosto #134 esq. Ruiz Cortines
Col. Ferrer Guardia Xalapa, Veracruz CP 91020
Tel. (228) 840 3284
WA 228 840 3284
victor@accett.com.mx
www.accett.com.mx
