### ISSUE TITLE
Error Margin module (price / reduc) 3.8.3

### ISSUE THREAD

**Issue by FAPMLIL** [Dolibarr/dolibarr#4497]
Hi, 

Dolibarr 3.8.3

I encounter a problem when I apply a discount on an item

Example below.

It increases my PU HT when I apply a discount

![prixv1](https://cloud.githubusercontent.com/assets/16575944/12570542/bea05676-c3d8-11e5-95a2-0fc46d1629d5.png)

![prixvrem1](https://cloud.githubusercontent.com/assets/16575944/12570549/c62b6f8e-c3d8-11e5-8947-4f4fae8818cf.png)

I tried with -10 instead of 10 it's worse.

![ko](https://cloud.githubusercontent.com/assets/16575944/12570550/cae94ca8-c3d8-11e5-954c-4eb824634506.png)

**Comment by FAPMLIL** [comment]
It increases my PU HT

**Comment by BebZ** [comment]
where does it happen ? proposals ? orders ?

**Comment by FAPMLIL** [comment]
in Proposals, orders ...

**Comment by FAPMLIL** [comment]
Module margin activate

**Comment by FAPMLIL** [comment]
???

**Comment by BebZ** [comment]
OK i see, no need to remind me everday with "???" you are not on a paying hotline here... and my answer is not guaranteed.
i already reported it on french forum long time ago... and also maybe on github. 
Since, I use a module from ATM to recover last invoiced price to customer, so i dont have the problem all the time... but still, it happens, so I use very rarely a discount on my documents...
Maybe we need some explanation from the module developper of Margin ? @altatof

**Comment by FAPMLIL** [comment]
Sorry ;)
Yes indeed, because the margin module is no longer functional since version 3.8

**Comment by altairis-tof** [comment]
i think you should ask @eldy who made changes for pmp support on margin module on 3.8 and it seems that the problem appeared on this release.

**Comment by FAPMLIL** [comment]
Thanks :+1: :)

**Comment by eldy** [comment]
This looks a very old bug/behaviour. If you edit field to enter a discount, price will be recalculated.
Because margin is already set, it is used for reclaculation and it is unit price that is changed.
Can you try to edit field, add your discount and clear the field margin to ask dolibarr to recalculate margin instead of unit price. Is it ok now ?

**Comment by FAPMLIL** [comment]
Thank @eldy :) It's ok for me :+1:
