### ISSUE TITLE
Feature Request: HTML5

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#4593]
Dolibarr v3.8.3

Can it be compatible with HTML5 to speed up page display?

**Comment by rdoursenaud** [comment]
HTML5 has nothing to do with speed. Your webserver is doing the work.
Dolibarr already experimentally support some HTML5 features like the cache manifest : https://wiki.dolibarr.org/index.php/Setup_Other#List_of_known_hidden_options
A complete HTML5 rewrite won't happen anytime soon because of the huge workforce required (which we don't have) and no short term benefits.
