### ISSUE TITLE
Feature Request: Supplier Ref/Global Discount/Refund on Invoice Line

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#4624]
v3.8.3

When creating a supplier order the supplier reference should be shown (it's not) or have an option to enable it so we can decide to show it or not. - **_I think this is proposed for v5.0_**

When creating a supplier order, the product description should not be shown (it is) or have the option to enable it so we can decide to show it or not.

When creating a supplier order, the dicount percentage is shown per line per product. There should be an option to apply a global discount to the order whether amount or percentage.

If these were options we could enable/disable in the admin, it would help a lot.

**Comment by aljawaid** [comment]
v4.0.2

As an update...

The supplier gives me a 15-20% discount on the total value of the invoice.  At the moment I apply it as a 'service' type line with the value and then a 200% discount.

After doing that for many months, it would be nice to see a button where i can add a perentage OR a value which will show on the invoice line as a (translated) discount and be deducted.  The same would be nice as a refund (for any product refunds)

**Comment by BebZ** [comment]
My 2 cents : 
If you wish to apply discounts that would also apply on the product (buying) price in stock 
(Average Weighted price or PMP in french) 
you have to apply the discount on a product line, instead of doing a last line with a discount 200% or negative line.
For refund, or negative invoices i use a "negative" line with negative qty, but as I manage sotcks with manual dispatch it doesn't reflect in a stock movement, so I have to make manual negative movement after validating a refund with products sent back to supplier.

There is a module in crowdfunding for refunds and products back to the supplier... see with zendsi.com
https://shop.zendsi.com/dolibarr-financement-participatif-2017.html
