### ISSUE TITLE
Bug: Deposit payments are shown as "Interbank payment"

### ISSUE THREAD

**Issue by marcosgdf** [Dolibarr/dolibarr#4750]
# Bug

Payments registered in 3.7 version as "Deposit" are now shown in 3.8 as "Interbank Payment"
## Environment
- **Version**: 3.8.3
- **URL(s)**: /compta/bank/releve.php

**Comment by eldy** [comment]
Error was probably in 3.7: Having a payment type "deposit" has no sense. You can enter a payment for a deposit invoice but for a payment in cash, there is already the payment mode "LIQ/cash" and "VIR/bank deposit". So the entry "Deposit" with code TIP looks to be a bad label that was fixed with 3.8 into "Interbank Payment Ticket" (a payment mode done with a paper transfer, used in france called "TIP").
This is annoying for people who used it in 3.7 or lower but we should remove the type TIP that is required to replace it with a payment mode that already exists into another entries.

**Comment by marcosgdf** [comment]
In Spain having a payment type named "Deposit" has sense. It is a different payment method than bank transfer and cash.

The customer can go to a bank branch and say "I want to deposit 1 000 € into this account". That kind of payment is not either cash or a bank transfer.

If everyone that was using 3.7 were using "TIP" for "Deposit", why changing it everyone? Why not creating a new TIP2 label for that "Interbank Payment"? This is a very annoying regression…

**Comment by simnandez** [comment]
This issue is on an old version. It is very likely that this problem is fixed in the new versions. If no, please re-open a issue
