### ISSUE TITLE
Bug: Generate button file documents

### ISSUE THREAD

**Issue by esgarbal** [Dolibarr/dolibarr#5251]
# Environment
- **Version**: 3.9.2
- **OS**: Linux
- **Web server**: Apache/2.2.22 (Ubuntu)
- **PHP**: apache2handler 5.3.10-1ubuntu3.21
- **Database**: MySQL or MariaDB 5.5.47-0ubuntu0.12.04.1-log
- **URL**: /contrat/card.php?id=200
# Report

When you modify the contract can't not rebuild the document with the new values, the button doesn't appear to generate.

**Comment by atm-maxime** [comment]
I think that your contract pdf model is not active, that's why you can't see it and generate.
Not a bug for me.

![image](https://cloud.githubusercontent.com/assets/2097773/15793086/e9988d98-29e1-11e6-9d01-9e88ebde2d52.png)

![image](https://cloud.githubusercontent.com/assets/2097773/15793045/b06be77c-29e1-11e6-8ac3-3c4a3aa8b372.png)
