### ISSUE TITLE
Bug: Field type entreprise not displayed after importation

### ISSUE THREAD

**Issue by mikygee** [Dolibarr/dolibarr#5341]
Version: 3.9.2
Browser: Firefox 43.0.1

Hello,
Some fields are not displayed after importation: Start Up, Grossiste, Revendeur
However they exist in the llx_c_typent table

So I guess they should be either:
- displayed
- or removed from the llx_c_typent table

You can try to import these companies, then go to the GUI and edit startup, grossiste and revendeur
[Dolibarr-Bug_Import_Type_Societes-11Jun2016.txt](https://github.com/Dolibarr/dolibarr/files/310208/Dolibarr-Bug_Import_Type_Societes-11Jun2016.txt)

**Comment by atm-maxime** [comment]
Hello,

By default in Dolibarr, these 3 company types are in llx_c_typent but are not active. So they are not available in the dropdown list. If you import the file with these values, it will be correctly imported, but not displayed because not active.

Can you check in your dictionnary if these are active ?

**Comment by mikygee** [comment]
Hello Maxime,
What you say is correct. I imported the file with these values and they were not displayed.
In GUI, they don't appear as a choice (they're not active)
I didn't know about the dictionnary.
I'm closing this case since everything works as expected.
