### ISSUE TITLE
[Feature Request] Using package product with lot/serial physical product 

### ISSUE THREAD

**Issue by mfaroukg** [Dolibarr/dolibarr#5342]
# Bug

stock managment for sub products with lot/serial number enabled not getting changed with order of the parent virtual product.
## Environment
- **Version**: 3.9.X
- **OS**: Ubuntu 14.04.4 LTS
- **Web server**: apache2  2.4.7-1ubuntu4.9 
- **PHP**: PHP5 5.5.9+dfsg-1ubuntu4.17
- **Database**: mysql 5.5.49-0ubuntu0.14.04.1
## Expected and actual behavior

I created 4 different physical products dummy01, dummy02, dummy03, dummy04 and the virtual product dummy00 which is consists of certain weight and numbers of the subproducts. when i populate the dummy01-04 with some stocks, some behavior is not convincing :
1- dummy00 does not increase  according to the ratio of the increased sub stocks increase. i have to do it manually (since it gave me error can't order).
2- when i order dummy00 in customer order dummy01-04 follow the decrease in the stock except the stocks with lot/serial number they don't change.
3- for stocks with no lot/serial number stocks can go -ve to allow the order to be issued.
4- no alarm for the sub products dummy01-04 that the stocks are not enough.

**Comment by BebZ** [comment]
Please first check it works or not without lot/serial number. 
If not, it will not work with the lot/serial number module by magic...

**Comment by mfaroukg** [comment]
@BebZ thanks for reply 
Yes it is working with none lot/serial as mentioned in point 2.
Still have issue with parent stock increase manually, lot/serial products no change with parent change, no alarm for stocks running short and child products can go -ve stocks.
If you want to reproduce the issue you can follow the steps i mentioned above.

**Comment by BebZ** [comment]
Could you please send some screenshots of the steps described ? I will try later to reproduce it...

**Comment by mfaroukg** [comment]
Hi, 
please check the attachment.
I think there is something need to tell the parent that the children are satisfied to increase its stock or when we increase the parent stock manually should not increase the children. 
As this is grayed in the stock module settings due to the lot module enabled i can't stop increasing children stock when i increase parent.
[bug-report.pdf](https://github.com/Dolibarr/dolibarr/files/312570/bug-report.pdf)

**Comment by BebZ** [comment]
Ok, the first point, is an already reported subject, and Dolibarr can't handle it at the moment, because physical stock of package products is not dynamical, or not re-calculated, each time child-product has a movement. Maybe necessary to open another Issue for this, named : physical stock of packaged products not changing when movements on childs.

For the second point, it is surprising that on the shipment screen it doesn't display the serials to ship.
I think it's a small modification that @KreizIT or @fappels  can handle if you know them...
I will ask my intern developper but i'm not sure he knows these functions.

**Comment by mfaroukg** [comment]
Thanks for the reply, i will wait till you plan for point 1 i hope soon.
I had find before someone trying to do this through one of the extensions in dolistore did you see this and is it the thing i asked? 
for the point  2 @KreizIT  @fappels could you update?

**Comment by mfaroukg** [comment]
@BebZ I am searching among the old cases and i saw  case  #3116

**Comment by mfaroukg** [comment]
@BebZ @fappels @KreizIT   when i make order for product with more than stock available it gives me error, but when i order within the stock available it give me no issue EVEN with multiple lines of orders for the same product with total exceeding the stock , this is really a bug!

**Comment by mfaroukg** [comment]
Any progress in the lot/serial relation with stock and POS and any fixing ?

**Comment by BebZ** [comment]
Sry no, I'm not a dev.... I can just confirm and report

**Comment by mfaroukg** [comment]
Dolibarr is a great application and the people developing it are awesome and i wish they can reach the maximum standards to fulfill all customer requirements, right now it is reaching to 90% of average users and there still some essential line of interest needed to be touched since it is daily professional business requirements like packing and manufacturing and using serial numbers and lots so I am asking if there an activity in that line in any dev interest.

**Comment by mfaroukg** [comment]
Any feedback?

**Comment by BebZ** [comment]
I am surprised, others @fappels  don't reply to you with a quotation. 
if you at least need this for business reasons,
... you should allow a budget for its development.

Please tell us what is your budget, then maybe you will get an answer. 
This is not a place to post "up" "up" and again... just to get "code"... 
A bug would be solved, a new functionnality has to be financed or volunteered, and if no one answered you Positively. It means no one can volunteer, and that you need to allow a budget.

**Comment by BebZ** [comment]
"Sub-products lot management" is a NEW feature ;) just to be more precise.
You can create your scenario on https://demo.dolibarr.org/product/reassortlot.php?type=0&leftmenu=

and try if it happens and if it happens, send us screenshots and the URLs and then we can maybe make a common project to dev it.

**Comment by atm-maxime** [comment]
Was with a customer today who has this issue. Needs to deal with serial numbers and virtual product. After some tests, when shipping the virtual products, sub-products stock with no serial management are correctly decreased, but sub-products with serial management are not.
The improvement will consist in asking for serial numbers of sub-products in the shipment.

**Comment by BebZ** [comment]
True. It is the same here, i use virtual products without serial management  (I increase them manually) 
and I decrease manually the products with serial management. This is a shame and we should work on it :)

I will speak to my dev maybe he can find the way to put in the loop the serials of sub-products, which should'nt be complicated at first sight ;)

Are you ready to test it and review development / correct it ?

Thanks

**Comment by atm-maxime** [comment]
Ok, I'll try and test it no problem.

**Comment by fappels** [comment]
Sub products are not stored in the expedition tables, so it will be necessary to find a way to store the sub product serials into the database.

**Comment by BebZ** [comment]
Today I am facing the same problem, maybe we will develop a solution ourselves based on Francis's very useful remark : store sub products in shipping tables ;) 
or maybe add a function to store as many child as need for X parent products (from the virtual products view) in a "temp" table to increase the parent product's stock virtually, make a movement on child to withdraw child's from stock) and then make it able to send it all Parent and Childrens :package: looks simple at first sight/thought.

**Comment by prietojc** [comment]
Is it the same for me. Managing lot/serial of subproducts doesn't work. Not only with expedition, even transfering to other warehose is worst. Should move parent product and its childrens. 

Thinking about that issue, my best approach is to use a [future manufacturing module](https://github.com/Dolibarr/dolibarr/issues/5824), for packing or factoring.

The virtual products has a lot of problems, storing movements of subproducts became a headache, but if we manufacture a product, the materials (subproducts) are deleted from store because they are transformed in a new product which is created.

**Comment by prietojc** [comment]
Is it the same for me. Managing lot/serial of subproducts doesn't work. Not only with expedition, even transfering to other warehose is worst. Should move parent product and its childrens. 

Thinking about that issue, my best approach is to use a [future manufacturing module](https://github.com/Dolibarr/dolibarr/issues/5824), for packing or factoring.

The virtual products has a lot of problems, storing movements of subproducts became a headache, but if we manufacture a product, the materials (subproducts) are discount from store because they are transformed in a new product which is created.

**Comment by prietojc** [comment]
Keep in mind: 
- Virtual products should not have any stock, that stock **belong** to their childrens. However Dolibarr manages virtual products as standard ones. When you look at product quantity of a warehouse, the list shows the pack and its components, it seems like we have double items!!
- Maybe using virtual products as services (which not have batch neither stock) could be useful without problems.

**Comment by BebZ** [comment]
If we want to ship virtual products, we should manage a stock of them.
That's why we made it possible to "decrease" sub products from virtual product card, being able to choose what sub product batch and qty should be in the virtual... 
So if sub products are booked for a virtual product, their stock is decreased, and in a second time we increase the virtual product stock with an internal batch and shortest expiry date (of a sub product).
Because if you want to ship a virtual product that has no stock, and depends on its children's stock you will have to choose the batches you put in the virtual product at the time of shipment (so you can't book in advance the sub products stock for the virtual)...
It is more like an "assembling" module. 
For example if you make a promotional virtual product (2 chickens bought, one pack of salt offered) with : 
- 2 chickens (you have 4 chickens in stock with batch A, B, C and D )
- 1 pack of salt ( you have 3 packs of salt with batch S, T and U)
(you say in the limit of the stocks available)

You also sell the chicken and the salt by unit

So if you have 3 orders : 
2 promotional offers and 
1 chicken by unit 
you won't have enough stock of promotional offer (namely : chickens)...
if you did not book the promotional offers before.

Maybe the logisitcs will send 1 promo offer and 1 chicken by unit instead of the 2 promo offers...

I hope I made a clear enough example :package:

**Comment by prietojc** [comment]
Right **Bebz**,  I tried to solve the issue of shipping virtual product, but I found several problems:

- I can't group subproduct with standard ones for booking their batch. I can't know in advance if have enough stock. Maybe using a recursive function, it seems complicate.
- I realized that transfering is even worst. What move? If I move just virtual products, then I won't able to ship them, because I have not stock for children. If I move parents and children, I won't know my stock (Have I just a virtual product or  one virtual and several single items?).

This is my decision: too complicated, I will use a factory module. (Even this module will have the challenge for managing the batch of subproducts, but it is easier because the built product doesn't repeat components, it's just quantity).

Many thank for your aproach.

**Comment by BebZ** [comment]
What do you produce or assemble "basically" ?
Our approach was to refactor the virtual products module and make it "factory-like" but with compliance of batches of sub products in stock (because with a factory you have to re"create" the sub prods batches....)
it was a double task we wanted to avoid to our teams ;)

**Comment by BebZ** [comment]
We remade virtual product card and could name it virtual product "composition" 
it took much time to us, but we use it on production environment since 6 months now, 
and we can make quite serious traceability (it was audited by a quality-specialised company).
It is off course based on Dolibarr's Core (9.0.2) no core files have been changed. 
IF we make a PR for 10 (closed ?) or dolibarr 11,
 can you tell me if yes or not you will have time to review it ?

This virtual product "composition" is the basic step towards a real manufacturing based on Dolibarr's Core : picking products in stock to "reserve" it for immediate or later production.
It handles : 
"calculations" based on how many pieces are necessary to make a virtual product and how many virtuals you want to produce
"movements" + or - (if composition has to be changed) 
"stickers" to have a "pick list" of the products with serials to make the virtual
"virtual batch numbers" when your composition is finished you can add it to stock with a "new batch number" (link between new batch and batch composing the virtual is on card, or in database)

Off course it decrease sub products stocks if chosen
and increase it if you wish to change qty of subproduct or batch of subproduct

And many other little useful tweaks.
like handling reservation of sub-sub-products with a sticker of composition, subcomposition, subsubcomposition :)

**Comment by cfoellmann** [comment]
@BebZ do you have a working module for this?
Would be very interesting to me

**Comment by BebZ** [comment]
Yes it is in production since 1 year and half, with no major bugs :)
Do you have an e-mail ? or I joined you slack ah att fm medical

**Comment by sneznaovca** [comment]
Hi, any news? I am interesting about your module @BebZ is it possible to try it or use it?

**Comment by BebZ** [comment]
Sorry guys @cfoellmann @sneznaovca 
We are in a quite serious period for our company (medical business) 
I won't have time yet to compile everything and send you...

Do you have an email if I find time in the night to send it to you ?

**Comment by sneznaovca** [comment]
@BebZ pavol@sivy.net thanks

**Comment by prietojc** [comment]
I think this request is still relevant and version 13 not yet cover.
