### ISSUE TITLE
Associer paiement TVA à une année pour avoir une balance TVA réelle et correcte

### ISSUE THREAD

**Issue by mmorelon** [Dolibarr/dolibarr#5365]
# Feature Request

Associer paiement TVA à une année.
## Use case

Il serait bien de pouvoir saisir l'année correspondante à un paiement ou remboursement de TVA afin de pouvoir afficher un paiement sur l'année N-1 par exemple dans le menu TVA (balance TVA et TVA payée). Ce champs serait utilisé uniquement pour l'affichage dans le menu TVA et non pour les écritures bancaires.
## Suggested implementation

Ajouter une liste déroulante avec les années dans le formulaire paiement ou remboursement de TVA.

**Comment by BebZ** [comment]
A screenshot speaks more than french text.
A VAT payment MUST be linked to a FISCAL YEAR.
because you can pay VAT of year N on N+1 sometimes

![image](https://cloud.githubusercontent.com/assets/3694135/16143732/f0464206-346e-11e6-9179-629bb0c51c6a.png)

![image](https://cloud.githubusercontent.com/assets/3694135/16143781/4085c99e-346f-11e6-9fbc-e7c2fcbd3967.png)

can you also translate your msg ?
