### ISSUE TITLE
[docker image] missing "scripts" folder

### ISSUE THREAD

**Issue by eesprit** [Dolibarr/dolibarr#5612]
While evaluating dolibarr using the docker image (built from the Dockerfile present in the repo), I found out that the image only embeds the htdocs folder, and not the "scripts" one.

I don't really know the dolibarr architecture, but i am pretty sure that the absence of the "scripts" folder will be a problem at some point.

Can you tell me if i am right or if not ?

I see that there is a "cron" subfolder : cron jobs are pretty out of the scope of Docker, would a dolibarr instance still be functionnal without it ? What would it be missing ?
Same questions for the other subfolders (from where are they supposed to be called ? from the web application ? from CRON ?)

Thanks for your answers.

**Comment by rdoursenaud** [comment]
Since this don't really pertain to the issue tracker, you'd be better off asking in the [forum](http://dolibarr.org/forum). I'll answer here though since I don't use the forum myself…

Despite having played with it a bit, I'm not totally familiar with Docker, so please take everything I'll say with a grain of salt.

`scripts` are only used for maintenance purposes and supposed to be run from the CLI.
You can certainly use cron (or at, or anything else really) to call them if need be but this is not a requirement.
They are not needed to run Dolibarr.

`htdocs` contains all the main application code.

The only other directory you'll need is `documents` which holds uploaded and generated data (logos, PDFs, logs…).
It is created at installation time but can be set within `htdocs/conf/conf.php`.
I don't know how it is setup in the Docker instance but it certainly should be in a specific persistant data volume and/or container.

All other directories are used for development purposes and won't be needed by the application:
- build: tools to build the various releases
- dev: developers tools
- doc: documentation
- test: various tests (unit tests, SOAP API…)

**Comment by eesprit** [comment]
You're right that the forum would have been a better place to ask about that.
But as I was thinking of contributing potentials changes to the Dockerfile depending on that question, I asked here.

Thank you very much for your answer, it's making things a little more clear.

And you are right about the volumes for documents and conf, I made a PR about that 3 days ago : #5610
