### ISSUE TITLE
Module cron => cron_run_jobs.php (problem with get_default_tva)

### ISSUE THREAD

**Issue by altzone** [Dolibarr/dolibarr#5687]
Hi,
There is a problem on function get_default_tva when cron_run_jobs run Facture->create.

In cron_run_jobs.php line 30, there is 
`if (! defined('NOREQUIRESOC'))   define('NOREQUIRESOC','1');`
so get_default_tva return an error : 
`PHP Catchable fatal error:  Argument 1 passed to get_default_tva() must be an instance of Societe, null given`

because $mysoc is undefined.

so I have to comment out this line for the generation of invoices by the cron works.

**Comment by loxK** [comment]
@eldy can you reopen this please? 

The bug occurs when calling cron from url "htdocs/public/cron/cron_run_jobs.php" and still exists as of 5.0.2.  Running the same task from the script (scripts/cron/cron_run_jobs.php) has no issue.

To reproduce, create a predefined invoice due to generate an invoice and call then then call the cron url.
Here is the full error message:

```
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to get_default_tva() must be an instance of Societe, null given, called in /srv/dolibarr/htdocs/compta/facture/class/facture.class.php on line 626 and defined in /srv/dolibarr/htdocs/core/lib/functions.lib.php:4124
Stack trace:
#0 /srv/dolibarr/htdocs/compta/facture/class/facture.class.php(626): get_default_tva(NULL, Object(Societe), NULL)
#1 /srv/dolibarr/htdocs/compta/facture/class/facture-rec.class.php(853): Facture-&gt;create(Object(User))
#2 /srv/dolibarr/htdocs/cron/class/cronjob.class.php(969): FactureRec-&gt;createRecurringInvoices('')
#3 /srv/dolibarr/htdocs/public/cron/cron_run_jobs.php(152): Cronjob-&gt;run_jobs('gecka')
#4 {main}
  thrown in <b>/srv/dolibarr/htdocs/core/lib/functions.lib.php</b> on line <b>4124</b><br />
```

@altzone found the fix
