### ISSUE TITLE
Feature Request: dynamic category types

### ISSUE THREAD

**Issue by maikaspanring** [Dolibarr/dolibarr#5899]
# Feature Request

The category types are static and can not be used in other modules to add category types.

The same problem is in the viewcat.php. 
Only the static types can be shown.
Without a hook it is impossible to show other modules category types

So the question here is: 
Why are they static and is there any plan to let other external modules add category types?
## Use case

Adding categories in the future would be much simpler.
External modules can add category types.
External modules can display their categories.
## Suggested implementation

Possible implementation would be to add the types to the database so other modules can add category types there.

In the viewcat.php the best practice would be to add a hook for other category types.
## Suggested steps
- add a table or use an existing table to handle category types:
  - rowid, name, foreign_keys, categorie_table, object_class, object_table
  - example:
  - 1, 'product', 'product', 'categorie_product', 'Product', 'product'
  - 2, 'supplier', 'soc', 'categorie_fournisseur', 'Fournisseur', 'societe'
- remove the const types in the categories.class.php and add a fetch method for category types.
- add a hook in the viewcat.php for other modules to handle their category types.
- for backward compatibility the values of the table could be fetched to define new cons variables. As well as adding the values to the MAP arrays.

**Comment by rdoursenaud** [comment]
I've been doing some of the categories code refactoring.
The types are static because we were only using it for core modules and we kept it as simple as possible.
Opening up categories management to external modules is a very good idea.

About the design, I don't think that the database is required for types management? Can't we just generate this at runtime from module metadata? This should have less overhead than database requests.
Of course a database storage model will still be needed for the categories data ;)

Looking forward to your contribution.
