### ISSUE TITLE
Weak password management in user SQL table

### ISSUE THREAD

**Issue by ygini** [Dolibarr/dolibarr#5950]
# Bug

Password are stored in SQL database in clear text + simple MD5. This is useless and a big risk for all Dolibarr users.

Any small vuln in Dolibarr will lead to a password leak on targeted company.

Since most company will allow remote access to Dolibarr, this is a really dangerous problem.

Also, the pass_crypted use a md5 hash (small terminology error, the password isn't encrypted but hashed when using md5). Using md5 without salt is also a bad idea, rainbowtables exists.

## Environment
- **Version**: 4.0.2 and previous version
- **OS**: Debian 3.16.7-ckt20-1+deb8u2
- **Web server**: Apache 2.4.10
- **PHP**: PHP 5.6.27
- **Database**: MySQL 5.5.52

## Suggested implementation

To avoid such a weakness, you're supposed to use PHP crypt with salt or password_hash.

**Comment by eldy** [comment]
You probably miss something during install or in your setup. Password are already saved using hashing functions. Did you migrate from a very old version ?

**Comment by ygini** [comment]
Sorry for my late answer.

I didn't miss something during the install. The update wizard miss something.

As a simple recall, update process for Dolibarr is simple (as it should): upload new file and follow the configuration wizard.

I've started using Dolibarr in 3.8 if my memory is right.

Also, don't forget the second part of my bug report: broken crypto mean no crypto at all. A simple md5 to hash a password is not secure at all.

Use builtin PHP feature like crypt or password_hash to keep the end user safe.

**Comment by ygini** [comment]
I'm surprised to not see any reactions to this bug report. Update process is broken and current password storage is weak…

Maybe you should take this seriously?

**Comment by eldy** [comment]
As mentionned the 10 november, the bug you mention is already fixed since several month. Note that you can also set the hashing algorith to encrypt pasword with constant  MAIN_SECURITY_HASH_ALGO to value 'sha1' or 'sha1md5' that is combination of sha1 + md5.
php crypt is not as secured than combination sha1+md5

**Comment by ygini** [comment]
Yep, of course, the bug is fixed but still here… Wonderfull answer. If you say that you removed clear text password, and I say I've done all the update and still has my clear text after all updates applied, that mean you've a bug you your bugfix. That's all.

**Comment by eldy** [comment]
If you make a first install, you will see that clear password is not saved.
If you still have it clear, it probably because:
- it was kept for compatibility because you come from an old migrated version (if yes, just clear it)
- you set the option to keep the clear password for compatibility purpose (menu home - setup - security). If you don't need it anymore, disable it. If you still have it, just clear it manually. If setup is correct (set like for a new install), they will never appear again.
It seems other users does not suffer your trouble, that's why there is many feedback on this thread.

**Comment by ygini** [comment]
The option "don't store clear text password in the database" is enabled on my instance. So this feature don't do anything.

This option enabled I shouldn't have anything to do to get a rid of this clear text password (and the answer you made now should have been your first answer, previous answer you made was useless).

**Comment by SBA18** [comment]
Hi,
What @eldy saying is true, when this option is actived the password is not stored in clear text. I'm testing now the version 5.0.0RC1 and this option is enabled by default. Maybe the bug come from the update. Try to make fresh install for the latest version (stable or RC). Maybe MD5 is not the best secured system, better is to use salted password because one day I forget my password and I just go to the database and just change with new password and apply MD5 for stable structure and it works. Normally this won't happen if it was encrypted and salted at the same time. This is a security issue I admit.

**Comment by ygini** [comment]
OK! The @acericonia comment lead me to the solution. The setting UI in security section is misleading. The line has an "enable" (but in french) button at the end, but the button does not reflect the current state, it was the button to actually enable it. 

I didn't paid attention to the verb form so didn't notice the french term was describing an action instead of a state. This is my fault and I'm sorry for that. If I clic on it, clear text password are removed from the database as expected and a checkmark is added in the UI.

Maybe this part of the admin UI should adopt the same behavior as other part of Dolibarr and display a "-" instead of nothing when the option isn't enabled.

@eldy regarding php method, I told you php crypt with salt or even better, password_hash. This last feature will use bcrypt with salt for you and store it properly in a single field. The algo under the hood is the one created by Bruce Schneier. Using password_hash make you sure to always use the strongest hash method available, and the system is able to maintain compatibility with previous version of the hash. So when the security framework in PHP will evolve, Dolibarr stay to the top without any work to do on your side. It will always be better than anything you can implement by yourself.

**Comment by rdoursenaud** [comment]
@ygini If the text is misleading, you're very welcome to clarify it for your language.
Our translation system is at https://www.transifex.com/dolibarr-association/dolibarr/languages/
Thanks for your contribution!

**Comment by marcosgdf** [comment]
I guess this issue can be closed now

**Comment by dpriskorn** [comment]
Are we using password_hash as suggested now? If not I think we should reopen this and switch to it.

**Comment by DanielRuf** [comment]
@egils-consulting see https://github.com/Dolibarr/dolibarr/search?q=password_hash and https://github.com/Dolibarr/dolibarr/pull/8063

**Comment by DanielRuf** [comment]
> You probably miss something during install or in your setup. Password are already saved using hashing functions. Did you migrate from a very old version ?

In my case I have used the autoinstall feature as it seems. The option to hash (not encrypt) passwords was not enabled by default.

So there might be some issue with the installer probably (default value for hashing passwords).

https://github.com/tuxgasy/docker-dolibarr/blob/81bf31ccc5a3d9f6bd72ec03ec4a2ef9d3821a05/images/12.0.3-php7.4/docker-run.sh
