### ISSUE TITLE
Feature Request: Optionally disable creating PROV

### ISSUE THREAD

**Issue by clamisch** [Dolibarr/dolibarr#5953]
# Feature Request
[*Just I wanted to mention that I do not see in many cases need to go through a PROV. Ought may be optional in each module or as a parameter (Setup / Other setup) example MAIN_DISABLE_PROV_IN_MODULES.
For example, make a final quotation, order or facture immediately.*].

**Comment by BebZ** [comment]
PROV is essential because of steps of validation : 
one can make a draft and not validate, the other can validate but not make a draft
aftr validating it often triggers some mechanism that activate code for other modules.
Please don't write here such ideas that are non-sense for businness workflows & can destroy all the mechanics of the ERP.
You can make suggestions in the forum if you don't write line of code, here...

**Comment by clamisch** [comment]
Forum OK.
For being exactly an ERP community, I see absolutely necessary to provide flexibility for more agile work flows that are afected by giving too many clicks to get to invoice a quote.
The business environments in wich the campaigns have good results and customers arrive in greater numbers, you need to be quick to take the quote (propale) or order (commande) to your outgoing end state => INVOICE(facture).
There are staff that requires supervision- But others are independent businesses to close and are faster in these sales tasks, while the computer system will not delay management.
It is required to configure MORE AGILITY IN THE PROCESS.

**Comment by rdoursenaud** [comment]
This is a terrible idea IMHO. You're essentially asking to validate empty documents. What could possibly go wrong?

**Comment by altairis-tof** [comment]
not sure if it is out of subject or not, but there is a module on dolistore that allows to give a real ref for a draft : https://www.dolistore.com/fr/modules/546-R--f--rences-personnalis--es.html
