### ISSUE TITLE
Feature Request: Provide a Way to Convert Existing Product Reference to Leopard Mask

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6077]
## Environment
- **Version**: 4.0.2

# Feature Request
Allow the admin, through a sql script or GUI feature, to convert all existing product reference numbers to (configured) Leopard numbering model mask format.

# Use Case
Current product references are all free format.  Now the products have grown to a large number so text is not viable.  Should be a *mass* option to convert all product-a, product-b, product-c etc etc to {xx}{0000} leopard format.  Then we can set the last increment as an offset for when we create new products in dolibarr.

**Comment by aljawaid** [comment]
If anyone can provide an SQL script to use in MySQL Workbench, even that would be useful.

**Comment by aljawaid** [comment]
I'm looking at something like this but I can't seem to tell the script to change all reference numbers to PP1001, PP1002, PP1003
Obviously the below script is only for product with rowid 10... I would try to change that to <1 once I can get the mysql script sorted.

`UPDATE `cl13-dolibarr`.`llx_product` SET `ref`= concat('PP','1000'+1) WHERE `rowid` ='10';`

Any mysql gurus who could help?

**Comment by fappels** [comment]
It's better to create a CLI script for this.
[https://github.com/Dolibarr/dolibarr/blob/develop/dev/skeletons/skeleton_script.php](url)

**Comment by aljawaid** [comment]
I'm not familiar with developing scripts... surely there must be a faster way to do it?

**Comment by aljawaid** [comment]
I wouldn't even know how to begin to code that lol

**Comment by aljawaid** [comment]
@eldy Could you kindly provide your opinion on the best method to convert all existing products to the Leopard numbering model format?

**Comment by aljawaid** [comment]
Looking through /documents/produit/ folder I just realised that the product images would need to be changed too with new reference numbers to match (if they rely on them in the database).

**Comment by aljawaid** [comment]
@eldy @fappels Quick question, as a workaround... If I enable the leopard mask and gradually edit (already old free-format reference numbers) the product and then save the changes...will the current v4.0.2 change the reference to the new selected leopard mask or will it leave it as it is since it was an existing product?

**Comment by rdoursenaud** [comment]
Please remember, this is an issue tracker for developers: https://github.com/Dolibarr/dolibarr/blob/develop/.github/CONTRIBUTING.md

I believe this is a question better suited for the forum, the mailing list or even IRC.
This is also a service any prefered partner should be able to provide https://wiki.dolibarr.org/index.php/List_of_Dolibarr_partners_and_providers#Official_Preferred_partners_11

**Comment by aljawaid** [comment]
Try finding me a partner in the UK and I will follow them 'rules'!  The only ONE UK unofficial partner listed doesn't even exist any more after chasing them up!

Sick to death of the power-tripping by developers who aren't even the project leader!

I'm a business user with non-coding skills.  I share ideas and can fix (language files) where they are obvious.  I believe our input helps in the progression of the dolibarr platform.  We don't recognise 'bugs', we simply share what should or should not be.  The rest is upto the core team if there is such a team.

@fappels is working on this for me already but I kept the issue open as I thought any of the other developers may be kind enough to provide valuable information.

When the 'active' french forum becomes english language only, the forum may be a better place to discuss things I agree but there doesn't seem to be any notice taken on that.

Also, as business users we don't have the time to join mailing lists or even join IRC channels.

My apologies if I come across as rude but too many developers on here are showing arrogance without any kind of backup.

Please remind every other person that this is an 'issue' tracker too and please get @eldy to change the documentation in Github so we are not lead to believe we can freely submit our 'Feature**Requests**'!

After using Dolibarr for a year I am just about starting to get my finances sorted for it and this kind of stuff puts us off.  I can pay for a custom service/platform but I would rather mentally and financially contribute to an open-source platform where it benefits everybody.

Thank you for closing the issue anyway, as you have the authority to do so!

**Comment by aljawaid** [comment]
I've now closed all my Feature Requests and will refrain from suggesting in the future.

**Comment by rdoursenaud** [comment]
Look, I'm very sorry you're reacting that way. Chill out a bit, will you?

You have to also understand our point of view.
This project is completely free software (As in freedom of speech not as in free beer. See: https://www.gnu.org/philosophy/free-sw.en.html). This means that each and every developer is giving it's time FOR FREE to review and address the issues. We are also *very* short on resources.
I'm trying to keep them (particularly the so-called project manager) from being overwhelmed by requests not pertaining to the core system so they can focus on more important matters.
This is one of my contributions to the community, hence the "power" I have.
Sorry I've had to use it on you.

This particular request looked like a support request to me. Changing numbering systems in an ERP is no easy task. It's not something mundane we have to implement in the core. It's a very specific use case better served by a tailored solution.

The usual options are to pay for the service or get it for free via the *appropriate* community channels. The issue tracker is not meant for that. Period. Sorry if the realization came harsh to you.

Suggestions of improvements with proper research, argumentation and background are very welcome though and you're just over-reacting by closing all your feature requests.

I know the English speaking forum is not that great but, hey, it exists and this is a community, do something about it!
This is the spirit of free software.

The french forum is more active because we have a long history there. The project started in france with only french people. You can't ask them to speak english, it won't happen. We've already made huge efforts towards reaching to non-french people but you can't be entitled to have us do all the work.

I know very well what it is to be a business user as I'm one myself, thank you very much. I even own one of the Preferred Partners and guess what, we can provide support to the UK, we're on the internet and it's 2017 already. Notice it's not a shameless plug as I have no interrest working with whining customers.

Sorry if anything came harsh but this is the real world. I deal with that each time I open the issue tracker. And instead of swiftly fixing bugs, I write letters to entitled users but don't worry, I've been there and done that. If you really believe in free software, you'll learn soon enough, stick to it.

Keep calm and welcome to the community!
