### ISSUE TITLE
FR: Calculate selling price of parent fom sub-services/-products

### ISSUE THREAD

**Issue by casati-dolibarr** [Dolibarr/dolibarr#6089]
The scenario:

An as such offered "complete service" consists out of independent services, which are "produced" internally (even) as separate projects with separate resources.

Each of the sub-services has a purchasing and selling price offered standalone and is often sold in this way too.

Can we handle this with Dolibarr?

Any idea for workarounds (naturally avoiding manual calculations)?

Idea: Use a "markup" calculation on the sum of the purchase prices of the sub-services/-products

Best regards

**Comment by rdoursenaud** [comment]
IMHO the forum or the mailing list are better places to discuss this.

AFAIK Dolibarr already supports that with "Virtual services". See https://wiki.dolibarr.org/index.php/Module_Services#Services_virtuels (Sorry, didn't find an english reference, only on the french wiki)

**Comment by dom-breizh** [comment]
Sorry to restart this old thread, but since no answer has been offered it seems still valid.

Virtual services/products are great to combine elements into one. 
Sub products are discounted from inventory when the Virtual products are being sold (at least as of v6, did not check prior versions), but sub-products purchasing prices are not taken into consideration when building the the virtual products. It would be nice that those prices are pulled automatically/manually (as proposed early with a button) into the virtual products, hence allowing for margin calculation. There is little value in a manual calculation and it is open to manual errors for the individual users.

The documentation (although in french does not cover that part).

Any ideas?

**Comment by BebZ** [comment]
So there is just a button and/or a small calculation missing 
to pull buying prices of real products/services associated to a virtual
cumulate them and put this sum in the buying price of a virtual one on a propal or order ?

Not that complicated, but not in the functionnal mood / mind of Dolib devs... yet.

Or maybe you did not describe the Feature Request well enough...
