### ISSUE TITLE
Add Font Awesome support

### ISSUE THREAD

**Issue by jfefe** [Dolibarr/dolibarr#6146]
# Feature Request

Implement the iconic font and CSS toolkit : http://fontawesome.io/ 

Font Awesome is a full suite of 675 pictographic icons for easy scalable vector graphics on websites.

**Comment by eldy** [comment]
I planned to add "octicons". It is a set of svg icons. Also the svg file of fontawesome seems to not be compatible with inkscape. Also, with octicon, you don't need to manipulate a font file, you have directly one image .svg file per icon making things easier to use/edit them.

**Comment by gnovaro** [comment]
Create a custom web font with other existing projects and SVG support
http://fontastic.me/

**Comment by jfefe** [comment]
@eldy : seems to be a nice project but a smaller than Font Awesome (at the moment).
I think we need two sort of icons : those for menus/titles and those for calling action buttons.  For this usage we don't need to modify them because we want the advantage of something working out the box…

My 2 cents : SVG file is perfect for menus and Font Awesome is nice for buttons.

**Comment by gnovaro** [comment]
Maybe can use http://glyphicons.com/ have and SVG version.

**Comment by gnovaro** [comment]
Sory only PRO version have SVG

> Maybe can use http://glyphicons.com/ have and SVG version.
>

**Comment by aljawaid** [comment]
Would somehow switching to bootstrap not solve this issue?  It would definitely give the interface a newer look and be more user friendly.

Just an opinion.

**Comment by gnovaro** [comment]
I think @aljawaidis right, we do not need to reinvent the wheel and we should adopt the standard in the industry. I understand that the ideal would be to use svg and have its own font, but if dolibarr runs in a browser or in mobile with png would reach us. We would focus on what really matters, and we do not waste so much time on the UI.

**Comment by rdoursenaud** [comment]
I'm a bit late to the party but let me add my grain of salt ;)

For the MD theme I used the material design icons provided by Google and the community: https://material.io/icons/
The SVGs are nice to work with and there's also an icon font.
The look and feel is very good IMHO but I'm certainly biased since I work with Google products a lot.
In the end, I believe this is up to theme designers to decide and/or provide alternatives.

@aljawaid No need to embed the huge and ugly bootstrap. The fonts are from https://glyphicons.com/ which is yet another (already cited) alternative.

@gnovaro Looking at the plethora of alternatives, I don't believe there is any standard in this field. Sure there are some players with bigger shares but I don't think this is the only thing to take into account when deciding to invest in a dependency. For example, Dolibarr being a GPLv3 project, the license is probably the first issue to tackle.

The issue should really be titled "Provide a font icon" :p

My 2 cents.

**Comment by gnovaro** [comment]
I understand the license. Maybe we can use others alternatives like: Foundation or Material UI, We reinvent the wheel. And we lose focus on functionality. Having a grid work with divs instead of tables, making the responsive layout much easier and improve frontend, clean code.
