### ISSUE TITLE
Feature Request: Allow Multiple Barcodes per Product

### ISSUE THREAD

**Issue by aljawaid** [Dolibarr/dolibarr#6191]
## Environment
- **Version**: 4.0.2

# Current Dolibarr Limitation
To add more than one barcode is not possible unless it is in the note or description fields.
![multi-barcode-example_2016-09-21](https://cloud.githubusercontent.com/assets/10233708/21286382/11e1dc7a-c44a-11e6-991e-c170235a4adb.png)

# Feature Request
Allow user to add extra barcodes for each product. Currently, only one barcode is allowed for one product.  To be searchable, extra barcodes must be added into the note or description fields.  Use an extra field to save the barcode does not allow it to be included in the search fields when finding a product.

## Use case
**Drinking Cup** 
= _barcode 1_ = manufacturer 1 EAN13
= _barcode 2_ = manufacturer 2 EAN13
= _barcode 3_ = carton barcode for 12pcs form manufacturer 1 (manufacturer 2 sells their version of product loose)
= _barcode 4_ = manufacturer 3 Code39

Then the same barcodes can be included in the search fields to help inventory and stock control purposes.

**Comment by BebZ** [comment]
True ! 
in forums i already talked a lot about that... 
will you implement / finance it / need financing ? 

I sugges we can use also the batch/dluo extrafields ? Because it is already linked with a stock qty...
isn'it ?

**Comment by aljawaid** [comment]
Hello

Depends on what the cost would be. Bit restricted (allowed business expenses) in the UK for a small business which is why I went for the open source software.

I'm happy to try help where I can. I'm not a proper developer and dolibarr coding is very confusing as a starter. Doesn't help that the most active forum is in French either lol

Anyway, I use extrafields for carton barcodes but the field is not included in search. Maybe if there was a checkbox for the extra field to select so certain field types could be included in search. Then in theory we would just need to add a field type as barcode.

I think batch would be confusing as the (already) main problem with Dolibarr is the extra clicks to get to certain areas. With a extrafield type or new field, it would show as a summary on the product card.

I'm not sure how dolibarr finance would work but I would definitely have to get it authorised by the accountant.

Sent from my BlackBerry 10 smartphone.
From: BebZ
Sent: Saturday, 17 December 2016 17:23
To: Dolibarr/dolibarr
Reply To: Dolibarr/dolibarr
Cc: IJ; Author
Subject: Re: [Dolibarr/dolibarr] Feature Request: Allow Multiple Barcodes per Product (#6191)

**Comment by BebZ** [comment]
I disagree : 
I think batch would be confusing as the (already) main problem with Dolibarr is the extra clicks to get to certain areas. With a extrafield type or new field, it would show as a summary on the product card.

Instead of going to summary you have to go to the stocks tab 
as barcodes IMHO concern stock. activate batch/dluo and please try.

So you can have one product unit one barcode so if you got 1002 products it would display barcode as : 
1234567890123 (x1002) 
carton of 10 units = 2345678901234 (x100) + 1234567890123 (x2)
boxes of 5 cartons = 3456789012345 (x20) + 1234567890123 (x2)
etc....

the reason I think batch would be a better solution is that 
you can use multiple barcodes per products without getting confused 
which product is concerned when you try to decrease stock on picking, because you also have the batch/or serial on the carton.

On the summary of the product, and extrafields there is no real link on stocks increase/decrease.

Financing a batch evolution would be less costly than an extrafields link to stocks... maybe.

**Comment by aljawaid** [comment]
I think my use of barcodes is different to that of 'batch'.

In terms of the stock tab, it would have been alot easier if dolibarr updated to have drop-down top menus so we can go directly to certain sections instead of just the left menu.

As there is no way to 'scan' the item into stock, using batch is very time consuming. 
Example 1:
Product A has xxx (EAN13) barcode
Product A is packed in 6 packs, which is YYY barcode
Product A is then packed into one carton which is ZZZ barcode
....all the above barcodes should be searchable.

Example 2:
Product B is made in china with barcode CCC from 555 supplier
Product C is also made in china but with barcode DDD from 555 and 666 suppliers
Products B + C are created as one single product F in dolibarr as they are identical products just from different manufacturers.  Creating as one product saves time and also allows us to compare supplier buying prices within the same product.  Both products may or may not be in stock at the same time.

Maybe I am not using dolibarr the way it was designed to work, but this is the way that works for our small business.

For us to the best solution seems like:
Allowing extra barcodes to be linked to the product and then label them as 'carton' 'pack' etc
All the barcodes should be searchable.

At the moment we free-type the barcodes on separate lines in the note field, as it is searchable.

**Comment by BebZ** [comment]
I think your comment on the tabs is misplaced here : 

> In terms of the stock tab, it would have been alot easier if dolibarr updated to have drop-down top menus so we can go directly to certain sections instead of just the left menu.

... and you are FREE TO DEVELOP your own dropdowns if wished, or buy the module to manage multiple tabs, and put your own shortcuts, i'm sure you can achieve something if you try.

> no way to 'scan' the item into stock, using batch is very time consuming.
did you even ask ? 
@fappels is working on this already, do you have any finance capabilities too ?

You can use another module or anoter way to manage it... 
and you will see what is "time consuming", believe me... or not !

For your example 1 : I agree all should be search-able, but Dolibarr users are not all wholesalers as we are, i would love it but it would be called "WholeSal-ibarr", or smthg like, so don't lose your patience if it doesn't fit exactly your business workflows exactly !
That's why i suggested we use barcodes on batch module because a "product A", B or C 
is the smallest sale-able qty, batch-able qty.

The thing missing is "just" to have 
a table of "packagings" to link how many products are inside a pack or a carton.

example 2 : I use the same method (but i dont create B C separately, i just create F with 2 supplier prices)

> B + C are created as one single product F in dolibarr as they are identical products just from different manufacturers. Creating as one product saves time and also allows us to compare supplier buying prices within the same product. Both products may or may not be in stock at the same time.

The problem you will have, even with extra barcodes linked, is that 
you dont know what you have chosen when you will "put in stock / receive" 
or "ship" the product. 
As you have different manufacturers, you need to keep in mind that if you complain about the quality of one product to one of them he will ask "what batch" is involved. 
It happened to me with tissue products, i could not know to which supplier complain !

Please continue to : 

> free-type the barcodes on separate lines in the note field, as it is searchable.

Because : 
> Allowing extra barcodes to be linked to the product and then label them as 'carton' 'pack' etc
All the barcodes should be searchable.

is not clear enough to manage a stock, 
and as long as no one proposes some finance to get it in Core of Dolibarr 
it will stay as "issue" "discussion" and "great idea" ! 
on my side we will develop it this year and include it in our own Dolibarr 5.0 or 6.0 
if there is no crowdfunding @Darkjeff 
If there is a crowdfunding we can core-integrate as a complementary module ;)

**Comment by aljawaid** [comment]
Thanks for the detailed explanation.
