### ISSUE TITLE
Feature Request: invoice split payments 

### ISSUE THREAD

**Issue by cicalo** [Dolibarr/dolibarr#6201]
## Suggested implementation
PAYMENT TERMS-
for each type of payments I would like to select the terms (for example 30/60 end of month) and in the invoice when i select the terms of payments automatically dolibar could calcolate the payment date, and put the date on the invoice and in the customer situation and also in the "bill book"
as attached i've send a copy of my invoice software payment terms image

![payment-terms](https://cloud.githubusercontent.com/assets/24680908/21357103/4be827d0-c6d4-11e6-851e-d7f4484bd1a0.jpg)

## Suggested steps
[*List of tasks to achieve goal*]

**Comment by a-schild** [comment]
Hello Cicalo,

we too would have a use case for split due dates.
We have a client which makes client invoices for subscriptions for the next 6 and 12 months.
Some clients will pay these invoices in 6 or 12 steps, so every month only the corresponding amount of one months is due.

André

**Comment by atm-maxime** [comment]
Dolibarr already calculates due date based on invoice date and payment terms.
As for having a multi-payment of the invoice lasting on 6 month, I think this feature won't be implemented. Regulations implies a maximum delay of payment so waiting 6 month to finally pay the entire invoice is forbidden. You should create an invoice every month with model invoices. Otherwise I suggest to use an external module for this.

**Comment by a-schild** [comment]
@atm-maxime The regulations are not identical over the world.
In Switzerland you can make a invoice which has to be payed in 6 or 12 "slices"
