### ISSUE TITLE
BUG : Invoice generation not refreshed on lines ordered save

### ISSUE THREAD

**Issue by homer8173** [Dolibarr/dolibarr#6262]
# Bug
when an Invoice is updated by re-order lines, the document generated id not updated 

## Environment
- **Version**: 4.0.3
- **OS**: linux
- **Web server**: apache
- **PHP**: 5.6
- **Database**: mysqli
- **URL(s)**: /comm/propal.php?id=XX

## Expected and actual behavior
i had to manualy generate a new PDF

## Steps to reproduce the behavior
add 2 lines in invoice and order them, then see related PDF

**Comment by rdoursenaud** [comment]
Albeit a bit counter-intuitive, this is the expected behavior to keep UI responsiveness and preserve server performance.
If we would be to generate a new PDF each time the user reorders the lines, you'd be waiting a lot when reordering a large document and the backend would uselessly spend valuable time rebuilding the file on each and every change.
That's one of the reasons to have the rebuild document button.
Sounds like an acceptable tradeoff to me.
