### ISSUE TITLE
[Question] - Explain sql update scripts

### ISSUE THREAD

**Issue by laudeco** [Dolibarr/dolibarr#6452]
Could someone explain clearly how the migration scripts works ?

Exemple:
I want improve the membership system but for that I have to update the table. 

How can I do this ? 
When are executed the migration scripts ?
Should I also update the script that create table ?

Kind regards
Laurent

**Comment by laudeco** [comment]
someone ?

**Comment by rdoursenaud** [comment]
@laudeco You are asking in the wrong place.
We are only tracking feature requests and bugs here.
You may want to try the mailing list: https://lists.nongnu.org/mailman/listinfo/dolibarr-dev
Or the forum: https://www.dolibarr.org/forum/

Since I'm in a good mood today, I'll draft a reply, but please refrain from asking development related questions here.
What you need is to take a look at the code under ```htdocs/install```.
All the table schemas are declared in the ```mysql/tables``` subfolder and provisioned at install time.
If you need to change the schema or add a new table, you also need to add the related stanzas to the migration file for the unreleased version in ```mysql/migration``` (```5.0.0-6.0.0.sql``` at the time of writing).
This is used by the ```upgrade2.php``` script during the update procedure.
Install an old version of Dolibarr and run an update to familiarize yourself with the procedure!
Remember that you can also use ```git``` (mostly log and show) to take a look at the history of these files for insights.

Thanks for your understanding.
