### ISSUE TITLE
getversion()

### ISSUE THREAD

**Issue by dolibarr95** [Dolibarr/dolibarr#6641]
Hi

With Dolibar 4 and 5

Sorry but I don't know if it's a bug or and old code or what : 

Why in dolibarr/htdocs/admin/modules.php we call the function getversion() with an argument 0 and 1 ?
I never saw a module (internal or external) that's declare this argument is it deprecated ?
Should we delete it ? Can't find documentation about it.

Tks

**Comment by atm-quentin** [comment]
Hello,

$version=$objMod->getVersion(0);
is used just before to get the module type.

With the module type, we get the icon (we need the module type not translated to get it).

And after that we add getVersion(1) to the icon, because the 1 parameter translate it. 

(See htdocs/core/modules/DolibarrModules.class.php, function getVersion($translated=1))

Best regards,
Quentin.

**Comment by dolibarr95** [comment]
Tks !!
