### ISSUE TITLE
Multi Currency Module puts 0€ price on all lines . 5.0.1

### ISSUE THREAD

**Issue by jfposi** [Dolibarr/dolibarr#6743]
# Bug
Multi Currency module makes all prices to 0€ when the currency is the standard.

## Environment
- **Version**: 5.0.1

## Expected and actual behavior
Multi-Currency module should just tell you whats is the price with the new currency rates etc. But if you don't change it (Because it is the standard € selected on the company currency) and the conversion rate is 0 (you are not allowed to change it because I supose it is the standard one) it will create the documents with all the lines 0€. 

## Steps to reproduce the behavior
Activate multicurrency. Try to generate a PDF from a customer order or an invoice. You will get the lines with 0. And Im using Crabe (invoice) and Einstein (customer order). The only way to fast fix this is to disable the module.

Best Regards

**Comment by marcosgdf** [comment]
~~Multicurrency module is a thirdparty module not supported by Dolibarr team. This is not the place to report those errors~~

**Comment by braito4** [comment]
Actually it was introduced in 5.0:
https://github.com/Dolibarr/dolibarr/blob/develop/ChangeLog#L44

**Comment by marcosgdf** [comment]
Oh. Sorry, I confused it with the multicompany module 😞

**Comment by marcosgdf** [comment]
Is it happening with the latest one? I've tried and I get a conversion of "1" by default

**Comment by MartinFulgueiras** [comment]
Hi, you need to set up the module correctly. Go to module configuration and establish an exchange rate for the foreign currency. 

Having said this, the error does persist in the local currency and even if you put 1, the local currency appears as 0 :/  You need to change currency, then put 1 and then fo back to local currency so that your pdfs are not multiplied by 0 and end up as a 0.00 invoice or order or proposal.

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
