### ISSUE TITLE
Supplier code does not increase 

### ISSUE THREAD

**Issue by hasse-basse** [Dolibarr/dolibarr#7082]
# Bug

## Environment
- **Version**: 5.0.4
- **OS**: Linux
- **Web server**: Apache
- **PHP**: cgi-fcgi 7.0.20-1~dotdeb+8.1
- **Database**: MySQL or MariaDB 5.5.55-0+deb8u1-log
- **URL**: /dolibarr/htdocs/societe/soc.php

## Report
Hi

I've reported this issue earlier but the problem remain. When I try to create a supplier the supplier code does not increase so I have to manually search to find what was the latest supplier code used and then type it in by myself. Pls find the attached pictures. It is very anoying and I can't see that I've made any mistake in the configuration.

![skarmklipp1](https://user-images.githubusercontent.com/24247236/27692317-b1306dde-5ce6-11e7-9306-5ea9498fdd54.jpg)
![skarmklipp2](https://user-images.githubusercontent.com/24247236/27692329-b5dc9ed4-5ce6-11e7-8a29-2e2fee7d1a28.jpg)

All the best
Hans

**Comment by atm-maxime** [comment]
Hi Hans,

Sorry for the late response. This issue is often due to existing codes in the database. If all of your supplier codes respect the mask you setup, there should be any trouble. But if one code doesn't, the  numbering module won't work. I suggest you to extract all of your thirdparties and check if all supplier code are correctly formatted.

**Comment by hasse-basse** [comment]
Hi, no problems. I have got your answer in another tread (6790), I asked the question once before. Yeah, it is surely connected to the format of the old DB i imported from Sage. I actually suspected it and I will redo all the old supplier numbers.

Thanks
Hans
