### ISSUE TITLE
Unable to import stock

### ISSUE THREAD

**Issue by technoartista** [Dolibarr/dolibarr#7277]
* Line none    > Error running final request: UPDATE llx_product p SET p.stock= (SELECT SUM(ps.reel) FROM llx_product_stock ps WHERE ps.fk_product = p.rowid);
--

![image](https://user-images.githubusercontent.com/19356598/29570017-dfda669c-8772-11e7-8d06-ee9e0cdff59b.png)

can anyone tell me how to fix it

**Comment by eldy** [comment]
What is your dolibarr version and your database ?

**Comment by suryacaprice** [comment]
dolibarr 5.0.4 ... I fixed it by changing the code for database name for some reason for every upgrade llx_product_stock is changing . currently its llxeh_product_stock .. Code is not updated in the import module . after updating it it was working . Please check these settings while doing a version upgrade.

**Comment by ioaldo** [comment]
Hello, could you please elaborate more? Im having the same isuue with Dolibarr 6.0.2 and database  5.5.58-MariaDB - MariaDB Server,

Where do I supouse to change this , do you meant the name of the tables?

Got it now!.

core/modules/modStock.class.php must be edited at line 247 with the correct name of the table at your database

Cheers!

**Comment by vercinstex** [comment]
Hello
To fix this in versione 8 you have to change the file 

line 346 change it from 
`'UPDATE llx_product p SET p.stock= (SELECT SUM(ps.reel) FROM llx_product_stock ps WHERE ps.fk_product = p.rowid);'`

to:
`'UPDATE '.MAIN_DB_PREFIX.'product p SET p.stock= (SELECT SUM(ps.reel) FROM '.MAIN_DB_PREFIX.'product_stock ps WHERE ps.fk_product = p.rowid);'`

This will solve the problem looking for your custom database prefix

**Comment by vercinstex** [comment]
To fix the problem is very simple and works for every table prefix in database.

core/modules/modStock.class.php

Line 346 of versione 8.0.3
Original:     `'UPDATE llx_product p SET p.stock= (SELECT SUM(ps.reel) FROM llx_product_stock ps WHERE ps.fk_product = p.rowid);'`

Since I've changes the table prefix of database I think the best solution is this:
Solution:     `'UPDATE '.MAIN_DB_PREFIX.'product p SET p.stock= (SELECT SUM(ps.reel) FROM '.MAIN_DB_PREFIX.'product_stock ps WHERE ps.fk_product = p.rowid);'`

This will fix any problem
