### ISSUE TITLE
Bug: Wrong display of LocalTax2 in Supplier-Order and -Invoice

### ISSUE THREAD

**Issue by sbschumacher** [Dolibarr/dolibarr#7298]
# Bug
Spanish company is creating an order to a Spanish supplier. In this case the Spanish "IRPF" (LocalTax2) takes place. It is well calculated and the correct amount is visible in the PDF files (muscadet) but the value of percentage is wrong.

For example: in the generated supplier order PDF:
![irpf-bug](https://user-images.githubusercontent.com/14094327/29749866-d3400d30-8b35-11e7-894b-4d7c5edaca21.jpeg)

**The negative amount of -22,50 is correct (15 % of Total net)**, but in the description it says **22,5%**. Correct should be the label "**Total IRPF 15%**".

I am not a programmer, but in /core/modules/supplier_order/pdf/pdf_muscadet.modules.php the label is "created" in line `865: $totalvat.=vatrate(abs($tvakey),1).$tvacompl;` maybe there is an bug?

Same goes for the Supplier-Invoice

## Environment
- **Version**: 5.0.4 - 5.0.5

**Comment by technoartista** [comment]
i have the same issue . Using dolibarr 5.0.5 updated from 5.0.4. Local tax 2 is not taken for total
![image](https://user-images.githubusercontent.com/19356598/29780606-fcf7e48c-8c33-11e7-8d35-fca3f1c00527.png)


My round off settings
![image](https://user-images.githubusercontent.com/19356598/29780608-010b28cc-8c34-11e7-9c66-30f2c58156be.png)

if i set Step of rounding range to 0 or nothing calculation is correct. Can you tell me how to fix it ?
how to do round off in dolibarr without issue?
very urgent can you help me with it . Several invoices are pending due to this error .

if any value is set to Step of rounding range (for countries where rounding is done on something else than base 10. For example, put 0.05 if rounding is done by 0.05 steps) local tax 2 is not getting calculated for the total
![image](https://user-images.githubusercontent.com/19356598/29782133-0348b532-8c39-11e7-8852-862d90aecb33.png)

this isssue is also on 6.0.0 RC

**Comment by eldy** [comment]
Can you make a screen shot of the setup you did for taxes rates ?
Also some fixes around that were done in 6.0 last week. Can you test with version from
www.dolibarr.org/files/stable (6.0 is not finale but nearly)

**Comment by sbschumacher** [comment]
![es-vat-settings](https://user-images.githubusercontent.com/14094327/29994652-d48256a0-8fd4-11e7-80d7-b818e01daa86.jpg)

![es-supplier](https://user-images.githubusercontent.com/14094327/29995066-5ce4c78e-8fe0-11e7-8066-5838b080c98d.jpg)

**Comment by technoartista** [comment]
![image](https://user-images.githubusercontent.com/19356598/30003669-bf0c572a-90de-11e7-9b15-2b7151e7d1f0.png)

**Comment by sbschumacher** [comment]
For the sake of completeness: 
In the current version 6.0.0.0 another number (26,25 **%** seems to be the value in EUR) stands for the IRPF value (same settings as shown above):

![irpf6 0 0](https://user-images.githubusercontent.com/14094327/30113512-3cf82be0-9315-11e7-95da-9f5f43c13ad5.jpeg)

**Comment by eldy** [comment]
I pushed fixes in 6.0 branch.
Should be fixed with 6.0.2
