### ISSUE TITLE
Bug with holiday request

### ISSUE THREAD

**Issue by AurelienC** [Dolibarr/dolibarr#7358]
# Bug
Since version 6.0.0, users can't create a holiday request with the rigth *Créer/modifier vos demandes de congé*

The page is blank `holiday/card.php?action=request&leftmenu=`

## Environment
- **Version**: 6.0.0
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.4.45
- **Database**: mySQL
- **URL(s)**: holiday/card.php?action=request&leftmenu=

## Steps to reproduce the behavior
Create an user with only *Créer/modifier vos demandes de congé* rigth and try to make an holiday request.

# Feature Request
This page was functionnal with version 5

**Comment by eldy** [comment]
Can you see in your apache error.log if you have more details on error ?

**Comment by matll42** [comment]
Hi, we noticed the same problem today but still on 5.0.5. After some research and debug, we think it was introduced with #7035 since fuserid on line 684 is no longer initialized. If we initialized it like it was before, it works (just replaced `userid` by `fuserid`)
```
$fuserid = GETPOST('fuserid')?GETPOST('fuserid'):$user->id;
```

But this PR was made to avoid another problem, so I don't know why it was deleted. I'll post on the PR to check with fmarcet which is the author of the PR.

Hope it can help.

We'll try to upgrade to 6.0.1 but no many hopes on that.

## Environment
- **Version**: 5.05
- **OS**: Ubuntu 16.04.3
- **Web server**: Apache 2.4.18
- **PHP**: 7.0.22
- **Database**: MySQL 5.7.19
- **URL(s)**: /holiday/card.php?action=request&leftmenu=
