### ISSUE TITLE
Allow payment of invoices by the parent company

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#7543]
# Feature Request
A parent company must be able to make payment of the bills of its subsidiaries. There is already the option FACTURE_PAYMENTS_ON_DIFFERENT_THIRDPARTIES_BILLS that allows payment between subsidiaries.

## Suggested implementation
Add new hidden option like FACTURE_PAYMENTS_WITH_PARENT_COMPANY to enable this feature.

**Comment by BebZ** [comment]
How does it work in reality ? 
Because i can record a payment that came from a first company X on the invoice of second bill company Y
What is the use you want to make with that ? how does it show in Dolibarr (where do you record the X third in payment ? )
-Remember that X paid or pays for Y ? why not using contacts/addresses

Thanks for your explanations ;)

**Comment by tuxgasy** [comment]
one of my clients works with a big company and also its subsidiaries. Some time, the big company pays its bills with those of its subsidiaries also (by a single transfer).
A subsidiary is not a simple contact.
This issue was fixed by  2b2832d.
