### ISSUE TITLE
Bug : Convert credit note to discount

### ISSUE THREAD

**Issue by tuxgasy** [Dolibarr/dolibarr#7637]
# Bug
When convert a credit note to discount, if the credit note had a absolute discount from the invoice and the vat of absolute discount is différent of other line, two new discounts are created bug the sum is greatter than credit note amount.

## Environment
- **Version**: 5.0.x
- **OS**: Debian 8
- **Web server**: Apache2
- **PHP**: PHP7
- **Database**: Mariadb 10
- **URL(s)**: /comm/remx.php

## Steps to reproduce the behavior
- Create a standard invoice
- Add a product with sales tax 20% to the invoice
- Create an absolute discount with sales tax 0% for the customer
- Apply this absolute discount to the invoice
- Validate the invoice and then create a credit note with lines from the origin invoice
- Validate the credit note and convert it into future discount

**Comment by eldy** [comment]
Let's take example:
Invoice line 1 - price 100 - vat 20% = 120
Invoice line 2 - discount - 50
Total: 50 excl tax - 70 inc tax
We create the credit note from that invoice.

So credit note contains same lines for amount 70.
If we choose to convert credit note, we should have 1 discount of 70 inc tax so on next invoice we will deduce 70 from the remain to pay. We don't mind what is the vat rate. The vat part of a discount coming from a credit note has no sense.
So the problem is just the "feature to create a credit note doing 1 discount per vat". This has no sense for me on a credit note. If all vat are same, we can include the vat into the discount so we keep information (not used anywhere then, just visible in tracking screen of discount) but if we have several vat rate, we should have only 1 credit note of amount of credit note and a vat of zero (vat on discount from credit note is not important, because the discount will be use to reduce remain to pay and not to change the amount of an next invoice).
Having 1 discount per vat was probably introduced for deposit. For such invoice, we must keep details of vat rates and there is never discount on a deposit invoice.

I suggest instead to change the rule and say:
If we create a discount from a deposit, we keep code as it is (1 discount per vat).
But if we create a discount from something else, we create only 1 discount with vat of lines if all vat rates are similar, but with a vat zero if there is different vat rates (in such cases, the discount is a payment matter, not used by turnover, so we don't mind the rate, it will not be used later).

**Comment by atm-maxime** [comment]
Too old version, please upgrade and reopen if needed.
