### ISSUE TITLE
Export all attachments from suppliers' invoices

### ISSUE THREAD

**Issue by TheTrueTom** [Dolibarr/dolibarr#8118]
# Feature Request
Add a mass action to export all supplier invoices attachments

## Use case
I use the supplier invoices for every bill that I receive in my company, whether that is a lunch or construction materials, anything; when I have an expense I just create a supplier invoice and put all proofs/bills/tickets necessary as attachments to that invoice. 

Every month my accountant asks for the list of all expenses accompanied by all proofs/bills/tickets, it would be more that useful to be able to export all attachments either as one pdf or as a zip which would include all attachments.

## Suggested implementation
The best solution I think would be to be add a mass action on supplier invoices that would either :
- Make a PDF containing all attachments contained in the supplier invoices
- Provide a zip will containing all attachments contained in the supplier invoices

I can maybe help as I know a bit of php, however the project is big and I have no idea where to start.
If no one wants to do it but someone can give me pointers I can have a go at it!

**Comment by dolibarr95** [comment]
hi!
http://www.fpdf.org/en/script/script94.php

**Comment by Kaor** [comment]
+1 by date

**Comment by laudeco** [comment]
I thought to add the attachments in the expense note PDF. As this you have the expense note and all the attachments in the same PDF. Isn't easier to print ?

Kind regards
L.

**Comment by dpriskorn** [comment]
This is a very specialized need that seemingly not many has. Is there a reason why this should be in core? How did you solve it until now? I also have a company but I keep all the receipts in a yearly rotated folder outside Dolibarr. I rarely need them for anything because I have no accountant and the tax authorities have never asked for them.
I imagine you could easily lookup all the file-links via the orders or invoices via python and generate a zip of them. Would you like to hire my help writing such a script? It would only ask for the time period and output everything found within that.
