### ISSUE TITLE
FEATURE REQUEST: Delivery Note without order

### ISSUE THREAD

**Issue by FritzBrause66** [Dolibarr/dolibarr#8140]
# Feature Request
We receive from our customers samples we need for our production. For shipping, we have no change to do this without creating a product and creating an order....
If we can create a new shipping, without any other document, this would be helpful.
Also for repairs or rework of products.
Or just shipping a NDA to a customer...

**Comment by hregis** [comment]
@FritzBrause66 
yes it's in the pipes ... since a long time! ;-)

**Comment by BebZ** [comment]
/expedition/card.php?action=create2&leftmenu=sendings
if ($action == 'create2')
{
    print load_fiche_titre($langs->trans("CreateShipment")).'<br>';
    print $langs->trans("ShipmentCreationIsDoneFromOrder");
    $action=''; $id=''; $ref='';

I guess there is just missing a way to retrieve headers of the shipment ? no ?

since 2016 and product's batch this page had been really active on commits 
https://github.com/Dolibarr/dolibarr/commits/9d10eb57f2fee2374fe0719174ec30b241279df5/htdocs/expedition/card.php

Shipment (expedition) is deeply linked to order module (a thirdparty, contacts/Adresses, products or services (with origin line)....)
Why don't you simply use services to register your samples ? 
How do you register your samples from customers if you don't create a product/service ?
and how do you process them in production later if you don't have a "ref" of product/service ?
and ow do you send them back to your customers if you dont know which one is the one they sent to you ?

Maybe Order module is not what you're looking for, but if you don't explain your business matters better, and with a detailled specifications, no one can go towards your goal...

**Comment by rakeshpatil1983** [comment]
Its better to have a delivery challan and delivery receipt module(shipments module as a seperate module). If needed the module will be linked as usual with the order. 
The mode of business is first the production material is sent using a DC(delivery challan) once these material are approved then the Customer places the order and Invoices are then generated to the material which is already delivered. 
Its like giving the material credit before placing the order by the customer.
