### ISSUE TITLE
The Email template substitute __AMOUNT__ should be formatted

### ISSUE THREAD

**Issue by loxK** [Dolibarr/dolibarr#8475]
The Email template substitute __AMOUNT__ should be formatted according to the settings in the 'limites et précisions" screen.

Example with 3 / 0 / 8 settings in limits and precision an amount o 1000 will show as  1000.00000000 

I cannot find a single use case where an unformatted can be useful in an email template ...

**Comment by ghost** [comment]
I deal with it

**Comment by eldy** [comment]
In a email template, there is no reason to no trunc to 8 as requested by the setup.
But the substitution function is generic and used for other purpose, like to fill a calc ODT file. So original data must be kept. So i introduced in 8.0 new variables
__AMOUNT_FORMATED__
__AMOUNT_EXCL_TAX_FORMATED__
etc...  
__XXX_FORMATED__ with the "_FORMATED" at end of any __AMOUNT keys 
It returns a "formated" value (according to setup rules, size length but also language).

**Comment by PlanPc** [comment]
Dolibarr 7.0, with Setup in limit a precision of 2 / 2 / 2 same result when using variables in email template.

Is a Spanish installation, so decimal separator must also be "," instead of "."

Base | 190.00**000000**€
VAT | 39.90**000000**€
Total | 229.90**000000**€

Anyway to solve this without waiting to V 8 of Dolibarr?

**Comment by Bagu** [comment]
Same problem with Dolibarr 7.0.2
