### ISSUE TITLE
Cron job doesn't work

### ISSUE THREAD

**Issue by manukieli** [Dolibarr/dolibarr#8927]
# Bug
The URL to execute cronjob work.
But when I schedule a task with the command, they don't run.
With Curl or Wget command to shedule the cron to the URL, they return <b>Userlogin is required</b>.
Or if I use command to execute they do nothing.

## Environment
- **Version**: 7.0.2
- **OS**: Centos 7.5
- **Web server**: Apache 2.4.6
- **PHP**: 7.1
- **Database**: MariaDB 5.6
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
I'm using this command and they return this:
`Output from command /usr/bin/php /home/mydomain.com/public_html/scripts/cron/cron_run_jobs.php 96r9Br5izhGJK88xP40qYQ4GTuBE9fgk admin > /home/mydomain.com/public_html/documents/cron_run_jobs.php.log`

Execute this url to the browser, they work well:
`http://mydomain.com/htdocs/public/cron/cron_run_jobs.php?securitykey=96r9Br5izhGJK88xP40qYQ4GTuBE9fgk&userlogin=admin`

**Comment by loxK** [comment]
Same here. Executing from command line:

```
# sudo -H -u www-data /srv/dolibarr/scripts/cron/cron_run_jobs.php [hash] [user]
***** cron_run_jobs.php (7.0.1) pid=32461 ***** userlogin=[user] ***** 1533171287 *****
cron_run_jobs.php cronjobid: 16
```

**Comment by Ion00** [comment]
Same here with Dolibarr 8.0, upgraded from 6.0. Execute cronjobs from web explorer works fine, but execute cronjobs from cron does not work, this is the error messate:

Securitykey is required. Check setup of cron jobs module.

Note: Securitykey is already seted in cron jobs module setup

**Comment by delcroip** [comment]
I just proposed a PR to fix it.

**Comment by delcroip** [comment]
Hi,
Apparently we are executing the wrong file because there is another /cron_run_jobs.php  in Dolibarr/script/cron and this one takes the cli parameters into account.

Personally I'd rather have a single file that is used for the CLI and the CURL/WEB but it's not eldy's point of view:
https://github.com/Dolibarr/dolibarr/pull/9395

br

**Comment by edupulpillo** [comment]
Maybe a good idea to have only one filename, but doing that the script be able to work in both modes CLI and CGI, taking care of the right parameters.

Then if CLI then check the input parameters as CLI mode, and if CGI check the parameters in CGI mode, and inside the script apply the right parameters depending of the mode used.

In case of missing input parameters for the mode used, then write in the log the reason of the error, and that's it.

This is also very useful because some shared hosting are using also cgi mode to launch the cron tasks.
