### ISSUE TITLE
Full support for emojis

### ISSUE THREAD

**Issue by HackLo** [Dolibarr/dolibarr#8965]
# Bug / New feature ?
I was trying to insert emojis on some elements but they are not fully supported. It seems the problem comes from the query on the INSERT/UPDATE.

**Comment by john-botella** [comment]
Can you be more precise ? Can you give the emojis ? is it a simple text like ; - ) or do you use WYSIWYG interface button or other thing ?

Can you give us whose document or elements is affected ?

**Comment by HackLo** [comment]
I was talking about phone emojis you can add for example with a smartphone or Windows virtual keyboard, like this kind of emojis 😀 😁 😂 🤣🐶 🐱 🐭, etc). For an example, i add an emoji in a service title, and it replaced it with 4 "?".

**Comment by vgpastor** [comment]
I have the same issue with latest version 21.0.1
Server nginx/1.26.3
PHP 8.3.21
BBDD MariaDB 10.3.39-MariaDB-0+deb10u2
Collation utf8mb4_unicode_ci

In the bbdd if i force to put an emoji inside a email temaplate, this emoji are stored but when try to send or update the template are replaced by ? characters

**Comment by artemysfr** [comment]
Same problem on Dolibarr 20.0.4. Manually adding "&#1234;" codes in mailing body with phpMyadmin directly in database works, but as soon as I edit my mailing list through Dolibarr WYSIWYG interface, it's being replaced with "????".

**Comment by john-botella** [comment]
Ok, it is linked to UTF-8 / MySQL collation.

This issue is already fixed in the latest Dolibarr version, but you still need to run the database migration script to update the collation.

In most cases the problem comes from an old MySQL/MariaDB configuration where tables or columns are still using a non utf8mb4 collation, which leads to inconsistent behaviour when handling special characters.

So even after upgrading Dolibarr, the fix is not automatic: you must run the provided migration script (or the upgrade process that updates the schema) to ensure the database is fully converted to a proper utf8mb4 collation.

Without this step, you can still reproduce encoding issues even though the application code itself is now compliant.

**Comment by artemysfr** [comment]
Updating to utf8mb4 collation solved my problem, thanks !
