### ISSUE TITLE
bug dans 'get_next_value'

### ISSUE THREAD

**Issue by Vikingfr** [Dolibarr/dolibarr#9134]
# Bug
Bonjour,

en étudiant une anomalie chez un client, j'ai trouvé ce qui peut être considéré comme un bug ou un risque de problèmes.
Dans la fonction 'get_next_value' du fichier core/lib/function2.lib.php , une recherche est faites dans la base de données, mais le masque créé pour cela est trop générique.

Mon client utilisait les masques suivants, modèle de facture mercure:
{000000}{ttt}{mm}{yy}
FR{0000}{ttt}{mm}{yy}
AV{0000}{ttt}{mm}{yy}
AC{0000}{ttt}{mm}{yy}

'get_next_value' ne regarde pas le type de caractère et se contente de chercher les factures selon un masque générique. Du coup, 000020TTTMMYY ou AV00001TTTMMYY sont des réponses valides, alors que ce sont deux types de facture différentes (et c'est justement un avoir qui posait problème).
Il faudrait ne chercher que ce qu'il y a dans le masque et ne pas accepter les lettres si le masque est numérique et inversement.

Mon topic initial: https://www.dolibarr.fr/forum/12-howto--aide/62252-probleme-de-numerotation-automatique-de-facture

## Environment
- **Version**: découvert sur 7.0.0 et existe aussi sur 7.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: PHP 7
- **Database**: MySQL or MariaDB 5.6.39-log

**Comment by eldy** [comment]
This is true.
The get_next_value will fails if there is conflict with some masks
{000000}{ttt}{mm}{yy}
is in conflict with others
It is very difficult to take care of the type of chars (num or not) because we use a SQL sorting to retreive last num. What we recommand is to use same numering mask {000} at same position for all masks, and you wont get any problems.
