### ISSUE TITLE
# Feature Request: SQL sanitization function

### ISSUE THREAD

**Issue by delcroip** [Dolibarr/dolibarr#9205]
# Feature Request
Today the sanitization is done in the main.inc.php but the issue is that we can't sanitize versus an expected format (getpost does that but for PHP not SQL) 

## Use case
if a user wants to include a simple quote in a name, in today's implementation of dolibarr it will fail

## Suggested implementation
The developers should have a sanitization function to call each time they include variable in an sql querry:
$sql="t.date1=".$this->db->sanitization($this->date1, 'date');
$sql=",t.text1=".$this->db->sanitization($this->rexr1, 'text');

## Suggested steps
the function must:
- Trim the param
- Ensure there is no SQL keyword, not any SQL injection attempt (a sanitization for SQL string could replace the SEL by SELECT ... )
- Validate the input with the specified type
- Add escape characters when needed ('' iso ' -- this is 2x ' and one double-quote)  
- Format transformation ( date .. )

**Comment by eldy** [comment]
You have the
$this->db->escape 
so you can store any content in SQL, even with quote in it. There is an escape function for each storing format (sql, cli command, file, ...)
Sanitizing according a "format" looks strange because what we do for a format is "escaping" and what we sanitize is a data in memory that has not "storing" format.
What do you mean with "if a user wants to include a simple quote in a name, in today's implementation of dolibarr it will fail". Do you mean into a value of a field ? This should be already possible everywhere.

**Comment by delcroip** [comment]
Indeed I saw it later I should have closed the issue,
this poped up in this complain on the forum: https://www.dolibarr.fr/forum/8-mise-a-jour/62340-message-erreur-suite-mise-a-jour

br
