### ISSUE TITLE
Invoice bug 8.0.0 in label "not released"

### ISSUE THREAD

**Issue by John-H-Smith** [Dolibarr/dolibarr#9277]
If I create an invoice and confirm it, behind the invoice number there is still "not released".

Maybe the text is another, I use dolibarr in german.

**Comment by eldy** [comment]
Yes, surely a translation problem.
Bot that if you validate the invoice, this text must disappearr

**Comment by John-H-Smith** [comment]
@eldy Nope, if I validate the invoice, I see the buttons "edit", "send e-mail" and so on. But the invoice-number on PDF is still with "not released". Also if I send it with E-Mail.

**Comment by pangoSE** [comment]
Cannot reproduce this on 8.0.2. Danish language. Have you tried upgrading?

The invoice goes from draft->not paid->paid and the invoice and invoice number appear as expected. FA1810-0001 in my case.
The accounting is not automatic, but this seem to be by design. 
After paid-status the invoice appears in the list here 
I pressed commit to sale journal. 
Now visible in the sale journal I can commit it to the master journal http://dolibarr.localhost/accountancy/journal/sellsjournal.php?id_journal=1
After this step the invoice status is still paid and below it changed from "not booked in the master journal" to "booked in the master journal" in danish.
