### ISSUE TITLE
Hide origin country in {line_fulldesc} at ODT Commercial Proposal

### ISSUE THREAD

**Issue by ivancalax** [Dolibarr/dolibarr#9473]
# Bug
*There is anyone way to disable the origin country in {line_fulldesc}? Searching at https://wiki.dolibarr.org/index.php/Setup_Other I don't find any documentation about it*

## Environment
- **Version**: 7.0.3
- **OS**: Linux
- **Web server**: Apache
- **PHP**: 5.6.35
- **Database**: MySQL 5.5.51-38.2

**Comment by Nemtes** [comment]
I had the same problem.

My solution is to use:

`{line_desc}`

and set:

`MAIN_PRODUCT_DISABLE_CUSTOMCOUNTRYCODE to 1`

https://wiki.dolibarr.org/index.php/Setup_Other#Products_Module

**Comment by atm-maxime** [comment]
If you don't want custom country information added to your line description when you add a product to a document, the right way is to use MAIN_PRODUCT_DISABLE_CUSTOMCOUNTRYCODE.

**Comment by code-chicken** [comment]
Shouldn't the name of this constant be MAIN_PRODUCT_DISABLE_CUSTOMSCOUNTRYCODE, ie CUSTOM**S** instead of CUSTOM?
At least this information is mainly needed for the customs. On the other side I am wondering what the meaning of a custom country code would be. Country codes are standardized (like de, en, us or de_DE, de_AU, ...).
