### ISSUE TITLE
email module Adhérents

### ISSUE THREAD

**Issue by dieperie** [Dolibarr/dolibarr#9640]
# Bug
email feature does not work anymore properly.

_Échec de l'envoi de l'email (émetteur=xyz@123.com, destinataire=xyz@gmail.com). Failed to send mail with smtps lib to HOST=, PORT=465
Constructor of object CMailFile was not initialized without errors._

## Environment
- **Version**: 8.0.2

## Expected and actual behavior
When sending an email or activating /de-activating an "Adhérent", an error message appears and email not send. This is since version 8.0.0

**Comment by laudeco** [comment]
I found the issue and I do not know how it was before this version.

You must go in the configuration of the members module > e-mails > then configure an e-mail for each type ...

I'm still trying to figure out how it was to fix this.

**Comment by laudeco** [comment]
The problem is due to the new configuration of the module members. Indeed in the previous version the subject and the content of the e-mail were directly written in the module itself and saved in global variables.

In the new version this configuration has been replaced by the usage of e-mail templates (it's a very great idea) but it introduces a  backward compatibility break. Because if you do not change your configuration, the module doesn't send e-mails anymore.

My fix introduces a fallback on the previous configuration.

@eldy I created a first PR to fix the problem, but I agree to go one step further by removing this fallback. I'm not sure with the best approach to do this. I imagined : 
* Create an e-mail template with the old configuration on the next migration (do not know yet how to do that XD)
* Display a warning message somewhere to the administrator.
* Keep the fallback, after all there are already so many in the application.

**Comment by eldy** [comment]
I think best choice is to report a warning
"Setup of module Member - Tab email is not complete"

**Comment by aellert** [comment]
Actually, I'm using Dolibarr 18 and same problem (before I was on 14 and no pb)

When validating a member, you can choose by checking a box to send them a welcome email. In this case, Dolibarr generates this error:

Failed to send email (sender=xxx@xxx.fr, recipient=yyy@yyy.com). Failed to send mail with smtps lib to HOST=, PORT=587
Constructor of object CMailFile was not initialized without errors.

Workaround: Send the welcome email separately in two steps.

Thank you to re-open this issue !

**Comment by emheyarssi** [comment]
Hi, unable to reproduce on 18.0.6

**Comment by aellert** [comment]
There is no 18.0.6 version, latest is 18.0.5 ?

**Comment by emheyarssi** [comment]
Checkout from GitHub
![image](https://github.com/user-attachments/assets/f58a7dac-5802-40b1-b4e1-836adff37dc0)

But I'm not sure this resolve your problem. I started from a fresh installation on 18.0.6. Maybe if I upgrade from a previous version the problem still. I need to make further tests
