### ISSUE TITLE
Feature Request: Semi-automatic or automatic reconciliation via bank APIs

### ISSUE THREAD

**Issue by pangoSE** [Dolibarr/dolibarr#9732]
# Feature Request
I would like to be able to semi-automatically or automatically fetch bank transaction data from my banks public API.

For example
The number one business bank in Sweden has a public facing API for fetching banking account information.
Implementation details here: https://developer.sebgroup.com/

## Suggested implementation
Maybe we could have a generic API-module to enable implementors to easily support a new bank.
E.g. the following methods should be common:
* api-key
* social security number /authentication
* fetch transactions
* present fetched transactions for the user to setup the data 
* import the data

When this works we could building on this automate the process and create 1 module per bank as is done in Odoo.

**Comment by atm-maxime** [comment]
We have a "bank import" module that allows to import bank statements in order to reconcile. We are currently developing a version 3 that will add some features and stock data of the statement in a table (currently live reading the file). Version 4 will be to retrieve statements automatically from the bank using the EBICS format (not sure which contries use this, but France is)
