### ISSUE TITLE
Currency Conversion wrong USD to MXN in invoices

### ISSUE THREAD

**Issue by nanoxp** [Dolibarr/dolibarr#9801]
# Bug
[Currency Conversion wrong USD to MXN in invoices]

## Environment
- **Version**: [8.0.2 ]
- **OS**: [linux]
- **Web server**: [Apache 2.2.34]
- **PHP**: [5.6.30]
- **Database**: [MySQL 5.6.32-78.1]

## Expected and actual behavior
[Currency Conversion wrong USD to MXN in invoices¨
]

## Steps to reproduce the behavior
[Dolibarr is configured as USD Base Currency and it is indicated in the configuration section that 1 USD = 18.5 MXN
![image](https://user-images.githubusercontent.com/24461406/47125812-17e40600-d24b-11e8-8909-94f6d336fff3.png)
When making a invoice in the base currency that is USD we see that everything is fine:
![image](https://user-images.githubusercontent.com/24461406/47125881-672a3680-d24b-11e8-8a65-dd1fca70b65b.png)
when we do the convert to MXN and enter the Currency conversion rate, as it's shown in the following:
![image](https://user-images.githubusercontent.com/24461406/47126025-2848b080-d24c-11e8-8cdf-db5f463ec291.png)

is being made division instead of multiplying them as shown in the previous image (1 USD = 18.5 MXN) 35,641.00 USD = 659,358.5 No 1,926.54 as seen in Amount (inc. tax) in the previous image.

also in the generated PDF we see how it says it is in MXN but the totals are still put in USD
![image](https://user-images.githubusercontent.com/24461406/47126405-0d773b80-d24e-11e8-8431-e9a8f50c138c.png)

]

**Comment by atm-maxime** [comment]
There's an issue with the totals, but conversion is fine. I think this is more of a translation issue because "original currency" refers to MXN in your example. When you changed the exchange rate, I think it asked in which way you want to do the conversion. You must have selected MXN > USD instead of USD > MXN, that's why you have it the wrong way.

**Comment by nanoxp** [comment]
The system is set in USD, as shown in the first screen that you attach and we see how it is specified that 1 USD = 18.5 MXN. in the second screen we see the amount of the invoice in $ 35,641 USD, and the conversion is executed in the third screen, a correct operation in this case is 35.641 USD * 18.5 MXN = $ 659358.5 value that does not appear in "original currency" or in "Total amount" this in case of only be translation problem as you mention

**Comment by bv74** [comment]
It's seems to be same issue than #9711 and #9697.

**Comment by atm-maxime** [comment]
Ok got it. When you change the currency of a document, the system considers the price already defined in the document as the same in the new currency instead of keeping the internal currency as reference.
Eg : I have a invoice of 100 €, I change to MXN currency, the system considers that the invoice is of 100 MXN...

I'll look into it.

**Comment by bv74** [comment]
I've always the problem in the PDF proposal, invoice.... as in last picture of nanoxp : 
Total net of tax is in Euro as Total (inc Tax) is in CHF.

**Comment by atm-maxime** [comment]
Yes I know, sorry I just fixed the first issue and not the one in the PDF for now...
As you can see I didn't close the issue.

**Comment by bv74** [comment]
problem seems to be fixed with release 8.0.3.

**Comment by atm-maxime** [comment]
Is this fixed ? Can you close it ?

**Comment by bv74** [comment]
It can be closed. I don't how I can close it. 
Thank you.
