### ISSUE TITLE
Price / quantity on commercial document

### ISSUE THREAD

**Issue by Arre8** [Dolibarr/dolibarr#9818]
# Feature request
not possible to set price on a line in commercial document while adding a line

## Environment
- **Version**: 8.x
- **OS**: x
- **Web server**: x
- **PHP**: x
- **Database**: x

reported on : https://www.dolibarr.fr/forum/3-installation/61448-resolu-modifier-prix-dans-propale/reply/102200
and many other records in forums

-> is there a problem to do that ?

**Comment by atm-maxime** [comment]
This is not a bug, it's expected behaviour. The point of using a product/service catalog is that your selling price is already defined (with many options as price levels, price by customer, ... and many other coming from external modules). So when you add a line the system automatically retrieves the price.

This been said, we are working on an improvement which will allow to enter the unit price directly.
